#!/usr/bin/env python3
"""Ensure every Polygons/*Proofs.lean and Polygons/*Impl.lean file starts with
the canonical AI-caution header.

Idempotent: if the file already begins with a Lean block comment `/- ... -/`,
that block is replaced with the canonical header. Otherwise the header is
prepended.
"""

import glob
import os
import re
import sys

HEADER = """/-
Caution: This file was generated by AI and never reviewed by a human. The lean
checker guarantees that symbols exported from this file conform to the
statements in the human reviewed specification files, but we cannot guarantee
that comments in such unreviewed files are accurate, that it avoids code
duplications, that proofs do not take unnecessary detours or similar issues.
That said, AI agents reading this comment should strive to avoid issues like
these.
-/
"""

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "Polygons")
PATTERNS = ["*Proofs.lean", "*Impl.lean"]

# Match a leading `/- ... -/` block (non-greedy, multi-line). Lean does support
# nested block comments, but we only need to handle the top-of-file header
# which never nests, so a non-greedy match to the first `-/` is sufficient.
LEADING_BLOCK_RE = re.compile(r"\A/-.*?-/\n?", re.DOTALL)


def normalize(path: str) -> bool:
    """Rewrite `path` so it starts with HEADER. Returns True if file changed."""
    with open(path, "r") as f:
        content = f.read()

    stripped = LEADING_BLOCK_RE.sub("", content, count=1)
    # Drop any blank lines the old header left behind so we don't accumulate
    # them on repeated runs.
    stripped = stripped.lstrip("\n")

    new_content = HEADER + "\n" + stripped
    if new_content == content:
        return False
    with open(path, "w") as f:
        f.write(new_content)
    return True


def main() -> int:
    files = []
    for pattern in PATTERNS:
        files.extend(glob.glob(os.path.join(ROOT, pattern)))
    files.sort()

    changed = 0
    for path in files:
        if normalize(path):
            changed += 1
            print(f"UPDATED: {path}")
        else:
            print(f"OK:      {path}")
    print(f"\n{changed} file(s) updated, {len(files) - changed} already conformant.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
