/-
Caution: This file was generated by AI and never reviewed by a human. The lean
checker guarantees that symbols exported from this file conform to the
statements in the human reviewed specification files, but we cannot guarantee
that comments in such unreviewed files are accurate, that it avoids code
duplications, that proofs do not take unnecessary detours or similar issues.
That said, AI agents reading this comment should strive to avoid issues like
these.
-/

import Polygons.GraphVertexNeighborhood
import Polygons.Polygon
import Mathlib.Tactic.LinearCombination
import Mathlib.Data.Set.Finite.Basic

/-!
# Even Graph Characterization Helpers — Proofs

Internal lemmas supporting the proof of `Graph.isEven_of_exists_interior_set`.

The key construction is a *good polygon around a vertex*:
1. Start from `exists_polygon_separating_rays` (now strengthened with the
   line-avoids-origin invariant).
2. Shrink it toward the vertex so that:
   * the polygon fits inside the safe neighborhood from
     `exists_vertex_neighborhood_avoiding_non_incident`;
   * each polygon-segment line avoids all graph vertices, not only `v`.

We then prove a polygon-walk parity lemma: traversing such a polygon, the
total number of polygon-segment / graph-segment crossings is even, by a
ray-shooting argument from polygon vertices.
-/

open Classical Set List

noncomputable section

namespace EvenGraphCharacterizationHelpersProofs

/-! ### Polygon shrink toward a center -/

/-- Shrink a polygon vertex toward a center `c` by factor `s`. -/
def shrinkPoint (c : Vector2D) (s : ℚ) (p : Vector2D) : Vector2D :=
  ⟨(1 - s) * c.x + s * p.x, (1 - s) * c.y + s * p.y⟩

/-- Shrink a polygon toward a center by replacing each vertex. -/
def polygonShrink (P : Polygon) (c : Vector2D) (s : ℚ) : Polygon :=
  ⟨P.vertices.map (shrinkPoint c s)⟩

@[simp] theorem polygonShrink_vertices (P : Polygon) (c : Vector2D) (s : ℚ) :
    (polygonShrink P c s).vertices = P.vertices.map (shrinkPoint c s) := rfl

/-- Vertex membership for shrunken polygon. -/
theorem mem_polygonShrink_vertices (P : Polygon) (c : Vector2D) (s : ℚ)
    (q : Vector2D) :
    q ∈ (polygonShrink P c s).vertices ↔ ∃ p ∈ P.vertices, shrinkPoint c s p = q := by
  simp [polygonShrink_vertices]

/-- The list of segments of `polygonShrink P c s` is in bijection with the
list of segments of `P`, with `(p1, p2)` mapped to `(shrink p1, shrink p2)`. -/
theorem polygonShrink_segments (P : Polygon) (c : Vector2D) (s : ℚ) :
    (polygonShrink P c s).segments =
      P.segments.map (fun seg => ⟨shrinkPoint c s seg.p1, shrinkPoint c s seg.p2⟩) := by
  unfold polygonShrink Polygon.segments
  cases hverts : P.vertices with
  | nil => simp
  | cons v vs =>
    cases hvs : vs with
    | nil => simp
    | cons w ws =>
      simp only [List.map_cons]
      have hzip : ∀ (l1 l2 : List Vector2D),
          (l1.map (shrinkPoint c s)).zip (l2.map (shrinkPoint c s)) =
            (l1.zip l2).map (fun (a, b) => (shrinkPoint c s a, shrinkPoint c s b)) := by
        intro l1 l2
        induction l1 generalizing l2 with
        | nil => simp
        | cons a as ih =>
          cases l2 with
          | nil => simp
          | cons b bs => simp [ih bs]
      have h_app : (w :: ws ++ [v]).map (shrinkPoint c s) =
          (shrinkPoint c s w) :: (ws.map (shrinkPoint c s)) ++ [shrinkPoint c s v] := by
        simp
      rw [show ((shrinkPoint c s v :: shrinkPoint c s w :: ws.map (shrinkPoint c s)).zip
          (shrinkPoint c s w :: ws.map (shrinkPoint c s) ++ [shrinkPoint c s v])) =
        (((v :: w :: ws).map (shrinkPoint c s)).zip ((w :: ws ++ [v]).map (shrinkPoint c s))) by
          simp]
      rw [hzip]
      rw [List.map_map, List.map_map]
      rfl

/-! ### Distance bound for shrunken polygon -/

/-- A shrunken vertex is at scaled distance from the center. -/
theorem shrinkPoint_dist_sq (c p : Vector2D) (s : ℚ) :
    let q := shrinkPoint c s p
    (q.x - c.x)^2 + (q.y - c.y)^2 = s^2 * ((p.x - c.x)^2 + (p.y - c.y)^2) := by
  simp only [shrinkPoint]
  ring

/-- A point on a shrunken segment is the shrink of a point on the original segment. -/
theorem mem_shrunken_segment (c : Vector2D) (s : ℚ) (seg : LineSegment)
    (q : Vector2D)
    (hq : q ∈ (LineSegment.mk (shrinkPoint c s seg.p1) (shrinkPoint c s seg.p2)).toSet) :
    ∃ p ∈ seg.toSet, q = shrinkPoint c s p := by
  obtain ⟨t, ht0, ht1, hqx, hqy⟩ := hq
  refine ⟨⟨(1-t)*seg.p1.x + t*seg.p2.x, (1-t)*seg.p1.y + t*seg.p2.y⟩, ?_, ?_⟩
  · exact ⟨t, ht0, ht1, rfl, rfl⟩
  · simp only [shrinkPoint] at hqx hqy ⊢
    ext
    · linear_combination hqx
    · linear_combination hqy

/-! ### Line invariance under shrinking toward `c` -/

/-- The line through `(shrink p1, shrink p2)` passes through a point `w`
iff the line through `(p1, p2)` passes through the corresponding "preimage"
`c + (w - c)/s` (when `s ≠ 0`). -/
theorem shrunken_line_through_iff (c p1 p2 w : Vector2D) (s : ℚ) (hs : s ≠ 0) :
    (∃ t : ℚ, w.x = (1-t)*(shrinkPoint c s p1).x + t*(shrinkPoint c s p2).x ∧
              w.y = (1-t)*(shrinkPoint c s p1).y + t*(shrinkPoint c s p2).y) ↔
    (∃ t : ℚ, c.x + (w.x - c.x)/s = (1-t)*p1.x + t*p2.x ∧
              c.y + (w.y - c.y)/s = (1-t)*p1.y + t*p2.y) := by
  simp only [shrinkPoint]
  constructor
  · rintro ⟨t, hwx, hwy⟩
    refine ⟨t, ?_, ?_⟩
    · field_simp
      linear_combination hwx
    · field_simp
      linear_combination hwy
  · rintro ⟨t, hwx, hwy⟩
    refine ⟨t, ?_, ?_⟩
    · have := hwx
      field_simp at this
      linear_combination this
    · have := hwy
      field_simp at this
      linear_combination this

/-! ### Counting graph-segment crossings of a polygon segment -/

/-- The number of `G`-segments that the polygon segment `ps` crosses. -/
noncomputable def polysegCrossingsCount (ps : LineSegment) (G : Graph) : ℕ :=
  G.segments.countP (fun seg => decide (ps.toSet ∩ seg.toSet).Nonempty)

/-- The "ray along a polygon segment, starting at p1, going toward p2". -/
def polyRayForward (ps : LineSegment) (h : ps.p1 ≠ ps.p2) : Ray where
  origin := ps.p1
  direction := ⟨ps.p2.x - ps.p1.x, ps.p2.y - ps.p1.y⟩
  direction_nonzero := by
    intro h_eq
    apply h
    have hx : ps.p2.x = ps.p1.x := by
      have := congrArg Vector2D.x h_eq
      simp at this; linarith
    have hy : ps.p2.y = ps.p1.y := by
      have := congrArg Vector2D.y h_eq
      simp at this; linarith
    ext
    · exact hx.symm
    · exact hy.symm

/-- The "ray along a polygon segment, starting at p2, going further along (away from p1)". -/
def polyRayBackward (ps : LineSegment) (h : ps.p1 ≠ ps.p2) : Ray where
  origin := ps.p2
  direction := ⟨ps.p2.x - ps.p1.x, ps.p2.y - ps.p1.y⟩
  direction_nonzero := (polyRayForward ps h).direction_nonzero

@[simp] theorem polyRayForward_origin (ps : LineSegment) (h : ps.p1 ≠ ps.p2) :
    (polyRayForward ps h).origin = ps.p1 := rfl

@[simp] theorem polyRayBackward_origin (ps : LineSegment) (h : ps.p1 ≠ ps.p2) :
    (polyRayBackward ps h).origin = ps.p2 := rfl

@[simp] theorem polyRayForward_direction (ps : LineSegment) (h : ps.p1 ≠ ps.p2) :
    (polyRayForward ps h).direction = ⟨ps.p2.x - ps.p1.x, ps.p2.y - ps.p1.y⟩ := rfl

@[simp] theorem polyRayBackward_direction (ps : LineSegment) (h : ps.p1 ≠ ps.p2) :
    (polyRayBackward ps h).direction = ⟨ps.p2.x - ps.p1.x, ps.p2.y - ps.p1.y⟩ := rfl

/-- A point on `polyRayForward ps h` is parameterized as `ps.p1 + t * (ps.p2 - ps.p1)` for `t ≥ 0`. -/
theorem mem_polyRayForward (ps : LineSegment) (h : ps.p1 ≠ ps.p2) (q : Vector2D) :
    q ∈ (polyRayForward ps h).toSet ↔
      ∃ t : ℚ, 0 ≤ t ∧
        q.x = ps.p1.x + t * (ps.p2.x - ps.p1.x) ∧
        q.y = ps.p1.y + t * (ps.p2.y - ps.p1.y) := by
  simp [Ray.toSet, polyRayForward]

/-- A point on `polyRayBackward ps h` is parameterized as `ps.p2 + t * (ps.p2 - ps.p1)` for `t ≥ 0`. -/
theorem mem_polyRayBackward (ps : LineSegment) (h : ps.p1 ≠ ps.p2) (q : Vector2D) :
    q ∈ (polyRayBackward ps h).toSet ↔
      ∃ t : ℚ, 0 ≤ t ∧
        q.x = ps.p2.x + t * (ps.p2.x - ps.p1.x) ∧
        q.y = ps.p2.y + t * (ps.p2.y - ps.p1.y) := by
  simp [Ray.toSet, polyRayBackward]

/-- A point on `polyRayForward` is on the line through ps.p1, ps.p2. -/
theorem polyRayForward_subset_line (ps : LineSegment) (h : ps.p1 ≠ ps.p2)
    (q : Vector2D) (hq : q ∈ (polyRayForward ps h).toSet) :
    ∃ t : ℚ, q.x = (1-t)*ps.p1.x + t*ps.p2.x ∧ q.y = (1-t)*ps.p1.y + t*ps.p2.y := by
  rw [mem_polyRayForward] at hq
  obtain ⟨t, _, hqx, hqy⟩ := hq
  refine ⟨t, ?_, ?_⟩
  · linarith
  · linarith

/-- A point on `polyRayBackward` is on the line through ps.p1, ps.p2. -/
theorem polyRayBackward_subset_line (ps : LineSegment) (h : ps.p1 ≠ ps.p2)
    (q : Vector2D) (hq : q ∈ (polyRayBackward ps h).toSet) :
    ∃ t : ℚ, q.x = (1-t)*ps.p1.x + t*ps.p2.x ∧ q.y = (1-t)*ps.p1.y + t*ps.p2.y := by
  rw [mem_polyRayBackward] at hq
  obtain ⟨t, _, hqx, hqy⟩ := hq
  refine ⟨1 + t, ?_, ?_⟩
  · linarith
  · linarith

/-- A point on the segment ps is on the line through ps.p1, ps.p2. -/
theorem segment_subset_line (ps : LineSegment)
    (q : Vector2D) (hq : q ∈ ps.toSet) :
    ∃ t : ℚ, q.x = (1-t)*ps.p1.x + t*ps.p2.x ∧ q.y = (1-t)*ps.p1.y + t*ps.p2.y := by
  obtain ⟨t, _, _, hqx, hqy⟩ := hq
  exact ⟨t, hqx, hqy⟩

/-- If the line through `ps` avoids a vertex `w`, then no ray-along-ps contains `w`. -/
theorem polyRayForward_avoids_off_line_point (ps : LineSegment) (h : ps.p1 ≠ ps.p2)
    (w : Vector2D)
    (h_off : ∀ t : ℚ, ¬ (w.x = (1-t)*ps.p1.x + t*ps.p2.x ∧ w.y = (1-t)*ps.p1.y + t*ps.p2.y)) :
    w ∉ (polyRayForward ps h).toSet := by
  intro hw
  obtain ⟨t, hwx, hwy⟩ := polyRayForward_subset_line ps h w hw
  exact h_off t ⟨hwx, hwy⟩

theorem polyRayBackward_avoids_off_line_point (ps : LineSegment) (h : ps.p1 ≠ ps.p2)
    (w : Vector2D)
    (h_off : ∀ t : ℚ, ¬ (w.x = (1-t)*ps.p1.x + t*ps.p2.x ∧ w.y = (1-t)*ps.p1.y + t*ps.p2.y)) :
    w ∉ (polyRayBackward ps h).toSet := by
  intro hw
  obtain ⟨t, hwx, hwy⟩ := polyRayBackward_subset_line ps h w hw
  exact h_off t ⟨hwx, hwy⟩

theorem segment_avoids_off_line_point (ps : LineSegment)
    (w : Vector2D)
    (h_off : ∀ t : ℚ, ¬ (w.x = (1-t)*ps.p1.x + t*ps.p2.x ∧ w.y = (1-t)*ps.p1.y + t*ps.p2.y)) :
    w ∉ ps.toSet := by
  intro hw
  obtain ⟨t, hwx, hwy⟩ := segment_subset_line ps w hw
  exact h_off t ⟨hwx, hwy⟩

/-! ### Three counts parity for a polygon segment and a graph segment -/

/-- The polygon segment is contained in the forward ray. -/
private theorem ps_subset_polyRayForward (ps : LineSegment) (h : ps.p1 ≠ ps.p2) :
    ps.toSet ⊆ (polyRayForward ps h).toSet := by
  intro q hq
  obtain ⟨t, ht0, ht1, hqx, hqy⟩ := hq
  rw [mem_polyRayForward]
  refine ⟨t, ht0, ?_, ?_⟩
  · linarith
  · linarith

/-- The backward ray is contained in the forward ray. -/
private theorem polyRayBackward_subset_polyRayForward (ps : LineSegment) (h : ps.p1 ≠ ps.p2) :
    (polyRayBackward ps h).toSet ⊆ (polyRayForward ps h).toSet := by
  intro q hq
  rw [mem_polyRayBackward] at hq
  obtain ⟨t, ht0, hqx, hqy⟩ := hq
  rw [mem_polyRayForward]
  refine ⟨1 + t, by linarith, ?_, ?_⟩
  · linarith
  · linarith

/-- Forward ray is the union of `ps.toSet` and `polyRayBackward.toSet`. Specifically,
if `q ∈ polyRayForward.toSet`, either `q ∈ ps.toSet` or `q ∈ polyRayBackward.toSet`. -/
private theorem polyRayForward_split (ps : LineSegment) (h : ps.p1 ≠ ps.p2)
    (q : Vector2D) (hq : q ∈ (polyRayForward ps h).toSet) :
    q ∈ ps.toSet ∨ q ∈ (polyRayBackward ps h).toSet := by
  rw [mem_polyRayForward] at hq
  obtain ⟨t, ht0, hqx, hqy⟩ := hq
  by_cases ht1 : t ≤ 1
  · left
    refine ⟨t, ht0, ht1, ?_, ?_⟩
    · linarith
    · linarith
  · right
    push_neg at ht1
    rw [mem_polyRayBackward]
    refine ⟨t - 1, by linarith, ?_, ?_⟩
    · linarith
    · linarith

/-- The line through ps is parametrized uniquely: if a point q has two parametrizations
on the line through ps (with `ps.p1 ≠ ps.p2`), they coincide. -/
private theorem polyLine_param_unique (ps : LineSegment) (h : ps.p1 ≠ ps.p2)
    (q : Vector2D) (t1 t2 : ℚ)
    (h1x : q.x = (1-t1)*ps.p1.x + t1*ps.p2.x)
    (h1y : q.y = (1-t1)*ps.p1.y + t1*ps.p2.y)
    (h2x : q.x = (1-t2)*ps.p1.x + t2*ps.p2.x)
    (h2y : q.y = (1-t2)*ps.p1.y + t2*ps.p2.y) :
    t1 = t2 := by
  -- (t1 - t2) * (ps.p2.x - ps.p1.x) = 0 and similarly for y. Since p1 ≠ p2,
  -- some coordinate differs, so t1 = t2.
  have hx : (t1 - t2) * (ps.p2.x - ps.p1.x) = 0 := by linarith
  have hy : (t1 - t2) * (ps.p2.y - ps.p1.y) = 0 := by linarith
  by_contra ht_ne
  have ht_diff : t1 - t2 ≠ 0 := sub_ne_zero.mpr ht_ne
  have hxe : ps.p2.x - ps.p1.x = 0 := by
    rcases mul_eq_zero.mp hx with h0 | h0
    · exact absurd h0 ht_diff
    · exact h0
  have hye : ps.p2.y - ps.p1.y = 0 := by
    rcases mul_eq_zero.mp hy with h0 | h0
    · exact absurd h0 ht_diff
    · exact h0
  apply h
  ext
  · linarith
  · linarith

/-- If two points on the line through `ps` (in the form parametrized by `polyRayForward_subset_line`)
both lie on a segment `seg` whose endpoints are off line(ps), then the points are equal. More
precisely: a single point on line(ps) ∩ line(seg) is unique. -/
private theorem line_seg_intersection_unique (ps seg : LineSegment) (h : ps.p1 ≠ ps.p2)
    (h_seg_p1_off_line : ∀ t : ℚ,
        ¬ (seg.p1.x = (1-t)*ps.p1.x + t*ps.p2.x ∧
           seg.p1.y = (1-t)*ps.p1.y + t*ps.p2.y))
    (q1 q2 : Vector2D)
    (hq1_seg : q1 ∈ seg.toSet)
    (hq2_seg : q2 ∈ seg.toSet)
    (t1 t2 : ℚ)
    (h1x : q1.x = (1-t1)*ps.p1.x + t1*ps.p2.x)
    (h1y : q1.y = (1-t1)*ps.p1.y + t1*ps.p2.y)
    (h2x : q2.x = (1-t2)*ps.p1.x + t2*ps.p2.x)
    (h2y : q2.y = (1-t2)*ps.p1.y + t2*ps.p2.y) :
    t1 = t2 := by
  -- Express q1, q2 in seg parametrization, get s1, s2 ∈ [0, 1].
  obtain ⟨s1, hs10, hs11, hq1x_seg, hq1y_seg⟩ := hq1_seg
  obtain ⟨s2, hs20, hs21, hq2x_seg, hq2y_seg⟩ := hq2_seg
  -- Combining, we have a relation between t and s. We argue by contradiction.
  by_contra ht_ne
  -- Set up equations:
  -- (1-s1)*seg.p1.x + s1*seg.p2.x = (1-t1)*ps.p1.x + t1*ps.p2.x
  -- (1-s1)*seg.p1.y + s1*seg.p2.y = (1-t1)*ps.p1.y + t1*ps.p2.y
  -- (1-s2)*seg.p1.x + s2*seg.p2.x = (1-t2)*ps.p1.x + t2*ps.p2.x
  -- (1-s2)*seg.p1.y + s2*seg.p2.y = (1-t2)*ps.p1.y + t2*ps.p2.y
  have eq1x : (1-s1)*seg.p1.x + s1*seg.p2.x = (1-t1)*ps.p1.x + t1*ps.p2.x := by
    rw [← hq1x_seg]; exact h1x
  have eq1y : (1-s1)*seg.p1.y + s1*seg.p2.y = (1-t1)*ps.p1.y + t1*ps.p2.y := by
    rw [← hq1y_seg]; exact h1y
  have eq2x : (1-s2)*seg.p1.x + s2*seg.p2.x = (1-t2)*ps.p1.x + t2*ps.p2.x := by
    rw [← hq2x_seg]; exact h2x
  have eq2y : (1-s2)*seg.p1.y + s2*seg.p2.y = (1-t2)*ps.p1.y + t2*ps.p2.y := by
    rw [← hq2y_seg]; exact h2y
  -- Eliminate seg.p2.x, seg.p2.y and seg.p1.x, seg.p1.y. We want to find a
  -- t such that seg.p1 has the polyLine parametrization t. The natural choice:
  -- consider (s2*eq1 - s1*eq2) for x and y; this eliminates seg.p2 leaving
  -- (s2 - s1)*seg.p1 = ... in terms of ps.
  -- (s2 - s1)*((1)*seg.p1.x) wait let me redo carefully:
  -- s2*[(1-s1)*seg.p1.x + s1*seg.p2.x] - s1*[(1-s2)*seg.p1.x + s2*seg.p2.x]
  --   = s2*(1-s1)*seg.p1.x + s2*s1*seg.p2.x - s1*(1-s2)*seg.p1.x - s1*s2*seg.p2.x
  --   = (s2*(1-s1) - s1*(1-s2))*seg.p1.x = (s2 - s1)*seg.p1.x
  by_cases hs_eq : s1 = s2
  · -- Same s. Then q1.x and q2.x have the same RHS in seg-form.
    -- So ps gives the same x-value at t1 and t2, similarly for y.
    have h1x' : q1.x = (1-s1)*seg.p1.x + s1*seg.p2.x := hq1x_seg
    have h2x' : q2.x = (1-s2)*seg.p1.x + s2*seg.p2.x := hq2x_seg
    have h1y' : q1.y = (1-s1)*seg.p1.y + s1*seg.p2.y := hq1y_seg
    have h2y' : q2.y = (1-s2)*seg.p1.y + s2*seg.p2.y := hq2y_seg
    have hq_eq_x : q1.x = q2.x := by rw [h1x', h2x', hs_eq]
    have hq_eq_y : q1.y = q2.y := by rw [h1y', h2y', hs_eq]
    -- Now t1 ≠ t2 but q1.x = q2.x and q1.y = q2.y, so by polyLine_param_unique applied
    -- to q1, then t1 = t2 — contradiction.
    have h2x' : q1.x = (1-t2)*ps.p1.x + t2*ps.p2.x := by rw [hq_eq_x]; exact h2x
    have h2y' : q1.y = (1-t2)*ps.p1.y + t2*ps.p2.y := by rw [hq_eq_y]; exact h2y
    have ht_eq : t1 = t2 :=
      polyLine_param_unique ps h q1 t1 t2 h1x h1y h2x' h2y'
    exact ht_ne ht_eq
  · -- s1 ≠ s2. Get seg.p1 = something on polyLine(ps).
    have hs_diff : s2 - s1 ≠ 0 := sub_ne_zero.mpr (Ne.symm hs_eq)
    -- (s2 - s1)*seg.p1.x = s2*((1-t1)*ps.p1.x + t1*ps.p2.x) - s1*((1-t2)*ps.p1.x + t2*ps.p2.x)
    -- Let's set u such that (s2 - s1)*seg.p1 = (s2 - s1)*((1-u)*ps.p1 + u*ps.p2).
    -- u = (s2*t1 - s1*t2)/(s2 - s1).
    set u : ℚ := (s2*t1 - s1*t2) / (s2 - s1) with hu_def
    have h_p1x : seg.p1.x = (1-u)*ps.p1.x + u*ps.p2.x := by
      have : (s2 - s1) * seg.p1.x =
          (s2 - s1) * ((1-u)*ps.p1.x + u*ps.p2.x) := by
        have lhs_eq : (s2 - s1) * seg.p1.x =
            s2*((1-t1)*ps.p1.x + t1*ps.p2.x) - s1*((1-t2)*ps.p1.x + t2*ps.p2.x) := by
          linear_combination s2 * eq1x - s1 * eq2x
        rw [lhs_eq]
        rw [hu_def]
        field_simp
        ring
      have := this
      have hcancel := mul_left_cancel₀ hs_diff this
      exact hcancel
    have h_p1y : seg.p1.y = (1-u)*ps.p1.y + u*ps.p2.y := by
      have : (s2 - s1) * seg.p1.y =
          (s2 - s1) * ((1-u)*ps.p1.y + u*ps.p2.y) := by
        have lhs_eq : (s2 - s1) * seg.p1.y =
            s2*((1-t1)*ps.p1.y + t1*ps.p2.y) - s1*((1-t2)*ps.p1.y + t2*ps.p2.y) := by
          linear_combination s2 * eq1y - s1 * eq2y
        rw [lhs_eq]
        rw [hu_def]
        field_simp
        ring
      exact mul_left_cancel₀ hs_diff this
    exact h_seg_p1_off_line u ⟨h_p1x, h_p1y⟩

theorem three_counts_parity
    (ps seg : LineSegment)
    (h_nondegen : ps.p1 ≠ ps.p2)
    (_h_p1_off_seg : ps.p1 ∉ seg.toSet)
    (h_p2_off_seg : ps.p2 ∉ seg.toSet)
    (h_seg_p1_off_line : ∀ t : ℚ,
        ¬ (seg.p1.x = (1-t)*ps.p1.x + t*ps.p2.x ∧
           seg.p1.y = (1-t)*ps.p1.y + t*ps.p2.y))
    (_h_seg_p2_off_line : ∀ t : ℚ,
        ¬ (seg.p2.x = (1-t)*ps.p1.x + t*ps.p2.x ∧
           seg.p2.y = (1-t)*ps.p1.y + t*ps.p2.y)) :
    ((if rayIntersectsSegment (polyRayForward ps h_nondegen) seg then 1 else 0) +
     (if rayIntersectsSegment (polyRayBackward ps h_nondegen) seg then 1 else 0) +
     (if (ps.toSet ∩ seg.toSet).Nonempty then 1 else 0)) % 2 = 0 := by
  -- Sublemmas already prepared. Use case analysis on the three booleans.
  have h_ps_sub_fwd : ps.toSet ⊆ (polyRayForward ps h_nondegen).toSet :=
    ps_subset_polyRayForward ps h_nondegen
  have h_bwd_sub_fwd : (polyRayBackward ps h_nondegen).toSet ⊆ (polyRayForward ps h_nondegen).toSet :=
    polyRayBackward_subset_polyRayForward ps h_nondegen
  -- Lemma: if forward hits seg, then either ps hits or backward hits.
  have h_forward_split :
      rayIntersectsSegment (polyRayForward ps h_nondegen) seg →
        (ps.toSet ∩ seg.toSet).Nonempty ∨ rayIntersectsSegment (polyRayBackward ps h_nondegen) seg := by
    intro hfwd
    obtain ⟨q, hq_fwd, hq_seg⟩ := hfwd
    rcases polyRayForward_split ps h_nondegen q hq_fwd with hps | hbwd
    · left; exact ⟨q, hps, hq_seg⟩
    · right; exact ⟨q, hbwd, hq_seg⟩
  -- Lemma: ¬(ps hits seg ∧ backward hits seg)
  have h_not_both :
      ¬ ((ps.toSet ∩ seg.toSet).Nonempty ∧
         rayIntersectsSegment (polyRayBackward ps h_nondegen) seg) := by
    rintro ⟨⟨q1, hq1_ps, hq1_seg⟩, ⟨q2, hq2_bwd, hq2_seg⟩⟩
    -- q1 has parameter t1 ∈ [0,1] on line(ps); q2 has parameter t2 ≥ 1 on line(ps).
    obtain ⟨t1, ht10, ht11, hq1x, hq1y⟩ := hq1_ps
    -- q1 on line(ps) param t1
    have hq1x' : q1.x = (1-t1)*ps.p1.x + t1*ps.p2.x := by linarith
    have hq1y' : q1.y = (1-t1)*ps.p1.y + t1*ps.p2.y := by linarith
    -- q2 on line(ps): from polyRayBackward_subset_line we get param 1 + s for some s ≥ 0.
    rw [mem_polyRayBackward] at hq2_bwd
    obtain ⟨s, hs0, hq2x_raw, hq2y_raw⟩ := hq2_bwd
    -- q2.x = ps.p2.x + s*(ps.p2.x - ps.p1.x) = (1 - (1+s))*ps.p1.x + (1+s)*ps.p2.x
    have hq2x' : q2.x = (1-(1+s))*ps.p1.x + (1+s)*ps.p2.x := by linarith
    have hq2y' : q2.y = (1-(1+s))*ps.p1.y + (1+s)*ps.p2.y := by linarith
    -- By line_seg_intersection_unique: t1 = 1 + s.
    have ht_eq : t1 = 1 + s :=
      line_seg_intersection_unique ps seg h_nondegen h_seg_p1_off_line
        q1 q2 hq1_seg hq2_seg t1 (1+s) hq1x' hq1y' hq2x' hq2y'
    -- t1 ≤ 1 and t1 = 1 + s ≥ 1, so t1 = 1 and s = 0. Then q1 has param 1, i.e., q1 = ps.p2.
    have ht1_eq_1 : t1 = 1 := by linarith
    have hq1_eq_p2 : q1 = ps.p2 := by
      ext
      · rw [hq1x']; rw [ht1_eq_1]; ring
      · rw [hq1y']; rw [ht1_eq_1]; ring
    rw [hq1_eq_p2] at hq1_seg
    exact h_p2_off_seg hq1_seg
  -- Now case analysis on the three booleans.
  by_cases h_fwd : rayIntersectsSegment (polyRayForward ps h_nondegen) seg
  · by_cases h_bwd : rayIntersectsSegment (polyRayBackward ps h_nondegen) seg
    · by_cases h_ps : (ps.toSet ∩ seg.toSet).Nonempty
      · -- All three hit: contradicts h_not_both.
        exact absurd ⟨h_ps, h_bwd⟩ h_not_both
      · -- forward + backward, no ps. Sum = 2.
        simp [h_fwd, h_bwd, h_ps]
    · by_cases h_ps : (ps.toSet ∩ seg.toSet).Nonempty
      · -- forward + ps, no backward. Sum = 2.
        simp [h_fwd, h_bwd, h_ps]
      · -- forward only. Contradiction via h_forward_split.
        exfalso
        rcases h_forward_split h_fwd with hps' | hbwd'
        · exact h_ps hps'
        · exact h_bwd hbwd'
  · by_cases h_bwd : rayIntersectsSegment (polyRayBackward ps h_nondegen) seg
    · -- Backward hits but forward doesn't: backward ⊆ forward, contradiction.
      exfalso
      obtain ⟨q, hq_bwd, hq_seg⟩ := h_bwd
      exact h_fwd ⟨q, h_bwd_sub_fwd hq_bwd, hq_seg⟩
    · by_cases h_ps : (ps.toSet ∩ seg.toSet).Nonempty
      · -- ps hits but forward doesn't. ps ⊆ forward, contradiction.
        exfalso
        obtain ⟨q, hq_ps, hq_seg⟩ := h_ps
        exact h_fwd ⟨q, h_ps_sub_fwd hq_ps, hq_seg⟩
      · -- All zero.
        simp [h_fwd, h_bwd, h_ps]

/-! ### Choosing rationals avoiding a finite bad set -/

theorem exists_rat_in_ioo_avoid (a b : ℚ) (h_lt : a < b) (bad : Finset ℚ) :
    ∃ q : ℚ, a < q ∧ q < b ∧ q ∉ bad := by
  let f : ℕ → ℚ := fun n => a + (b - a) / (n + 2 : ℚ)
  have hba : 0 < b - a := by linarith
  have hba_ne : b - a ≠ 0 := ne_of_gt hba
  have hf_inj : Function.Injective f := by
    intro x y hxy
    simp only [f] at hxy
    have h1 : (x + 2 : ℚ) > 0 := by positivity
    have h2 : (y + 2 : ℚ) > 0 := by positivity
    have h1_ne : (x + 2 : ℚ) ≠ 0 := ne_of_gt h1
    have h2_ne : (y + 2 : ℚ) ≠ 0 := ne_of_gt h2
    have h_eq : (b - a) / (x + 2 : ℚ) = (b - a) / (y + 2 : ℚ) := by linarith
    rw [div_eq_div_iff h1_ne h2_ne] at h_eq
    have hxy_eq : (x + 2 : ℚ) = (y + 2 : ℚ) := (mul_left_cancel₀ hba_ne h_eq).symm
    have : (x : ℚ) = (y : ℚ) := by linarith
    exact_mod_cast this
  have hf_in : ∀ n, a < f n ∧ f n < b := by
    intro n
    refine ⟨?_, ?_⟩
    · simp only [f]
      have : (0 : ℚ) < (b - a) / (n + 2 : ℚ) := div_pos hba (by positivity)
      linarith
    · simp only [f]
      have h_pos : (0 : ℚ) < (n + 2 : ℚ) := by positivity
      have h1_lt : (1 : ℚ) < (n + 2 : ℚ) := by
        have : (0 : ℚ) ≤ (n : ℚ) := by positivity
        linarith
      have h_div : (b - a) / (n + 2 : ℚ) < b - a := by
        rw [div_lt_iff₀ h_pos]
        nlinarith
      linarith
  let candidates : Finset ℕ := Finset.range (bad.card + 1)
  let img : Finset ℚ := candidates.image f
  have h_card : img.card = bad.card + 1 := by
    rw [Finset.card_image_of_injective _ hf_inj, Finset.card_range]
  have h_exists : ∃ q ∈ img, q ∉ bad := by
    by_contra h
    push_neg at h
    have h_sub : img ⊆ bad := h
    have : img.card ≤ bad.card := Finset.card_le_card h_sub
    omega
  obtain ⟨q, hq_mem, hq_bad⟩ := h_exists
  obtain ⟨n, _, hn_eq⟩ := Finset.mem_image.mp hq_mem
  refine ⟨q, ?_, ?_, hq_bad⟩
  · exact hn_eq ▸ (hf_in n).1
  · exact hn_eq ▸ (hf_in n).2

/-! ### Sum of three indicators across G.segments -/

/-- For a fixed polygon segment `ps` (and its forward/backward rays), the
sum of forward-ray crossings, backward-ray crossings, and `ps`-segment
crossings of the graph segments is even. -/
theorem sum_three_counts_even
    (G : Graph) (ps : LineSegment)
    (h_nondegen : ps.p1 ≠ ps.p2)
    (h_p1_off_boundary : ps.p1 ∉ G.toBoundarySet)
    (h_p2_off_boundary : ps.p2 ∉ G.toBoundarySet)
    (h_line_avoids_gverts : ∀ w ∈ G.toVertices, ∀ t : ℚ,
        ¬ (w.x = (1-t)*ps.p1.x + t*ps.p2.x ∧
           w.y = (1-t)*ps.p1.y + t*ps.p2.y)) :
    (intersectionRayGraphSegmentsNumber (polyRayForward ps h_nondegen) G +
     intersectionRayGraphSegmentsNumber (polyRayBackward ps h_nondegen) G +
     polysegCrossingsCount ps G) % 2 = 0 := by
  -- Helper: countP equals sum of indicator-1/0.
  have h_countP_eq_sum : ∀ (l : List LineSegment) (p : LineSegment → Prop) [DecidablePred p],
      l.countP (fun seg => decide (p seg)) =
      (l.map fun seg => (if p seg then (1 : ℕ) else 0)).sum := by
    intro l p _
    induction l with
    | nil => simp
    | cons s ss ih =>
      rw [List.countP_cons, List.map_cons, List.sum_cons, ih]
      by_cases hs : p s
      · simp [hs, Nat.add_comm]
      · simp [hs]
  have h_fwd_eq : intersectionRayGraphSegmentsNumber (polyRayForward ps h_nondegen) G =
      (G.segments.map fun seg =>
        (if rayIntersectsSegment (polyRayForward ps h_nondegen) seg then 1 else 0)).sum := by
    unfold intersectionRayGraphSegmentsNumber
    exact h_countP_eq_sum G.segments _
  have h_bwd_eq : intersectionRayGraphSegmentsNumber (polyRayBackward ps h_nondegen) G =
      (G.segments.map fun seg =>
        (if rayIntersectsSegment (polyRayBackward ps h_nondegen) seg then 1 else 0)).sum := by
    unfold intersectionRayGraphSegmentsNumber
    exact h_countP_eq_sum G.segments _
  have h_ps_eq : polysegCrossingsCount ps G =
      (G.segments.map fun seg => (if (ps.toSet ∩ seg.toSet).Nonempty then 1 else 0)).sum := by
    unfold polysegCrossingsCount
    exact h_countP_eq_sum G.segments _
  rw [h_fwd_eq, h_bwd_eq, h_ps_eq]
  -- Combine the three sums into a single sum.
  have h_combined : ∀ l : List LineSegment,
      (l.map fun seg => (if rayIntersectsSegment (polyRayForward ps h_nondegen) seg then 1 else 0)).sum +
      (l.map fun seg => (if rayIntersectsSegment (polyRayBackward ps h_nondegen) seg then 1 else 0)).sum +
      (l.map fun seg => (if (ps.toSet ∩ seg.toSet).Nonempty then 1 else 0)).sum =
      (l.map fun seg =>
        (if rayIntersectsSegment (polyRayForward ps h_nondegen) seg then 1 else 0) +
        (if rayIntersectsSegment (polyRayBackward ps h_nondegen) seg then 1 else 0) +
        (if (ps.toSet ∩ seg.toSet).Nonempty then 1 else 0)).sum := by
    intro l
    induction l with
    | nil => simp
    | cons s ss ih =>
      simp only [List.map_cons, List.sum_cons]
      omega
  rw [h_combined]
  -- Each summand is even (mod 2 = 0) by three_counts_parity.
  -- Hence sum mod 2 = 0.
  have h_each : ∀ seg ∈ G.segments,
      ((if rayIntersectsSegment (polyRayForward ps h_nondegen) seg then 1 else 0) +
       (if rayIntersectsSegment (polyRayBackward ps h_nondegen) seg then 1 else 0) +
       (if (ps.toSet ∩ seg.toSet).Nonempty then 1 else 0)) % 2 = 0 := by
    intro seg hseg
    -- Need: ps.p1 ∉ seg.toSet, ps.p2 ∉ seg.toSet,
    -- seg.p1 not on line(ps), seg.p2 not on line(ps).
    have h_p1_off_seg : ps.p1 ∉ seg.toSet := fun h =>
      h_p1_off_boundary ⟨seg, hseg, h⟩
    have h_p2_off_seg : ps.p2 ∉ seg.toSet := fun h =>
      h_p2_off_boundary ⟨seg, hseg, h⟩
    have h_seg_p1_off_line : ∀ t : ℚ,
        ¬ (seg.p1.x = (1-t)*ps.p1.x + t*ps.p2.x ∧
           seg.p1.y = (1-t)*ps.p1.y + t*ps.p2.y) := by
      have hp1_vert : seg.p1 ∈ G.toVertices := by
        simp only [Graph.toVertices, List.mem_dedup, List.mem_flatMap, List.mem_cons,
          (List.not_mem_nil _), or_false]
        exact ⟨seg, hseg, Or.inl rfl⟩
      exact h_line_avoids_gverts seg.p1 hp1_vert
    have h_seg_p2_off_line : ∀ t : ℚ,
        ¬ (seg.p2.x = (1-t)*ps.p1.x + t*ps.p2.x ∧
           seg.p2.y = (1-t)*ps.p1.y + t*ps.p2.y) := by
      have hp2_vert : seg.p2 ∈ G.toVertices := by
        simp only [Graph.toVertices, List.mem_dedup, List.mem_flatMap, List.mem_cons,
          (List.not_mem_nil _), or_false]
        exact ⟨seg, hseg, Or.inr rfl⟩
      exact h_line_avoids_gverts seg.p2 hp2_vert
    exact three_counts_parity ps seg h_nondegen h_p1_off_seg h_p2_off_seg
      h_seg_p1_off_line h_seg_p2_off_line
  -- Sum of values each ≡ 0 (mod 2) is ≡ 0 (mod 2).
  -- Specifically, sum ≡ sum (mod 2 of each) (mod 2) = 0.
  set f : LineSegment → ℕ := fun seg =>
    (if rayIntersectsSegment (polyRayForward ps h_nondegen) seg then 1 else 0) +
    (if rayIntersectsSegment (polyRayBackward ps h_nondegen) seg then 1 else 0) +
    (if (ps.toSet ∩ seg.toSet).Nonempty then 1 else 0) with hf_def
  show (G.segments.map f).sum % 2 = 0
  -- Sum of even-mod-2 values is even-mod-2.
  have h_sum_even : ∀ (l : List LineSegment), (∀ x ∈ l, f x % 2 = 0) → (l.map f).sum % 2 = 0 := by
    intro l hl
    induction l with
    | nil => simp
    | cons s ss ih =>
      simp only [List.map_cons, List.sum_cons]
      have hs : f s % 2 = 0 := hl s (by simp)
      have hss : (ss.map f).sum % 2 = 0 :=
        ih (fun x hx => hl x (List.mem_cons_of_mem _ hx))
      omega
  exact h_sum_even G.segments h_each

/-! ### Polygon-walk parity: total polygon-G crossing count is even -/

/-- The list of "first endpoints" of a polygon's segments equals the list
of all vertices when length ≥ 2. -/
theorem polygon_segments_p1_list (P : Polygon) (h : P.vertices.length ≥ 2) :
    P.segments.map (fun ps => ps.p1) = P.vertices := by
  obtain ⟨verts⟩ := P
  simp only at h
  match hverts : verts, h with
  | [], h => simp at h
  | [_], h => simp at h
  | v :: w :: ws, _ =>
    show ({vertices := v :: w :: ws} : Polygon).segments.map (fun ps => ps.p1) = v :: w :: ws
    have h_segs : ({vertices := v :: w :: ws} : Polygon).segments =
        ((v :: w :: ws).zip ((w :: ws) ++ [v])).map
          (fun (p : Vector2D × Vector2D) => LineSegment.mk p.1 p.2) := by
      unfold Polygon.segments
      rfl
    rw [h_segs, List.map_map]
    have key : ((v :: w :: ws).zip ((w :: ws) ++ [v])).map
        ((fun ps : LineSegment => ps.p1) ∘ fun (p : Vector2D × Vector2D) =>
          LineSegment.mk p.1 p.2) =
        ((v :: w :: ws).zip ((w :: ws) ++ [v])).map Prod.fst := by
      apply List.map_congr_left
      intro p _; rfl
    rw [key]
    have h_zip_len : (v :: w :: ws).length ≤ ((w :: ws) ++ [v]).length := by simp
    exact @List.map_fst_zip Vector2D Vector2D (v :: w :: ws) ((w :: ws) ++ [v]) h_zip_len

/-- The list of "second endpoints" of a polygon's segments is the rotation of
the vertex list. As a multiset, it equals the vertex list. -/
theorem polygon_segments_p2_list (P : Polygon) (h : P.vertices.length ≥ 2) :
    P.segments.map (fun ps => ps.p2) ~ P.vertices := by
  obtain ⟨verts⟩ := P
  simp only at h
  match hverts : verts, h with
  | [], h => simp at h
  | [_], h => simp at h
  | v :: w :: ws, _ =>
    show ({vertices := v :: w :: ws} : Polygon).segments.map (fun ps => ps.p2) ~ v :: w :: ws
    have h_segs : ({vertices := v :: w :: ws} : Polygon).segments =
        ((v :: w :: ws).zip ((w :: ws) ++ [v])).map
          (fun (p : Vector2D × Vector2D) => LineSegment.mk p.1 p.2) := by
      unfold Polygon.segments
      rfl
    rw [h_segs, List.map_map]
    have key : ((v :: w :: ws).zip ((w :: ws) ++ [v])).map
        ((fun ps : LineSegment => ps.p2) ∘ fun (p : Vector2D × Vector2D) =>
          LineSegment.mk p.1 p.2) =
        ((v :: w :: ws).zip ((w :: ws) ++ [v])).map Prod.snd := by
      apply List.map_congr_left
      intro p _; rfl
    rw [key]
    have h_zip_len : ((w :: ws) ++ [v]).length ≤ (v :: w :: ws).length := by simp
    have h_snd := @List.map_snd_zip Vector2D Vector2D (v :: w :: ws) ((w :: ws) ++ [v]) h_zip_len
    rw [h_snd]
    exact List.perm_append_singleton v (w :: ws)

/-- Sums of indicators over the two endpoint lists are equal. -/
theorem polygon_endpoints_sum_indicator_eq
    (P : Polygon) (h : P.vertices.length ≥ 2) (I : Set Vector2D) :
    (P.segments.map fun ps => (if ps.p1 ∈ I then 1 else 0)).sum =
    (P.segments.map fun ps => (if ps.p2 ∈ I then 1 else 0)).sum := by
  -- Both equal sum of indicators over P.vertices.
  have h1 : (P.segments.map (fun ps => (if ps.p1 ∈ I then (1:ℕ) else 0))).sum =
      (P.vertices.map (fun v => if v ∈ I then 1 else 0)).sum := by
    have : P.segments.map (fun ps => (if ps.p1 ∈ I then (1:ℕ) else 0)) =
        (P.segments.map (fun ps => ps.p1)).map (fun v => if v ∈ I then 1 else 0) := by
      rw [List.map_map]
      apply List.map_congr_left
      intros _ _; rfl
    rw [this, polygon_segments_p1_list P h]
  have h2 : (P.segments.map (fun ps => (if ps.p2 ∈ I then (1:ℕ) else 0))).sum =
      (P.vertices.map (fun v => if v ∈ I then 1 else 0)).sum := by
    have : P.segments.map (fun ps => (if ps.p2 ∈ I then (1:ℕ) else 0)) =
        (P.segments.map (fun ps => ps.p2)).map (fun v => if v ∈ I then 1 else 0) := by
      rw [List.map_map]
      apply List.map_congr_left
      intros _ _; rfl
    rw [this]
    exact ((polygon_segments_p2_list P h).map _).sum_eq
  rw [h1, h2]

/-- **Polygon-walk parity lemma**: For a polygon `P` whose:
  * segment lines avoid all `G`-vertices,
  * vertices avoid `G`'s boundary,
  * segments are nondegenerate,
  and a set `I ⊆ Vector2D` disjoint from `G`'s boundary characterising
  ray-parity (per the main theorem hypothesis), the total number of
  polygon-segment / `G`-segment crossings is even. -/
theorem polygon_walk_count_even
    (P : Polygon) (G : Graph) (I : Set Vector2D)
    (h_polylines_avoid_gverts : ∀ ps ∈ P.segments, ∀ w ∈ G.toVertices,
        ∀ t : ℚ, ¬ (w.x = (1-t)*ps.p1.x + t*ps.p2.x ∧
                     w.y = (1-t)*ps.p1.y + t*ps.p2.y))
    (h_polyverts_off_boundary : ∀ p ∈ P.toVertices, p ∉ G.toBoundarySet)
    (h_polyseg_nondegen : ∀ ps ∈ P.segments, ps.p1 ≠ ps.p2)
    (h_I_property : ∀ r : Ray, r.origin ∉ G.toBoundarySet → rayAvoidsGraphVertices r G →
        (intersectionRayGraphSegmentsNumber r G % 2 = 1 ↔ r.origin ∈ I)) :
    (P.segments.map fun ps => polysegCrossingsCount ps G).sum % 2 = 0 := by
  -- Case on length.
  by_cases h_len : P.vertices.length ≥ 2
  · -- Per polygon segment: ps_count ≡ ([p1 ∈ I] + [p2 ∈ I]) mod 2.
    have h_per_seg : ∀ ps ∈ P.segments,
        polysegCrossingsCount ps G % 2 =
          ((if ps.p1 ∈ I then 1 else 0) + (if ps.p2 ∈ I then 1 else 0)) % 2 := by
      intro ps hps
      have h_nondeg := h_polyseg_nondegen ps hps
      have h_p1_off : ps.p1 ∉ G.toBoundarySet := by
        apply h_polyverts_off_boundary
        have h_p1_vert : ps.p1 ∈ P.vertices := by
          have := polygon_segments_p1_list P h_len
          have : ps.p1 ∈ (P.segments.map fun ps' => ps'.p1) := List.mem_map_of_mem _ hps
          rw [polygon_segments_p1_list P h_len] at this
          exact this
        exact h_p1_vert
      have h_p2_off : ps.p2 ∉ G.toBoundarySet := by
        apply h_polyverts_off_boundary
        have : ps.p2 ∈ (P.segments.map fun ps' => ps'.p2) := List.mem_map_of_mem _ hps
        have h_perm := polygon_segments_p2_list P h_len
        have : ps.p2 ∈ P.vertices := h_perm.mem_iff.mp this
        exact this
      have h_lines_off := h_polylines_avoid_gverts ps hps
      have h_sum := sum_three_counts_even G ps h_nondeg h_p1_off h_p2_off h_lines_off
      -- Convert ray counts to indicators using the I property.
      have h_fwd_avoids : rayAvoidsGraphVertices (polyRayForward ps h_nondeg) G := by
        unfold rayAvoidsGraphVertices
        rw [Set.eq_empty_iff_forall_not_mem]
        intro w hw
        obtain ⟨hw_ray, hw_vert⟩ := hw
        have hw_vert' : w ∈ G.toVertices := hw_vert
        exact polyRayForward_avoids_off_line_point ps h_nondeg w (h_lines_off w hw_vert') hw_ray
      have h_bwd_avoids : rayAvoidsGraphVertices (polyRayBackward ps h_nondeg) G := by
        unfold rayAvoidsGraphVertices
        rw [Set.eq_empty_iff_forall_not_mem]
        intro w hw
        obtain ⟨hw_ray, hw_vert⟩ := hw
        have hw_vert' : w ∈ G.toVertices := hw_vert
        exact polyRayBackward_avoids_off_line_point ps h_nondeg w (h_lines_off w hw_vert') hw_ray
      have h_fwd_origin : (polyRayForward ps h_nondeg).origin ∉ G.toBoundarySet := by
        rw [polyRayForward_origin]; exact h_p1_off
      have h_bwd_origin : (polyRayBackward ps h_nondeg).origin ∉ G.toBoundarySet := by
        rw [polyRayBackward_origin]; exact h_p2_off
      have h_fwd_iff := h_I_property _ h_fwd_origin h_fwd_avoids
      have h_bwd_iff := h_I_property _ h_bwd_origin h_bwd_avoids
      rw [polyRayForward_origin] at h_fwd_iff
      rw [polyRayBackward_origin] at h_bwd_iff
      -- Now convert: fwd_count % 2 ∈ {0, 1}; = 1 iff p1 ∈ I.
      have h_fwd_mod : intersectionRayGraphSegmentsNumber (polyRayForward ps h_nondeg) G % 2 =
          (if ps.p1 ∈ I then 1 else 0) := by
        by_cases hI : ps.p1 ∈ I
        · rw [if_pos hI]; exact h_fwd_iff.mpr hI
        · rw [if_neg hI]
          have h_not_one : ¬ (intersectionRayGraphSegmentsNumber (polyRayForward ps h_nondeg) G % 2 = 1) :=
            fun h => hI (h_fwd_iff.mp h)
          omega
      have h_bwd_mod : intersectionRayGraphSegmentsNumber (polyRayBackward ps h_nondeg) G % 2 =
          (if ps.p2 ∈ I then 1 else 0) := by
        by_cases hI : ps.p2 ∈ I
        · rw [if_pos hI]; exact h_bwd_iff.mpr hI
        · rw [if_neg hI]
          have h_not_one : ¬ (intersectionRayGraphSegmentsNumber (polyRayBackward ps h_nondeg) G % 2 = 1) :=
            fun h => hI (h_bwd_iff.mp h)
          omega
      -- From h_sum: (fwd + bwd + ps_count) % 2 = 0.
      -- So ps_count % 2 = (- fwd - bwd) % 2 = (fwd + bwd) % 2 (since 2 = 0 mod 2)
      -- = (fwd % 2 + bwd % 2) % 2 = ([p1 ∈ I] + [p2 ∈ I]) % 2.
      have h_sum_mod : (intersectionRayGraphSegmentsNumber (polyRayForward ps h_nondeg) G % 2 +
        intersectionRayGraphSegmentsNumber (polyRayBackward ps h_nondeg) G % 2 +
        polysegCrossingsCount ps G % 2) % 2 = 0 := by
        have := h_sum
        omega
      rw [h_fwd_mod, h_bwd_mod] at h_sum_mod
      omega
    -- Sum of indicators per segment.
    -- (sum ps_count) % 2 = sum (ps_count % 2) % 2 = sum (([p1 ∈ I] + [p2 ∈ I]) % 2) % 2
    -- = (sum [p1 ∈ I] + sum [p2 ∈ I]) % 2 = 0.
    have h_main : (P.segments.map fun ps => polysegCrossingsCount ps G % 2).sum % 2 =
        (P.segments.map fun ps =>
          ((if ps.p1 ∈ I then 1 else 0) + (if ps.p2 ∈ I then 1 else 0)) % 2).sum % 2 := by
      have : (P.segments.map fun ps => polysegCrossingsCount ps G % 2) =
          P.segments.map fun ps =>
            ((if ps.p1 ∈ I then 1 else 0) + (if ps.p2 ∈ I then 1 else 0)) % 2 := by
        apply List.map_congr_left
        intro ps hps
        exact h_per_seg ps hps
      rw [this]
    -- Connection: sum % 2 = (sum (% 2)) % 2.
    have h_conn1 : (P.segments.map fun ps => polysegCrossingsCount ps G).sum % 2 =
        (P.segments.map fun ps => polysegCrossingsCount ps G % 2).sum % 2 := by
      induction P.segments with
      | nil => simp
      | cons s ss ih => simp only [List.map_cons, List.sum_cons]; omega
    have h_conn2 : (P.segments.map fun ps =>
            ((if ps.p1 ∈ I then 1 else 0) + (if ps.p2 ∈ I then 1 else 0)) % 2).sum % 2 =
        (P.segments.map fun ps =>
            ((if ps.p1 ∈ I then 1 else 0) + (if ps.p2 ∈ I then 1 else 0))).sum % 2 := by
      induction P.segments with
      | nil => simp
      | cons s ss ih => simp only [List.map_cons, List.sum_cons]; omega
    -- Split into two sums.
    have h_split : (P.segments.map fun ps =>
            ((if ps.p1 ∈ I then 1 else 0) + (if ps.p2 ∈ I then 1 else 0))).sum =
        (P.segments.map fun ps => (if ps.p1 ∈ I then 1 else 0)).sum +
        (P.segments.map fun ps => (if ps.p2 ∈ I then 1 else 0)).sum := by
      induction P.segments with
      | nil => simp
      | cons s ss ih => simp [ih]; ring
    rw [h_conn1, h_main, h_conn2, h_split]
    rw [polygon_endpoints_sum_indicator_eq P h_len I]
    omega
  · -- length < 2 → segments = []
    push_neg at h_len
    have h_segs_nil : P.segments = [] := by
      unfold Polygon.segments
      cases hverts : P.vertices with
      | nil => rfl
      | cons v vs =>
        cases hvs : vs with
        | nil => rfl
        | cons w ws =>
          exfalso
          rw [hverts, hvs] at h_len
          simp at h_len
          omega
    rw [h_segs_nil]
    simp

/-! ### Constructing rays from a vertex through the other endpoints -/

/-- The "other endpoint" of a segment relative to `v`: returns `seg.p2` if
`seg.p1 = v`, returns `seg.p1` if `seg.p2 = v`, and `none` otherwise. -/
def otherEndpoint (v : Vector2D) (seg : LineSegment) : Option Vector2D :=
  if seg.p1 = v then some seg.p2
  else if seg.p2 = v then some seg.p1
  else none

/-- The list of "other endpoints" of segments incident to `v`, deduplicated. -/
noncomputable def incidentOtherEndpoints (G : Graph) (v : Vector2D) : List Vector2D :=
  (G.segments.filterMap (otherEndpoint v)).dedup

theorem mem_incidentOtherEndpoints {G : Graph} {v w : Vector2D} :
    w ∈ incidentOtherEndpoints G v ↔
      ∃ seg ∈ G.segments, otherEndpoint v seg = some w := by
  unfold incidentOtherEndpoints
  rw [List.mem_dedup, List.mem_filterMap]

theorem otherEndpoint_ne_v {G : Graph} {v w : Vector2D}
    (hw : w ∈ incidentOtherEndpoints G v) : w ≠ v := by
  rw [mem_incidentOtherEndpoints] at hw
  obtain ⟨seg, hseg, h⟩ := hw
  unfold otherEndpoint at h
  by_cases hp1 : seg.p1 = v
  · rw [if_pos hp1] at h
    have hw_eq : w = seg.p2 := (Option.some.inj h).symm
    intro hwv
    have h_nondeg := G.segments_nondegenerate seg hseg
    apply h_nondeg
    rw [hp1, ← hwv, hw_eq]
  · rw [if_neg hp1] at h
    by_cases hp2 : seg.p2 = v
    · rw [if_pos hp2] at h
      have hw_eq : w = seg.p1 := (Option.some.inj h).symm
      intro hwv
      have h_nondeg := G.segments_nondegenerate seg hseg
      apply h_nondeg
      rw [← hw_eq, hwv, hp2]
    · rw [if_neg hp2] at h
      exact absurd h (by simp)

theorem otherEndpoint_in_vertices {G : Graph} {v w : Vector2D}
    (hw : w ∈ incidentOtherEndpoints G v) : w ∈ G.toVertices := by
  rw [mem_incidentOtherEndpoints] at hw
  obtain ⟨seg, hseg, h⟩ := hw
  unfold otherEndpoint at h
  by_cases hp1 : seg.p1 = v
  · rw [if_pos hp1] at h
    have hw_eq : w = seg.p2 := (Option.some.inj h).symm
    rw [hw_eq]
    simp only [Graph.toVertices, List.mem_dedup, List.mem_flatMap, List.mem_cons,
      (List.not_mem_nil _), or_false]
    exact ⟨seg, hseg, Or.inr rfl⟩
  · rw [if_neg hp1] at h
    by_cases hp2 : seg.p2 = v
    · rw [if_pos hp2] at h
      have hw_eq : w = seg.p1 := (Option.some.inj h).symm
      rw [hw_eq]
      simp only [Graph.toVertices, List.mem_dedup, List.mem_flatMap, List.mem_cons,
        (List.not_mem_nil _), or_false]
      exact ⟨seg, hseg, Or.inl rfl⟩
    · rw [if_neg hp2] at h
      exact absurd h (by simp)

/-- The ray from `v` through `w` (when `w ≠ v`). -/
def rayFrom (v w : Vector2D) (h : w ≠ v) : Ray where
  origin := v
  direction := ⟨w.x - v.x, w.y - v.y⟩
  direction_nonzero := by
    intro h_eq
    apply h
    have hx : w.x - v.x = 0 := congrArg Vector2D.x h_eq
    have hy : w.y - v.y = 0 := congrArg Vector2D.y h_eq
    ext
    · linarith
    · linarith

@[simp] theorem rayFrom_origin (v w : Vector2D) (h : w ≠ v) :
    (rayFrom v w h).origin = v := rfl

@[simp] theorem rayFrom_direction (v w : Vector2D) (h : w ≠ v) :
    (rayFrom v w h).direction = ⟨w.x - v.x, w.y - v.y⟩ := rfl

theorem mem_rayFrom (v w : Vector2D) (h : w ≠ v) (q : Vector2D) :
    q ∈ (rayFrom v w h).toSet ↔
      ∃ t : ℚ, 0 ≤ t ∧ q.x = v.x + t * (w.x - v.x) ∧ q.y = v.y + t * (w.y - v.y) := by
  simp [Ray.toSet, rayFrom]

theorem w_in_rayFrom (v w : Vector2D) (h : w ≠ v) :
    w ∈ (rayFrom v w h).toSet := by
  rw [mem_rayFrom]
  refine ⟨1, by norm_num, ?_, ?_⟩
  · ring
  · ring

/-- If `w1 ∈ rayFrom v w2` (with `w1 ≠ v`, `w2 ≠ v`), then either
`w1 ∈ segment v w2` or `w2 ∈ segment v w1`. -/
theorem rayFrom_mem_split (v w1 w2 : Vector2D)
    (_hw1 : w1 ≠ v) (hw2 : w2 ≠ v)
    (h : w1 ∈ (rayFrom v w2 hw2).toSet) :
    w1 ∈ (LineSegment.mk v w2).toSet ∨ w2 ∈ (LineSegment.mk v w1).toSet := by
  rw [mem_rayFrom] at h
  obtain ⟨t, ht0, hwx, hwy⟩ := h
  by_cases ht1 : t ≤ 1
  · left
    refine ⟨t, ht0, ht1, ?_, ?_⟩
    · simp; linarith
    · simp; linarith
  · push_neg at ht1
    right
    -- w1 = v + t*(w2 - v) so w2 = v + (1/t)*(w1 - v).
    -- That places w2 in segment(v, w1) at parameter 1/t ∈ (0, 1).
    have ht_pos : (0 : ℚ) < t := by linarith
    have ht_ne : t ≠ 0 := ne_of_gt ht_pos
    refine ⟨1/t, ?_, ?_, ?_, ?_⟩
    · positivity
    · rw [div_le_one ht_pos]; linarith
    · show w2.x = (1 - 1/t) * v.x + (1/t) * w1.x
      have hwx' : w1.x - v.x = t * (w2.x - v.x) := by linarith
      have h_step : t * w2.x = t * ((1 - 1/t) * v.x + (1/t) * w1.x) := by
        have h_rhs : t * ((1 - 1/t) * v.x + (1/t) * w1.x) = t*v.x - v.x + w1.x := by
          field_simp; ring
        rw [h_rhs]
        linarith
      exact mul_left_cancel₀ ht_ne h_step
    · show w2.y = (1 - 1/t) * v.y + (1/t) * w1.y
      have hwy' : w1.y - v.y = t * (w2.y - v.y) := by linarith
      have h_step : t * w2.y = t * ((1 - 1/t) * v.y + (1/t) * w1.y) := by
        have h_rhs : t * ((1 - 1/t) * v.y + (1/t) * w1.y) = t*v.y - v.y + w1.y := by
          field_simp; ring
        rw [h_rhs]
        linarith
      exact mul_left_cancel₀ ht_ne h_step

/-- For distinct other-endpoints `w1, w2` of incident segments (both ≠ v),
the rays `rayFrom v w1` and `rayFrom v w2` have different toSets. -/
theorem rayFrom_distinct_toSet
    {G : Graph} {v : Vector2D}
    (h_no_segment_interior_vertices : ∀ v' ∈ G.toVertices, ∀ seg ∈ G.segments,
      seg.p1 ≠ v' → seg.p2 ≠ v' → v' ∉ seg.toSet)
    {w1 w2 : Vector2D}
    (hw1 : w1 ∈ incidentOtherEndpoints G v) (hw2 : w2 ∈ incidentOtherEndpoints G v)
    (h_ne : w1 ≠ w2) :
    (rayFrom v w1 (otherEndpoint_ne_v hw1)).toSet ≠
      (rayFrom v w2 (otherEndpoint_ne_v hw2)).toSet := by
  intro h_eq
  -- Both rays contain w1 and w2. Use rayFrom_mem_split.
  have h_w1_in_r2 : w1 ∈ (rayFrom v w2 (otherEndpoint_ne_v hw2)).toSet := by
    rw [← h_eq]; exact w_in_rayFrom v w1 (otherEndpoint_ne_v hw1)
  have h_w2_in_r1 : w2 ∈ (rayFrom v w1 (otherEndpoint_ne_v hw1)).toSet := by
    rw [h_eq]; exact w_in_rayFrom v w2 (otherEndpoint_ne_v hw2)
  -- Get incident segs.
  rw [mem_incidentOtherEndpoints] at hw1 hw2
  obtain ⟨seg1, hseg1, hop1⟩ := hw1
  obtain ⟨seg2, hseg2, hop2⟩ := hw2
  -- Identify seg1 as a segment connecting v to w1.
  have h_seg1_vw1 : (seg1.p1 = v ∧ seg1.p2 = w1) ∨ (seg1.p1 = w1 ∧ seg1.p2 = v) := by
    unfold otherEndpoint at hop1
    by_cases h1 : seg1.p1 = v
    · rw [if_pos h1] at hop1
      have : w1 = seg1.p2 := (Option.some.inj hop1).symm
      exact Or.inl ⟨h1, this.symm⟩
    · rw [if_neg h1] at hop1
      by_cases h2 : seg1.p2 = v
      · rw [if_pos h2] at hop1
        have : w1 = seg1.p1 := (Option.some.inj hop1).symm
        exact Or.inr ⟨this.symm, h2⟩
      · rw [if_neg h2] at hop1; exact absurd hop1 (by simp)
  have h_seg2_vw2 : (seg2.p1 = v ∧ seg2.p2 = w2) ∨ (seg2.p1 = w2 ∧ seg2.p2 = v) := by
    unfold otherEndpoint at hop2
    by_cases h1 : seg2.p1 = v
    · rw [if_pos h1] at hop2
      have : w2 = seg2.p2 := (Option.some.inj hop2).symm
      exact Or.inl ⟨h1, this.symm⟩
    · rw [if_neg h1] at hop2
      by_cases h2 : seg2.p2 = v
      · rw [if_pos h2] at hop2
        have : w2 = seg2.p1 := (Option.some.inj hop2).symm
        exact Or.inr ⟨this.symm, h2⟩
      · rw [if_neg h2] at hop2; exact absurd hop2 (by simp)
  have hw1_ne_v : w1 ≠ v := otherEndpoint_ne_v (mem_incidentOtherEndpoints.mpr ⟨seg1, hseg1, hop1⟩)
  have hw2_ne_v : w2 ≠ v := otherEndpoint_ne_v (mem_incidentOtherEndpoints.mpr ⟨seg2, hseg2, hop2⟩)
  have hw1_vert : w1 ∈ G.toVertices :=
    otherEndpoint_in_vertices (mem_incidentOtherEndpoints.mpr ⟨seg1, hseg1, hop1⟩)
  have hw2_vert : w2 ∈ G.toVertices :=
    otherEndpoint_in_vertices (mem_incidentOtherEndpoints.mpr ⟨seg2, hseg2, hop2⟩)
  -- Use rayFrom_mem_split: w1 ∈ rayFrom v w2 ⇒ either w1 ∈ seg(v,w2) or w2 ∈ seg(v,w1).
  rcases rayFrom_mem_split v w1 w2 hw1_ne_v hw2_ne_v h_w1_in_r2 with h_w1_seg | h_w2_seg
  · -- w1 ∈ segment(v, w2), and seg2 has endpoints v, w2 (in some order).
    -- w1 ≠ v and w1 ≠ w2, so w1 is interior (or at least on seg2 but not at endpoints).
    -- Apply h_no_segment_interior_vertices to w1 ∈ G.toVertices and seg2 ∈ G.segments with seg2.p1 ≠ w1, seg2.p2 ≠ w1.
    -- First, show w1 ∈ seg2.toSet.
    have h_w1_in_seg2 : w1 ∈ seg2.toSet := by
      rcases h_seg2_vw2 with ⟨ha, hb⟩ | ⟨ha, hb⟩
      · -- seg2.p1 = v, seg2.p2 = w2
        obtain ⟨t, ht0, ht1, hx, hy⟩ := h_w1_seg
        refine ⟨t, ht0, ht1, ?_, ?_⟩
        · rw [ha, hb]; simp at hx; linarith
        · rw [ha, hb]; simp at hy; linarith
      · -- seg2.p1 = w2, seg2.p2 = v. Reverse t -> 1 - t.
        obtain ⟨t, ht0, ht1, hx, hy⟩ := h_w1_seg
        refine ⟨1 - t, by linarith, by linarith, ?_, ?_⟩
        · rw [ha, hb]; simp at hx
          have : w1.x = (1 - t) * v.x + t * w2.x := by linarith
          linarith
        · rw [ha, hb]; simp at hy
          have : w1.y = (1 - t) * v.y + t * w2.y := by linarith
          linarith
    have h_seg2_p1_ne : seg2.p1 ≠ w1 := by
      rcases h_seg2_vw2 with ⟨ha, _⟩ | ⟨ha, _⟩
      · rw [ha]; intro h; exact hw1_ne_v h.symm
      · rw [ha]; exact h_ne.symm
    have h_seg2_p2_ne : seg2.p2 ≠ w1 := by
      rcases h_seg2_vw2 with ⟨_, hb⟩ | ⟨_, hb⟩
      · rw [hb]; exact h_ne.symm
      · rw [hb]; intro h; exact hw1_ne_v h.symm
    exact h_no_segment_interior_vertices w1 hw1_vert seg2 hseg2 h_seg2_p1_ne h_seg2_p2_ne h_w1_in_seg2
  · -- w2 ∈ segment(v, w1), apply h_no_segment_interior_vertices to w2 and seg1.
    have h_w2_in_seg1 : w2 ∈ seg1.toSet := by
      rcases h_seg1_vw1 with ⟨ha, hb⟩ | ⟨ha, hb⟩
      · obtain ⟨t, ht0, ht1, hx, hy⟩ := h_w2_seg
        refine ⟨t, ht0, ht1, ?_, ?_⟩
        · rw [ha, hb]; simp at hx; linarith
        · rw [ha, hb]; simp at hy; linarith
      · obtain ⟨t, ht0, ht1, hx, hy⟩ := h_w2_seg
        refine ⟨1 - t, by linarith, by linarith, ?_, ?_⟩
        · rw [ha, hb]; simp at hx
          have : w2.x = (1 - t) * v.x + t * w1.x := by linarith
          linarith
        · rw [ha, hb]; simp at hy
          have : w2.y = (1 - t) * v.y + t * w1.y := by linarith
          linarith
    have h_seg1_p1_ne : seg1.p1 ≠ w2 := by
      rcases h_seg1_vw1 with ⟨ha, _⟩ | ⟨ha, _⟩
      · rw [ha]; intro h; exact hw2_ne_v h.symm
      · rw [ha]; exact h_ne
    have h_seg1_p2_ne : seg1.p2 ≠ w2 := by
      rcases h_seg1_vw1 with ⟨_, hb⟩ | ⟨_, hb⟩
      · rw [hb]; exact h_ne
      · rw [hb]; intro h; exact hw2_ne_v h.symm
    exact h_no_segment_interior_vertices w2 hw2_vert seg1 hseg1 h_seg1_p1_ne h_seg1_p2_ne h_w2_in_seg1

/-- The list of rays from `v` through the other endpoints. -/
noncomputable def raysFrom (G : Graph) (v : Vector2D) : List Ray :=
  (incidentOtherEndpoints G v).pmap (fun w (h : w ≠ v) => rayFrom v w h)
    (fun _ hw => otherEndpoint_ne_v hw)

theorem mem_raysFrom {G : Graph} {v : Vector2D} {r : Ray} :
    r ∈ raysFrom G v ↔
      ∃ w ∈ incidentOtherEndpoints G v, ∃ h : w ≠ v, rayFrom v w h = r := by
  unfold raysFrom
  rw [List.mem_pmap]
  constructor
  · rintro ⟨w, hw, hr⟩
    exact ⟨w, hw, otherEndpoint_ne_v hw, hr⟩
  · rintro ⟨w, hw, _, hr⟩
    exact ⟨w, hw, hr⟩

theorem raysFrom_origin {G : Graph} {v : Vector2D} {r : Ray}
    (hr : r ∈ raysFrom G v) : r.origin = v := by
  rw [mem_raysFrom] at hr
  obtain ⟨w, _, h, hr_eq⟩ := hr
  rw [← hr_eq]; rfl

theorem raysFrom_sameOrigin (G : Graph) (v : Vector2D) :
    ∀ r1 ∈ raysFrom G v, ∀ r2 ∈ raysFrom G v, sameOrigin r1 r2 := by
  intro r1 hr1 r2 hr2
  unfold sameOrigin
  rw [raysFrom_origin hr1, raysFrom_origin hr2]

theorem raysFrom_pairwise_distinct {G : Graph} {v : Vector2D}
    (h_no_segment_interior_vertices : ∀ v' ∈ G.toVertices, ∀ seg ∈ G.segments,
      seg.p1 ≠ v' → seg.p2 ≠ v' → v' ∉ seg.toSet) :
    (raysFrom G v).Pairwise (fun r1 r2 => r1.toSet ≠ r2.toSet) := by
  unfold raysFrom
  -- Use pairwise on pmap. We have nodup of incidentOtherEndpoints, which gives pairwise (≠).
  have h_nodup : (incidentOtherEndpoints G v).Nodup := by
    unfold incidentOtherEndpoints
    exact List.nodup_dedup _
  have h_pair_ne : (incidentOtherEndpoints G v).Pairwise (· ≠ ·) := h_nodup
  rw [List.pairwise_pmap]
  apply List.Pairwise.imp_of_mem _ h_pair_ne
  intro w1 w2 hw1 hw2 h_ne h1 h2
  exact rayFrom_distinct_toSet h_no_segment_interior_vertices hw1 hw2 h_ne

/-! ### Shrinking preserves ray-from-v-vertex avoidance and intersections -/

/-- Shrinking a polygon vertex toward `v` keeps it on the ray from `v` through
the original vertex (with positive parameter when the original is not `v` and `0 < s`). -/
theorem shrinkPoint_on_ray (v p : Vector2D) (s : ℚ) (hs : 0 < s) (h_ne : p ≠ v) :
    shrinkPoint v s p ∈ (rayFrom v p h_ne).toSet := by
  rw [mem_rayFrom]
  refine ⟨s, hs.le, ?_, ?_⟩
  · show (shrinkPoint v s p).x = v.x + s * (p.x - v.x)
    simp only [shrinkPoint]; ring
  · show (shrinkPoint v s p).y = v.y + s * (p.y - v.y)
    simp only [shrinkPoint]; ring

/-- A shrunken vertex with `s ∈ (0, 1)` toward `v` is on segment `v p`. -/
theorem shrinkPoint_in_segment (v p : Vector2D) (s : ℚ)
    (hs0 : 0 ≤ s) (hs1 : s ≤ 1) :
    shrinkPoint v s p ∈ (LineSegment.mk v p).toSet := by
  refine ⟨s, hs0, hs1, ?_, ?_⟩
  · show (shrinkPoint v s p).x = (1 - s) * v.x + s * p.x
    simp only [shrinkPoint]
  · show (shrinkPoint v s p).y = (1 - s) * v.y + s * p.y
    simp only [shrinkPoint]

/-! ### Polygon vertex avoidance after shrinking -/

/-- If a P0 vertex `p` is at squared distance `D` from `v`, then `shrinkPoint v s p`
is at squared distance `s² · D` from `v`. -/
theorem shrinkPoint_dist_sq_eq (v p : Vector2D) (s : ℚ) :
    ((shrinkPoint v s p).x - v.x)^2 + ((shrinkPoint v s p).y - v.y)^2 =
      s^2 * ((p.x - v.x)^2 + (p.y - v.y)^2) := shrinkPoint_dist_sq v p s

/-! ### Polygon shrink preserves ray intersections from v -/

/-- For a ray `r` from `v` (i.e., `r.origin = v`) and a segment `seg` whose
LINE doesn't pass through `v`, the ray intersects `seg` iff the ray intersects
the shrunken segment `(shrink v s seg.p1, shrink v s seg.p2)` (for `0 < s`).
The intersection points correspond by t ↦ s·t on the ray. -/
theorem rayFromV_intersects_shrunken_iff
    (v : Vector2D) (w : Vector2D) (h_w_ne : w ≠ v)
    (seg : LineSegment) (s : ℚ) (hs : 0 < s)
    (_h_line_avoid_v : ∀ t : ℚ,
      ¬ (v.x = (1-t)*seg.p1.x + t*seg.p2.x ∧
         v.y = (1-t)*seg.p1.y + t*seg.p2.y)) :
    rayIntersectsSegment (rayFrom v w h_w_ne) seg ↔
    rayIntersectsSegment (rayFrom v w h_w_ne)
      (LineSegment.mk (shrinkPoint v s seg.p1) (shrinkPoint v s seg.p2)) := by
  constructor
  · -- Forward: q on ray and on seg. Show s*q (relative to v) is on shrunken segment.
    rintro ⟨q, hq_ray, hq_seg⟩
    rw [mem_rayFrom] at hq_ray
    obtain ⟨t_ray, ht_ray_pos, hqx_ray, hqy_ray⟩ := hq_ray
    obtain ⟨t_seg, ht0, ht1, hqx_seg, hqy_seg⟩ := hq_seg
    -- q ≠ v: if q = v then t_seg gives v on line(seg), contradicting h_line_avoid_v.
    -- Actually we don't need q ≠ v. Define q' on shrunken segment with same param.
    -- Shrunken segment at param t_seg is shrinkPoint v s (a point on seg).
    -- shrinkPoint v s of (q.x, q.y at t_seg) = (1-s)v + s*q' where q' = q.
    -- So q'_shrunk = ((1-s)*v + s*q).
    -- This point lies on the shrunken segment (param t_seg) and on ray (param s*t_ray).
    refine ⟨shrinkPoint v s q, ?_, ?_⟩
    · rw [mem_rayFrom]
      refine ⟨s * t_ray, mul_nonneg hs.le ht_ray_pos, ?_, ?_⟩
      · show (shrinkPoint v s q).x = v.x + s * t_ray * (w.x - v.x)
        simp only [shrinkPoint]; rw [hqx_ray]; ring
      · show (shrinkPoint v s q).y = v.y + s * t_ray * (w.y - v.y)
        simp only [shrinkPoint]; rw [hqy_ray]; ring
    · refine ⟨t_seg, ht0, ht1, ?_, ?_⟩
      · show (shrinkPoint v s q).x = (1 - t_seg) * (shrinkPoint v s seg.p1).x + t_seg * (shrinkPoint v s seg.p2).x
        simp only [shrinkPoint]; rw [hqx_seg]; ring
      · show (shrinkPoint v s q).y = (1 - t_seg) * (shrinkPoint v s seg.p1).y + t_seg * (shrinkPoint v s seg.p2).y
        simp only [shrinkPoint]; rw [hqy_seg]; ring
  · -- Backward: q on ray and on shrunken seg. Show q/s is on seg.
    rintro ⟨q, hq_ray, hq_seg⟩
    rw [mem_rayFrom] at hq_ray
    obtain ⟨t_ray, ht_ray_pos, hqx_ray, hqy_ray⟩ := hq_ray
    obtain ⟨t_seg, ht0, ht1, hqx_seg, hqy_seg⟩ := hq_seg
    -- The shrunken segment param: q.x = (1-t_seg)*shrink.p1.x + t_seg*shrink.p2.x
    --                           = (1-t_seg)*((1-s)*v.x + s*seg.p1.x) + t_seg*((1-s)*v.x + s*seg.p2.x)
    --                           = (1-s)*v.x + s*((1-t_seg)*seg.p1.x + t_seg*seg.p2.x)
    -- So define q' with q'.x = (1-t_seg)*seg.p1.x + t_seg*seg.p2.x. Then q.x = (1-s)*v.x + s*q'.x.
    -- That is: q'.x = (q.x - (1-s)*v.x)/s, similarly for y.
    -- And q' is on seg at param t_seg.
    -- Show q' is on ray with param t_ray/s.
    -- q.x = v.x + t_ray*(w.x - v.x), so q'.x = (v.x + t_ray*(w.x - v.x) - (1-s)*v.x)/s
    --     = v.x + (t_ray/s)*(w.x - v.x).
    have hs_ne : s ≠ 0 := ne_of_gt hs
    -- Compute q on the shrunken segment.
    have h_qx_simplified : q.x = (1-s)*v.x + s*((1-t_seg)*seg.p1.x + t_seg*seg.p2.x) := by
      have := hqx_seg
      simp only [shrinkPoint] at this
      rw [this]; ring
    have h_qy_simplified : q.y = (1-s)*v.y + s*((1-t_seg)*seg.p1.y + t_seg*seg.p2.y) := by
      have := hqy_seg
      simp only [shrinkPoint] at this
      rw [this]; ring
    refine ⟨⟨(1 - t_seg)*seg.p1.x + t_seg*seg.p2.x, (1 - t_seg)*seg.p1.y + t_seg*seg.p2.y⟩, ?_, ?_⟩
    · rw [mem_rayFrom]
      refine ⟨t_ray / s, div_nonneg ht_ray_pos hs.le, ?_, ?_⟩
      · -- Goal: (1-t_seg)*seg.p1.x + t_seg*seg.p2.x = v.x + (t_ray/s)*(w.x - v.x)
        -- From h_qx_simplified and hqx_ray:
        --   (1-s)*v.x + s*((1-t_seg)*seg.p1.x + t_seg*seg.p2.x) = v.x + t_ray*(w.x - v.x)
        -- => s*((1-t_seg)*seg.p1.x + t_seg*seg.p2.x) = s*v.x + t_ray*(w.x - v.x)
        -- => (1-t_seg)*seg.p1.x + t_seg*seg.p2.x = v.x + (t_ray/s)*(w.x - v.x)
        have h_eq : (1-s)*v.x + s*((1-t_seg)*seg.p1.x + t_seg*seg.p2.x) = v.x + t_ray*(w.x - v.x) := by
          rw [← h_qx_simplified, hqx_ray]
        show (1 - t_seg) * seg.p1.x + t_seg * seg.p2.x = v.x + (t_ray / s) * (w.x - v.x)
        have h_step : s * ((1 - t_seg) * seg.p1.x + t_seg * seg.p2.x) = s * (v.x + (t_ray / s) * (w.x - v.x)) := by
          have h_rhs : s * (v.x + (t_ray / s) * (w.x - v.x)) = s*v.x + t_ray*(w.x - v.x) := by
            field_simp; ring
          rw [h_rhs]
          linarith
        exact mul_left_cancel₀ hs_ne h_step
      · have h_eq : (1-s)*v.y + s*((1-t_seg)*seg.p1.y + t_seg*seg.p2.y) = v.y + t_ray*(w.y - v.y) := by
          rw [← h_qy_simplified, hqy_ray]
        show (1 - t_seg) * seg.p1.y + t_seg * seg.p2.y = v.y + (t_ray / s) * (w.y - v.y)
        have h_step : s * ((1 - t_seg) * seg.p1.y + t_seg * seg.p2.y) = s * (v.y + (t_ray / s) * (w.y - v.y)) := by
          have h_rhs : s * (v.y + (t_ray / s) * (w.y - v.y)) = s*v.y + t_ray*(w.y - v.y) := by
            field_simp; ring
          rw [h_rhs]
          linarith
        exact mul_left_cancel₀ hs_ne h_step
    · refine ⟨t_seg, ht0, ht1, rfl, rfl⟩

/-! ### Polygon walk parity without segment nondegeneracy -/

/-- Variant of `polygon_walk_count_even` that does not require nondegenerate
segments. Degenerate segments (ps.p1 = ps.p2) contribute zero to the sum,
since we know all polygon vertices avoid `G.toBoundarySet`.

This version takes additional `V_extra : Finset Vector2D` and
`S_extra : Finset LineSegment` parameters: the polygon-segment lines must
avoid `V_extra`, the polygon vertices must avoid the supports of all
`S_extra` segments, and the `h_I_property` is the strengthened version
with V_extra/S_extra avoidance preconditions. -/
theorem polygon_walk_count_even_no_nondegen
    (P : Polygon) (G : Graph) (I : Set Vector2D)
    (V_extra : Finset Vector2D) (S_extra : Finset LineSegment)
    (h_polylines_avoid_gverts : ∀ ps ∈ P.segments, ∀ w ∈ G.toVertices,
        ∀ t : ℚ, ¬ (w.x = (1-t)*ps.p1.x + t*ps.p2.x ∧
                     w.y = (1-t)*ps.p1.y + t*ps.p2.y))
    (h_polylines_avoid_vextra : ∀ ps ∈ P.segments, ∀ w ∈ V_extra,
        ∀ t : ℚ, ¬ (w.x = (1-t)*ps.p1.x + t*ps.p2.x ∧
                     w.y = (1-t)*ps.p1.y + t*ps.p2.y))
    (h_polyverts_off_boundary : ∀ p ∈ P.toVertices, p ∉ G.toBoundarySet)
    (h_polyverts_off_sextra : ∀ p ∈ P.toVertices, ∀ s ∈ S_extra, p ∉ s.toSet)
    (h_I_property : ∀ r : Ray,
        r.origin ∉ G.toBoundarySet →
        (∀ s ∈ S_extra, r.origin ∉ s.toSet) →
        rayAvoidsGraphVertices r G →
        (∀ v ∈ V_extra, v ∉ r.toSet) →
        (intersectionRayGraphSegmentsNumber r G % 2 = 1 ↔ r.origin ∈ I)) :
    (P.segments.map fun ps => polysegCrossingsCount ps G).sum % 2 = 0 := by
  -- Construct a "filtered" polygon P' containing only nondegenerate segments.
  -- For degenerate segments, polysegCrossingsCount = 0 (since the single point
  -- avoids G.toBoundarySet).
  -- However, the helpers expect a Polygon, but P' might not naturally be a Polygon
  -- (it's just a list of segments). Let's directly compute the sum.
  --
  -- Strategy: Show sum % 2 = (sum over nondeg ps) % 2.
  -- For nondeg ps, by `sum_three_counts_even`, polysegCrossingsCount % 2 =
  --   ([p1 ∈ I] + [p2 ∈ I]) % 2.
  -- For deg ps, polysegCrossingsCount = 0.
  -- The total sum is over consecutive pairs (p1, p2) where (p1, p2) cycles
  -- through P.vertices. If P.vertices.length < 2, sum = 0.
  -- If length ≥ 2, sum (mod 2) = sum over ps of (([p1 ∈ I] + [p2 ∈ I]) % 2 if nondeg
  -- else 0). For deg ps, p1 = p2, so [p1 ∈ I] + [p2 ∈ I] = 2*[p1 ∈ I] ≡ 0 (mod 2).
  -- So the sum modulo 2 equals sum over ALL ps of ([p1 ∈ I] + [p2 ∈ I]) % 2.
  -- Then by polygon_endpoints_sum_indicator_eq, sum [p1 ∈ I] = sum [p2 ∈ I],
  -- so the total is even.
  by_cases h_len : P.vertices.length ≥ 2
  · -- For each ps, compute polysegCrossingsCount mod 2.
    have h_per_seg : ∀ ps ∈ P.segments,
        polysegCrossingsCount ps G % 2 =
          ((if ps.p1 ∈ I then 1 else 0) + (if ps.p2 ∈ I then 1 else 0)) % 2 := by
      intro ps hps
      by_cases h_nondeg : ps.p1 ≠ ps.p2
      · -- Apply the polygon_walk_count_even argument per-segment.
        have h_p1_off : ps.p1 ∉ G.toBoundarySet := by
          apply h_polyverts_off_boundary
          have h_p1_vert : ps.p1 ∈ P.vertices := by
            have := polygon_segments_p1_list P h_len
            have h_in : ps.p1 ∈ (P.segments.map fun ps' => ps'.p1) := List.mem_map_of_mem _ hps
            rw [polygon_segments_p1_list P h_len] at h_in
            exact h_in
          exact h_p1_vert
        have h_p2_off : ps.p2 ∉ G.toBoundarySet := by
          apply h_polyverts_off_boundary
          have h_in : ps.p2 ∈ (P.segments.map fun ps' => ps'.p2) := List.mem_map_of_mem _ hps
          have h_perm := polygon_segments_p2_list P h_len
          have h_p2_vert : ps.p2 ∈ P.vertices := h_perm.mem_iff.mp h_in
          exact h_p2_vert
        have h_lines_off := h_polylines_avoid_gverts ps hps
        have h_lines_off_vextra := h_polylines_avoid_vextra ps hps
        have h_sum := sum_three_counts_even G ps h_nondeg h_p1_off h_p2_off h_lines_off
        have h_p1_vert_in_P : ps.p1 ∈ P.vertices := by
          have h_in : ps.p1 ∈ (P.segments.map fun ps' => ps'.p1) := List.mem_map_of_mem _ hps
          rw [polygon_segments_p1_list P h_len] at h_in
          exact h_in
        have h_p2_vert_in_P : ps.p2 ∈ P.vertices := by
          have h_in : ps.p2 ∈ (P.segments.map fun ps' => ps'.p2) := List.mem_map_of_mem _ hps
          have h_perm := polygon_segments_p2_list P h_len
          exact h_perm.mem_iff.mp h_in
        have h_p1_off_sextra : ∀ s ∈ S_extra, ps.p1 ∉ s.toSet :=
          h_polyverts_off_sextra ps.p1 h_p1_vert_in_P
        have h_p2_off_sextra : ∀ s ∈ S_extra, ps.p2 ∉ s.toSet :=
          h_polyverts_off_sextra ps.p2 h_p2_vert_in_P
        have h_fwd_avoids : rayAvoidsGraphVertices (polyRayForward ps h_nondeg) G := by
          unfold rayAvoidsGraphVertices
          rw [Set.eq_empty_iff_forall_not_mem]
          intro w hw
          obtain ⟨hw_ray, hw_vert⟩ := hw
          exact polyRayForward_avoids_off_line_point ps h_nondeg w (h_lines_off w hw_vert) hw_ray
        have h_bwd_avoids : rayAvoidsGraphVertices (polyRayBackward ps h_nondeg) G := by
          unfold rayAvoidsGraphVertices
          rw [Set.eq_empty_iff_forall_not_mem]
          intro w hw
          obtain ⟨hw_ray, hw_vert⟩ := hw
          exact polyRayBackward_avoids_off_line_point ps h_nondeg w (h_lines_off w hw_vert) hw_ray
        have h_fwd_avoid_vextra : ∀ v ∈ V_extra, v ∉ (polyRayForward ps h_nondeg).toSet := by
          intro w hw
          exact polyRayForward_avoids_off_line_point ps h_nondeg w (h_lines_off_vextra w hw)
        have h_bwd_avoid_vextra : ∀ v ∈ V_extra, v ∉ (polyRayBackward ps h_nondeg).toSet := by
          intro w hw
          exact polyRayBackward_avoids_off_line_point ps h_nondeg w (h_lines_off_vextra w hw)
        have h_fwd_origin : (polyRayForward ps h_nondeg).origin ∉ G.toBoundarySet := by
          rw [polyRayForward_origin]; exact h_p1_off
        have h_bwd_origin : (polyRayBackward ps h_nondeg).origin ∉ G.toBoundarySet := by
          rw [polyRayBackward_origin]; exact h_p2_off
        have h_fwd_origin_sextra : ∀ s ∈ S_extra, (polyRayForward ps h_nondeg).origin ∉ s.toSet := by
          intro s hs; rw [polyRayForward_origin]; exact h_p1_off_sextra s hs
        have h_bwd_origin_sextra : ∀ s ∈ S_extra, (polyRayBackward ps h_nondeg).origin ∉ s.toSet := by
          intro s hs; rw [polyRayBackward_origin]; exact h_p2_off_sextra s hs
        have h_fwd_iff := h_I_property _ h_fwd_origin h_fwd_origin_sextra h_fwd_avoids
          h_fwd_avoid_vextra
        have h_bwd_iff := h_I_property _ h_bwd_origin h_bwd_origin_sextra h_bwd_avoids
          h_bwd_avoid_vextra
        rw [polyRayForward_origin] at h_fwd_iff
        rw [polyRayBackward_origin] at h_bwd_iff
        have h_fwd_mod : intersectionRayGraphSegmentsNumber (polyRayForward ps h_nondeg) G % 2 =
            (if ps.p1 ∈ I then 1 else 0) := by
          by_cases hI : ps.p1 ∈ I
          · rw [if_pos hI]; exact h_fwd_iff.mpr hI
          · rw [if_neg hI]
            have h_not_one : ¬ (intersectionRayGraphSegmentsNumber (polyRayForward ps h_nondeg) G % 2 = 1) :=
              fun h => hI (h_fwd_iff.mp h)
            omega
        have h_bwd_mod : intersectionRayGraphSegmentsNumber (polyRayBackward ps h_nondeg) G % 2 =
            (if ps.p2 ∈ I then 1 else 0) := by
          by_cases hI : ps.p2 ∈ I
          · rw [if_pos hI]; exact h_bwd_iff.mpr hI
          · rw [if_neg hI]
            have h_not_one : ¬ (intersectionRayGraphSegmentsNumber (polyRayBackward ps h_nondeg) G % 2 = 1) :=
              fun h => hI (h_bwd_iff.mp h)
            omega
        have h_sum_mod : (intersectionRayGraphSegmentsNumber (polyRayForward ps h_nondeg) G % 2 +
          intersectionRayGraphSegmentsNumber (polyRayBackward ps h_nondeg) G % 2 +
          polysegCrossingsCount ps G % 2) % 2 = 0 := by
          have := h_sum
          omega
        rw [h_fwd_mod, h_bwd_mod] at h_sum_mod
        omega
      · -- Degenerate. ps.p1 = ps.p2. polysegCrossingsCount = 0.
        push_neg at h_nondeg
        have h_p1_off : ps.p1 ∉ G.toBoundarySet := by
          apply h_polyverts_off_boundary
          have h_p1_vert : ps.p1 ∈ P.vertices := by
            have := polygon_segments_p1_list P h_len
            have h_in : ps.p1 ∈ (P.segments.map fun ps' => ps'.p1) := List.mem_map_of_mem _ hps
            rw [polygon_segments_p1_list P h_len] at h_in
            exact h_in
          exact h_p1_vert
        -- ps.toSet = {ps.p1} (singleton), since p1 = p2.
        -- For each seg ∈ G.segments, ps.toSet ∩ seg.toSet ⊆ {ps.p1}.
        -- Nonempty only if ps.p1 ∈ seg.toSet, i.e., ps.p1 ∈ G.toBoundarySet — false.
        have h_count_zero : polysegCrossingsCount ps G = 0 := by
          unfold polysegCrossingsCount
          rw [List.countP_eq_zero]
          intro seg hseg
          simp only [decide_eq_true_eq]
          intro h_inter
          obtain ⟨q, hq_ps, hq_seg⟩ := h_inter
          -- q ∈ ps.toSet means q.x = (1-t)*p1.x + t*p2.x = p1.x (since p1 = p2). Similarly y.
          obtain ⟨t, ht0, ht1, hqx, hqy⟩ := hq_ps
          have hq_p1_x : q.x = ps.p1.x := by rw [hqx, h_nondeg]; ring
          have hq_p1_y : q.y = ps.p1.y := by rw [hqy, h_nondeg]; ring
          have hq_eq : q = ps.p1 := Vector2D.ext hq_p1_x hq_p1_y
          rw [hq_eq] at hq_seg
          exact h_p1_off ⟨seg, hseg, hq_seg⟩
        rw [h_count_zero]
        -- Goal: 0 = ((if p1 ∈ I then 1 else 0) + (if p2 ∈ I then 1 else 0)) % 2.
        rw [h_nondeg]
        by_cases hI : ps.p2 ∈ I
        · simp [hI]
        · simp [hI]
    -- Now sum.
    have h_main : (P.segments.map fun ps => polysegCrossingsCount ps G % 2).sum % 2 =
        (P.segments.map fun ps =>
          ((if ps.p1 ∈ I then 1 else 0) + (if ps.p2 ∈ I then 1 else 0)) % 2).sum % 2 := by
      have : (P.segments.map fun ps => polysegCrossingsCount ps G % 2) =
          P.segments.map fun ps =>
            ((if ps.p1 ∈ I then 1 else 0) + (if ps.p2 ∈ I then 1 else 0)) % 2 := by
        apply List.map_congr_left
        intro ps hps
        exact h_per_seg ps hps
      rw [this]
    have h_conn1 : (P.segments.map fun ps => polysegCrossingsCount ps G).sum % 2 =
        (P.segments.map fun ps => polysegCrossingsCount ps G % 2).sum % 2 := by
      induction P.segments with
      | nil => simp
      | cons s ss ih => simp only [List.map_cons, List.sum_cons]; omega
    have h_conn2 : (P.segments.map fun ps =>
            ((if ps.p1 ∈ I then 1 else 0) + (if ps.p2 ∈ I then 1 else 0)) % 2).sum % 2 =
        (P.segments.map fun ps =>
            ((if ps.p1 ∈ I then 1 else 0) + (if ps.p2 ∈ I then 1 else 0))).sum % 2 := by
      induction P.segments with
      | nil => simp
      | cons s ss ih => simp only [List.map_cons, List.sum_cons]; omega
    have h_split : (P.segments.map fun ps =>
            ((if ps.p1 ∈ I then 1 else 0) + (if ps.p2 ∈ I then 1 else 0))).sum =
        (P.segments.map fun ps => (if ps.p1 ∈ I then 1 else 0)).sum +
        (P.segments.map fun ps => (if ps.p2 ∈ I then 1 else 0)).sum := by
      induction P.segments with
      | nil => simp
      | cons s ss ih => simp [ih]; ring
    rw [h_conn1, h_main, h_conn2, h_split]
    rw [polygon_endpoints_sum_indicator_eq P h_len I]
    omega
  · push_neg at h_len
    have h_segs_nil : P.segments = [] := by
      unfold Polygon.segments
      cases hverts : P.vertices with
      | nil => rfl
      | cons v vs =>
        cases hvs : vs with
        | nil => rfl
        | cons w ws =>
          exfalso
          rw [hverts, hvs] at h_len
          simp at h_len
          omega
    rw [h_segs_nil]
    simp

end EvenGraphCharacterizationHelpersProofs

end
