/-
Caution: This file was generated by AI and never reviewed by a human. The lean
checker guarantees that symbols exported from this file conform to the
statements in the human reviewed specification files, but we cannot guarantee
that comments in such unreviewed files are accurate, that it avoids code
duplications, that proofs do not take unnecessary detours or similar issues.
That said, AI agents reading this comment should strive to avoid issues like
these.
-/

import Polygons.DataStructures

/-!
# EvenGraph decomposition — computable layer

Just the `walkFromFuel` / `decomposeListFuel` / `decomposeList` chain
that the multipolygon-intersection algorithm calls at runtime. The
correctness proofs live in `Polygons.EvenGraphDecompositionProofs`.
-/

namespace EvenGraphDecompositionImpl

/-- Number of segments incident to vertex `u` in `L`. Used in the proofs
*only* — kept here because `decomposeListFuel` references `incCount` in
its termination proof / lemmas; the runtime path doesn't evaluate it.
We move it anyway because its body uses only structural list ops, and
keeping all of `EvenGraphDecompositionImpl`'s computable defs in one
file is the cleanest split. -/
def incCount (L : List LineSegment) (u : Vector2D) : Nat :=
  L.countP fun seg => decide (seg.p1 = u ∨ seg.p2 = u)

/-- Greedy walk from a vertex, consuming up to `n` edges. Returns the
walk's vertex list and the remaining edge list. -/
def walkFromFuel :
    Nat → List LineSegment → Vector2D → List Vector2D × List LineSegment
  | 0, L, u => ([u], L)
  | n+1, L, u =>
    match L.find? (fun s => decide (s.p1 = u ∨ s.p2 = u)) with
    | none => ([u], L)
    | some s =>
      let next := if s.p1 = u then s.p2 else s.p1
      let res := walkFromFuel n (L.erase s) next
      (u :: res.1, res.2)

/-- Convert a closed-walk vertex list into the list of its edges. -/
def walkEdges : List Vector2D → List LineSegment
  | [] => []
  | [_] => []
  | a :: b :: rest => ⟨a, b⟩ :: walkEdges (b :: rest)

/-- Greedy decomposition with explicit fuel. -/
def decomposeListFuel : Nat → List LineSegment → List Polygon
  | 0, _ => []
  | _+1, [] => []
  | n+1, s₀ :: rest =>
    let L := s₀ :: rest
    let u := s₀.p1
    let walk := walkFromFuel L.length L u
    let poly : Polygon := ⟨walk.1.dropLast⟩
    poly :: decomposeListFuel n walk.2

/-- Public computable wrapper. -/
def decomposeList (L : List LineSegment) : List Polygon :=
  decomposeListFuel L.length L

end EvenGraphDecompositionImpl
