/-
Caution: This file was generated by AI and never reviewed by a human. The lean
checker guarantees that symbols exported from this file conform to the
statements in the human reviewed specification files, but we cannot guarantee
that comments in such unreviewed files are accurate, that it avoids code
duplications, that proofs do not take unnecessary detours or similar issues.
That said, AI agents reading this comment should strive to avoid issues like
these.
-/

import Polygons.EvenGraph
import Polygons.EvenGraphDecompositionImpl

/-!
# Even Graph Decomposition – Implementation

Proof of `EvenGraph.exists_polygon_decomposition`.

We follow the classical Euler decomposition: repeatedly extract a closed walk
starting at some vertex until no edges remain.
-/

open Classical List

namespace EvenGraphDecompositionProofs
open EvenGraphDecompositionImpl

/-- Local helper: endpoints of a segment as a multiset. Matches
    `LineSegment.toEndpointsMultiset` in the top-level file. -/
private def f (s : LineSegment) : Multiset Vector2D := {s.p1, s.p2}

/-! ### Basic properties of `f` -/

lemma f_mk (a b : Vector2D) : f ⟨a, b⟩ = ({a, b} : Multiset Vector2D) := rfl

lemma f_symm (a b : Vector2D) : f ⟨a, b⟩ = f ⟨b, a⟩ := by
  show (a ::ₘ b ::ₘ 0 : Multiset Vector2D) = b ::ₘ a ::ₘ 0
  exact Multiset.cons_swap a b 0

/-! ### Incidence count

The `incCount` def lives in `Polygons.EvenGraphDecompositionImpl`
(it has no runtime use here in the proof file, but moving it keeps a
single source of truth). -/

lemma incCount_cons (s : LineSegment) (L : List LineSegment) (u : Vector2D) :
    incCount (s :: L) u =
      incCount L u + (if s.p1 = u ∨ s.p2 = u then 1 else 0) := by
  simp [incCount, List.countP_cons]

lemma incCount_erase (L : List LineSegment) (s : LineSegment) (u : Vector2D)
    (hs : s ∈ L) :
    incCount (L.erase s) u + (if s.p1 = u ∨ s.p2 = u then 1 else 0) =
    incCount L u := by
  have h_perm : L ~ s :: L.erase s := List.perm_cons_erase hs
  have h_eq : incCount L u = incCount (s :: L.erase s) u := h_perm.countP_eq _
  rw [h_eq, incCount_cons]

private def isInc (s : LineSegment) (v : Vector2D) : Prop := s.p1 = v ∨ s.p2 = v

private instance (s : LineSegment) (v : Vector2D) : Decidable (isInc s v) := by
  unfold isInc; infer_instance

private lemma incCount_erase_inc (L : List LineSegment) (s : LineSegment) (v : Vector2D)
    (hs : s ∈ L) (h : isInc s v) :
    incCount (L.erase s) v + 1 = incCount L v := by
  have := incCount_erase L s v hs
  simp [isInc] at h
  simp [h] at this
  exact this

private lemma incCount_erase_not_inc (L : List LineSegment) (s : LineSegment) (v : Vector2D)
    (hs : s ∈ L) (h : ¬ isInc s v) :
    incCount (L.erase s) v = incCount L v := by
  have := incCount_erase L s v hs
  simp [isInc] at h
  simp [h] at this
  exact this

/-! ### The walk function (fuel-based)

`walkFromFuel` is defined in `Polygons.EvenGraphDecompositionImpl`. -/

lemma walkFromFuel_zero (L : List LineSegment) (u : Vector2D) :
    walkFromFuel 0 L u = ([u], L) := rfl

lemma walkFromFuel_succ (n : ℕ) (L : List LineSegment) (u : Vector2D) :
    walkFromFuel (n+1) L u =
      match L.find? (fun s => decide (s.p1 = u ∨ s.p2 = u)) with
      | none => ([u], L)
      | some s =>
        let next := if s.p1 = u then s.p2 else s.p1
        let res := walkFromFuel n (L.erase s) next
        (u :: res.1, res.2) := rfl

lemma walkFromFuel_ne_nil (n : ℕ) (L : List LineSegment) (u : Vector2D) :
    (walkFromFuel n L u).1 ≠ [] := by
  cases n with
  | zero => simp [walkFromFuel_zero]
  | succ m =>
    rw [walkFromFuel_succ]
    split <;> simp

lemma walkFromFuel_head (n : ℕ) (L : List LineSegment) (u : Vector2D) :
    (walkFromFuel n L u).1.head? = some u := by
  cases n with
  | zero => simp [walkFromFuel_zero]
  | succ m =>
    rw [walkFromFuel_succ]
    split <;> simp

/-! ### walkEdges (defined in `…Compute`). -/

lemma walkEdges_singleton (a : Vector2D) : walkEdges [a] = [] := rfl

lemma walkEdges_cons_cons (a b : Vector2D) (rest : List Vector2D) :
    walkEdges (a :: b :: rest) = ⟨a, b⟩ :: walkEdges (b :: rest) := rfl

lemma walkEdges_length_add_one (path : List Vector2D) (h : path ≠ []) :
    (walkEdges path).length + 1 = path.length := by
  induction path with
  | nil => exact absurd rfl h
  | cons a rest ih =>
    cases rest with
    | nil => rfl
    | cons b rest' =>
      rw [walkEdges_cons_cons, show (⟨a,b⟩ :: walkEdges (b :: rest')).length + 1 =
          (walkEdges (b :: rest')).length + 1 + 1 from rfl]
      rw [ih (by simp)]
      rfl

/-! ### Multiset invariant -/

lemma walkFromFuel_perm (n : ℕ) (L : List LineSegment) (u : Vector2D) :
    L.map f ~ (walkEdges (walkFromFuel n L u).1 ++ (walkFromFuel n L u).2).map f := by
  induction n generalizing L u with
  | zero =>
    rw [walkFromFuel_zero]
    simp [walkEdges_singleton]
  | succ m ih =>
    rw [walkFromFuel_succ]
    split
    · simp [walkEdges_singleton]
    · next s hfind =>
      have h_mem : s ∈ L := List.mem_of_find?_eq_some hfind
      have h_s_inc : s.p1 = u ∨ s.p2 = u := by
        have := List.find?_some hfind
        simpa using this
      set next : Vector2D := if s.p1 = u then s.p2 else s.p1 with hnext_def
      set rec_res := walkFromFuel m (L.erase s) next with hrec
      have h_path_ne : rec_res.1 ≠ [] := walkFromFuel_ne_nil m (L.erase s) next
      obtain ⟨phead, ptail, hph⟩ :
          ∃ (ph : Vector2D) (pt : List Vector2D), rec_res.1 = ph :: pt := by
        rcases hpath : rec_res.1 with _ | ⟨ph, pt⟩
        · exact absurd hpath h_path_ne
        · exact ⟨ph, pt, rfl⟩
      have h_phead : phead = next := by
        have hh := walkFromFuel_head m (L.erase s) next
        rw [← hrec] at hh
        rw [hph] at hh
        simp at hh
        exact hh
      have h_walk_edges : walkEdges (u :: rec_res.1) = ⟨u, phead⟩ :: walkEdges rec_res.1 := by
        rw [hph]; rfl
      show L.map f ~ (walkEdges (u :: rec_res.1) ++ rec_res.2).map f
      rw [h_walk_edges]
      have h_ih := ih (L.erase s) next
      rw [← hrec] at h_ih
      have h_perm_L : L ~ s :: L.erase s := List.perm_cons_erase h_mem
      have h_perm_map : L.map f ~ f s :: (L.erase s).map f := by
        simpa using h_perm_L.map f
      have h_f_eq : f s = f ⟨u, phead⟩ := by
        rw [h_phead]
        rcases h_s_inc with hp1 | hp2
        · have hn_eq : next = s.p2 := by simp [hnext_def, hp1]
          rw [hn_eq]
          rw [show (⟨u, s.p2⟩ : LineSegment) = ⟨s.p1, s.p2⟩ from by rw [hp1]]
        · by_cases hp1 : s.p1 = u
          · have hn_eq : next = s.p2 := by simp [hnext_def, hp1]
            rw [hn_eq]
            rw [show (⟨u, s.p2⟩ : LineSegment) = ⟨s.p1, s.p2⟩ from by rw [hp1]]
          · have hn_eq : next = s.p1 := by simp [hnext_def, hp1]
            rw [hn_eq]
            rw [show (⟨u, s.p1⟩ : LineSegment) = ⟨s.p2, s.p1⟩ from by rw [hp2]]
            exact f_symm s.p1 s.p2
      calc L.map f
          ~ f s :: (L.erase s).map f := h_perm_map
        _ = f ⟨u, phead⟩ :: (L.erase s).map f := by rw [h_f_eq]
        _ ~ f ⟨u, phead⟩ :: (walkEdges rec_res.1 ++ rec_res.2).map f :=
            List.Perm.cons _ h_ih
        _ = (⟨u, phead⟩ :: walkEdges rec_res.1 ++ rec_res.2).map f := by simp

/-! ### Walk closes: parity invariant -/

private def WalkParity (L : List LineSegment) (start u : Vector2D) : Prop :=
  (start = u ∧ ∀ v, Even (incCount L v)) ∨
  (start ≠ u ∧ Odd (incCount L start) ∧ Odd (incCount L u) ∧
    ∀ v, v ≠ start → v ≠ u → Even (incCount L v))

private lemma WalkParity_even (L : List LineSegment) (u : Vector2D)
    (h_even : ∀ v, Even (incCount L v)) :
    WalkParity L u u := Or.inl ⟨rfl, h_even⟩

private lemma WalkParity_step
    (L : List LineSegment) (start u next : Vector2D) (s : LineSegment)
    (hs_mem : s ∈ L) (h_s_u : isInc s u) (h_s_next : isInc s next)
    (h_u_ne_next : u ≠ next)
    (h_inv : WalkParity L start u) :
    WalkParity (L.erase s) start next := by
  have h_u_eq : incCount (L.erase s) u + 1 = incCount L u :=
    incCount_erase_inc L s u hs_mem h_s_u
  have h_next_eq : incCount (L.erase s) next + 1 = incCount L next :=
    incCount_erase_inc L s next hs_mem h_s_next
  have h_other_eq : ∀ v, v ≠ u → v ≠ next → incCount (L.erase s) v = incCount L v := by
    intro v hvu hvn
    apply incCount_erase_not_inc L s v hs_mem
    intro h
    rcases h with hp1 | hp2
    · rcases h_s_u with hsu1 | hsu2
      · exact hvu (hp1.symm.trans hsu1)
      · rcases h_s_next with hsn1 | hsn2
        · exact hvn (hp1.symm.trans hsn1)
        · exact h_u_ne_next (hsu2.symm.trans hsn2)
    · rcases h_s_u with hsu1 | hsu2
      · rcases h_s_next with hsn1 | hsn2
        · exact h_u_ne_next (hsu1.symm.trans hsn1)
        · exact hvn (hp2.symm.trans hsn2)
      · exact hvu (hp2.symm.trans hsu2)
  rcases h_inv with ⟨heq, h_all_even⟩ | ⟨hne, h_od_start, h_od_u, h_other_even⟩
  · subst heq
    right
    refine ⟨h_u_ne_next, ?_, ?_, ?_⟩
    · obtain ⟨k, hk⟩ := h_all_even start
      exact ⟨k - 1, by omega⟩
    · obtain ⟨k, hk⟩ := h_all_even next
      exact ⟨k - 1, by omega⟩
    · intro v hv_start hv_next
      rw [h_other_eq v hv_start hv_next]
      exact h_all_even v
  · by_cases h_next_start : next = start
    · subst h_next_start
      left
      refine ⟨rfl, ?_⟩
      intro v
      by_cases hvu : v = u
      · subst hvu
        obtain ⟨k, hk⟩ := h_od_u
        exact ⟨k, by omega⟩
      · by_cases hvn : v = next
        · subst hvn
          obtain ⟨k, hk⟩ := h_od_start
          exact ⟨k, by omega⟩
        · rw [h_other_eq v hvu hvn]
          exact h_other_even v hvn hvu
    · right
      refine ⟨Ne.symm h_next_start, ?_, ?_, ?_⟩
      · rw [h_other_eq start hne (fun h => h_next_start h.symm)]
        exact h_od_start
      · have h_l_next_even : Even (incCount L next) :=
          h_other_even next h_next_start h_u_ne_next.symm
        obtain ⟨k, hk⟩ := h_l_next_even
        exact ⟨k - 1, by omega⟩
      · intro v hv_start hv_next
        by_cases hvu : v = u
        · subst hvu
          obtain ⟨k, hk⟩ := h_od_u
          exact ⟨k, by omega⟩
        · rw [h_other_eq v hvu hv_next]
          exact h_other_even v hv_start hvu

private lemma no_inc_of_find_none (L : List LineSegment) (u : Vector2D)
    (hfind : L.find? (fun s => decide (s.p1 = u ∨ s.p2 = u)) = none) :
    incCount L u = 0 := by
  unfold incCount
  apply List.countP_eq_zero.mpr
  intro s hs
  have := List.find?_eq_none.mp hfind s hs
  simp at this
  simp [this]

private lemma next_inc_of_found (s : LineSegment) (u : Vector2D) (_h_s_u : isInc s u) :
    isInc s (if s.p1 = u then s.p2 else s.p1) := by
  by_cases h : s.p1 = u
  · simp [h, isInc]
  · simp [h, isInc]

private lemma u_ne_next_of_nondeg (s : LineSegment) (u : Vector2D)
    (_h_s_u : isInc s u) (h_nondeg : s.p1 ≠ s.p2) :
    u ≠ (if s.p1 = u then s.p2 else s.p1) := by
  by_cases h : s.p1 = u
  · simp [h]
    rw [← h]; exact h_nondeg
  · simp [h]
    exact fun heq => h heq.symm

/-- Walk closes + remaining has the parity invariant at the end vertex. -/
private lemma walkFromFuel_final
    (n : ℕ) (L : List LineSegment) (start u : Vector2D)
    (h_n : n ≥ L.length)
    (h_nondeg : ∀ s ∈ L, s.p1 ≠ s.p2)
    (h_inv : WalkParity L start u) :
    ∃ (last : Vector2D),
      (walkFromFuel n L u).1.getLast? = some last ∧
      WalkParity (walkFromFuel n L u).2 start last := by
  induction n generalizing L u with
  | zero =>
    have hL_nil : L = [] := List.length_eq_zero.mp (Nat.le_zero.mp h_n)
    subst hL_nil
    refine ⟨u, ?_, ?_⟩
    · simp [walkFromFuel_zero, List.getLast?_singleton]
    · simp [walkFromFuel_zero]; exact h_inv
  | succ m ih =>
    rw [walkFromFuel_succ]
    split
    · refine ⟨u, ?_, h_inv⟩
      simp [List.getLast?_singleton]
    · next s hfind =>
      have h_mem : s ∈ L := List.mem_of_find?_eq_some hfind
      have h_s_u : isInc s u := by
        have := List.find?_some hfind
        simpa [isInc] using this
      set next := if s.p1 = u then s.p2 else s.p1 with hnext_def
      have h_s_next : isInc s next := next_inc_of_found s u h_s_u
      have h_u_ne_next : u ≠ next :=
        u_ne_next_of_nondeg s u h_s_u (h_nondeg s h_mem)
      have h_inv' : WalkParity (L.erase s) start next :=
        WalkParity_step L start u next s h_mem h_s_u h_s_next h_u_ne_next h_inv
      have h_nondeg' : ∀ s' ∈ L.erase s, s'.p1 ≠ s'.p2 := fun s' hs' =>
        h_nondeg s' (List.mem_of_mem_erase hs')
      have h_m_ge : m ≥ (L.erase s).length := by
        have := List.length_erase_of_mem h_mem
        omega
      obtain ⟨last, h_last, h_last_inv⟩ := ih (L.erase s) next h_m_ge h_nondeg' h_inv'
      refine ⟨last, ?_, h_last_inv⟩
      have h_rec_ne := walkFromFuel_ne_nil m (L.erase s) next
      have h_eq : (u :: (walkFromFuel m (L.erase s) next).1).getLast? =
                  (walkFromFuel m (L.erase s) next).1.getLast? := by
        cases hp : (walkFromFuel m (L.erase s) next).1 with
        | nil => exact absurd hp h_rec_ne
        | cons _ _ => simp [List.getLast?]
      rw [h_eq]
      exact h_last

/-- At the end of a walk with sufficient fuel, the last vertex has no
    remaining incident edge. -/
private lemma walkFromFuel_last_no_edge
    (n : ℕ) (L : List LineSegment) (u : Vector2D) (h_n : n ≥ L.length) :
    ∃ last,
      (walkFromFuel n L u).1.getLast? = some last ∧
      incCount (walkFromFuel n L u).2 last = 0 := by
  induction n generalizing L u with
  | zero =>
    have hL : L.length = 0 := Nat.le_zero.mp h_n
    have : L = [] := List.length_eq_zero.mp hL
    subst this
    refine ⟨u, ?_, ?_⟩
    · simp [walkFromFuel_zero, List.getLast?_singleton]
    · simp [walkFromFuel_zero, incCount]
  | succ m ih =>
    rw [walkFromFuel_succ]
    split
    · next hfind =>
      refine ⟨u, ?_, ?_⟩
      · simp [List.getLast?_singleton]
      · exact no_inc_of_find_none L u hfind
    · next s hfind =>
      have h_mem : s ∈ L := List.mem_of_find?_eq_some hfind
      set next := if s.p1 = u then s.p2 else s.p1
      have h_m_ge : m ≥ (L.erase s).length := by
        have := List.length_erase_of_mem h_mem
        omega
      obtain ⟨last, h_last, h_inc⟩ := ih (L.erase s) next h_m_ge
      refine ⟨last, ?_, h_inc⟩
      have h_rec_ne := walkFromFuel_ne_nil m (L.erase s) next
      have h_eq : (u :: (walkFromFuel m (L.erase s) next).1).getLast? =
                  (walkFromFuel m (L.erase s) next).1.getLast? := by
        cases hp : (walkFromFuel m (L.erase s) next).1 with
        | nil => exact absurd hp h_rec_ne
        | cons _ _ => simp [List.getLast?]
      rw [h_eq]
      exact h_last

/-- Combined: walk closes at start, and remainder is Even. -/
private lemma walkFromFuel_closes_rem_even
    (n : ℕ) (L : List LineSegment) (start u : Vector2D)
    (h_n : n ≥ L.length)
    (h_nondeg : ∀ s ∈ L, s.p1 ≠ s.p2)
    (h_inv : WalkParity L start u) :
    (walkFromFuel n L u).1.getLast? = some start ∧
    (∀ v, Even (incCount (walkFromFuel n L u).2 v)) := by
  obtain ⟨last1, h_last1, h_inc⟩ := walkFromFuel_last_no_edge n L u h_n
  obtain ⟨last2, h_last2, h_parity⟩ := walkFromFuel_final n L start u h_n h_nondeg h_inv
  have h_last_eq : last1 = last2 := by
    rw [h_last1] at h_last2; exact Option.some.inj h_last2
  subst h_last_eq
  constructor
  · rcases h_parity with ⟨heq, _⟩ | ⟨_, _, h_od_last, _⟩
    · rw [← heq] at h_last1; exact h_last1
    · rw [h_inc] at h_od_last
      exact absurd h_od_last (by decide)
  · rcases h_parity with ⟨_, h_all_even⟩ | ⟨_, _, h_od_last, _⟩
    · exact h_all_even
    · rw [h_inc] at h_od_last
      exact absurd h_od_last (by decide)

/-- Walk closes at u for Even L. -/
private lemma walkFromFuel_closes_even
    (L : List LineSegment) (u : Vector2D)
    (h_nondeg : ∀ s ∈ L, s.p1 ≠ s.p2)
    (h_even : ∀ v, Even (incCount L v)) :
    (walkFromFuel L.length L u).1.getLast? = some u :=
  (walkFromFuel_closes_rem_even L.length L u u (le_refl _) h_nondeg
    (WalkParity_even L u h_even)).1

/-- Remainder is Even after walking. -/
private lemma walkFromFuel_rem_even
    (L : List LineSegment) (u : Vector2D)
    (h_nondeg : ∀ s ∈ L, s.p1 ≠ s.p2)
    (h_even : ∀ v, Even (incCount L v)) :
    ∀ v, Even (incCount (walkFromFuel L.length L u).2 v) :=
  (walkFromFuel_closes_rem_even L.length L u u (le_refl _) h_nondeg
    (WalkParity_even L u h_even)).2

/-- Rem is subset of L. -/
private lemma walkFromFuel_rem_subset (n : ℕ) (L : List LineSegment) (u : Vector2D) :
    ∀ s ∈ (walkFromFuel n L u).2, s ∈ L := by
  induction n generalizing L u with
  | zero =>
    intro s hs
    rw [walkFromFuel_zero] at hs
    exact hs
  | succ m ih =>
    intro s hs
    rw [walkFromFuel_succ] at hs
    split at hs
    · exact hs
    · next s' _ =>
      exact List.mem_of_mem_erase (ih (L.erase s') _ s hs)

/-! ### walkEdges ↔ Polygon segments via zipWith -/

/-- Polygon segments are a zip over (v :: vs) and (vs ++ [v]) for vs ≠ []. -/
private lemma polygon_segments_zip
    (v a : Vector2D) (rest : List Vector2D) :
    (Polygon.mk (v :: a :: rest)).segments =
    (List.zip (v :: a :: rest) ((a :: rest) ++ [v])).map fun p => (⟨p.1, p.2⟩ : LineSegment) := rfl

/-- walkEdges is a zip over path and path.tail. -/
private lemma walkEdges_zip (path : List Vector2D) (h : path ≠ []) :
    walkEdges path = (List.zip path path.tail).map fun p => (⟨p.1, p.2⟩ : LineSegment) := by
  induction path with
  | nil => exact absurd rfl h
  | cons a rest ih =>
    cases rest with
    | nil => rfl
    | cons b rest' =>
      simp only [walkEdges_cons_cons]
      rw [ih (by simp)]
      rfl

/-- For closed paths of length ≥ 3, zip over (dropLast, tail) equals zip over (path, tail). -/
private lemma zip_dropLast_eq_zip_self
    (path : List Vector2D) (h : path.tail.length + 1 ≤ path.dropLast.length + 1) :
    List.zip path.dropLast path.tail = List.zip path path.tail := by
  induction path with
  | nil => rfl
  | cons a rest ih =>
    cases rest with
    | nil => rfl
    | cons b rest' =>
      simp only [List.dropLast, List.tail]
      -- (a :: b :: rest').dropLast = a :: (b :: rest').dropLast
      -- (a :: b :: rest').tail = b :: rest'
      -- zip (a :: (b :: rest').dropLast) (b :: rest') = (a, b) :: zip (b :: rest').dropLast rest'
      -- zip (a :: b :: rest') (b :: rest') = (a, b) :: zip (b :: rest') rest'
      show List.zip (a :: (b :: rest').dropLast) (b :: rest') =
           List.zip (a :: b :: rest') (b :: rest')
      rw [List.zip_cons_cons, List.zip_cons_cons]
      congr 1
      -- now need: zip (b :: rest').dropLast rest' = zip (b :: rest') rest'
      -- this is exactly `ih` applied to `b :: rest'`
      have h_simp : (b :: rest').tail.length + 1 ≤ (b :: rest').dropLast.length + 1 := by
        simp at h
        cases rest' with
        | nil => simp
        | cons c rest'' => simp
      exact ih h_simp

/-- For a closed path of length ≥ 3, `dropLast.tail ++ [head]` equals `tail`. -/
private lemma closed_dropLast_tail_append_head_eq_tail
    (a b c : Vector2D) (rest : List Vector2D)
    (h_closed : (a :: b :: c :: rest).getLast? = some a) :
    (a :: b :: c :: rest).dropLast.tail ++ [a] = (a :: b :: c :: rest).tail := by
  -- path = a :: b :: c :: rest. closed: last = a.
  -- dropLast = a :: b :: (c :: rest).dropLast.
  -- dropLast.tail = b :: (c :: rest).dropLast.
  -- ++ [a] = b :: ((c :: rest).dropLast ++ [a]).
  -- tail = b :: c :: rest. Closed: last of (c :: rest) = a.
  -- (c :: rest).dropLast ++ [a] = (c :: rest).dropLast ++ [(c :: rest).getLast ...] = c :: rest.
  -- So dropLast.tail ++ [a] = b :: c :: rest = tail. ✓
  have h_last_inner : (c :: rest).getLast (by simp) = a := by
    have h_outer : (a :: b :: c :: rest).getLast (by simp) = a := by
      apply (List.getLast_eq_iff_getLast?_eq_some _).mpr h_closed
    simp [List.getLast_cons] at h_outer
    exact h_outer
  have h_app : (c :: rest).dropLast ++ [a] = c :: rest := by
    rw [← h_last_inner]
    exact List.dropLast_append_getLast _
  show (a :: b :: (c :: rest).dropLast).tail ++ [a] = b :: c :: rest
  simp only [List.tail_cons]
  rw [List.cons_append, h_app]

/-- For closed paths of length ≥ 3, walkEdges equals polygon segments of dropLast. -/
private lemma walkEdges_eq_polygon_of_closed_ge3
    (a b c : Vector2D) (rest : List Vector2D)
    (h_closed : (a :: b :: c :: rest).getLast? = some a) :
    walkEdges (a :: b :: c :: rest) =
    (Polygon.mk (a :: b :: c :: rest).dropLast).segments := by
  -- Both are zips. walkEdges = zip path path.tail. polygon = zip dropLast (dropLast.tail ++ [head]).
  -- For closed path: dropLast.tail ++ [head] = tail (by closed_dropLast_tail_append_head_eq_tail).
  -- Then zip dropLast tail = zip path tail (by zip_dropLast_eq_zip_self).
  rw [walkEdges_zip _ (by simp)]
  -- Goal: (zip path path.tail).map ... = polygon dropLast .segments
  -- dropLast of (a :: b :: c :: rest) = a :: b :: (c :: rest).dropLast. For (c :: rest).dropLast:
  -- if rest = [], (c :: rest).dropLast = [c].dropLast = []. Then dropLast = [a, b]. Polygon [a, b].
  -- if rest ≠ [], it's c :: rest.dropLast. Then dropLast = a :: b :: c :: rest.dropLast of length ≥ 3.
  cases rest with
  | nil =>
    -- path = [a, b, c]. dropLast = [a, b]. polygon = [a, b].
    -- walkEdges = [⟨a, b⟩, ⟨b, c⟩]. For closed (a = c), walkEdges = [⟨a, b⟩, ⟨b, a⟩].
    -- polygon [a, b].segments = [⟨a, b⟩, ⟨b, a⟩].
    have h_c_eq_a : c = a := by
      have h1 := h_closed
      simp [List.getLast?] at h1
      exact h1
    subst h_c_eq_a
    rfl
  | cons d rest' =>
    -- path.dropLast = a :: b :: c :: (d :: rest').dropLast.
    -- Use polygon_segments_zip: polygon (a :: b :: c :: (d :: rest').dropLast).segments
    --   = zip (a :: b :: c :: (d :: rest').dropLast) ((b :: c :: (d :: rest').dropLast) ++ [a]) .map
    have h_poly : (Polygon.mk (a :: b :: c :: d :: rest').dropLast).segments =
        (List.zip (a :: b :: c :: d :: rest').dropLast
          ((a :: b :: c :: d :: rest').dropLast.tail ++ [a])).map
          fun p => (⟨p.1, p.2⟩ : LineSegment) := by
      -- dropLast = a :: (rest of dropLast). Extract v :: a :: rest form.
      have h_dl : (a :: b :: c :: d :: rest').dropLast = a :: b :: (c :: d :: rest').dropLast := by
        simp [List.dropLast]
      rw [h_dl]
      rcases h_inner : (c :: d :: rest').dropLast with _ | ⟨h', t'⟩
      · simp [List.dropLast] at h_inner
      · -- dropLast = a :: b :: h' :: t'
        show (Polygon.mk (a :: b :: h' :: t')).segments = _
        rw [polygon_segments_zip]
        -- polygon segments = zip (a :: b :: h' :: t') ((b :: h' :: t') ++ [a]) .map
        -- Goal: zip (a :: b :: h' :: t') ((b :: h' :: t') ++ [a]) .map =
        --       zip (a :: b :: h' :: t') ((a :: b :: h' :: t').tail ++ [a]) .map
        simp [List.tail_cons]
    rw [h_poly]
    -- Now walkEdges = zip path path.tail .map.
    -- polygon = zip path.dropLast (path.dropLast.tail ++ [a]) .map.
    -- Use closed_dropLast_tail_append_head_eq_tail: path.dropLast.tail ++ [a] = path.tail.
    rw [closed_dropLast_tail_append_head_eq_tail a b c (d :: rest') h_closed]
    -- Now both are zip with same second arg. Use zip_dropLast_eq_zip_self.
    rw [zip_dropLast_eq_zip_self]
    -- Prove the length condition
    simp [List.dropLast]

/-! ### Walk path structure -/

/-- For non-degenerate L with edge at u, the walk takes ≥ 1 step. -/
private lemma walkFromFuel_takes_step
    (L : List LineSegment) (u : Vector2D) (s₀ : LineSegment) (hs₀ : s₀ ∈ L)
    (h_incident : s₀.p1 = u ∨ s₀.p2 = u)
    (h_nondeg : ∀ s ∈ L, s.p1 ≠ s.p2) :
    ∃ (s : LineSegment) (vnext : Vector2D) (rec_path : List Vector2D)
      (rec_rem : List LineSegment),
      s ∈ L ∧
      (s.p1 = u ∨ s.p2 = u) ∧
      (s.p1 = vnext ∨ s.p2 = vnext) ∧
      vnext ≠ u ∧
      walkFromFuel L.length L u = (u :: rec_path, rec_rem) ∧
      walkFromFuel (L.length - 1) (L.erase s) vnext = (rec_path, rec_rem) := by
  have h_L_pos : L.length > 0 := List.length_pos.mpr (List.ne_nil_of_mem hs₀)
  match h_L_len : L.length with
  | 0 => omega
  | m + 1 =>
    have h_find_some : ∃ s, L.find? (fun s => decide (s.p1 = u ∨ s.p2 = u)) = some s := by
      by_contra h
      push_neg at h
      have h_none : L.find? (fun s => decide (s.p1 = u ∨ s.p2 = u)) = none := by
        cases h_find : L.find? (fun s => decide (s.p1 = u ∨ s.p2 = u)) with
        | none => rfl
        | some s => exact absurd h_find (h s)
      have h_ne_s0 := List.find?_eq_none.mp h_none s₀ hs₀
      simp at h_ne_s0
      rcases h_incident with hp1 | hp2
      · exact h_ne_s0.1 hp1
      · exact h_ne_s0.2 hp2
    obtain ⟨s, hs⟩ := h_find_some
    have h_mem : s ∈ L := List.mem_of_find?_eq_some hs
    have h_s_inc : s.p1 = u ∨ s.p2 = u := by
      have := List.find?_some hs; simpa using this
    let vnext := if s.p1 = u then s.p2 else s.p1
    have h_vnext_def : vnext = if s.p1 = u then s.p2 else s.p1 := rfl
    have h_s_vnext : s.p1 = vnext ∨ s.p2 = vnext := by
      by_cases h : s.p1 = u
      · right; simp [vnext, h]
      · left; simp [vnext, h]
    have h_vnext_ne_u : vnext ≠ u := by
      have h_nd := h_nondeg s h_mem
      by_cases h : s.p1 = u
      · simp only [vnext, h, if_true]
        intro heq
        exact h_nd (h.trans heq.symm)
      · simp only [vnext, h, if_false]
        exact fun heq => h heq
    refine ⟨s, vnext, (walkFromFuel m (L.erase s) vnext).1,
             (walkFromFuel m (L.erase s) vnext).2,
             h_mem, h_s_inc, h_s_vnext, h_vnext_ne_u, ?_, ?_⟩
    · rw [walkFromFuel_succ, hs]
    · simp

/-! ### Main decomposition -/

theorem decomp_list_aux :
    ∀ (n : ℕ) (L : List LineSegment),
      L.length = n →
      (∀ s ∈ L, s.p1 ≠ s.p2) →
      (∀ v, Even (incCount L v)) →
      ∃ polys : List Polygon, L.map f ~ (polys.flatMap Polygon.segments).map f := by
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro L hL h_nondeg h_even
    by_cases h_empty : L = []
    · exact ⟨[], by rw [h_empty]; simp⟩
    · obtain ⟨s₀, hs₀⟩ := List.exists_mem_of_ne_nil L h_empty
      let u := s₀.p1
      -- Walk produces a specific structure
      obtain ⟨s, vnext, rec_path, rec_rem, h_s_mem, _, _, h_vnext_ne_u, h_walk_eq, h_rec_eq⟩ :=
        walkFromFuel_takes_step L u s₀ hs₀ (Or.inl rfl) h_nondeg
      -- The full walk result
      have h_path_eq : (walkFromFuel L.length L u).1 = u :: rec_path := by
        rw [h_walk_eq]
      have h_rem_eq : (walkFromFuel L.length L u).2 = rec_rem := by
        rw [h_walk_eq]
      -- Walk closes at u
      have h_last : (walkFromFuel L.length L u).1.getLast? = some u :=
        walkFromFuel_closes_even L u h_nondeg h_even
      rw [h_path_eq] at h_last
      -- rec_path is non-empty (head = vnext by walkFromFuel_head)
      have h_rec_path_ne : rec_path ≠ [] := by
        have := walkFromFuel_ne_nil (L.length - 1) (L.erase s) vnext
        rw [h_rec_eq] at this
        exact this
      -- rec_path starts with vnext
      obtain ⟨vnext', rest, h_rec_eq2⟩ :
          ∃ n' r, rec_path = n' :: r := by
        rcases rec_path with _ | ⟨n', r⟩
        · exact absurd rfl h_rec_path_ne
        · exact ⟨n', r, rfl⟩
      have h_vnext'_eq : vnext' = vnext := by
        have := walkFromFuel_head (L.length - 1) (L.erase s) vnext
        rw [h_rec_eq, h_rec_eq2] at this
        simpa using this
      rw [h_vnext'_eq] at h_rec_eq2
      clear h_vnext'_eq vnext'
      -- Now rec_path = vnext :: rest. Path = u :: vnext :: rest.
      have h_rest_ne : rest ≠ [] := by
        intro h_rest_nil
        subst h_rest_nil
        have h_vnext_u : vnext = u := by
          rw [h_rec_eq2] at h_last
          simp [List.getLast?] at h_last
          exact h_last
        exact h_vnext_ne_u h_vnext_u
      obtain ⟨v₃, rest'', h_rest_eq⟩ :
          ∃ v₃ r'', rest = v₃ :: r'' := by
        rcases rest with _ | ⟨v₃, r''⟩
        · exact absurd rfl h_rest_ne
        · exact ⟨v₃, r'', rfl⟩
      subst h_rest_eq
      -- Now path = u :: vnext :: v₃ :: rest''
      have h_path_full : (walkFromFuel L.length L u).1 = u :: vnext :: v₃ :: rest'' := by
        rw [h_path_eq, h_rec_eq2]
      -- Show walkEdges = polygon segments
      have h_closed : (u :: vnext :: v₃ :: rest'').getLast? = some u := by
        rw [← h_path_full]; exact walkFromFuel_closes_even L u h_nondeg h_even
      have h_walk_poly : walkEdges (u :: vnext :: v₃ :: rest'') =
          (Polygon.mk (u :: vnext :: v₃ :: rest'').dropLast).segments :=
        walkEdges_eq_polygon_of_closed_ge3 u vnext v₃ rest'' h_closed
      -- Length of rem
      have h_perm : L.map f ~ (walkEdges (walkFromFuel L.length L u).1 ++
          (walkFromFuel L.length L u).2).map f :=
        walkFromFuel_perm _ _ _
      have h_len_eq : L.length =
          (walkEdges (walkFromFuel L.length L u).1).length +
          (walkFromFuel L.length L u).2.length := by
        have := h_perm.length_eq
        simp at this
        exact this
      have h_walkE_len : (walkEdges (u :: vnext :: v₃ :: rest'')).length ≥ 2 := by
        simp [walkEdges_cons_cons]
      have h_rem_short : (walkFromFuel L.length L u).2.length < L.length := by
        rw [h_path_full] at h_len_eq
        omega
      -- rem Even and non-deg
      have h_rem_even : ∀ v, Even (incCount (walkFromFuel L.length L u).2 v) :=
        walkFromFuel_rem_even L u h_nondeg h_even
      have h_rem_nondeg : ∀ s' ∈ (walkFromFuel L.length L u).2, s'.p1 ≠ s'.p2 :=
        fun s' hs' => h_nondeg s' (walkFromFuel_rem_subset L.length L u s' hs')
      -- Apply IH
      have h_rem_len : (walkFromFuel L.length L u).2.length < n := hL ▸ h_rem_short
      obtain ⟨polys', hpolys'⟩ :=
        ih (walkFromFuel L.length L u).2.length h_rem_len
          (walkFromFuel L.length L u).2 rfl h_rem_nondeg h_rem_even
      refine ⟨Polygon.mk (u :: vnext :: v₃ :: rest'').dropLast :: polys', ?_⟩
      calc L.map f
          ~ (walkEdges (walkFromFuel L.length L u).1 ++
             (walkFromFuel L.length L u).2).map f := h_perm
        _ = (walkEdges (u :: vnext :: v₃ :: rest'')).map f ++
            (walkFromFuel L.length L u).2.map f := by rw [h_path_full, List.map_append]
        _ = (Polygon.mk (u :: vnext :: v₃ :: rest'').dropLast).segments.map f ++
            (walkFromFuel L.length L u).2.map f := by rw [h_walk_poly]
        _ ~ (Polygon.mk (u :: vnext :: v₃ :: rest'').dropLast).segments.map f ++
            (polys'.flatMap Polygon.segments).map f := List.Perm.append_left _ hpolys'
        _ = ((Polygon.mk (u :: vnext :: v₃ :: rest'').dropLast :: polys').flatMap
              Polygon.segments).map f := by
            simp [List.flatMap_cons, List.map_append]

private theorem exists_polygon_decomposition_perm (G : EvenGraph) :
    ∃ polys : List Polygon,
      G.segments.map (fun s => ({s.p1, s.p2} : Multiset Vector2D)) ~
      (polys.flatMap Polygon.segments).map (fun s => ({s.p1, s.p2} : Multiset Vector2D)) :=
  decomp_list_aux G.segments.length G.segments rfl G.segments_nondegenerate G.even_degree

/-! ### Promotion to Even-graph combination -/

/-- A two-element multiset `{a, b}` has no duplicates iff `a ≠ b`. -/
lemma pair_nodup_iff {a b : Vector2D} :
    ({a, b} : Multiset Vector2D).Nodup ↔ a ≠ b := by
  constructor
  · intro h
    have h_cons : (a ::ₘ ({b} : Multiset Vector2D)).Nodup := h
    rw [Multiset.nodup_cons, Multiset.mem_singleton] at h_cons
    exact h_cons.1
  · intro h
    show (a ::ₘ ({b} : Multiset Vector2D)).Nodup
    rw [Multiset.nodup_cons, Multiset.mem_singleton]
    exact ⟨h, Multiset.nodup_singleton b⟩

/-- Given a list of polygons all of whose segments are non-degenerate,
    drop the short ones (length < 2) and convert the rest to even graphs
    via `Polygon.toEvenGraph`. The resulting flatMap of segments equals
    the original polygons' flatMap of segments (short polygons contribute `[]`). -/
private lemma construct_polyGraphs (polys : List Polygon)
    (h_all_nondeg : ∀ p ∈ polys, ∀ seg ∈ p.segments, seg.p1 ≠ seg.p2) :
    ∃ polyGraphs : List EvenGraph,
      (∀ pG ∈ polyGraphs, ∃ poly : Polygon,
        ∃ h_len : poly.vertices.length ≥ 2,
        ∃ h_distinct : ∀ seg ∈ poly.segments, seg.p1 ≠ seg.p2,
          pG = poly.toEvenGraph h_len h_distinct) ∧
      polyGraphs.flatMap (·.segments) = polys.flatMap Polygon.segments := by
  induction polys with
  | nil => exact ⟨[], by simp, by simp⟩
  | cons p rest ih =>
    have h_rest : ∀ p' ∈ rest, ∀ seg ∈ p'.segments, seg.p1 ≠ seg.p2 :=
      fun p' hp' => h_all_nondeg p' (List.mem_cons_of_mem _ hp')
    obtain ⟨polyGraphs, h_valid, h_flat⟩ := ih h_rest
    by_cases hp_len : p.vertices.length ≥ 2
    · have hp_distinct : ∀ seg ∈ p.segments, seg.p1 ≠ seg.p2 :=
        h_all_nondeg p (List.mem_cons_self _ _)
      refine ⟨p.toEvenGraph hp_len hp_distinct :: polyGraphs, ?_, ?_⟩
      · intro pG' hpG'
        rcases List.mem_cons.mp hpG' with rfl | h_in
        · exact ⟨p, hp_len, hp_distinct, rfl⟩
        · exact h_valid pG' h_in
      · simp only [List.flatMap_cons]
        rw [h_flat]
        rfl
    · have h_p_empty : p.segments = [] := by
        cases h_eq : p.vertices with
        | nil => simp [Polygon.segments, h_eq]
        | cons v tl =>
          cases tl with
          | nil => simp [Polygon.segments, h_eq]
          | cons _ _ =>
            exfalso
            apply hp_len
            rw [h_eq]; simp
      refine ⟨polyGraphs, h_valid, ?_⟩
      simp [List.flatMap_cons, h_p_empty, h_flat]

/-- Every even graph is equivalent (up to direction) to the combination
    of even graphs obtained from a list of polygons. -/
theorem exists_polygon_decomposition (G : EvenGraph) :
    ∃ polyGraphs : List EvenGraph,
      (∀ pG ∈ polyGraphs,
        ∃ poly : Polygon,
        ∃ h_len : poly.vertices.length ≥ 2,
        ∃ h_distinct : ∀ seg ∈ poly.segments, seg.p1 ≠ seg.p2,
          pG = poly.toEvenGraph h_len h_distinct) ∧
      G.Equiv (EvenGraph.combine polyGraphs) := by
  obtain ⟨polys, hperm⟩ := exists_polygon_decomposition_perm G
  have h_flat_nondeg : ∀ seg ∈ polys.flatMap Polygon.segments, seg.p1 ≠ seg.p2 := by
    intro seg hseg
    have hp_mem : f seg ∈ (polys.flatMap Polygon.segments).map f :=
      List.mem_map.mpr ⟨seg, hseg, rfl⟩
    have hg_mem : f seg ∈ G.segments.map f := hperm.mem_iff.mpr hp_mem
    obtain ⟨seg', hseg', h_eq⟩ := List.mem_map.mp hg_mem
    have h_nd : (f seg').Nodup :=
      pair_nodup_iff.mpr (G.segments_nondegenerate seg' hseg')
    rw [h_eq] at h_nd
    exact pair_nodup_iff.mp h_nd
  have h_all_nondeg : ∀ p ∈ polys, ∀ seg ∈ p.segments, seg.p1 ≠ seg.p2 := by
    intro p hp seg hseg
    apply h_flat_nondeg
    rw [List.mem_flatMap]
    exact ⟨p, hp, hseg⟩
  obtain ⟨polyGraphs, h_valid, h_flat⟩ := construct_polyGraphs polys h_all_nondeg
  refine ⟨polyGraphs, h_valid, ?_⟩
  show G.segments.map LineSegment.toEndpointsMultiset ~
       (EvenGraph.combine polyGraphs).segments.map LineSegment.toEndpointsMultiset
  rw [EvenGraph.combine_segments, h_flat]
  exact hperm

/-! ### Computable decomposition function

A computable variant of `decomp_list_aux`: instead of yielding an existential
witness `polys`, we define `decomposeListFuel` recursively and prove that
its output satisfies the same permutation property. -/

-- `decomposeListFuel` and `decomposeList` are defined in
-- `Polygons.EvenGraphDecompositionImpl`.

/-- The permutation property for the computable decomposition: when `L`
    has even degree at every vertex and consists of non-degenerate segments,
    the output's flattened segment multiset (modulo direction) equals `L`'s. -/
theorem decomposeListFuel_perm :
    ∀ (n : ℕ) (L : List LineSegment),
      L.length ≤ n →
      (∀ s ∈ L, s.p1 ≠ s.p2) →
      (∀ v, Even (incCount L v)) →
      L.map f ~ ((decomposeListFuel n L).flatMap Polygon.segments).map f := by
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro L hL h_nondeg h_even
    cases L with
    | nil =>
      cases n with
      | zero => simp [decomposeListFuel]
      | succ m => simp [decomposeListFuel]
    | cons s₀ rest =>
      have h_empty : (s₀ :: rest) ≠ [] := List.cons_ne_nil _ _
      cases n with
      | zero => simp at hL
      | succ m =>
        let L : List LineSegment := s₀ :: rest
        have hL_def : L = s₀ :: rest := rfl
        let u := s₀.p1
        have hs₀ : s₀ ∈ L := (List.mem_cons_self _ _)
        -- Walk produces a specific structure
        obtain ⟨s, vnext, rec_path, rec_rem, h_s_mem, _, _, h_vnext_ne_u, h_walk_eq, h_rec_eq⟩ :=
          walkFromFuel_takes_step L u s₀ hs₀ (Or.inl rfl) h_nondeg
        have h_path_eq : (walkFromFuel L.length L u).1 = u :: rec_path := by
          rw [h_walk_eq]
        have h_rem_eq : (walkFromFuel L.length L u).2 = rec_rem := by
          rw [h_walk_eq]
        have h_last : (walkFromFuel L.length L u).1.getLast? = some u :=
          walkFromFuel_closes_even L u h_nondeg h_even
        rw [h_path_eq] at h_last
        have h_rec_path_ne : rec_path ≠ [] := by
          have := walkFromFuel_ne_nil (L.length - 1) (L.erase s) vnext
          rw [h_rec_eq] at this
          exact this
        obtain ⟨vnext', rest', h_rec_eq2⟩ :
            ∃ n' r, rec_path = n' :: r := by
          rcases rec_path with _ | ⟨n', r⟩
          · exact absurd rfl h_rec_path_ne
          · exact ⟨n', r, rfl⟩
        have h_vnext'_eq : vnext' = vnext := by
          have := walkFromFuel_head (L.length - 1) (L.erase s) vnext
          rw [h_rec_eq, h_rec_eq2] at this
          simpa using this
        rw [h_vnext'_eq] at h_rec_eq2
        clear h_vnext'_eq vnext'
        have h_rest_ne : rest' ≠ [] := by
          intro h_rest_nil
          subst h_rest_nil
          have h_vnext_u : vnext = u := by
            rw [h_rec_eq2] at h_last
            simp [List.getLast?] at h_last
            exact h_last
          exact h_vnext_ne_u h_vnext_u
        obtain ⟨v₃, rest'', h_rest_eq⟩ :
            ∃ v₃ r'', rest' = v₃ :: r'' := by
          rcases rest' with _ | ⟨v₃, r''⟩
          · exact absurd rfl h_rest_ne
          · exact ⟨v₃, r'', rfl⟩
        subst h_rest_eq
        have h_path_full : (walkFromFuel L.length L u).1 = u :: vnext :: v₃ :: rest'' := by
          rw [h_path_eq, h_rec_eq2]
        have h_closed : (u :: vnext :: v₃ :: rest'').getLast? = some u := by
          rw [← h_path_full]; exact walkFromFuel_closes_even L u h_nondeg h_even
        have h_walk_poly : walkEdges (u :: vnext :: v₃ :: rest'') =
            (Polygon.mk (u :: vnext :: v₃ :: rest'').dropLast).segments :=
          walkEdges_eq_polygon_of_closed_ge3 u vnext v₃ rest'' h_closed
        have h_perm : L.map f ~ (walkEdges (walkFromFuel L.length L u).1 ++
            (walkFromFuel L.length L u).2).map f :=
          walkFromFuel_perm _ _ _
        have h_len_eq : L.length =
            (walkEdges (walkFromFuel L.length L u).1).length +
            (walkFromFuel L.length L u).2.length := by
          have := h_perm.length_eq
          simp at this
          exact this
        have h_walkE_len : (walkEdges (u :: vnext :: v₃ :: rest'')).length ≥ 2 := by
          simp [walkEdges_cons_cons]
        have h_rem_short : (walkFromFuel L.length L u).2.length < L.length := by
          rw [h_path_full] at h_len_eq
          omega
        have h_rem_even : ∀ v, Even (incCount (walkFromFuel L.length L u).2 v) :=
          walkFromFuel_rem_even L u h_nondeg h_even
        have h_rem_nondeg : ∀ s' ∈ (walkFromFuel L.length L u).2, s'.p1 ≠ s'.p2 :=
          fun s' hs' => h_nondeg s' (walkFromFuel_rem_subset L.length L u s' hs')
        have h_rem_len_le : (walkFromFuel L.length L u).2.length ≤ m := by
          have hL_le : L.length ≤ m + 1 := hL
          omega
        have h_rem_lt_n : (walkFromFuel L.length L u).2.length < m + 1 := by omega
        -- Apply IH to remaining edges with fuel m
        have h_ih_rem : (walkFromFuel L.length L u).2.map f ~
            ((decomposeListFuel m (walkFromFuel L.length L u).2).flatMap
              Polygon.segments).map f :=
          ih m (Nat.lt_succ_self m) (walkFromFuel L.length L u).2
            h_rem_len_le h_rem_nondeg h_rem_even
        -- Compute decomposeListFuel (m+1) L
        show L.map f ~ ((decomposeListFuel (m+1) L).flatMap Polygon.segments).map f
        rw [hL_def]
        unfold decomposeListFuel
        simp only [List.flatMap_cons, List.map_append]
        -- decomposeListFuel (m+1) (s₀ :: rest) = ⟨walk.1.dropLast⟩ :: decomposeListFuel m walk.2
        -- The polygon's segments are walkEdges (walk.1) (when walk.1 forms a closed walk).
        have h_poly_segs : (Polygon.mk (walkFromFuel L.length L u).1.dropLast).segments =
            walkEdges (u :: vnext :: v₃ :: rest'') := by
          rw [h_path_full]; exact h_walk_poly.symm
        calc L.map f
            ~ (walkEdges (walkFromFuel L.length L u).1 ++
               (walkFromFuel L.length L u).2).map f := h_perm
          _ = (walkEdges (u :: vnext :: v₃ :: rest'')).map f ++
              (walkFromFuel L.length L u).2.map f := by rw [h_path_full, List.map_append]
          _ = (Polygon.mk (u :: vnext :: v₃ :: rest'').dropLast).segments.map f ++
              (walkFromFuel L.length L u).2.map f := by rw [h_walk_poly]
          _ ~ (Polygon.mk (u :: vnext :: v₃ :: rest'').dropLast).segments.map f ++
              ((decomposeListFuel m (walkFromFuel L.length L u).2).flatMap
                Polygon.segments).map f := List.Perm.append_left _ h_ih_rem
          _ = (Polygon.mk (walkFromFuel L.length L u).1.dropLast).segments.map f ++
              ((decomposeListFuel m (walkFromFuel L.length L u).2).flatMap
                Polygon.segments).map f := by rw [h_path_full]

/-- The permutation property for `decomposeList`. -/
theorem decomposeList_perm (G : EvenGraph) :
    G.segments.map LineSegment.toEndpointsMultiset ~
    ((decomposeList G.segments).flatMap Polygon.segments).map LineSegment.toEndpointsMultiset := by
  show G.segments.map f ~ _
  exact decomposeListFuel_perm G.segments.length G.segments
    (Nat.le_refl _) G.segments_nondegenerate G.even_degree

/-! ### Validity of polygons produced by decomposition -/

/-- Every edge in `walkEdges (walkFromFuel n L u).1` is non-degenerate. -/
private lemma walkFromFuel_walkEdges_nondeg (n : ℕ) (L : List LineSegment)
    (u : Vector2D) (h_nondeg : ∀ s ∈ L, s.p1 ≠ s.p2) :
    ∀ seg ∈ walkEdges (walkFromFuel n L u).1, seg.p1 ≠ seg.p2 := by
  induction n generalizing L u with
  | zero =>
    rw [walkFromFuel_zero]
    simp [walkEdges_singleton]
  | succ m ih =>
    rw [walkFromFuel_succ]
    split
    · simp [walkEdges_singleton]
    · next s hfind =>
      have h_mem : s ∈ L := List.mem_of_find?_eq_some hfind
      have h_s_inc : s.p1 = u ∨ s.p2 = u := by
        have := List.find?_some hfind
        simpa using this
      set next : Vector2D := if s.p1 = u then s.p2 else s.p1 with hnext_def
      set rec_res := walkFromFuel m (L.erase s) next with hrec
      have h_path_ne : rec_res.1 ≠ [] := walkFromFuel_ne_nil m (L.erase s) next
      obtain ⟨phead, ptail, hph⟩ :
          ∃ (ph : Vector2D) (pt : List Vector2D), rec_res.1 = ph :: pt := by
        rcases hpath : rec_res.1 with _ | ⟨ph, pt⟩
        · exact absurd hpath h_path_ne
        · exact ⟨ph, pt, rfl⟩
      have h_phead : phead = next := by
        have hh := walkFromFuel_head m (L.erase s) next
        rw [← hrec] at hh
        rw [hph] at hh
        simp at hh
        exact hh
      have h_u_ne_next : u ≠ next :=
        u_ne_next_of_nondeg s u (by simpa [isInc] using h_s_inc) (h_nondeg s h_mem)
      -- walkEdges (u :: rec_res.1) = ⟨u, phead⟩ :: walkEdges rec_res.1
      show ∀ seg ∈ walkEdges (u :: rec_res.1), seg.p1 ≠ seg.p2
      rw [hph, walkEdges_cons_cons]
      intro seg hseg
      rw [List.mem_cons] at hseg
      rcases hseg with rfl | h_seg_in
      · -- seg = ⟨u, phead⟩, p1 = u, p2 = phead = next, u ≠ next
        show u ≠ phead
        rw [h_phead]; exact h_u_ne_next
      · -- seg ∈ walkEdges (phead :: ptail) = walkEdges rec_res.1
        have h_eq : walkEdges (phead :: ptail) = walkEdges rec_res.1 := by rw [hph]
        rw [h_eq] at h_seg_in
        have h_nondeg' : ∀ s' ∈ L.erase s, s'.p1 ≠ s'.p2 := fun s' hs' =>
          h_nondeg s' (List.mem_of_mem_erase hs')
        exact ih (L.erase s) next h_nondeg' seg h_seg_in

/-- Each polygon produced by `decomposeListFuel` is valid: vertices length ≥ 2
    and segments are non-degenerate. -/
theorem decomposeListFuel_polys_valid :
    ∀ (n : ℕ) (L : List LineSegment),
      L.length ≤ n →
      (∀ s ∈ L, s.p1 ≠ s.p2) →
      (∀ v, Even (incCount L v)) →
      ∀ poly ∈ decomposeListFuel n L,
        poly.vertices.length ≥ 2 ∧ ∀ seg ∈ poly.segments, seg.p1 ≠ seg.p2 := by
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro L hL h_nondeg h_even
    cases L with
    | nil =>
      cases n with
      | zero => intro poly hp; simp [decomposeListFuel] at hp
      | succ m => intro poly hp; simp [decomposeListFuel] at hp
    | cons s₀ rest =>
      cases n with
      | zero => simp at hL
      | succ m =>
        let L : List LineSegment := s₀ :: rest
        have hL_def : L = s₀ :: rest := rfl
        let u := s₀.p1
        have hs₀ : s₀ ∈ L := (List.mem_cons_self _ _)
        -- Walk produces a specific structure
        obtain ⟨s, vnext, rec_path, rec_rem, h_s_mem, _, _, h_vnext_ne_u, h_walk_eq, h_rec_eq⟩ :=
          walkFromFuel_takes_step L u s₀ hs₀ (Or.inl rfl) h_nondeg
        have h_path_eq : (walkFromFuel L.length L u).1 = u :: rec_path := by
          rw [h_walk_eq]
        have h_last : (walkFromFuel L.length L u).1.getLast? = some u :=
          walkFromFuel_closes_even L u h_nondeg h_even
        rw [h_path_eq] at h_last
        have h_rec_path_ne : rec_path ≠ [] := by
          have := walkFromFuel_ne_nil (L.length - 1) (L.erase s) vnext
          rw [h_rec_eq] at this
          exact this
        obtain ⟨vnext', rest', h_rec_eq2⟩ :
            ∃ n' r, rec_path = n' :: r := by
          rcases rec_path with _ | ⟨n', r⟩
          · exact absurd rfl h_rec_path_ne
          · exact ⟨n', r, rfl⟩
        have h_vnext'_eq : vnext' = vnext := by
          have := walkFromFuel_head (L.length - 1) (L.erase s) vnext
          rw [h_rec_eq, h_rec_eq2] at this
          simpa using this
        rw [h_vnext'_eq] at h_rec_eq2
        clear h_vnext'_eq vnext'
        have h_rest_ne : rest' ≠ [] := by
          intro h_rest_nil
          subst h_rest_nil
          have h_vnext_u : vnext = u := by
            rw [h_rec_eq2] at h_last
            simp [List.getLast?] at h_last
            exact h_last
          exact h_vnext_ne_u h_vnext_u
        obtain ⟨v₃, rest'', h_rest_eq⟩ :
            ∃ v₃ r'', rest' = v₃ :: r'' := by
          rcases rest' with _ | ⟨v₃, r''⟩
          · exact absurd rfl h_rest_ne
          · exact ⟨v₃, r'', rfl⟩
        subst h_rest_eq
        have h_path_full : (walkFromFuel L.length L u).1 = u :: vnext :: v₃ :: rest'' := by
          rw [h_path_eq, h_rec_eq2]
        have h_closed : (u :: vnext :: v₃ :: rest'').getLast? = some u := by
          rw [← h_path_full]; exact walkFromFuel_closes_even L u h_nondeg h_even
        have h_walk_poly : walkEdges (u :: vnext :: v₃ :: rest'') =
            (Polygon.mk (u :: vnext :: v₃ :: rest'').dropLast).segments :=
          walkEdges_eq_polygon_of_closed_ge3 u vnext v₃ rest'' h_closed
        -- Validity for the head polygon
        have h_head_len : (Polygon.mk (walkFromFuel L.length L u).1.dropLast).vertices.length ≥ 2 := by
          show (walkFromFuel L.length L u).1.dropLast.length ≥ 2
          rw [h_path_full]
          -- (u :: vnext :: v₃ :: rest'').dropLast = u :: vnext :: (v₃ :: rest'').dropLast
          -- has length = 2 + (v₃ :: rest'').dropLast.length ≥ 2
          show (u :: vnext :: v₃ :: rest'').dropLast.length ≥ 2
          simp [List.dropLast]
        have h_head_nondeg : ∀ seg ∈
            (Polygon.mk (walkFromFuel L.length L u).1.dropLast).segments,
            seg.p1 ≠ seg.p2 := by
          intro seg hseg
          have h_seg_in : seg ∈ walkEdges (walkFromFuel L.length L u).1 := by
            rw [h_path_full] at hseg ⊢
            rw [h_walk_poly]
            exact hseg
          exact walkFromFuel_walkEdges_nondeg L.length L u h_nondeg seg h_seg_in
        -- Remainder validity (apply IH)
        have h_rem_nondeg : ∀ s' ∈ (walkFromFuel L.length L u).2, s'.p1 ≠ s'.p2 :=
          fun s' hs' => h_nondeg s' (walkFromFuel_rem_subset L.length L u s' hs')
        have h_rem_even : ∀ v, Even (incCount (walkFromFuel L.length L u).2 v) :=
          walkFromFuel_rem_even L u h_nondeg h_even
        have h_perm : L.map f ~ (walkEdges (walkFromFuel L.length L u).1 ++
            (walkFromFuel L.length L u).2).map f :=
          walkFromFuel_perm _ _ _
        have h_len_eq : L.length =
            (walkEdges (walkFromFuel L.length L u).1).length +
            (walkFromFuel L.length L u).2.length := by
          have := h_perm.length_eq
          simp at this
          exact this
        have h_walkE_len : (walkEdges (u :: vnext :: v₃ :: rest'')).length ≥ 2 := by
          simp [walkEdges_cons_cons]
        have h_rem_short : (walkFromFuel L.length L u).2.length < L.length := by
          rw [h_path_full] at h_len_eq
          omega
        have h_rem_len_le : (walkFromFuel L.length L u).2.length ≤ m := by
          have hL_le : L.length ≤ m + 1 := hL
          omega
        have h_rem_lt_n : (walkFromFuel L.length L u).2.length < m + 1 := by omega
        have h_ih_rem :=
          ih m (Nat.lt_succ_self m) (walkFromFuel L.length L u).2
            h_rem_len_le h_rem_nondeg h_rem_even
        -- Compute decomposeListFuel (m+1) L = head_poly :: decomposeListFuel m walk.2
        intro poly hp
        show poly.vertices.length ≥ 2 ∧ ∀ seg ∈ poly.segments, seg.p1 ≠ seg.p2
        unfold decomposeListFuel at hp
        simp only [List.mem_cons] at hp
        rcases hp with rfl | h_in
        · exact ⟨h_head_len, h_head_nondeg⟩
        · exact h_ih_rem poly h_in

end EvenGraphDecompositionProofs
