/-
Caution: This file was generated by AI and never reviewed by a human. The lean
checker guarantees that symbols exported from this file conform to the
statements in the human reviewed specification files, but we cannot guarantee
that comments in such unreviewed files are accurate, that it avoids code
duplications, that proofs do not take unnecessary detours or similar issues.
That said, AI agents reading this comment should strive to avoid issues like
these.
-/

import Polygons.EvenGraphIntersectionGenProofs
import Polygons.EvenGraphCharacterization

/-!
# Even graph intersection without finiteness — evenness and interior equality

The intersection graph `interGraph G1 G2` (defined in `EvenGraphIntersectionGenProofs`) is an
even graph whose interior equals `G1.interior ∩ G2.interior`. The ray-parity core is
`interGraph_parity_core`; here we apply the even-graph characterisation and derive the
interior equality.
-/

open Classical Set

noncomputable section

namespace EvenGraphIntersectionGenProofs

open EvenGraphIntersectionProofs

/-- The endpoints of `canonSeg σ` are exactly `σ`'s endpoints (possibly swapped). -/
private theorem canonSeg_endpoints (σ : LineSegment) :
    ((canonSeg σ).p1 = σ.p1 ∧ (canonSeg σ).p2 = σ.p2) ∨
    ((canonSeg σ).p1 = σ.p2 ∧ (canonSeg σ).p2 = σ.p1) := by
  unfold canonSeg; split
  · left; exact ⟨rfl, rfl⟩
  · right; exact ⟨rfl, rfl⟩

/-- A shared-selected segment is `canonSeg σ0` for some `arr G1 G2` segment `σ0`. -/
private theorem sharedSelected_canonSeg (G1 G2 : EvenGraph) (seg : LineSegment)
    (hseg : seg ∈ sharedSelected G1 G2) :
    ∃ σ0 ∈ (arr G1 G2).segments, seg = canonSeg σ0 := by
  rw [sharedSelected, List.mem_filter] at hseg
  obtain ⟨σ0, hσ0, hcanon⟩ := List.mem_map.mp (List.mem_dedup.mp hseg.1)
  exact ⟨σ0, hσ0, hcanon.symm⟩

/-! ### Collinearity helpers

`lineOf`/`SameLine` algebra used to convert collinearity between a segment and sub/super-segments
of it. -/

/-- A segment whose endpoints lie on a line lies entirely on that line. -/
private theorem lineOf_closed (c Y : LineSegment) (h1 : Y.p1 ∈ lineOf c) (h2 : Y.p2 ∈ lineOf c) :
    Y.toSet ⊆ lineOf c := by
  intro p hp
  obtain ⟨t, _, _, hx, hy⟩ := hp
  simp only [lineOf, Set.mem_setOf_eq] at h1 h2 ⊢
  rw [hx, hy]; linear_combination (1 - t) * h1 + t * h2

/-- Line membership transfers from a non-degenerate `d` (whose endpoints — via `c.p1`, `c.p2` —
    sit on `d`'s line) to `c`. -/
private theorem mem_lineOf_transfer (d : LineSegment) (hd : d.p1 ≠ d.p2) (c : LineSegment)
    (h1 : c.p1 ∈ lineOf d) (h2 : c.p2 ∈ lineOf d) : lineOf d ⊆ lineOf c := by
  intro z hz
  have hd_dir : (d.p2.x - d.p1.x, d.p2.y - d.p1.y) ≠ (0, 0) := by
    intro hh
    apply hd
    have hhx : d.p2.x - d.p1.x = 0 := congrArg Prod.fst hh
    have hhy : d.p2.y - d.p1.y = 0 := congrArg Prod.snd hh
    exact (Vector2D.ext (by linarith) (by linarith)).symm
  -- (c.p2 - c.p1) ∥ d_dir  and  (z - c.p1) ∥ d_dir  ⟹  (c.p2 - c.p1) ∥ (z - c.p1).
  have hc12 := dir_parallel_of_two_mem_lineOf d c.p1 c.p2 h1 h2
  have hcz := dir_parallel_of_two_mem_lineOf d c.p1 z h1 hz
  have := parallel_trans_of_nonzero (c.p2.x - c.p1.x) (c.p2.y - c.p1.y)
    (z.x - c.p1.x) (z.y - c.p1.y) (d.p2.x - d.p1.x) (d.p2.y - d.p1.y) hd_dir hc12 hcz
  simp only [lineOf, Set.mem_setOf_eq]; linarith [this]

/-- Two non-degenerate segments whose endpoints lie on each other's line have the same line. -/
private theorem lineOf_eq (a b : LineSegment) (ha : a.p1 ≠ a.p2) (hb : b.p1 ≠ b.p2)
    (h1 : a.p1 ∈ lineOf b) (h2 : a.p2 ∈ lineOf b) : lineOf a = lineOf b := by
  have h_ba : lineOf b ⊆ lineOf a := mem_lineOf_transfer b hb a h1 h2
  have hbp1 : b.p1 ∈ lineOf a := h_ba (mem_lineOf_p1 b)
  have hbp2 : b.p2 ∈ lineOf a := h_ba (mem_lineOf_p2 b)
  exact Set.Subset.antisymm (mem_lineOf_transfer a ha b hbp1 hbp2) h_ba

/-- If `X ⊆ Y` (as point sets) and `SameLine c Y`, then `SameLine c X`. -/
private theorem sameLine_of_subset (c X Y : LineSegment) (h_sub : X.toSet ⊆ Y.toSet)
    (h_cY : SameLine c Y) : SameLine c X := by
  have hY : Y.toSet ⊆ lineOf c := lineOf_closed c Y h_cY.1 h_cY.2
  exact ⟨hY (h_sub (seg_p1_mem X)), hY (h_sub (seg_p2_mem X))⟩

/-- If `X ⊆ Y` with both non-degenerate, then `SameLine c X` gives `SameLine c Y`
    (for non-degenerate `c`). -/
private theorem sameLine_of_superset (c X Y : LineSegment) (hc : c.p1 ≠ c.p2)
    (hX : X.p1 ≠ X.p2) (hY : Y.p1 ≠ Y.p2) (h_sub : X.toSet ⊆ Y.toSet)
    (h_cX : SameLine c X) : SameLine c Y := by
  -- lineOf X = lineOf Y (X ⊆ Y, both nondeg) and lineOf X = lineOf c (SameLine c X, both nondeg).
  have hXp1Y : X.p1 ∈ lineOf Y := toSet_subset_lineOf Y (h_sub (seg_p1_mem X))
  have hXp2Y : X.p2 ∈ lineOf Y := toSet_subset_lineOf Y (h_sub (seg_p2_mem X))
  have hXY : lineOf X = lineOf Y := lineOf_eq X Y hX hY hXp1Y hXp2Y
  have hXc : lineOf X = lineOf c := lineOf_eq X c hX hc h_cX.1 h_cX.2
  have hYc : lineOf Y = lineOf c := by rw [← hXY, hXc]
  exact ⟨by rw [← hYc]; exact mem_lineOf_p1 Y, by rw [← hYc]; exact mem_lineOf_p2 Y⟩

/-- Collinearity transitivity through a non-degenerate common segment. -/
private theorem sameLine_trans (c a b : LineSegment) (hc : c.p1 ≠ c.p2) (ha : a.p1 ≠ a.p2)
    (h_ca : SameLine c a) (h_cb : SameLine c b) : SameLine a b := by
  have hac : lineOf a = lineOf c := lineOf_eq a c ha hc h_ca.1 h_ca.2
  exact ⟨by rw [hac]; exact h_cb.1, by rw [hac]; exact h_cb.2⟩

/-! ### Coverage of an original segment by refinement pieces

These helper lemmas record the (converse-to-`arr_seg_subset`) fact that every point of an
original segment is covered by a refinement piece contained in that segment. -/

/-- One `graphRefinement` step covers every point of an original segment by a piece contained
    in that segment. -/
private theorem graphRefinement_seg_cover (G : EvenGraph) (seg : LineSegment) (pt : Vector2D)
    (h_seg : seg ∈ G.segments) (h_pt : pt ∈ seg.toSet)
    (s₀ : LineSegment) (hs₀ : s₀ ∈ G.segments) (v : Vector2D) (hv : v ∈ s₀.toSet) :
    ∃ w ∈ (EvenGraphRefinementProofs.graphRefinement G seg pt h_seg h_pt).segments,
      v ∈ w.toSet ∧ w.toSet ⊆ s₀.toSet := by
  unfold EvenGraphRefinementProofs.graphRefinement
  split
  · -- pt is an endpoint of seg: graph unchanged.
    exact ⟨s₀, hs₀, hv, le_refl _⟩
  · rename_i h_not_ep
    -- segments = replaceSegment G.segments seg ⟨seg.p1, pt⟩ ⟨pt, seg.p2⟩.
    by_cases h_eq : s₀ = seg
    · -- s₀ = seg: v ∈ seg.toSet = ⟨seg.p1,pt⟩.toSet ∪ ⟨pt,seg.p2⟩.toSet.
      subst h_eq
      have h_eta : (⟨s₀.p1, s₀.p2⟩ : LineSegment) = s₀ := by cases s₀; rfl
      have h_split := EvenGraphRefinementProofs.segment_split s₀.p1 s₀.p2 pt (by rw [h_eta]; exact h_pt)
      rw [h_eta] at h_split
      have hv' : v ∈ (LineSegment.mk s₀.p1 pt).toSet ∪ (LineSegment.mk pt s₀.p2).toSet := by
        rw [h_split]; exact hv
      rcases hv' with hv1 | hv2
      · exact ⟨⟨s₀.p1, pt⟩,
          EvenGraphRefinementProofs.seg1_mem_replaceSegment G.segments s₀ ⟨s₀.p1, pt⟩ ⟨pt, s₀.p2⟩ hs₀,
          hv1, EvenGraphRefinementProofs.subseg_p1_subset s₀ pt h_pt⟩
      · exact ⟨⟨pt, s₀.p2⟩,
          EvenGraphRefinementProofs.seg2_mem_replaceSegment G.segments s₀ ⟨s₀.p1, pt⟩ ⟨pt, s₀.p2⟩ hs₀,
          hv2, EvenGraphRefinementProofs.subseg_p2_subset s₀ pt h_pt⟩
    · -- s₀ ≠ seg: s₀ survives.
      exact ⟨s₀, EvenGraphRefinementProofs.replaceSegment_of_mem_ne G.segments seg ⟨seg.p1, pt⟩
        ⟨pt, seg.p2⟩ s₀ hs₀ h_eq, hv, le_refl _⟩

/-- `refineAllPtBounded` covers every point of an original segment by a piece contained in it. -/
private theorem refineAllPtBounded_seg_cover (n : ℕ) (pt : Vector2D) :
    ∀ (G : EvenGraph) (s₀ : LineSegment), s₀ ∈ G.segments → ∀ v ∈ s₀.toSet,
      ∃ w ∈ (EvenGraphRefinementProofs.refineAllPtBounded n G pt).segments,
        v ∈ w.toSet ∧ w.toSet ⊆ s₀.toSet := by
  induction n with
  | zero =>
    intro G s₀ hs₀ v hv
    exact ⟨s₀, hs₀, hv, le_refl _⟩
  | succ n ih =>
    intro G s₀ hs₀ v hv
    simp only [EvenGraphRefinementProofs.refineAllPtBounded]
    split
    · exact ⟨s₀, hs₀, hv, le_refl _⟩
    · rename_i seg h_find
      have h_seg := List.mem_of_find?_eq_some h_find
      have h_pred := List.find?_some h_find
      have h_pt : pt ∈ seg.toSet := by
        simp only [Bool.and_eq_true, decide_eq_true_eq] at h_pred; exact h_pred.1
      -- Cover v by a piece w' of s₀ in graphRefinement, then recurse.
      obtain ⟨w', hw', hvw', hw'sub⟩ :=
        graphRefinement_seg_cover G seg pt h_seg h_pt s₀ hs₀ v hv
      obtain ⟨w, hw, hvw, hwsub⟩ :=
        ih (EvenGraphRefinementProofs.graphRefinement G seg pt h_seg h_pt) w' hw' v hvw'
      exact ⟨w, hw, hvw, hwsub.trans hw'sub⟩

/-- `refineAllPt` covers every point of an original segment by a piece contained in it. -/
private theorem refineAllPt_seg_cover (G : EvenGraph) (pt : Vector2D)
    (s₀ : LineSegment) (hs₀ : s₀ ∈ G.segments) (v : Vector2D) (hv : v ∈ s₀.toSet) :
    ∃ w ∈ (EvenGraphRefinementProofs.refineAllPt G pt).segments,
      v ∈ w.toSet ∧ w.toSet ⊆ s₀.toSet :=
  refineAllPtBounded_seg_cover _ pt G s₀ hs₀ v hv

/-- `refineGraphWithPoints` covers every point of an original segment by a piece contained
    in it. -/
private theorem refineGraphWithPoints_seg_cover :
    ∀ (G : EvenGraph) (pts : List Vector2D)
      (h_all : ∀ pt ∈ pts, pt ∈ G.toBoundarySet) (s₀ : LineSegment),
      s₀ ∈ G.segments → ∀ v ∈ s₀.toSet,
      ∃ w ∈ (EvenGraphRefinementProofs.refineGraphWithPoints G pts h_all).segments,
        v ∈ w.toSet ∧ w.toSet ⊆ s₀.toSet
  | G, [], _, s₀, hs₀, v, hv => ⟨s₀, hs₀, hv, le_refl _⟩
  | G, pt :: rest, h_all, s₀, hs₀, v, hv => by
      simp only [EvenGraphRefinementProofs.refineGraphWithPoints]
      obtain ⟨w', hw', hvw', hw'sub⟩ := refineAllPt_seg_cover G pt s₀ hs₀ v hv
      obtain ⟨w, hw, hvw, hwsub⟩ :=
        refineGraphWithPoints_seg_cover (EvenGraphRefinementProofs.refineAllPt G pt) rest _ w' hw' v hvw'
      exact ⟨w, hw, hvw, hwsub.trans hw'sub⟩

/-- Coverage for the self-refinement: every point of an original `G`-segment lies on a
    `graphRefinementSelf G` segment contained in it. -/
private theorem graphRefinementSelf_seg_cover (G : EvenGraph)
    (s₀ : LineSegment) (hs₀ : s₀ ∈ G.segments) (v : Vector2D) (hv : v ∈ s₀.toSet) :
    ∃ w ∈ (graphRefinementSelf G).segments, v ∈ w.toSet ∧ w.toSet ⊆ s₀.toSet :=
  refineGraphWithPoints_seg_cover G _ _ s₀ hs₀ v hv

/-- The endpoint property for the self-refinement, for **any** original-vertex `v`
    (not just a self-refined vertex): every `graphRefinementSelf G` segment containing `v`
    has `v` as an endpoint. This generalises `graphRefinementSelf_no_segment_interior_vertices`
    from `(graphRefinementSelf G).toVertices` to `G.toVertices`. -/
private theorem graphRefinementSelf_endpoint_of_orig_vertex (G : EvenGraph) (v : Vector2D)
    (hv : v ∈ G.toVertices) :
    ∀ w ∈ (graphRefinementSelf G).segments, v ∈ w.toSet → v = w.p1 ∨ v = w.p2 := by
  intro w hw hvw
  have h_fin := EvenGraphRefinementProofs.selfSegmentInteriorVertices_finite G
  set pts := h_fin.toFinset.toList with hpts_def
  have h_all : ∀ pt ∈ pts, pt ∈ G.toBoundarySet := fun pt h_mem =>
    EvenGraphRefinementProofs.selfSegmentInteriorVertices_subset_boundary G
      (h_fin.mem_toFinset.mp (Finset.mem_toList.mp h_mem))
  -- v ∈ G.toVertexSet.
  have h_v_vset : v ∈ G.toVertexSet := hv
  by_cases h_v_pts : v ∈ pts
  · -- v is a self-refined breakpoint; pts_endpoint applies.
    exact EvenGraphRefinementProofs.refineGraphWithPoints_pts_endpoint G pts h_all v h_v_pts w hw hvw
  · -- v ∉ pts ⇒ v ∉ selfSegmentInteriorVertices G ⇒ v is endpoint of every G-segment ∋ v.
    have h_v_not_si : v ∉ EvenGraphRefinementProofs.selfSegmentInteriorVertices G := by
      intro h_si
      exact h_v_pts (Finset.mem_toList.mpr (h_fin.mem_toFinset.mpr h_si))
    have h_v_ep_G : ∀ s ∈ G.segments, v ∈ s.toSet → v = s.p1 ∨ v = s.p2 := by
      intro s hs h_v_s
      by_contra h_not_ep
      push_neg at h_not_ep
      exact h_v_not_si ⟨h_v_vset, s, hs, h_v_s, h_not_ep.1, h_not_ep.2⟩
    exact EvenGraphRefinementProofs.refineGraphWithPoints_preserves_endpoint G pts h_all v
      h_v_ep_G w hw hvw

/-- Every segment of `graphRefinementSelf G` is contained in some `G`-segment. -/
private theorem graphRefinementSelf_seg_subset (G : EvenGraph) (σ : LineSegment)
    (hσ : σ ∈ (graphRefinementSelf G).segments) :
    ∃ s ∈ G.segments, σ.toSet ⊆ s.toSet :=
  refineGraphWithPoints_seg_subset G _ _ σ hσ

/-- Self-refinement does not introduce vertices outside `G`'s vertex set. -/
private theorem graphRefinementSelf_toVertexSet_subset (G : EvenGraph) :
    (graphRefinementSelf G).toVertexSet ⊆ G.toVertexSet := by
  intro v hv
  have h_fin := EvenGraphRefinementProofs.selfSegmentInteriorVertices_finite G
  have h_sub := EvenGraphRefinementProofs.refineGraphWithPoints_toVertexSet_subset G
    h_fin.toFinset.toList (fun pt h_mem =>
      EvenGraphRefinementProofs.selfSegmentInteriorVertices_subset_boundary G
        (h_fin.mem_toFinset.mp (Finset.mem_toList.mp h_mem)))
  rcases h_sub hv with h | h_pts
  · exact h
  · -- v ∈ selfPts ⊆ selfSegmentInteriorVertices G ⊆ G.toVertexSet.
    exact (h_fin.mem_toFinset.mp (Finset.mem_toList.mp h_pts)).1

/-! ### Non-collinear witness gives a contradiction

For a `seg ∈ (arr G1 G2).segments` and `v` in its **open interior**, no `(graphRefinementSelf G1)`-,
`(graphRefinementSelf G2)`-, `G1`- or `G2`-segment that is non-collinear with `seg` may pass
through `v`. This is the engine for the "crossing" sub-case. -/

/-- If a `(graphRefinementSelf G1)`- or `G2`-segment non-collinear with `seg` passes through a point
    `v` in the open interior of `seg`, we get a contradiction. -/
private theorem noncollinear_absurd_arr1_or_G2 (G1 G2 : EvenGraph) (seg : LineSegment)
    (hseg : seg ∈ (arr G1 G2).segments) (v : Vector2D) (hon : v ∈ seg.toSet)
    (hv1 : v ≠ seg.p1) (hv2 : v ≠ seg.p2) (W : LineSegment)
    (hW : W ∈ (graphRefinementSelf G1).segments ++ G2.segments)
    (hvW : v ∈ W.toSet) (hncol : ¬ SameLine seg W) : False :=
  arr_int_avoids_noncollinear G1 G2 seg hseg W hW hncol v hon hv1 hv2 hvW

/-- A non-collinear-with-`seg` segment through `v` (open interior of `seg`), drawn from
    `G1.segments`, `G2.segments`, `(graphRefinementSelf G1).segments`, or
    `(graphRefinementSelf G2).segments`, yields a contradiction. -/
private theorem noncollinear_absurd (G1 G2 : EvenGraph) (seg : LineSegment)
    (hseg : seg ∈ (arr G1 G2).segments) (hsegnd : seg.p1 ≠ seg.p2) (v : Vector2D)
    (hon : v ∈ seg.toSet) (hv1 : v ≠ seg.p1) (hv2 : v ≠ seg.p2) (W : LineSegment)
    (hvW : v ∈ W.toSet) (hncol : ¬ SameLine seg W)
    (hWsrc : W ∈ G1.segments ∨ W ∈ G2.segments ∨
      W ∈ (graphRefinementSelf G1).segments ∨ W ∈ (graphRefinementSelf G2).segments) :
    False := by
  rcases hWsrc with hG1 | hG2 | hgrs1 | hgrs2
  · -- W ∈ G1.segments: cover v by a (gRS G1)-piece w'' ⊆ W; w'' non-collinear with seg.
    obtain ⟨w'', hw'', hvw'', hw''sub⟩ := graphRefinementSelf_seg_cover G1 W hG1 v hvW
    have hWnd : W.p1 ≠ W.p2 := G1.segments_nondegenerate W hG1
    have hw''nd : w''.p1 ≠ w''.p2 := (graphRefinementSelf G1).segments_nondegenerate w'' hw''
    have hncol'' : ¬ SameLine seg w'' := by
      intro h_col
      exact hncol (sameLine_of_superset seg w'' W hsegnd hw''nd hWnd hw''sub h_col)
    exact noncollinear_absurd_arr1_or_G2 G1 G2 seg hseg v hon hv1 hv2 w''
      (List.mem_append.mpr (Or.inl hw'')) hvw'' hncol''
  · -- W ∈ G2.segments: directly in the append.
    exact noncollinear_absurd_arr1_or_G2 G1 G2 seg hseg v hon hv1 hv2 W
      (List.mem_append.mpr (Or.inr hG2)) hvW hncol
  · -- W ∈ (gRS G1).segments: directly in the append (left).
    exact noncollinear_absurd_arr1_or_G2 G1 G2 seg hseg v hon hv1 hv2 W
      (List.mem_append.mpr (Or.inl hgrs1)) hvW hncol
  · -- W ∈ (gRS G2).segments: contained in some G2-segment g2 (collinear with W).
    obtain ⟨g2, hg2, hWsub⟩ := graphRefinementSelf_seg_subset G2 W hgrs2
    have hncol2 : ¬ SameLine seg g2 := by
      intro h_col
      exact hncol (sameLine_of_subset seg W g2 hWsub h_col)
    exact noncollinear_absurd_arr1_or_G2 G1 G2 seg hseg v hon hv1 hv2 g2
      (List.mem_append.mpr (Or.inr hg2)) (hWsub hvW) hncol2

/-- A vertex of `arr G2 G1` that lies on a *shared* `arr G1 G2` segment `seg`
    (i.e. `seg.toSet ⊆ ∂G2`) is one of `seg`'s endpoints. -/
private theorem arr_shared_vertex_endpoint (G1 G2 : EvenGraph) (seg : LineSegment)
    (hseg : seg ∈ (arr G1 G2).segments) (_hshared : IsShared G2 seg) (v : Vector2D)
    (_hvG2 : v ∈ G2.toBoundarySet) (hv2 : v ∈ (arr G2 G1).toVertices)
    (hon : v ∈ seg.toSet) : v = seg.p1 ∨ v = seg.p2 := by
  -- seg ∈ arr1.segments ⊆ some self-refined-G1 segment s.
  obtain ⟨s, hs, hseg_sub_s⟩ := arr_seg_subset G1 G2 seg hseg
  have hsnd : s.p1 ≠ s.p2 := (graphRefinementSelf G1).segments_nondegenerate s hs
  have hsegnd : seg.p1 ≠ seg.p2 := (arr G1 G2).segments_nondegenerate seg hseg
  by_contra hvne
  push_neg at hvne
  obtain ⟨hvn1, hvn2⟩ := hvne
  -- v ∈ open interior of seg.
  -- (M1) If v is a breakpoint of (graphRefinementSelf G1) wrt G2, it is an endpoint of seg.
  have m1 : v ∈ breakpointsSet (graphRefinementSelf G1) G2 → False := by
    intro hbp
    have hv_list : v ∈ breakpointsList (graphRefinementSelf G1) G2 :=
      (mem_breakpointsList_iff _ _ v).mpr hbp
    rcases EvenGraphRefinementProofs.refineGraphWithPoints_pts_endpoint (graphRefinementSelf G1)
        (breakpointsList (graphRefinementSelf G1) G2)
        (breakpointsList_subset_boundary (graphRefinementSelf G1) G2)
        v hv_list seg hseg hon with h | h
    · exact hvn1 h
    · exact hvn2 h
  -- (M2) If v is an endpoint of every (graphRefinementSelf G1)-segment containing it,
  -- it is an endpoint of seg.
  have m2 : (∀ w ∈ (graphRefinementSelf G1).segments, v ∈ w.toSet → v = w.p1 ∨ v = w.p2) →
      False := by
    intro hep
    rcases EvenGraphRefinementProofs.refineGraphWithPoints_preserves_endpoint (graphRefinementSelf G1)
        (breakpointsList (graphRefinementSelf G1) G2)
        (breakpointsList_subset_boundary (graphRefinementSelf G1) G2)
        v hep seg hseg hon with h | h
    · exact hvn1 h
    · exact hvn2 h
  -- v ∈ ∂G1 = ∂(graphRefinementSelf G1) (it lies on seg ⊆ ∂arr1 = ∂G1).
  have hv_grs1_bnd : v ∈ (graphRefinementSelf G1).toBoundarySet := by
    rw [graphRefinementSelf_boundary_eq, ← arr_boundary_eq G1 G2]
    exact ⟨seg, hseg, hon⟩
  -- Characterise the arr2-vertex v.
  have hv2' : v ∈ (arr G2 G1).toVertexSet := hv2
  have h_arr2_split : v ∈ (graphRefinementSelf G2).toVertexSet ∨
      v ∈ { p | p ∈ breakpointsList (graphRefinementSelf G2) G1 } :=
    EvenGraphRefinementProofs.refineGraphWithPoints_toVertexSet_subset (graphRefinementSelf G2)
      (breakpointsList (graphRefinementSelf G2) G1)
      (breakpointsList_subset_boundary (graphRefinementSelf G2) G1) hv2'
  rcases h_arr2_split with hA | hB
  · -- Case A: v ∈ (gRS G2).toVertexSet ⊆ G2.toVertexSet = G2.toVertices.
    have hvG2_vert : v ∈ G2.toVertices := graphRefinementSelf_toVertexSet_subset G2 hA
    exact m1 (Or.inr ⟨hvG2_vert, hv_grs1_bnd⟩)
  · -- Case B: v ∈ breakpointsList (gRS G2) G1 = breakpointsSet (gRS G2) G1.
    have hB' : v ∈ breakpointsSet (graphRefinementSelf G2) G1 :=
      (mem_breakpointsList_iff _ _ v).mp hB
    rcases hB' with ⟨s', hs', t', ht', hncol_st, hvs', hvt'⟩ | ⟨hvG1_vert, _⟩
    · -- B1 (crossing): s', t' non-collinear, both through v.
      -- s' ∈ (gRS G2).segments, t' ∈ (gRS G2).segments ++ G1.segments.
      have hs'nd : s'.p1 ≠ s'.p2 := (graphRefinementSelf G2).segments_nondegenerate s' hs'
      -- At least one of s', t' is non-collinear with seg.
      by_cases hcol_s' : SameLine seg s'
      · -- s' collinear with seg ⇒ t' non-collinear with seg (else SameLine s' t').
        have hcol_t' : ¬ SameLine seg t' := by
          intro hcol_t'
          exact hncol_st (sameLine_trans seg s' t' hsegnd hs'nd hcol_s' hcol_t')
        -- t' ∈ (gRS G2).segments ++ G1.segments.
        rcases List.mem_append.mp ht' with ht'1 | ht'2
        · exact noncollinear_absurd G1 G2 seg hseg hsegnd v hon hvn1 hvn2 t' hvt' hcol_t'
            (Or.inr (Or.inr (Or.inr ht'1)))
        · exact noncollinear_absurd G1 G2 seg hseg hsegnd v hon hvn1 hvn2 t' hvt' hcol_t'
            (Or.inl ht'2)
      · -- s' non-collinear with seg; s' ∈ (gRS G2).segments.
        exact noncollinear_absurd G1 G2 seg hseg hsegnd v hon hvn1 hvn2 s' hvs' hcol_s'
          (Or.inr (Or.inr (Or.inr hs')))
    · -- B2: v ∈ G1.toVertices. Then v is an endpoint of every (gRS G1)-segment ∋ v (M2).
      exact m2 (graphRefinementSelf_endpoint_of_orig_vertex G1 v hvG1_vert)

/-- A ray from `p` whose support avoids every point of a finite list `pts` not containing `p`. -/
private theorem exists_ray_avoiding_point_list (p : Vector2D) (pts : List Vector2D)
    (h_not_p : ∀ v ∈ pts, v ≠ p) :
    ∃ r : Ray, r.origin = p ∧ ∀ v ∈ pts, v ∉ r.toSet := by
  have h_inf : Infinite ℚ := Infinite.of_injective (fun n : ℕ => (n : ℚ)) Nat.cast_injective
  let badSlopes : Finset ℚ := (pts.filterMap fun v =>
    if v.x > p.x then some ((v.y - p.y) / (v.x - p.x)) else none).toFinset
  obtain ⟨q, hq⟩ := Finset.exists_not_mem badSlopes
  have h_nonzero : (⟨1, q⟩ : Vector2D) ≠ ⟨0, 0⟩ := by
    intro h; exact absurd (congrArg Vector2D.x h) (by norm_num)
  refine ⟨⟨p, ⟨1, q⟩, h_nonzero⟩, rfl, ?_⟩
  intro v hv hmem
  simp only [Ray.toSet, Set.mem_setOf_eq] at hmem
  obtain ⟨t, ht_nonneg, hvx, hvy⟩ := hmem
  simp only [mul_one] at hvx
  have hne : v ≠ p := h_not_p v hv
  have ht_eq : t = v.x - p.x := by linarith
  by_cases h_gt : v.x > p.x
  · have h_slope_mem : (v.y - p.y) / (v.x - p.x) ∈ badSlopes := by
      simp only [badSlopes, List.mem_toFinset, List.mem_filterMap]
      exact ⟨v, hv, by simp [if_pos h_gt]⟩
    have hvmy : v.y - p.y = t * q := by linarith
    rw [ht_eq] at hvmy
    have hvx_ne : v.x - p.x ≠ 0 := ne_of_gt (by linarith : v.x - p.x > 0)
    have hq_eq : q = (v.y - p.y) / (v.x - p.x) := by
      rw [eq_div_iff hvx_ne, mul_comm]; linarith
    exact hq (hq_eq ▸ h_slope_mem)
  · push_neg at h_gt
    by_cases h_eq : v.x = p.x
    · have ht_zero : t = 0 := by linarith
      have hvy_eq : v.y = p.y := by
        have := hvy; rw [ht_zero] at this; simp at this; exact this
      exact hne (by cases v; cases p; simp_all)
    · linarith [lt_of_le_of_ne h_gt h_eq]

/-- Every point of `Xlist G1 G2` lies on `∂G1 ∪ ∂G2`. -/
private theorem Xlist_subset_boundary (G1 G2 : EvenGraph) (x : Vector2D)
    (hx : x ∈ Xlist G1 G2) : x ∈ G1.toBoundarySet ∪ G2.toBoundarySet := by
  rw [mem_Xlist_iff] at hx
  obtain ⟨s, hs, _, _, _, hxs, _⟩ := hx
  rcases List.mem_append.mp hs with h | h
  · left; rw [← arr_boundary_eq G1 G2]; exact ⟨s, h, hxs⟩
  · right; rw [← arr_boundary_eq G2 G1]; exact ⟨s, h, hxs⟩

/-- A qualifying ray from `p`: avoids `arr G1 G2` and `arr G2 G1` vertices and `Xlist G1 G2`. -/
private theorem exists_qualifying_ray (G1 G2 : EvenGraph) (p : Vector2D)
    (h_not_both : ∀ v ∈ (arr G1 G2).toVertices ++ (arr G2 G1).toVertices, v ≠ p)
    (h_off_G1 : p ∉ G1.toBoundarySet) (h_off_G2 : p ∉ G2.toBoundarySet) :
    ∃ r : Ray, r.origin = p ∧
      rayAvoidsGraphVertices r (arr G1 G2) ∧
      rayAvoidsGraphVertices r (arr G2 G1) ∧
      ∀ x ∈ Xlist G1 G2, x ∉ r.toSet := by
  let pts := (arr G1 G2).toVertices ++ (arr G2 G1).toVertices ++ Xlist G1 G2
  have h_pts_not_p : ∀ v ∈ pts, v ≠ p := by
    intro v hv
    rcases List.mem_append.mp hv with h | h
    · exact h_not_both v h
    · intro heq; subst heq
      rcases Xlist_subset_boundary G1 G2 v h with hb | hb
      · exact h_off_G1 hb
      · exact h_off_G2 hb
  obtain ⟨r, h_orig, h_avoid⟩ := exists_ray_avoiding_point_list p pts h_pts_not_p
  refine ⟨r, h_orig, ?_, ?_, ?_⟩
  · rw [rayAvoidsGraphVertices, Set.eq_empty_iff_forall_not_mem]
    intro v ⟨hv_ray, hv_vert⟩
    exact h_avoid v (List.mem_append.mpr (Or.inl (List.mem_append.mpr (Or.inl hv_vert)))) hv_ray
  · rw [rayAvoidsGraphVertices, Set.eq_empty_iff_forall_not_mem]
    intro v ⟨hv_ray, hv_vert⟩
    exact h_avoid v (List.mem_append.mpr (Or.inl (List.mem_append.mpr (Or.inr hv_vert)))) hv_ray
  · intro x hx hx_ray
    exact h_avoid x (List.mem_append.mpr (Or.inr hx)) hx_ray

/-! ### Shared machinery for the boundary-exclusion theorems

Both `interGraph_interior_off_G1` and `interGraph_interior_off_G2` are proved by contradiction
through the same three cases. The helpers below are parameterised on the *boundary* graph `Gb`
(the one we assume `p` is on) and the *other* graph `Go`, with `interGraph G1 G2` kept fixed, so
they instantiate for both theorems. -/

/-- From an odd `interGraph` crossing count (at a qualifying ray) both arrangement counts are odd. -/
private theorem both_arr_odd_of_interGraph_odd (G1 G2 : EvenGraph) (r : Ray)
    (h1 : rayAvoidsGraphVertices r (arr G1 G2))
    (h2 : rayAvoidsGraphVertices r (arr G2 G1))
    (hX : ∀ x ∈ Xlist G1 G2, x ∉ r.toSet)
    (hoff1 : r.origin ∉ G1.toBoundarySet) (hoff2 : r.origin ∉ G2.toBoundarySet)
    (h_odd : intersectionRayGraphSegmentsNumber r (interGraph G1 G2) % 2 = 1) :
    intersectionRayGraphSegmentsNumber r (arr G1 G2) % 2 = 1 ∧
    intersectionRayGraphSegmentsNumber r (arr G2 G1) % 2 = 1 := by
  have h_core := interGraph_parity_core G1 G2 r h1 h2 hX hoff1 hoff2
  rw [h_core] at h_odd
  constructor
  · by_contra hne
    have : intersectionRayGraphSegmentsNumber r (arr G1 G2) % 2 = 0 := by
      have := Nat.mod_lt (intersectionRayGraphSegmentsNumber r (arr G1 G2)) (show 0 < 2 by norm_num)
      omega
    rw [Nat.mul_mod, this] at h_odd; simp at h_odd
  · by_contra hne
    have : intersectionRayGraphSegmentsNumber r (arr G2 G1) % 2 = 0 := by
      have := Nat.mod_lt (intersectionRayGraphSegmentsNumber r (arr G2 G1)) (show 0 < 2 by norm_num)
      omega
    rw [Nat.mul_mod, this] at h_odd; simp at h_odd

/-- An `arr Gb Go` segment through `p` (with `p ∈ ∂Gb`) is transversal when `p ∉ ∂Go`. -/
private theorem arr_seg_through_p_not_shared (Gb Go : EvenGraph) (p : Vector2D)
    (h_p_on_Gb : p ∈ Gb.toBoundarySet) (h_p_not_Go : p ∉ Go.toBoundarySet) :
    ∃ σ ∈ (arr Gb Go).segments, p ∈ σ.toSet ∧ ¬ IsShared Go σ := by
  have h_p_arr : p ∈ (arr Gb Go).toBoundarySet := by rw [arr_boundary_eq Gb Go]; exact h_p_on_Gb
  obtain ⟨σ, hσ, hp_σ⟩ := h_p_arr
  refine ⟨σ, hσ, hp_σ, ?_⟩
  intro h_shared
  exact h_p_not_Go (h_shared hp_σ)

/-- Parametric step (mirrors the `case1` template): for a transversal `arr Gb Go` segment `σ`,
    with `p ∈ σ.toSet` and `q` in `σ`'s open interior, any `x` on segment `p-q` that meets `∂Go`
    must equal `p`. Since both `p` and `q` are off `∂Go`, the whole segment `p-q` is off `∂Go`. -/
private theorem case1_segpq_off_Go (Gb Go : EvenGraph) (σ : LineSegment)
    (hσ : σ ∈ (arr Gb Go).segments) (hns : ¬ IsShared Go σ) (p q : Vector2D)
    (hp_σ : p ∈ σ.toSet) (h_p_not_Go : p ∉ Go.toBoundarySet)
    (hq_seg : q ∈ σ.toSet) (hq_p1 : q ≠ σ.p1) (hq_p2 : q ≠ σ.p2) :
    ∀ x ∈ (LineSegment.mk p q).toSet, x ∉ Go.toBoundarySet := by
  have h_seg_nondeg : σ.p1 ≠ σ.p2 := (arr Gb Go).segments_nondegenerate σ hσ
  have h_segpq_subset_seg : ∀ x ∈ (LineSegment.mk p q).toSet, x ∈ σ.toSet :=
    EvenGraphIntersectionProofs.segment_pq_subset_refined_seg σ p q hp_σ hq_seg
  intro x hx h_x_Go
  have hx_seg : x ∈ σ.toSet := h_segpq_subset_seg x hx
  have hx_endpts : x ∈ ({σ.p1, σ.p2} : Set Vector2D) :=
    arr_transversal_inter_boundary Gb Go σ hσ hns ⟨hx_seg, h_x_Go⟩
  obtain ⟨u, hu0, hu1, hux, huy⟩ := hx
  obtain ⟨t_p, ht_p0, ht_p1, htpx, htpy⟩ := hp_σ
  obtain ⟨t_q, ht_q0, ht_q1, htqx, htqy⟩ := hq_seg
  have h_t_q_ne : t_q ≠ 0 := by
    intro ht_q_zero
    exact hq_p1 (Vector2D.ext (by rw [htqx, ht_q_zero]; ring) (by rw [htqy, ht_q_zero]; ring))
  have h_t_q_ne_one : t_q ≠ 1 := by
    intro ht_q_one
    exact hq_p2 (Vector2D.ext (by rw [htqx, ht_q_one]; ring) (by rw [htqy, ht_q_one]; ring))
  rcases hx_endpts with hxp1 | hxp2
  · set s := (1 - u) * t_p + u * t_q with hs_def
    have hxx : x.x = (1 - s) * σ.p1.x + s * σ.p2.x := by rw [hux, htpx, htqx, hs_def]; ring
    have hxy : x.y = (1 - s) * σ.p1.y + s * σ.p2.y := by rw [huy, htpy, htqy, hs_def]; ring
    have hxx_eq : σ.p1.x = (1 - s) * σ.p1.x + s * σ.p2.x := by
      rw [← hxx]; exact (congrArg Vector2D.x hxp1).symm
    have hxy_eq : σ.p1.y = (1 - s) * σ.p1.y + s * σ.p2.y := by
      rw [← hxy]; exact (congrArg Vector2D.y hxp1).symm
    have hdx : s * (σ.p2.x - σ.p1.x) = 0 := by linarith
    have hdy : s * (σ.p2.y - σ.p1.y) = 0 := by linarith
    have hs_zero : s = 0 := by
      by_contra h_s_ne
      have hpx_eq : σ.p2.x = σ.p1.x := by
        rcases mul_eq_zero.mp hdx with h | h
        · exact absurd h h_s_ne
        · linarith
      have hpy_eq : σ.p2.y = σ.p1.y := by
        rcases mul_eq_zero.mp hdy with h | h
        · exact absurd h h_s_ne
        · linarith
      exact h_seg_nondeg (Vector2D.ext hpx_eq.symm hpy_eq.symm)
    have h_sum_zero : (1 - u) * t_p + u * t_q = 0 := by rw [← hs_def]; exact hs_zero
    have h_1mu_nn : 0 ≤ 1 - u := by linarith
    have h_lhs_nn : 0 ≤ (1 - u) * t_p := mul_nonneg h_1mu_nn ht_p0
    have h_rhs_nn : 0 ≤ u * t_q := mul_nonneg hu0 ht_q0
    have h_rhs_zero : u * t_q = 0 := by linarith
    have h_u_zero : u = 0 := by
      rcases mul_eq_zero.mp h_rhs_zero with h | h
      · exact h
      · exact absurd h h_t_q_ne
    have h_x_eq_p : x = p :=
      Vector2D.ext (by rw [hux, h_u_zero]; ring) (by rw [huy, h_u_zero]; ring)
    rw [h_x_eq_p] at h_x_Go; exact h_p_not_Go h_x_Go
  · set s := (1 - u) * t_p + u * t_q with hs_def
    have hxx : x.x = (1 - s) * σ.p1.x + s * σ.p2.x := by rw [hux, htpx, htqx, hs_def]; ring
    have hxy : x.y = (1 - s) * σ.p1.y + s * σ.p2.y := by rw [huy, htpy, htqy, hs_def]; ring
    have hxx_eq : σ.p2.x = (1 - s) * σ.p1.x + s * σ.p2.x := by
      rw [← hxx]; exact (congrArg Vector2D.x hxp2).symm
    have hxy_eq : σ.p2.y = (1 - s) * σ.p1.y + s * σ.p2.y := by
      rw [← hxy]; exact (congrArg Vector2D.y hxp2).symm
    have hdx : (1 - s) * (σ.p2.x - σ.p1.x) = 0 := by linarith
    have hdy : (1 - s) * (σ.p2.y - σ.p1.y) = 0 := by linarith
    have hs_one : s = 1 := by
      by_contra h_s_ne
      have h_1ms_ne : 1 - s ≠ 0 := fun h => h_s_ne (by linarith)
      have hpx_eq : σ.p2.x = σ.p1.x := by
        rcases mul_eq_zero.mp hdx with h | h
        · exact absurd h h_1ms_ne
        · linarith
      have hpy_eq : σ.p2.y = σ.p1.y := by
        rcases mul_eq_zero.mp hdy with h | h
        · exact absurd h h_1ms_ne
        · linarith
      exact h_seg_nondeg (Vector2D.ext hpx_eq.symm hpy_eq.symm)
    have h_sum_one : (1 - u) * t_p + u * t_q = 1 := by rw [← hs_def]; exact hs_one
    have h_1mu_nn : 0 ≤ 1 - u := by linarith
    have h_1mtp_nn : 0 ≤ 1 - t_p := by linarith
    have h_1mtq_nn : 0 ≤ 1 - t_q := by linarith
    have h_eq : (1 - u) * (1 - t_p) + u * (1 - t_q) = 0 := by linarith
    have h_lhs_nn : 0 ≤ (1 - u) * (1 - t_p) := mul_nonneg h_1mu_nn h_1mtp_nn
    have h_rhs_nn : 0 ≤ u * (1 - t_q) := mul_nonneg hu0 h_1mtq_nn
    have h_rhs_zero : u * (1 - t_q) = 0 := by linarith
    have h_u_zero : u = 0 := by
      rcases mul_eq_zero.mp h_rhs_zero with h | h
      · exact h
      · exact absurd (by linarith : t_q = 1) h_t_q_ne_one
    have h_x_eq_p : x = p :=
      Vector2D.ext (by rw [hux, h_u_zero]; ring) (by rw [huy, h_u_zero]; ring)
    rw [h_x_eq_p] at h_x_Go; exact h_p_not_Go h_x_Go

/-- Case 1: when `p ∈ ∂Gb ∩ Go.interior` (and `p ∉ ∂Go`), there is a selected `arr Gb Go`
    segment through `p`, i.e. one with open interior inside `Go.interior`. -/
private theorem case1_selected_seg (Gb Go : EvenGraph) (p : Vector2D)
    (h_p_on_Gb : p ∈ Gb.toBoundarySet) (h_p_in_Go_int : p ∈ Go.interior) :
    ∃ σ ∈ _root_.selectSegmentsInside (arr Gb Go).segments Go.interior, p ∈ σ.toSet := by
  have h_p_not_Go : p ∉ Go.toBoundarySet := by
    rintro ⟨seg', hseg', h_in_seg⟩; exact h_p_in_Go_int.1 seg' hseg' h_in_seg
  obtain ⟨σ, hσ, hp_σ, hns⟩ := arr_seg_through_p_not_shared Gb Go p h_p_on_Gb h_p_not_Go
  have h_seg_selected : segmentOpenInteriorSubset σ Go.interior := by
    intro q hq_seg hq_p1 hq_p2
    have h_q_not_Go : q ∉ Go.toBoundarySet := by
      intro h_in
      rcases arr_transversal_inter_boundary Gb Go σ hσ hns ⟨hq_seg, h_in⟩ with h | h
      · exact hq_p1 h
      · exact hq_p2 h
    have h_segpq_avoids_Go : ∀ x ∈ (LineSegment.mk p q).toSet, x ∉ Go.toBoundarySet :=
      case1_segpq_off_Go Gb Go σ hσ hns p q hp_σ h_p_not_Go hq_seg hq_p1 hq_p2
    have h_p_in_arr_int : p ∈ (arr Go Gb).interior := by
      rw [arr_interior_eq Go Gb]; exact h_p_in_Go_int
    have h_q_not_arr : q ∉ (arr Go Gb).toBoundarySet := by
      rw [arr_boundary_eq Go Gb]; exact h_q_not_Go
    have h_segpq_arr : ∀ x ∈ (LineSegment.mk p q).toSet, x ∉ (arr Go Gb).toBoundarySet := by
      intro x hx; rw [arr_boundary_eq Go Gb]; exact h_segpq_avoids_Go x hx
    have := interior_via_segment_gen (arr Go Gb) p q h_p_in_arr_int h_q_not_arr h_segpq_arr
    rwa [arr_interior_eq Go Gb] at this
  refine ⟨σ, ?_, hp_σ⟩
  simp only [_root_.selectSegmentsInside, List.mem_filter, decide_eq_true_eq]
  exact ⟨hσ, h_seg_selected⟩

/-- Every `interGraph G1 G2` segment has the same point set as some `arr G1 G2`/`arr G2 G1`
    segment (the selected blocks are sublists of `arr`; the shared block is a canonicalised
    `arr G1 G2` segment). -/
private theorem interGraph_seg_toSet_eq_arr (G1 G2 : EvenGraph) (seg : LineSegment)
    (hseg : seg ∈ (interGraph G1 G2).segments) :
    ∃ s ∈ (arr G1 G2).segments ++ (arr G2 G1).segments, seg.toSet = s.toSet := by
  rcases interGraph_seg_origin G1 G2 seg hseg with h | h | h
  · exact ⟨seg, List.mem_append.mpr (Or.inl h), rfl⟩
  · exact ⟨seg, List.mem_append.mpr (Or.inr h), rfl⟩
  · obtain ⟨σ0, hσ0, hcanon⟩ := h
    exact ⟨σ0, List.mem_append.mpr (Or.inl hσ0), by rw [hcanon, canonSeg_toSet]⟩

/-- A vertex of an even graph lies in its boundary set. -/
private theorem vert_in_bnd (G : EvenGraph) (v : Vector2D) (hv : v ∈ G.toVertices) :
    v ∈ G.toBoundarySet := by
  rw [EvenGraph.mem_toVertices_iff] at hv
  obtain ⟨seg, hseg, h_or⟩ := hv
  refine ⟨seg, hseg, ?_⟩
  rcases h_or with rfl | rfl
  · exact ⟨0, le_refl 0, zero_le_one, by ring, by ring⟩
  · exact ⟨1, zero_le_one, le_refl 1, by ring, by ring⟩

/-- A vertex of `arr G1 G2`/`arr G2 G1` that lies on an `arr G1 G2`/`arr G2 G1` segment is one of
    that segment's endpoints. (Mirrors the cross-graph reasoning of
    `interGraph_isEven_and_interior_eq`.) -/
private theorem arr_vert_on_arr_seg_endpoint (G1 G2 : EvenGraph) (v : Vector2D)
    (hv : v ∈ (arr G1 G2).toVertices ∨ v ∈ (arr G2 G1).toVertices)
    (seg : LineSegment) (hseg : seg ∈ (arr G1 G2).segments ∨ seg ∈ (arr G2 G1).segments)
    (hon : v ∈ seg.toSet) : v = seg.p1 ∨ v = seg.p2 := by
  have h_arr1_vert_bnd : ∀ w ∈ (arr G1 G2).toVertices, w ∈ G1.toBoundarySet := by
    intro w hw; rw [← arr_boundary_eq G1 G2]; exact vert_in_bnd (arr G1 G2) w hw
  have h_arr2_vert_bnd : ∀ w ∈ (arr G2 G1).toVertices, w ∈ G2.toBoundarySet := by
    intro w hw; rw [← arr_boundary_eq G2 G1]; exact vert_in_bnd (arr G2 G1) w hw
  by_contra hne
  push_neg at hne
  obtain ⟨h1, h2⟩ := hne
  rcases hseg with hsegA | hsegB
  · -- seg ∈ arr G1 G2.
    rcases hv with hv1 | hv2
    · exact arr_no_segment_interior_vertices G1 G2 v hv1 seg hsegA (fun h => h1 h.symm)
        (fun h => h2 h.symm) hon
    · -- cross: v ∈ arr2 verts, seg ∈ arr1. Either transversal (v endpoint) or shared.
      rcases arr_dichotomy G1 G2 seg hsegA with hsubset | hshared
      · rcases hsubset ⟨hon, h_arr2_vert_bnd v hv2⟩ with hp1 | hp2
        · exact h1 hp1
        · exact h2 hp2
      · rcases arr_shared_vertex_endpoint G1 G2 seg hsegA hshared v (h_arr2_vert_bnd v hv2) hv2 hon
          with h | h
        · exact h1 h
        · exact h2 h
  · -- seg ∈ arr G2 G1.
    rcases hv with hv1 | hv2
    · rcases arr_dichotomy G2 G1 seg hsegB with hsubset | hshared
      · rcases hsubset ⟨hon, h_arr1_vert_bnd v hv1⟩ with hp1 | hp2
        · exact h1 hp1
        · exact h2 hp2
      · rcases arr_shared_vertex_endpoint G2 G1 seg hsegB hshared v (h_arr1_vert_bnd v hv1) hv1 hon
          with h | h
        · exact h1 h
        · exact h2 h
    · exact arr_no_segment_interior_vertices G2 G1 v hv2 seg hsegB (fun h => h1 h.symm)
        (fun h => h2 h.symm) hon

/-- Every `arr A B` segment lies in `∂A`. -/
private theorem arr_seg_subset_boundary (A B : EvenGraph) (s : LineSegment)
    (hs : s ∈ (arr A B).segments) : s.toSet ⊆ A.toBoundarySet := by
  rw [← arr_boundary_eq A B]; intro x hx; exact ⟨s, hs, hx⟩

/-- A finer origin classification for `interGraph` segments, recording the *selected* property
    of the two `selectSegmentsInside` blocks. -/
private theorem interGraph_seg_block (G1 G2 : EvenGraph) (seg : LineSegment)
    (hseg : seg ∈ (interGraph G1 G2).segments) :
    (seg ∈ (arr G1 G2).segments ∧ segmentOpenInteriorSubset seg G2.interior) ∨
    (seg ∈ (arr G2 G1).segments ∧ segmentOpenInteriorSubset seg G1.interior) ∨
    seg ∈ sharedSelected G1 G2 ∨ seg ∈ phantomDoubled G1 G2 := by
  rw [interGraph_segments, List.mem_append, List.mem_append, List.mem_append] at hseg
  rcases hseg with ((h | h) | h) | h
  · left
    rw [_root_.selectSegmentsInside, List.mem_filter, decide_eq_true_eq] at h
    exact h
  · right; left
    rw [_root_.selectSegmentsInside, List.mem_filter, decide_eq_true_eq] at h
    exact h
  · right; right; left; exact h
  · right; right; right; exact h

/-- A `sharedSelected G1 G2` segment lies in `∂G1 ∩ ∂G2` (it is shared w.r.t. `G2` and a
    canonicalised `arr G1 G2` segment, hence in `∂G1`). -/
private theorem sharedSelected_subset_both (G1 G2 : EvenGraph) (seg : LineSegment)
    (hseg : seg ∈ sharedSelected G1 G2) :
    seg.toSet ⊆ G1.toBoundarySet ∧ seg.toSet ⊆ G2.toBoundarySet := by
  have h1 : seg.toSet ⊆ G1.toBoundarySet := by
    have := sharedSelected_toSet_subset G1 G2 seg hseg
    rwa [arr_boundary_eq G1 G2] at this
  have h2 : seg.toSet ⊆ G2.toBoundarySet := by
    rw [sharedSelected, List.mem_filter] at hseg
    have := of_decide_eq_true hseg.2
    exact this.1
  exact ⟨h1, h2⟩

/-- A `phantomDoubled G1 G2` segment lies in `∂G1 ∩ ∂G2` (it is shared w.r.t. `G2` and a
    canonicalised `arr G1 G2` segment, hence in `∂G1`). -/
private theorem phantomDoubled_subset_both (G1 G2 : EvenGraph) (seg : LineSegment)
    (hseg : seg ∈ phantomDoubled G1 G2) :
    seg.toSet ⊆ G1.toBoundarySet ∧ seg.toSet ⊆ G2.toBoundarySet := by
  have h1 : seg.toSet ⊆ G1.toBoundarySet := by
    have := phantomDoubled_toSet_subset G1 G2 seg hseg
    rwa [arr_boundary_eq G1 G2] at this
  have h2 : seg.toSet ⊆ G2.toBoundarySet := by
    rw [phantomDoubled, List.mem_flatMap] at hseg
    obtain ⟨τ, hτ, hmem⟩ := hseg
    have hστ : seg = τ := by
      rcases List.mem_cons.mp hmem with h | h
      · exact h
      · rcases List.mem_cons.mp h with h' | h'
        · exact h'
        · exact absurd h' (List.not_mem_nil _)
    rw [hστ]
    rw [List.mem_filter] at hτ
    have := of_decide_eq_true hτ.2
    exact this.1
  exact ⟨h1, h2⟩

/-- Every vertex of `interGraph G1 G2` is a vertex of `arr G1 G2` or `arr G2 G1`.
    (A `sharedSelected` segment is a `canonSeg` of an `arr G1 G2` segment, so its endpoints are
    `arr G1 G2` vertices.) -/
private theorem interGraph_vert_in_arr (G1 G2 : EvenGraph) (v : Vector2D)
    (hv : v ∈ (interGraph G1 G2).toVertices) :
    v ∈ (arr G1 G2).toVertices ∨ v ∈ (arr G2 G1).toVertices := by
  simp only [Graph.toVertices, List.mem_dedup, List.mem_flatMap, List.mem_cons,
             (List.not_mem_nil _), or_false] at hv
  obtain ⟨seg, hseg, h_or⟩ := hv
  have h_or' : seg.p1 = v ∨ seg.p2 = v := by
    rcases h_or with rfl | rfl
    · left; rfl
    · right; rfl
  rcases interGraph_seg_origin G1 G2 seg hseg with h1 | h2 | h3
  · left
    rw [(arr G1 G2).mem_toVertices_iff]; exact ⟨seg, h1, h_or'⟩
  · right
    rw [(arr G2 G1).mem_toVertices_iff]; exact ⟨seg, h2, h_or'⟩
  · -- shared/phantom: seg = canonSeg σ0 for some σ0 ∈ (arr G1 G2).segments, so endpoints are arr1 vertices.
    left
    obtain ⟨σ0, hσ0, hcanon⟩ := h3
    -- canonSeg σ0 endpoints are σ0.p1 or σ0.p2.
    rw [(arr G1 G2).mem_toVertices_iff]
    refine ⟨σ0, hσ0, ?_⟩
    -- v = seg.p1 or seg.p2; seg = canonSeg σ0; canonSeg σ0 endpoints ∈ {σ0.p1, σ0.p2}.
    have hcanon_ep : (canonSeg σ0).p1 = σ0.p1 ∧ (canonSeg σ0).p2 = σ0.p2 ∨
        (canonSeg σ0).p1 = σ0.p2 ∧ (canonSeg σ0).p2 = σ0.p1 := by
      unfold canonSeg; split
      · left; exact ⟨rfl, rfl⟩
      · right; exact ⟨rfl, rfl⟩
    rw [hcanon] at h_or'
    rcases hcanon_ep with ⟨he1, he2⟩ | ⟨he1, he2⟩
    · rcases h_or' with h | h
      · rw [← he1]; left; exact h
      · rw [← he2]; right; exact h
    · rcases h_or' with h | h
      · rw [← he1]; right; exact h
      · rw [← he2]; left; exact h

set_option maxHeartbeats 1000000 in
/-- **Case 2 (parameterised).** With the *boundary* graph `Gb` and the *other* graph `Go`
    (where `{Gb, Go} = {G1, G2}`), if `p ∈ ∂Gb`, `p ∉ ∂Go`, `p ∉ Go.interior`, while `p` avoids
    `interGraph G1 G2`'s segments and every ray from `p` avoiding its vertices has odd parity,
    we derive a contradiction. -/
private theorem case2_gen (G1 G2 : EvenGraph) (Gb Go : EvenGraph)
    (h_swap : (Gb = G1 ∧ Go = G2) ∨ (Gb = G2 ∧ Go = G1))
    (h_even : (interGraph G1 G2).IsEven)
    (p : Vector2D)
    (_h_p_on_Gb : p ∈ Gb.toBoundarySet)
    (h_p_not_Go : p ∉ Go.toBoundarySet)
    (h_p_not_Go_int : p ∉ Go.interior)
    (h_p_avoids_inter : ∀ seg ∈ (interGraph G1 G2).segments, pointAvoidsSegment p seg)
    (h_parity : ∀ r : Ray, r.origin = p → rayAvoidsGraphVertices r (interGraph G1 G2) →
      intersectionRayGraphSegmentsNumber r (interGraph G1 G2) % 2 = 1) :
    False := by
  set G_inter : Graph := interGraph G1 G2 with hG_inter_def
  set arr1 := arr G1 G2 with harr1_def
  set arr2 := arr G2 G1 with harr2_def
  set arrO := arr Go Gb with harrO_def
  -- ∂(arr X Y) = ∂X.
  have harr1_bnd : arr1.toBoundarySet = G1.toBoundarySet := arr_boundary_eq G1 G2
  have harr2_bnd : arr2.toBoundarySet = G2.toBoundarySet := arr_boundary_eq G2 G1
  have harrO_bnd : arrO.toBoundarySet = Go.toBoundarySet := arr_boundary_eq Go Gb
  have harrO_int : arrO.interior = Go.interior := arr_interior_eq Go Gb
  -- arrO is one of arr1, arr2.
  have harrO_mem : arrO = arr1 ∨ arrO = arr2 := by
    rcases h_swap with ⟨hb, ho⟩ | ⟨hb, ho⟩
    · right; rw [harrO_def, hb, ho]
    · left; rw [harrO_def, hb, ho]
  have h_pos_O := arrO.incident_count_pos
  -- L = arr1.segments ++ arr2.segments.
  let L : List LineSegment := arr1.segments ++ arr2.segments
  have hL_nondeg : ∀ seg ∈ L, seg.p1 ≠ seg.p2 := by
    intro seg hseg
    rcases List.mem_append.mp hseg with h | h
    · exact arr1.segments_nondegenerate seg h
    · exact arr2.segments_nondegenerate seg h
  have harrO_in_L : ∀ seg ∈ arrO.segments, seg ∈ L := by
    intro seg hseg
    rcases harrO_mem with h | h
    · exact List.mem_append.mpr (Or.inl (h ▸ hseg))
    · exact List.mem_append.mpr (Or.inr (h ▸ hseg))
  -- p avoids arrO segments (p ∉ ∂Go = ∂arrO).
  have h_p_avoids_arrO : ∀ seg ∈ arrO.segments, pointAvoidsSegment p seg := by
    intro seg hseg h_on
    exact h_p_not_Go (harrO_bnd ▸ ⟨seg, hseg, h_on⟩)
  -- Perturb.
  obtain ⟨p', h_p'_ne, h_p'_off_L, h_seg_disjoint⟩ :=
    exists_perturbation_off_segs p L hL_nondeg
  have h_p'_off_arr1 : ∀ seg ∈ arr1.segments, p' ∉ seg.toSet := fun seg hseg =>
    h_p'_off_L seg (List.mem_append.mpr (Or.inl hseg))
  have h_p'_off_arr2 : ∀ seg ∈ arr2.segments, p' ∉ seg.toSet := fun seg hseg =>
    h_p'_off_L seg (List.mem_append.mpr (Or.inr hseg))
  have h_p'_off_arrO : ∀ seg ∈ arrO.segments, p' ∉ seg.toSet := fun seg hseg =>
    h_p'_off_L seg (harrO_in_L seg hseg)
  -- p' off ∂G1, ∂G2, ∂Go.
  have h_p'_not_G1 : p' ∉ G1.toBoundarySet := by
    rw [← harr1_bnd]; rintro ⟨seg, hseg, hon⟩; exact h_p'_off_arr1 seg hseg hon
  have h_p'_not_G2 : p' ∉ G2.toBoundarySet := by
    rw [← harr2_bnd]; rintro ⟨seg, hseg, hon⟩; exact h_p'_off_arr2 seg hseg hon
  have h_p'_not_arrO_bnd : p' ∉ arrO.toBoundarySet := by
    rintro ⟨seg, hseg, hon⟩; exact h_p'_off_arrO seg hseg hon
  have h_p'_avoids_arrO : ∀ seg ∈ arrO.segments, pointAvoidsSegment p' seg := h_p'_off_arrO
  -- p' not a vertex of arr1, arr2.
  have h_p'_not_arr1_vert : ∀ v ∈ arr1.toVertices, v ≠ p' := by
    intro v hv heq
    obtain ⟨s, hs, hsv⟩ := vertex_on_some_segment arr1 v (arr1.incident_count_pos v hv)
    exact h_p'_off_arr1 s hs (heq ▸ hsv)
  have h_p'_not_arr2_vert : ∀ v ∈ arr2.toVertices, v ≠ p' := by
    intro v hv heq
    obtain ⟨s, hs, hsv⟩ := vertex_on_some_segment arr2 v (arr2.incident_count_pos v hv)
    exact h_p'_off_arr2 s hs (heq ▸ hsv)
  have h_p'_not_both : ∀ v ∈ arr1.toVertices ++ arr2.toVertices, v ≠ p' := by
    intro v hv
    rcases List.mem_append.mp hv with h | h
    · exact h_p'_not_arr1_vert v h
    · exact h_p'_not_arr2_vert v h
  -- Segment p-p' avoids arrO segments.
  have h_segpp'_avoids_arrO : ∀ seg ∈ arrO.segments,
      segmentDoesNotIntersectSegment ⟨p, p'⟩ seg :=
    fun seg hseg => h_seg_disjoint seg (harrO_in_L seg hseg) (h_p_avoids_arrO seg hseg)
  -- Segment p-p' avoids G_inter segments (each has the same toSet as an L-segment p avoids).
  have h_segpp'_avoids_inter : ∀ seg ∈ G_inter.segments,
      segmentDoesNotIntersectSegment ⟨p, p'⟩ seg := by
    intro seg hseg
    obtain ⟨s, hs, hseteq⟩ := interGraph_seg_toSet_eq_arr G1 G2 seg hseg
    have h_p_off_s : p ∉ s.toSet := by rw [← hseteq]; exact h_p_avoids_inter seg hseg
    have h_disj := h_seg_disjoint s hs h_p_off_s
    show (LineSegment.mk p p').toSet ∩ seg.toSet = ∅
    rw [hseteq]; exact h_disj
  -- arrO vertices off segment p-p'.
  have h_arrO_verts_off_segpp' : ∀ v ∈ arrO.toVertices, v ∉ (LineSegment.mk p p').toSet := by
    intro v hv hv_mem
    obtain ⟨s, hs, hsv⟩ := vertex_on_some_segment arrO v (h_pos_O v hv)
    have h_disj := h_segpp'_avoids_arrO s hs
    have : v ∈ (LineSegment.mk p p').toSet ∩ s.toSet := ⟨hv_mem, hsv⟩
    rw [h_disj] at this; exact this
  -- p ∉ arrO.interior (since p ∉ Go.interior).
  have h_p_not_arrO_int : p ∉ arrO.interior := by rw [harrO_int]; exact h_p_not_Go_int
  -- p not an arrO vertex.
  have h_p_not_arrO_vert : ∀ v ∈ arrO.toVertices, v ≠ p := by
    intro v hv heq
    obtain ⟨s, hs, hsv⟩ := vertex_on_some_segment arrO v (h_pos_O v hv)
    exact h_p_not_Go (harrO_bnd ▸ ⟨s, hs, heq ▸ hsv⟩)
  -- Step: #arrO(r₁) even, where r₁ is from p avoiding arrO verts.
  obtain ⟨r₁, h_r₁_orig, h_r₁_avoids_arrO⟩ :=
    exists_ray_avoiding_graph_verts p arrO h_p_not_arrO_vert
  have h_parity_arrO_r₁_zero : intersectionRayGraphSegmentsNumber r₁ arrO % 2 = 0 := by
    by_contra h_ne
    have h_one : intersectionRayGraphSegmentsNumber r₁ arrO % 2 = 1 := by
      have := Nat.mod_lt (intersectionRayGraphSegmentsNumber r₁ arrO) (show 0 < 2 by norm_num)
      omega
    apply h_p_not_arrO_int
    refine ⟨h_p_avoids_arrO, ?_⟩
    intro r' h_r'_orig h_r'_avoids
    have h_origin_avoids' : ∀ seg ∈ arrO.segments, pointAvoidsSegment r₁.origin seg := by
      rw [h_r₁_orig]; exact h_p_avoids_arrO
    have h_eq := intersectionParity_eq_of_sameOrigin_avoidsGraphVertices r₁ r' arrO
      (by simp [sameOrigin, h_r₁_orig, h_r'_orig]) h_r₁_avoids_arrO h_r'_avoids h_origin_avoids'
    rw [← h_eq]; exact h_one
  -- r₂ from p' avoiding arrO verts; #arrO(r₂) = #arrO(r₁) = 0.
  have h_p'_not_arrO_vert : ∀ v ∈ arrO.toVertices, v ≠ p' := by
    intro v hv heq
    obtain ⟨s, hs, hsv⟩ := vertex_on_some_segment arrO v (h_pos_O v hv)
    exact h_p'_not_arrO_bnd ⟨s, hs, heq ▸ hsv⟩
  obtain ⟨r₂, h_r₂_orig, h_r₂_avoids_arrO⟩ :=
    exists_ray_avoiding_graph_verts p' arrO h_p'_not_arrO_vert
  have h_sego_avoids_arrO : ∀ seg ∈ arrO.segments,
      segmentDoesNotIntersectSegment ⟨r₁.origin, r₂.origin⟩ seg := by
    intro seg hseg; rw [h_r₁_orig, h_r₂_orig]; exact h_segpp'_avoids_arrO seg hseg
  have h_verts_avoid_sego_arrO : ∀ v ∈ arrO.toVertices,
      v ∉ (LineSegment.mk r₁.origin r₂.origin).toSet := by
    intro v hv; rw [h_r₁_orig, h_r₂_orig]; exact h_arrO_verts_off_segpp' v hv
  have h_parity_arrO_r₂_zero : intersectionRayGraphSegmentsNumber r₂ arrO % 2 = 0 := by
    rw [← intersectionParity_eq_of_originSegmentAvoidsGraphSegments r₁ r₂ arrO
      h_r₁_avoids_arrO h_r₂_avoids_arrO h_sego_avoids_arrO h_verts_avoid_sego_arrO]
    exact h_parity_arrO_r₁_zero
  -- Build qualifying ray r₃ from p' (avoids arr1, arr2 verts AND Xlist).
  obtain ⟨r₃, h_r₃_orig, h_r₃_avoids_arr1, h_r₃_avoids_arr2, h_r₃_avoids_X⟩ :=
    exists_qualifying_ray G1 G2 p' h_p'_not_both h_p'_not_G1 h_p'_not_G2
  -- r₃ avoids arrO verts (arrO ∈ {arr1, arr2}).
  have h_r₃_avoids_arrO : rayAvoidsGraphVertices r₃ arrO := by
    rcases harrO_mem with h | h
    · rw [h]; exact h_r₃_avoids_arr1
    · rw [h]; exact h_r₃_avoids_arr2
  -- r₃ avoids G_inter verts.
  have h_r₃_avoids_inter : rayAvoidsGraphVertices r₃ G_inter := by
    rw [rayAvoidsGraphVertices, Set.eq_empty_iff_forall_not_mem]
    intro v ⟨hv_ray, hv_vert⟩
    rcases interGraph_vert_in_arr G1 G2 v hv_vert with h1 | h2
    · have : v ∈ r₃.toSet ∩ arr1.toVertexSet := ⟨hv_ray, h1⟩
      rw [h_r₃_avoids_arr1] at this; exact this
    · have : v ∈ r₃.toSet ∩ arr2.toVertexSet := ⟨hv_ray, h2⟩
      rw [h_r₃_avoids_arr2] at this; exact this
  -- Transfer #G_inter parity from p (via r_p) to r₃.
  have h_p_not_inter_vert : ∀ v ∈ G_inter.toVertices, v ≠ p := by
    intro v hv heq
    simp only [Graph.toVertices, List.mem_dedup, List.mem_flatMap, List.mem_cons,
               (List.not_mem_nil _), or_false] at hv
    obtain ⟨seg, hseg, h_or⟩ := hv
    have hv_on : v ∈ seg.toSet := by
      rcases h_or with rfl | rfl
      · exact ⟨0, le_refl 0, zero_le_one, by ring, by ring⟩
      · exact ⟨1, zero_le_one, le_refl 1, by ring, by ring⟩
    exact h_p_avoids_inter seg hseg (heq ▸ hv_on)
  obtain ⟨r_p, h_r_p_orig, h_r_p_avoids_inter⟩ :=
    exists_ray_avoiding_graph_verts p ⟨G_inter, h_even⟩ h_p_not_inter_vert
  have h_parity_inter_r_p : intersectionRayGraphSegmentsNumber r_p G_inter % 2 = 1 :=
    h_parity r_p h_r_p_orig h_r_p_avoids_inter
  have h_sego_avoids_inter : ∀ seg ∈ (⟨G_inter, h_even⟩ : EvenGraph).segments,
      segmentDoesNotIntersectSegment ⟨r_p.origin, r₃.origin⟩ seg := by
    intro seg hseg; rw [h_r_p_orig, h_r₃_orig]; exact h_segpp'_avoids_inter seg hseg
  have h_verts_avoid_sego_inter : ∀ v ∈ (⟨G_inter, h_even⟩ : EvenGraph).toVertices,
      v ∉ (LineSegment.mk r_p.origin r₃.origin).toSet := by
    intro v hv hv_mem
    simp only [Graph.toVertices, List.mem_dedup, List.mem_flatMap, List.mem_cons,
               (List.not_mem_nil _), or_false] at hv
    obtain ⟨s, hs, h_or⟩ := hv
    have hv_on_s : v ∈ s.toSet := by
      rcases h_or with rfl | rfl
      · exact ⟨0, le_refl 0, zero_le_one, by ring, by ring⟩
      · exact ⟨1, zero_le_one, le_refl 1, by ring, by ring⟩
    have h_disj := h_segpp'_avoids_inter s hs
    rw [h_r_p_orig, h_r₃_orig] at hv_mem
    have : v ∈ (LineSegment.mk p p').toSet ∩ s.toSet := ⟨hv_mem, hv_on_s⟩
    rw [h_disj] at this; exact this
  have h_parity_inter_eq := intersectionParity_eq_of_originSegmentAvoidsGraphSegments
    r_p r₃ ⟨G_inter, h_even⟩ h_r_p_avoids_inter h_r₃_avoids_inter
    h_sego_avoids_inter h_verts_avoid_sego_inter
  have h_parity_inter_r₃ : intersectionRayGraphSegmentsNumber r₃ G_inter % 2 = 1 := by
    have h_eq' : intersectionRayGraphSegmentsNumber r_p G_inter % 2 =
        intersectionRayGraphSegmentsNumber r₃ G_inter % 2 := h_parity_inter_eq
    rw [← h_eq']; exact h_parity_inter_r_p
  -- Both arr counts at r₃ odd ⟹ #arrO(r₃) odd.
  have h_off_G1₃ : r₃.origin ∉ G1.toBoundarySet := by rw [h_r₃_orig]; exact h_p'_not_G1
  have h_off_G2₃ : r₃.origin ∉ G2.toBoundarySet := by rw [h_r₃_orig]; exact h_p'_not_G2
  obtain ⟨h_arr1_odd, h_arr2_odd⟩ := both_arr_odd_of_interGraph_odd G1 G2 r₃
    h_r₃_avoids_arr1 h_r₃_avoids_arr2 h_r₃_avoids_X h_off_G1₃ h_off_G2₃ h_parity_inter_r₃
  have h_arrO_odd_r₃ : intersectionRayGraphSegmentsNumber r₃ arrO % 2 = 1 := by
    rcases harrO_mem with h | h
    · rw [h]; exact h_arr1_odd
    · rw [h]; exact h_arr2_odd
  -- But #arrO(r₃) = #arrO(r₂) = 0. Contradiction.
  have h_origin_avoids_arrO_r₂ : ∀ seg ∈ arrO.segments, pointAvoidsSegment r₂.origin seg := by
    rw [h_r₂_orig]; exact h_p'_avoids_arrO
  have h_parity_arrO_r₂_eq_r₃ := intersectionParity_eq_of_sameOrigin_avoidsGraphVertices
    r₂ r₃ arrO (by simp [sameOrigin, h_r₂_orig, h_r₃_orig]) h_r₂_avoids_arrO h_r₃_avoids_arrO
    h_origin_avoids_arrO_r₂
  rw [← h_parity_arrO_r₂_eq_r₃, h_parity_arrO_r₂_zero] at h_arrO_odd_r₃
  exact absurd h_arrO_odd_r₃ (by norm_num)

set_option maxHeartbeats 1000000 in
/-- **Case 3 via a transversal segment.** If `p ∈ ∂X ∩ ∂Y` and lies on a *transversal*
    `arr X Y` segment `seg` (where `{X, Y} = {G1, G2}`), then the midpoint `m` of `seg` lies in
    `∂X`, off `∂Y`, and off `Y.interior` (since `seg` is unselected because `p` avoids
    `interGraph`). We transfer `p`'s parity/avoidance properties to `m` along `seg` and apply
    `case2_gen` with boundary graph `X`. -/
private theorem case3_via_transversal_seg (G1 G2 : EvenGraph) (X Y : EvenGraph)
    (h_swap : (X = G1 ∧ Y = G2) ∨ (X = G2 ∧ Y = G1))
    (h_even : (interGraph G1 G2).IsEven)
    (p : Vector2D)
    (seg : LineSegment) (hseg : seg ∈ (arr X Y).segments) (hp_seg : p ∈ seg.toSet)
    (hns : ¬ IsShared Y seg)
    (h_p_avoids_inter : ∀ seg ∈ (interGraph G1 G2).segments, pointAvoidsSegment p seg)
    (h_parity : ∀ r : Ray, r.origin = p → rayAvoidsGraphVertices r (interGraph G1 G2) →
      intersectionRayGraphSegmentsNumber r (interGraph G1 G2) % 2 = 1) :
    False := by
  set G_inter : Graph := interGraph G1 G2 with hG_inter_def
  let G_inter_E : EvenGraph := ⟨G_inter, h_even⟩
  have h_seg_nondeg : seg.p1 ≠ seg.p2 := (arr X Y).segments_nondegenerate seg hseg
  -- seg is unselected (else p ∈ interGraph via the selected segment seg, contradicting avoids).
  have h_seg_unselected : ¬ segmentOpenInteriorSubset seg Y.interior := by
    intro h_sel
    have hseg_sel : seg ∈ _root_.selectSegmentsInside (arr X Y).segments Y.interior := by
      simp only [_root_.selectSegmentsInside, List.mem_filter, decide_eq_true_eq]
      exact ⟨hseg, h_sel⟩
    -- seg is in the appropriate block of interGraph.
    have hseg_in_inter : seg ∈ (interGraph G1 G2).segments := by
      rw [interGraph_segments]
      rcases h_swap with ⟨hX, hY⟩ | ⟨hX, hY⟩
      · exact List.mem_append.mpr (Or.inl (List.mem_append.mpr (Or.inl (List.mem_append.mpr (Or.inl (by rw [← hX, ← hY]; exact hseg_sel))))))
      · exact List.mem_append.mpr (Or.inl (List.mem_append.mpr (Or.inl (List.mem_append.mpr (Or.inr (by rw [← hX, ← hY]; exact hseg_sel))))))
    exact h_p_avoids_inter seg hseg_in_inter hp_seg
  -- midpoint m of seg.
  set m : Vector2D := ⟨(seg.p1.x + seg.p2.x) / 2, (seg.p1.y + seg.p2.y) / 2⟩ with hm_def
  have hm_seg : m ∈ seg.toSet :=
    ⟨1/2, by norm_num, by norm_num, by show (seg.p1.x + seg.p2.x)/2 = _; ring,
      by show (seg.p1.y + seg.p2.y)/2 = _; ring⟩
  have hm_ne_p1 : m ≠ seg.p1 := by
    intro h; apply h_seg_nondeg; ext
    · have : (seg.p1.x + seg.p2.x)/2 = seg.p1.x := congrArg Vector2D.x h; linarith
    · have : (seg.p1.y + seg.p2.y)/2 = seg.p1.y := congrArg Vector2D.y h; linarith
  have hm_ne_p2 : m ≠ seg.p2 := by
    intro h; apply h_seg_nondeg; ext
    · have : (seg.p1.x + seg.p2.x)/2 = seg.p2.x := congrArg Vector2D.x h; linarith
    · have : (seg.p1.y + seg.p2.y)/2 = seg.p2.y := congrArg Vector2D.y h; linarith
  -- m ∈ ∂X.
  have hm_X : m ∈ X.toBoundarySet := by rw [← arr_boundary_eq X Y]; exact ⟨seg, hseg, hm_seg⟩
  -- m ∉ ∂Y (transversal: open interior off ∂Y).
  have hm_not_Y : m ∉ Y.toBoundarySet := by
    intro h_in
    rcases arr_transversal_inter_boundary X Y seg hseg hns ⟨hm_seg, h_in⟩ with h | h
    · exact hm_ne_p1 h
    · exact hm_ne_p2 h
  -- m ∉ Y.interior (else B-status constant ⟹ selected, contra).
  have hm_not_Y_int : m ∉ Y.interior := by
    intro hm_int
    apply h_seg_unselected
    intro q hq hq1 hq2
    exact arr_same_B_status X Y seg hseg hns m q hm_seg hm_ne_p1 hm_ne_p2 hq hq1 hq2 hm_int
  -- Every interGraph segment's point set lies in Y.interior on its open interior OR in ∂Y.
  -- We need: segment p-m avoids interGraph segments.
  have h_segpm_sub_seg : ∀ x ∈ (LineSegment.mk p m).toSet, x ∈ seg.toSet :=
    EvenGraphIntersectionProofs.segment_pq_subset_refined_seg seg p m hp_seg hm_seg
  -- Open-interior points of seg are off ∂Y and off Y.interior (transversal + unselected).
  have h_seg_open_off_Y_bnd : ∀ x ∈ seg.toSet, x ≠ seg.p1 → x ≠ seg.p2 → x ∉ Y.toBoundarySet := by
    intro x hx hx1 hx2 h_in
    rcases arr_transversal_inter_boundary X Y seg hseg hns ⟨hx, h_in⟩ with h | h
    · exact hx1 h
    · exact hx2 h
  have h_seg_open_off_Y_int : ∀ x ∈ seg.toSet, x ≠ seg.p1 → x ≠ seg.p2 → x ∉ Y.interior := by
    intro x hx hx1 hx2 h_in
    apply h_seg_unselected
    intro q hq hq1 hq2
    exact arr_same_B_status X Y seg hseg hns x q hx hx1 hx2 hq hq1 hq2 h_in
  -- Segment p-m avoids interGraph segments.
  have h_segpm_avoids_inter : ∀ s ∈ G_inter.segments,
      segmentDoesNotIntersectSegment ⟨p, m⟩ s := by
    intro s hs
    ext x
    simp only [Set.mem_inter_iff, Set.mem_empty_iff_false, iff_false, not_and]
    intro hx_pm hx_s
    have hx_seg : x ∈ seg.toSet := h_segpm_sub_seg x hx_pm
    by_cases hx_p1 : x = seg.p1
    · -- x = seg.p1: then x ∈ s and (p-m) at endpoint side; show x = p, contra avoids.
      rcases (interGraph_seg_toSet_eq_arr G1 G2 s hs) with ⟨s', hs', hseteq⟩
      -- x ∈ s.toSet and x on seg endpoint; but p, m both on seg. The point x on segment p-m
      -- that is a seg-endpoint must be p (since m is in seg's open interior).
      have hx_eq_p : x = p := by
        obtain ⟨u, hu0, hu1, hux, huy⟩ := hx_pm
        -- x = seg.p1 = (1-u)p + u m, with m the midpoint; solve u.
        -- Use: x ∈ seg.toSet at parameter 0 (endpoint), p at t_p, m at 1/2.
        obtain ⟨t_p, ht_p0, ht_p1, htpx, htpy⟩ := hp_seg
        set s0 := (1 - u) * t_p + u * (1/2) with hs0_def
        have hxx : x.x = (1 - s0) * seg.p1.x + s0 * seg.p2.x := by
          rw [hux, htpx, hm_def, hs0_def]; ring
        have hxy : x.y = (1 - s0) * seg.p1.y + s0 * seg.p2.y := by
          rw [huy, htpy, hm_def, hs0_def]; ring
        have hxx_eq : seg.p1.x = (1 - s0) * seg.p1.x + s0 * seg.p2.x := by
          rw [← hxx]; exact (congrArg Vector2D.x hx_p1).symm
        have hxy_eq : seg.p1.y = (1 - s0) * seg.p1.y + s0 * seg.p2.y := by
          rw [← hxy]; exact (congrArg Vector2D.y hx_p1).symm
        have hdx : s0 * (seg.p2.x - seg.p1.x) = 0 := by linarith
        have hdy : s0 * (seg.p2.y - seg.p1.y) = 0 := by linarith
        have hs0_zero : s0 = 0 := by
          by_contra h_ne
          have hx2 : seg.p2.x = seg.p1.x := by
            rcases mul_eq_zero.mp hdx with h | h
            · exact absurd h h_ne
            · linarith
          have hy2 : seg.p2.y = seg.p1.y := by
            rcases mul_eq_zero.mp hdy with h | h
            · exact absurd h h_ne
            · linarith
          exact h_seg_nondeg (Vector2D.ext hx2.symm hy2.symm)
        -- s0 = (1-u)t_p + u/2 = 0 with all ≥ 0 ⟹ u = 0 (since 1/2 > 0).
        have h_1mu : 0 ≤ 1 - u := by linarith
        have ht1 : 0 ≤ (1 - u) * t_p := mul_nonneg h_1mu ht_p0
        have ht2 : 0 ≤ u * (1/2) := by nlinarith
        have hu_half : u * (1/2) = 0 := by rw [hs0_def] at hs0_zero; linarith
        have h_u_zero : u = 0 := by nlinarith [hu_half]
        exact Vector2D.ext (by rw [hux, h_u_zero]; ring) (by rw [huy, h_u_zero]; ring)
      rw [hx_eq_p] at hx_s; exact h_p_avoids_inter s hs hx_s
    · by_cases hx_p2 : x = seg.p2
      · -- symmetric: x = seg.p2 must be p.
        have hx_eq_p : x = p := by
          obtain ⟨u, hu0, hu1, hux, huy⟩ := hx_pm
          obtain ⟨t_p, ht_p0, ht_p1, htpx, htpy⟩ := hp_seg
          set s0 := (1 - u) * t_p + u * (1/2) with hs0_def
          have hxx : x.x = (1 - s0) * seg.p1.x + s0 * seg.p2.x := by
            rw [hux, htpx, hm_def, hs0_def]; ring
          have hxy : x.y = (1 - s0) * seg.p1.y + s0 * seg.p2.y := by
            rw [huy, htpy, hm_def, hs0_def]; ring
          have hxx_eq : seg.p2.x = (1 - s0) * seg.p1.x + s0 * seg.p2.x := by
            rw [← hxx]; exact (congrArg Vector2D.x hx_p2).symm
          have hxy_eq : seg.p2.y = (1 - s0) * seg.p1.y + s0 * seg.p2.y := by
            rw [← hxy]; exact (congrArg Vector2D.y hx_p2).symm
          have hdx : (1 - s0) * (seg.p2.x - seg.p1.x) = 0 := by linarith
          have hdy : (1 - s0) * (seg.p2.y - seg.p1.y) = 0 := by linarith
          have hs0_one : s0 = 1 := by
            by_contra h_ne
            have h1ms : 1 - s0 ≠ 0 := fun h => h_ne (by linarith)
            have hx2 : seg.p2.x = seg.p1.x := by
              rcases mul_eq_zero.mp hdx with h | h
              · exact absurd h h1ms
              · linarith
            have hy2 : seg.p2.y = seg.p1.y := by
              rcases mul_eq_zero.mp hdy with h | h
              · exact absurd h h1ms
              · linarith
            exact h_seg_nondeg (Vector2D.ext hx2.symm hy2.symm)
          -- s0 = (1-u)t_p + u/2 = 1, t_p ≤ 1, so (1-u)(1-t_p) + u/2 = ... ⟹ u = 0.
          have h_1mu : 0 ≤ 1 - u := by linarith
          have h_eq : (1 - u) * (1 - t_p) + u * (1/2) = 0 := by rw [hs0_def] at hs0_one; linarith
          have ht1 : 0 ≤ (1 - u) * (1 - t_p) := mul_nonneg h_1mu (by linarith)
          have ht2 : 0 ≤ u * (1/2) := by nlinarith
          have hu_half : u * (1/2) = 0 := by linarith
          have h_u_zero : u = 0 := by nlinarith [hu_half]
          exact Vector2D.ext (by rw [hux, h_u_zero]; ring) (by rw [huy, h_u_zero]; ring)
        rw [hx_eq_p] at hx_s; exact h_p_avoids_inter s hs hx_s
      · -- x ∈ seg open interior: off ∂Y and off Y.interior.
        -- First, if x is an endpoint of the interGraph seg s, then x is an arr vertex, so by the
        -- cross-vertex lemma x is an endpoint of seg, contradicting hx_p1/hx_p2.
        by_cases hxs1 : x = s.p1
        · obtain ⟨hd1, _⟩ := interGraph_seg_data G1 G2 s hs
          rcases arr_vert_on_arr_seg_endpoint G1 G2 x (hxs1 ▸ hd1) seg
            (by rcases h_swap with ⟨hX, hY⟩ | ⟨hX, hY⟩
                · left; rw [← hX, ← hY]; exact hseg
                · right; rw [← hX, ← hY]; exact hseg) hx_seg with h | h
          · exact hx_p1 h
          · exact hx_p2 h
        · by_cases hxs2 : x = s.p2
          · obtain ⟨_, hd2⟩ := interGraph_seg_data G1 G2 s hs
            rcases arr_vert_on_arr_seg_endpoint G1 G2 x (hxs2 ▸ hd2) seg
              (by rcases h_swap with ⟨hX, hY⟩ | ⟨hX, hY⟩
                  · left; rw [← hX, ← hY]; exact hseg
                  · right; rw [← hX, ← hY]; exact hseg) hx_seg with h | h
            · exact hx_p1 h
            · exact hx_p2 h
          · -- x in s's OPEN interior: dispatch on the block of s.
            rcases interGraph_seg_block G1 G2 s hs with ⟨hsmem, hsel⟩ | ⟨hsmem, hsel⟩ | hsh | hph
            · -- block1: s ∈ arr G1 G2, open interior ⊆ G2.interior.
              have hxG2 : x ∈ G2.interior := hsel x hx_s hxs1 hxs2
              have hxG1 : x ∈ G1.toBoundarySet := arr_seg_subset_boundary G1 G2 s hsmem hx_s
              rcases h_swap with ⟨_, hY⟩ | ⟨_, hY⟩
              · exact h_seg_open_off_Y_int x hx_seg hx_p1 hx_p2 (by rw [hY]; exact hxG2)
              · exact h_seg_open_off_Y_bnd x hx_seg hx_p1 hx_p2 (by rw [hY]; exact hxG1)
            · -- block2: s ∈ arr G2 G1, open interior ⊆ G1.interior.
              have hxG1 : x ∈ G1.interior := hsel x hx_s hxs1 hxs2
              have hxG2 : x ∈ G2.toBoundarySet := arr_seg_subset_boundary G2 G1 s hsmem hx_s
              rcases h_swap with ⟨_, hY⟩ | ⟨_, hY⟩
              · exact h_seg_open_off_Y_bnd x hx_seg hx_p1 hx_p2 (by rw [hY]; exact hxG2)
              · exact h_seg_open_off_Y_int x hx_seg hx_p1 hx_p2 (by rw [hY]; exact hxG1)
            · -- shared: s ⊆ ∂G1 ∩ ∂G2 ⊆ ∂Y.
              obtain ⟨hb1, hb2⟩ := sharedSelected_subset_both G1 G2 s hsh
              rcases h_swap with ⟨_, hY⟩ | ⟨_, hY⟩
              · exact h_seg_open_off_Y_bnd x hx_seg hx_p1 hx_p2 (by rw [hY]; exact hb2 hx_s)
              · exact h_seg_open_off_Y_bnd x hx_seg hx_p1 hx_p2 (by rw [hY]; exact hb1 hx_s)
            · -- phantom: s ⊆ ∂G1 ∩ ∂G2 ⊆ ∂Y.
              obtain ⟨hb1, hb2⟩ := phantomDoubled_subset_both G1 G2 s hph
              rcases h_swap with ⟨_, hY⟩ | ⟨_, hY⟩
              · exact h_seg_open_off_Y_bnd x hx_seg hx_p1 hx_p2 (by rw [hY]; exact hb2 hx_s)
              · exact h_seg_open_off_Y_bnd x hx_seg hx_p1 hx_p2 (by rw [hY]; exact hb1 hx_s)
  -- Transfer parity/avoidance to m and apply case2_gen.
  -- m avoids interGraph segments.
  have hm_avoids_inter : ∀ s ∈ G_inter.segments, pointAvoidsSegment m s := by
    intro s hs h_on
    have h_disj := h_segpm_avoids_inter s hs
    have : m ∈ (LineSegment.mk p m).toSet ∩ s.toSet :=
      ⟨⟨1, zero_le_one, le_refl 1, by ring, by ring⟩, h_on⟩
    rw [h_disj] at this; exact this
  -- vertices of interGraph off segment p-m.
  have h_inter_verts_off_pm : ∀ v ∈ G_inter.toVertices, v ∉ (LineSegment.mk p m).toSet := by
    intro v hv hv_mem
    simp only [Graph.toVertices, List.mem_dedup, List.mem_flatMap, List.mem_cons,
               (List.not_mem_nil _), or_false] at hv
    obtain ⟨s, hs, h_or⟩ := hv
    have hv_on : v ∈ s.toSet := by
      rcases h_or with rfl | rfl
      · exact ⟨0, le_refl 0, zero_le_one, by ring, by ring⟩
      · exact ⟨1, zero_le_one, le_refl 1, by ring, by ring⟩
    have h_disj := h_segpm_avoids_inter s hs
    have : v ∈ (LineSegment.mk p m).toSet ∩ s.toSet := ⟨hv_mem, hv_on⟩
    rw [h_disj] at this; exact this
  -- p not an interGraph vertex.
  have h_p_not_inter_vert : ∀ v ∈ G_inter.toVertices, v ≠ p := by
    intro v hv heq
    simp only [Graph.toVertices, List.mem_dedup, List.mem_flatMap, List.mem_cons,
               (List.not_mem_nil _), or_false] at hv
    obtain ⟨s, hs, h_or⟩ := hv
    have hv_on : v ∈ s.toSet := by
      rcases h_or with rfl | rfl
      · exact ⟨0, le_refl 0, zero_le_one, by ring, by ring⟩
      · exact ⟨1, zero_le_one, le_refl 1, by ring, by ring⟩
    exact h_p_avoids_inter s hs (heq ▸ hv_on)
  -- m not an interGraph vertex.
  have hm_not_inter_vert : ∀ v ∈ G_inter.toVertices, v ≠ m := by
    intro v hv heq
    simp only [Graph.toVertices, List.mem_dedup, List.mem_flatMap, List.mem_cons,
               (List.not_mem_nil _), or_false] at hv
    obtain ⟨s, hs, h_or⟩ := hv
    have hv_on : v ∈ s.toSet := by
      rcases h_or with rfl | rfl
      · exact ⟨0, le_refl 0, zero_le_one, by ring, by ring⟩
      · exact ⟨1, zero_le_one, le_refl 1, by ring, by ring⟩
    exact hm_avoids_inter s hs (heq ▸ hv_on)
  -- m's parity property.
  obtain ⟨r_p, h_r_p_orig, h_r_p_avoids⟩ :=
    exists_ray_avoiding_graph_verts p G_inter_E h_p_not_inter_vert
  have hm_parity : ∀ r : Ray, r.origin = m → rayAvoidsGraphVertices r G_inter →
      intersectionRayGraphSegmentsNumber r G_inter % 2 = 1 := by
    intro r h_origin h_avoids
    have h_sego_avoids : ∀ s ∈ G_inter_E.segments,
        segmentDoesNotIntersectSegment ⟨r_p.origin, r.origin⟩ s := by
      intro s hs; rw [h_r_p_orig, h_origin]; exact h_segpm_avoids_inter s hs
    have h_verts_avoid : ∀ v ∈ G_inter_E.toVertices,
        v ∉ (LineSegment.mk r_p.origin r.origin).toSet := by
      intro v hv; rw [h_r_p_orig, h_origin]; exact h_inter_verts_off_pm v hv
    have h_eq := intersectionParity_eq_of_originSegmentAvoidsGraphSegments
      r_p r G_inter_E h_r_p_avoids h_avoids h_sego_avoids h_verts_avoid
    have h_eq' : intersectionRayGraphSegmentsNumber r_p G_inter % 2 =
        intersectionRayGraphSegmentsNumber r G_inter % 2 := h_eq
    rw [← h_eq']; exact h_parity r_p h_r_p_orig h_r_p_avoids
  -- Apply case2_gen with boundary graph X, other Y.
  exact case2_gen G1 G2 X Y h_swap h_even m hm_X hm_not_Y hm_not_Y_int hm_avoids_inter hm_parity

/-- **Case 3 (parameterised).** `p ∈ ∂Gb ∩ ∂Go`. We find an arrangement segment through `p`
    that is *transversal* (its open interior crosses the other graph's boundary only at the
    endpoints) and reduce to `case3_via_transversal_seg`. We try `arr Gb Go` first, then
    `arr Go Gb`. -/
private theorem case3_gen (G1 G2 : EvenGraph) (Gb Go : EvenGraph)
    (h_swap : (Gb = G1 ∧ Go = G2) ∨ (Gb = G2 ∧ Go = G1))
    (h_even : (interGraph G1 G2).IsEven)
    (p : Vector2D)
    (h_p_on_Gb : p ∈ Gb.toBoundarySet)
    (h_p_on_Go : p ∈ Go.toBoundarySet)
    (h_p_avoids_inter : ∀ seg ∈ (interGraph G1 G2).segments, pointAvoidsSegment p seg)
    (h_parity : ∀ r : Ray, r.origin = p → rayAvoidsGraphVertices r (interGraph G1 G2) →
      intersectionRayGraphSegmentsNumber r (interGraph G1 G2) % 2 = 1) :
    False := by
  have h_swap' : (Go = G1 ∧ Gb = G2) ∨ (Go = G2 ∧ Gb = G1) := by
    rcases h_swap with ⟨hb, ho⟩ | ⟨hb, ho⟩
    · right; exact ⟨ho, hb⟩
    · left; exact ⟨ho, hb⟩
  -- A segment of arr Gb Go through p.
  have h_p_arrGbGo : p ∈ (arr Gb Go).toBoundarySet := by
    rw [arr_boundary_eq Gb Go]; exact h_p_on_Gb
  obtain ⟨seg_b, hseg_b, hp_b⟩ := h_p_arrGbGo
  by_cases hns_b : IsShared Go seg_b
  · -- seg_b shared. Try arr Go Gb.
    have h_p_arrGoGb : p ∈ (arr Go Gb).toBoundarySet := by
      rw [arr_boundary_eq Go Gb]; exact h_p_on_Go
    obtain ⟨seg_o, hseg_o, hp_o⟩ := h_p_arrGoGb
    by_cases hns_o : IsShared Gb seg_o
    · -- Fully shared at p: both arrangements' segments through p are shared edges.
      -- Extract the `arr G1 G2`-shaped shared edge `σ12` through p (⊆ ∂G2).
      obtain ⟨σ12, hσ12_arr, hp_σ12, hσ12_shared⟩ :
          ∃ σ12 ∈ (arr G1 G2).segments, p ∈ σ12.toSet ∧ IsShared G2 σ12 := by
        rcases h_swap with ⟨hb, ho⟩ | ⟨hb, ho⟩
        · -- Gb = G1, Go = G2: seg_b ∈ arr G1 G2, IsShared G2 seg_b.
          exact ⟨seg_b, by rw [← hb, ← ho]; exact hseg_b, hp_b, by rw [← ho]; exact hns_b⟩
        · -- Gb = G2, Go = G1: seg_o ∈ arr Go Gb = arr G1 G2, IsShared G2 (= Gb) seg_o.
          exact ⟨seg_o, by rw [← hb, ← ho]; exact hseg_o, hp_o, by rw [← hb]; exact hns_o⟩
      -- canonSeg σ12 has the same point set and is shared w.r.t. G2.
      have hcanon_shared : IsShared G2 (canonSeg σ12) := by
        rw [IsShared, canonSeg_toSet]; exact hσ12_shared
      have hp_canon : p ∈ (canonSeg σ12).toSet := by rw [canonSeg_toSet]; exact hp_σ12
      by_cases hoib : onInterBoundary G1 G2 (canonSeg σ12)
      · -- The shared edge is selected: it is in `interGraph`, and `p` lies on it. Contradiction.
        have hcanon_mem : canonSeg σ12 ∈ sharedSelected G1 G2 := by
          rw [sharedSelected, List.mem_filter]
          refine ⟨List.mem_dedup.mpr (List.mem_map.mpr ⟨σ12, hσ12_arr, rfl⟩), ?_⟩
          exact decide_eq_true ⟨hcanon_shared, hoib⟩
        have hcanon_inter : canonSeg σ12 ∈ (interGraph G1 G2).segments := by
          rw [interGraph_segments]
          exact List.mem_append.mpr (Or.inl (List.mem_append.mpr (Or.inr hcanon_mem)))
        exact h_p_avoids_inter (canonSeg σ12) hcanon_inter hp_canon
      · -- Degenerate overlap: the shared edge through `p` is NOT on `∂(G1.interior ∩ G2.interior)`
        -- (`¬ onInterBoundary`), hence lies in `phantomDoubled`, so it is in `interGraph` and `p`
        -- lies on it. Contradiction.
        have hph : canonSeg σ12 ∈ phantomDoubled G1 G2 := by
          rw [phantomDoubled, List.mem_flatMap]
          refine ⟨canonSeg σ12, ?_, by simp⟩
          rw [List.mem_filter]
          exact ⟨List.mem_dedup.mpr (List.mem_map.mpr ⟨σ12, hσ12_arr, rfl⟩),
                 decide_eq_true ⟨hcanon_shared, hoib⟩⟩
        have hmem : canonSeg σ12 ∈ (interGraph G1 G2).segments := by
          rw [interGraph_segments]; exact List.mem_append.mpr (Or.inr hph)
        exact h_p_avoids_inter (canonSeg σ12) hmem hp_canon
    · exact case3_via_transversal_seg G1 G2 Go Gb h_swap' h_even p seg_o hseg_o hp_o hns_o
        h_p_avoids_inter h_parity
  · exact case3_via_transversal_seg G1 G2 Gb Go h_swap h_even p seg_b hseg_b hp_b hns_b
      h_p_avoids_inter h_parity

/-- If `p ∈ (interGraph G1 G2).interior` then `p ∉ ∂G1`. -/
private theorem interGraph_interior_off_G1 (G1 G2 : EvenGraph)
    (h_even : (interGraph G1 G2).IsEven) (p : Vector2D)
    (h_p_avoids_inter : ∀ seg ∈ (interGraph G1 G2).segments, pointAvoidsSegment p seg)
    (h_parity : ∀ r : Ray, r.origin = p → rayAvoidsGraphVertices r (interGraph G1 G2) →
      intersectionRayGraphSegmentsNumber r (interGraph G1 G2) % 2 = 1) :
    p ∉ G1.toBoundarySet := by
  intro h_p_on_G1
  by_cases h_p_in_G2_int : p ∈ G2.interior
  · -- Case 1: the selected arr G1 G2 segment through p is in interGraph's first block.
    obtain ⟨σ, hσ_sel, hp_σ⟩ := case1_selected_seg G1 G2 p h_p_on_G1 h_p_in_G2_int
    have hσ_inter : σ ∈ (interGraph G1 G2).segments := by
      rw [interGraph_segments]
      exact List.mem_append.mpr (Or.inl (List.mem_append.mpr (Or.inl (List.mem_append.mpr (Or.inl hσ_sel)))))
    exact h_p_avoids_inter σ hσ_inter hp_σ
  · by_cases h_p_on_G2 : p ∈ G2.toBoundarySet
    · -- Case 3
      exact case3_gen G1 G2 G1 G2 (Or.inl ⟨rfl, rfl⟩) h_even p h_p_on_G1 h_p_on_G2
        h_p_avoids_inter h_parity
    · -- Case 2
      exact case2_gen G1 G2 G1 G2 (Or.inl ⟨rfl, rfl⟩) h_even p h_p_on_G1 h_p_on_G2
        h_p_in_G2_int h_p_avoids_inter h_parity

/-- If `p ∈ (interGraph G1 G2).interior` then `p ∉ ∂G2`. -/
private theorem interGraph_interior_off_G2 (G1 G2 : EvenGraph)
    (h_even : (interGraph G1 G2).IsEven) (p : Vector2D)
    (h_p_avoids_inter : ∀ seg ∈ (interGraph G1 G2).segments, pointAvoidsSegment p seg)
    (h_parity : ∀ r : Ray, r.origin = p → rayAvoidsGraphVertices r (interGraph G1 G2) →
      intersectionRayGraphSegmentsNumber r (interGraph G1 G2) % 2 = 1) :
    p ∉ G2.toBoundarySet := by
  intro h_p_on_G2
  by_cases h_p_in_G1_int : p ∈ G1.interior
  · -- Case 1 (boundary graph G2, other G1): selected arr G2 G1 segment lands in interGraph's
    -- second block.
    obtain ⟨σ, hσ_sel, hp_σ⟩ := case1_selected_seg G2 G1 p h_p_on_G2 h_p_in_G1_int
    have hσ_inter : σ ∈ (interGraph G1 G2).segments := by
      rw [interGraph_segments]
      exact List.mem_append.mpr (Or.inl (List.mem_append.mpr (Or.inl (List.mem_append.mpr (Or.inr hσ_sel)))))
    exact h_p_avoids_inter σ hσ_inter hp_σ
  · by_cases h_p_on_G1 : p ∈ G1.toBoundarySet
    · -- Case 3 (boundary graph G2, other G1)
      exact case3_gen G1 G2 G2 G1 (Or.inr ⟨rfl, rfl⟩) h_even p h_p_on_G2 h_p_on_G1
        h_p_avoids_inter h_parity
    · -- Case 2 (boundary graph G2, other G1)
      exact case2_gen G1 G2 G2 G1 (Or.inr ⟨rfl, rfl⟩) h_even p h_p_on_G2 h_p_on_G1
        h_p_in_G1_int h_p_avoids_inter h_parity

/-- The intersection graph is even and its interior equals `G1.interior ∩ G2.interior`. -/
theorem interGraph_isEven_and_interior_eq (G1 G2 : EvenGraph) :
    ∃ h_even : (interGraph G1 G2).IsEven,
      (⟨interGraph G1 G2, h_even⟩ : EvenGraph).interior = G1.interior ∩ G2.interior := by
  -- Setup
  set arr1 := arr G1 G2 with harr1_def
  set arr2 := arr G2 G1 with harr2_def
  set G_inter : Graph := interGraph G1 G2 with hG_inter_def
  have harr1_int : arr1.interior = G1.interior := arr_interior_eq G1 G2
  have harr2_int : arr2.interior = G2.interior := arr_interior_eq G2 G1
  have harr1_bnd : arr1.toBoundarySet = G1.toBoundarySet := arr_boundary_eq G1 G2
  have harr2_bnd : arr2.toBoundarySet = G2.toBoundarySet := arr_boundary_eq G2 G1
  -- Each G_inter segment is in arr1, arr2, or sharedSelected.
  have h_inter_seg_origin : ∀ seg ∈ G_inter.segments,
      seg ∈ arr1.segments ∨ seg ∈ arr2.segments ∨
        ∃ σ0 ∈ arr1.segments, seg = canonSeg σ0 :=
    interGraph_seg_origin G1 G2
  -- Vertices of G_inter are vertices of arr1 or arr2.
  have h_inter_vert_in_arr : ∀ v ∈ G_inter.toVertices,
      v ∈ arr1.toVertices ∨ v ∈ arr2.toVertices :=
    interGraph_vert_in_arr G1 G2
  -- arr1, arr2 vertices live in their boundaries (= G1, G2 boundaries).
  have h_arr1_vert_in_G1_bnd : ∀ v ∈ arr1.toVertices, v ∈ G1.toBoundarySet := by
    intro v hv; rw [← harr1_bnd]; exact vert_in_bnd arr1 v hv
  have h_arr2_vert_in_G2_bnd : ∀ v ∈ arr2.toVertices, v ∈ G2.toBoundarySet := by
    intro v hv; rw [← harr2_bnd]; exact vert_in_bnd arr2 v hv
  -- Build V_extra and S_extra for the characterization theorem.
  let V_extra : Finset Vector2D :=
    ((arr1.toVertices ++ arr2.toVertices) ++ Xlist G1 G2).toFinset
  let S_extra : Finset LineSegment := (arr1.segments ++ arr2.segments).toFinset
  -- Hypothesis (i): S_extra non-degenerate
  have h_S_extra_nondeg : ∀ seg ∈ S_extra, seg.p1 ≠ seg.p2 := by
    intro seg hseg
    simp only [S_extra, List.mem_toFinset, List.mem_append] at hseg
    rcases hseg with h | h
    · exact arr1.segments_nondegenerate seg h
    · exact arr2.segments_nondegenerate seg h
  -- Hypothesis (ii): no-cross.
  have h_no_segment_interior_vertices : ∀ v ∈ G_inter.toVertices,
      (∀ seg ∈ G_inter.segments, seg.p1 ≠ v → seg.p2 ≠ v → v ∉ seg.toSet) ∧
      (∀ seg ∈ S_extra, seg.p1 ≠ v → seg.p2 ≠ v → v ∉ seg.toSet) := by
    intro v hv
    have hv_arr := h_inter_vert_in_arr v hv
    -- Helper: v not on non-incident arr1 segment.
    have h_not_on_arr1 : ∀ seg ∈ arr1.segments, seg.p1 ≠ v → seg.p2 ≠ v → v ∉ seg.toSet := by
      intro seg hseg h1 h2
      rcases hv_arr with hv1 | hv2
      · exact arr_no_segment_interior_vertices G1 G2 v hv1 seg hseg h1 h2
      · -- cross-graph: v ∈ arr2.toVertices, seg ∈ arr1.segments.
        intro h_on
        have hv_G2_bnd : v ∈ G2.toBoundarySet := h_arr2_vert_in_G2_bnd v hv2
        rcases arr_dichotomy G1 G2 seg hseg with hsubset | hshared
        · -- transversal: v ∈ {seg.p1, seg.p2}.
          have hv_in : v ∈ ({seg.p1, seg.p2} : Set Vector2D) := hsubset ⟨h_on, hv_G2_bnd⟩
          rcases hv_in with hp1 | hp2
          · exact h1 hp1.symm
          · exact h2 hp2.symm
        · -- shared: seg.toSet ⊆ G2.toBoundarySet. Then v ∈ arr2.toVertices on seg ⊆ ∂G2 = ∂arr2.
          -- v is an arr2 vertex; v ∈ seg.toSet; seg ⊆ ∂arr2. Use arr2 no-interior-vertex via
          -- the arr2-segment containing v... Actually we use that v on seg (an arr1 seg in ∂G2)
          -- and v is endpoint of arr2. We need v = seg.p1 or seg.p2.
          -- Reduce: arr_no_segment_interior_vertices for arr2 can't apply (seg ∉ arr2).
          -- Instead: every point of seg is in ∂arr2; v is an arr2 vertex on seg. The other
          -- arr2-vertices on seg... we use the breakpoint property: an arr2 vertex on an arr1
          -- segment (collinear) is one of the arr1-segment's endpoints (breakpoint insertion).
          -- Equivalently, apply arr_dichotomy's collinear key: v ∈ G2.toVertices on seg.
          -- We have v ∈ arr2.toVertices ⊆ G2.toVertices? No, arr2 vertices ⊆ ∂G2 only.
          -- Use the shared-case structure of arr_dichotomy directly via the breakpoint argument.
          exact absurd (arr_shared_vertex_endpoint G1 G2 seg hseg hshared v
            (h_arr2_vert_in_G2_bnd v hv2) hv2 h_on) (by
            rintro (h | h)
            · exact h1 h.symm
            · exact h2 h.symm)
    have h_not_on_arr2 : ∀ seg ∈ arr2.segments, seg.p1 ≠ v → seg.p2 ≠ v → v ∉ seg.toSet := by
      intro seg hseg h1 h2
      rcases hv_arr with hv1 | hv2
      · -- cross-graph: v ∈ arr1.toVertices, seg ∈ arr2.segments.
        intro h_on
        have hv_G1_bnd : v ∈ G1.toBoundarySet := h_arr1_vert_in_G1_bnd v hv1
        rcases arr_dichotomy G2 G1 seg hseg with hsubset | hshared
        · have hv_in : v ∈ ({seg.p1, seg.p2} : Set Vector2D) := hsubset ⟨h_on, hv_G1_bnd⟩
          rcases hv_in with hp1 | hp2
          · exact h1 hp1.symm
          · exact h2 hp2.symm
        · exact absurd (arr_shared_vertex_endpoint G2 G1 seg hseg hshared v
            (h_arr1_vert_in_G1_bnd v hv1) hv1 h_on) (by
            rintro (h | h)
            · exact h1 h.symm
            · exact h2 h.symm)
      · exact arr_no_segment_interior_vertices G2 G1 v hv2 seg hseg h1 h2
    refine ⟨?_, ?_⟩
    · intro seg hseg h1 h2
      rcases h_inter_seg_origin seg hseg with hg1 | hg2 | hg3
      · exact h_not_on_arr1 seg hg1 h1 h2
      · exact h_not_on_arr2 seg hg2 h1 h2
      · -- shared/phantom seg = canonSeg σ0 of arr1. Then seg.toSet = σ0.toSet, σ0 ∈ arr1.segments.
        intro h_on
        obtain ⟨σ0, hσ0, hσ0sub⟩ := hg3
        subst hσ0sub
        rw [canonSeg_toSet] at h_on
        -- canonSeg σ0 endpoints are {σ0.p1, σ0.p2}; reduce to σ0.
        rcases canonSeg_endpoints σ0 with ⟨he1, he2⟩ | ⟨he1, he2⟩
        · rw [he1] at h1; rw [he2] at h2
          exact h_not_on_arr1 σ0 hσ0 h1 h2 h_on
        · rw [he1] at h1; rw [he2] at h2
          exact h_not_on_arr1 σ0 hσ0 h2 h1 h_on
    · intro seg hseg h1 h2
      simp only [S_extra, List.mem_toFinset, List.mem_append] at hseg
      rcases hseg with h | h
      · exact h_not_on_arr1 seg h h1 h2
      · exact h_not_on_arr2 seg h h1 h2
  -- Hypothesis (iii): the parity ↔ I = G1.int ∩ G2.int property.
  have h_exists : ∃ I : Set Vector2D,
      I ∩ G_inter.toBoundarySet = ∅ ∧
      ∀ r : Ray,
        r.origin ∉ G_inter.toBoundarySet →
        (∀ s ∈ S_extra, r.origin ∉ s.toSet) →
        rayAvoidsGraphVertices r G_inter →
        (∀ v ∈ V_extra, v ∉ r.toSet) →
        (intersectionRayGraphSegmentsNumber r G_inter % 2 = 1 ↔
          r.origin ∈ I) := by
    refine ⟨G1.interior ∩ G2.interior, ?_, ?_⟩
    · -- I ∩ G_inter.boundary = ∅.
      ext q
      simp only [Set.mem_inter_iff, Set.mem_empty_iff_false, iff_false, not_and]
      intro hq h_q_bnd
      have hq_in : q ∈ G1.toBoundarySet ∪ G2.toBoundarySet :=
        interGraph_boundary_subset G1 G2 h_q_bnd
      rcases hq_in with h | h
      · obtain ⟨s', hs', hin'⟩ := h
        exact hq.1.1 s' hs' hin'
      · obtain ⟨s', hs', hin'⟩ := h
        exact hq.2.1 s' hs' hin'
    · -- The parity ↔ membership property.
      intro r h_origin_off_G_inter h_origin_off_S r_avoids_G_inter h_verts_off_r
      -- Origin avoids both arr graphs (since S_extra ⊇ arr segments) ⇒ origin ∉ ∂G1, ∂G2.
      have h_origin_off_G1 : r.origin ∉ G1.toBoundarySet := by
        rw [← harr1_bnd]; rintro ⟨seg, hseg, hon⟩
        exact h_origin_off_S seg (by
          simp only [S_extra, List.mem_toFinset, List.mem_append]; exact Or.inl hseg) hon
      have h_origin_off_G2 : r.origin ∉ G2.toBoundarySet := by
        rw [← harr2_bnd]; rintro ⟨seg, hseg, hon⟩
        exact h_origin_off_S seg (by
          simp only [S_extra, List.mem_toFinset, List.mem_append]; exact Or.inr hseg) hon
      -- Ray avoids both arr vertex sets.
      have h_ray_avoids_arr1 : rayAvoidsGraphVertices r arr1 := by
        rw [rayAvoidsGraphVertices, Set.eq_empty_iff_forall_not_mem]
        intro v ⟨hv_ray, hv_vert⟩
        have : v ∈ V_extra := by
          simp only [V_extra, List.mem_toFinset, List.mem_append]
          exact Or.inl (Or.inl hv_vert)
        exact h_verts_off_r v this hv_ray
      have h_ray_avoids_arr2 : rayAvoidsGraphVertices r arr2 := by
        rw [rayAvoidsGraphVertices, Set.eq_empty_iff_forall_not_mem]
        intro v ⟨hv_ray, hv_vert⟩
        have : v ∈ V_extra := by
          simp only [V_extra, List.mem_toFinset, List.mem_append]
          exact Or.inl (Or.inr hv_vert)
        exact h_verts_off_r v this hv_ray
      -- Ray avoids Xlist.
      have h_ray_avoids_X : ∀ x ∈ Xlist G1 G2, x ∉ r.toSet := by
        intro x hx
        apply h_verts_off_r x
        simp only [V_extra, List.mem_toFinset, List.mem_append]
        exact Or.inr hx
      -- Origin avoids arr1, arr2 segments (for point_in_interior_iff_odd_count).
      have h_origin_avoids_arr1 : ∀ seg ∈ arr1.segments, pointAvoidsSegment r.origin seg := by
        intro seg hseg; apply h_origin_off_S
        simp only [S_extra, List.mem_toFinset, List.mem_append]; exact Or.inl hseg
      have h_origin_avoids_arr2 : ∀ seg ∈ arr2.segments, pointAvoidsSegment r.origin seg := by
        intro seg hseg; apply h_origin_off_S
        simp only [S_extra, List.mem_toFinset, List.mem_append]; exact Or.inr hseg
      -- The parity core identity.
      have h_core := interGraph_parity_core G1 G2 r h_ray_avoids_arr1 h_ray_avoids_arr2
        h_ray_avoids_X h_origin_off_G1 h_origin_off_G2
      -- Per-graph parity ↔ interior.
      have h_iff1 := point_in_interior_iff_odd_count r arr1 h_origin_avoids_arr1 h_ray_avoids_arr1
      have h_iff2 := point_in_interior_iff_odd_count r arr2 h_origin_avoids_arr2 h_ray_avoids_arr2
      rw [harr1_int] at h_iff1
      rw [harr2_int] at h_iff2
      -- Conclude.
      rw [Set.mem_inter_iff, h_iff1, h_iff2]
      have hGeq : intersectionRayGraphSegmentsNumber r G_inter =
          intersectionRayGraphSegmentsNumber r (interGraph G1 G2) := rfl
      rw [hGeq, h_core]
      -- Goal: (#arr1 * #arr2) % 2 = 1 ↔ #arr1 % 2 = 1 ∧ #arr2 % 2 = 1
      constructor
      · intro h_odd
        constructor
        · have := Nat.mod_two_eq_zero_or_one
            (intersectionRayGraphSegmentsNumber r (arr G1 G2).toGraph)
          rcases this with h | h
          · rw [Nat.mul_mod, h] at h_odd; simp at h_odd
          · exact h
        · have := Nat.mod_two_eq_zero_or_one
            (intersectionRayGraphSegmentsNumber r (arr G2 G1).toGraph)
          rcases this with h | h
          · rw [Nat.mul_mod, h] at h_odd; simp at h_odd
          · exact h
      · intro ⟨h1, h2⟩
        rw [Nat.mul_mod, h1, h2]
  -- Apply the characterization theorem.
  have h_even : G_inter.IsEven :=
    Graph.isEven_of_exists_interior_set G_inter V_extra S_extra
      h_S_extra_nondeg h_no_segment_interior_vertices h_exists
  refine ⟨h_even, ?_⟩
  -- Now prove interior equality.
  ext p
  rw [Set.mem_inter_iff]
  show ((∀ seg ∈ G_inter.segments, pointAvoidsSegment p seg) ∧
        ∀ r : Ray, r.origin = p → rayAvoidsGraphVertices r G_inter →
          intersectionRayGraphSegmentsNumber r G_inter % 2 = 1) ↔
        p ∈ G1.interior ∧ p ∈ G2.interior
  constructor
  · -- (⊆)
    intro ⟨h_p_avoids_inter, h_parity⟩
    -- Boundary exclusion.
    have h_p_off_G1 : p ∉ G1.toBoundarySet :=
      interGraph_interior_off_G1 G1 G2 h_even p h_p_avoids_inter h_parity
    have h_p_off_G2 : p ∉ G2.toBoundarySet :=
      interGraph_interior_off_G2 G1 G2 h_even p h_p_avoids_inter h_parity
    -- p avoids arr1, arr2 segments.
    have h_p_off_arr1 : p ∉ arr1.toBoundarySet := by rw [harr1_bnd]; exact h_p_off_G1
    have h_p_off_arr2 : p ∉ arr2.toBoundarySet := by rw [harr2_bnd]; exact h_p_off_G2
    have h_p_avoids_arr1 : ∀ seg ∈ arr1.segments, pointAvoidsSegment p seg := by
      intro seg hseg h_on; exact h_p_off_arr1 ⟨seg, hseg, h_on⟩
    have h_p_avoids_arr2 : ∀ seg ∈ arr2.segments, pointAvoidsSegment p seg := by
      intro seg hseg h_on; exact h_p_off_arr2 ⟨seg, hseg, h_on⟩
    -- p is not a vertex of either arr graph.
    have h_p_not_both : ∀ v ∈ arr1.toVertices ++ arr2.toVertices, v ≠ p := by
      intro v hv
      rcases List.mem_append.mp hv with h | h
      · intro heq; exact h_p_off_arr1 (by rw [← heq]; exact vert_in_bnd arr1 v h)
      · intro heq; exact h_p_off_arr2 (by rw [← heq]; exact vert_in_bnd arr2 v h)
    -- Find a ray from p avoiding both arr graphs' vertices AND Xlist.
    obtain ⟨r₀, h_origin₀, h_r₀_avoids1, h_r₀_avoids2, h_r₀_avoids_X⟩ :=
      exists_qualifying_ray G1 G2 p h_p_not_both h_p_off_G1 h_p_off_G2
    -- This ray avoids G_inter vertices.
    have h_r₀_avoids_inter : rayAvoidsGraphVertices r₀ G_inter := by
      rw [rayAvoidsGraphVertices, Set.eq_empty_iff_forall_not_mem]
      intro v ⟨hv_ray, hv_vert⟩
      rcases h_inter_vert_in_arr v hv_vert with h1 | h2
      · have : v ∈ r₀.toSet ∩ arr1.toVertexSet := ⟨hv_ray, h1⟩
        rw [h_r₀_avoids1] at this; exact this
      · have : v ∈ r₀.toSet ∩ arr2.toVertexSet := ⟨hv_ray, h2⟩
        rw [h_r₀_avoids2] at this; exact this
    -- Ray r₀ has odd parity for G_inter (from h_parity).
    have h_r₀_inter_odd := h_parity r₀ h_origin₀ h_r₀_avoids_inter
    -- By core, #arr1·#arr2 odd.
    have h_origin_segs1 : ∀ seg ∈ arr1.segments, pointAvoidsSegment r₀.origin seg := by
      rw [h_origin₀]; exact h_p_avoids_arr1
    have h_origin_segs2 : ∀ seg ∈ arr2.segments, pointAvoidsSegment r₀.origin seg := by
      rw [h_origin₀]; exact h_p_avoids_arr2
    have h_off_G1₀ : r₀.origin ∉ G1.toBoundarySet := by rw [h_origin₀]; exact h_p_off_G1
    have h_off_G2₀ : r₀.origin ∉ G2.toBoundarySet := by rw [h_origin₀]; exact h_p_off_G2
    have h_core := interGraph_parity_core G1 G2 r₀ h_r₀_avoids1 h_r₀_avoids2 h_r₀_avoids_X
      h_off_G1₀ h_off_G2₀
    rw [show interGraph G1 G2 = G_inter from rfl] at h_core
    rw [h_core] at h_r₀_inter_odd
    -- Both factors odd.
    have h_arr1_odd : intersectionRayGraphSegmentsNumber r₀ arr1 % 2 = 1 := by
      by_contra hne
      have : intersectionRayGraphSegmentsNumber r₀ arr1 % 2 = 0 := by
        have := Nat.mod_lt (intersectionRayGraphSegmentsNumber r₀ arr1) (show 0 < 2 by norm_num)
        omega
      rw [Nat.mul_mod, this] at h_r₀_inter_odd; simp at h_r₀_inter_odd
    have h_arr2_odd : intersectionRayGraphSegmentsNumber r₀ arr2 % 2 = 1 := by
      by_contra hne
      have : intersectionRayGraphSegmentsNumber r₀ arr2 % 2 = 0 := by
        have := Nat.mod_lt (intersectionRayGraphSegmentsNumber r₀ arr2) (show 0 < 2 by norm_num)
        omega
      rw [Nat.mul_mod, this] at h_r₀_inter_odd; simp at h_r₀_inter_odd
    -- Conclude p ∈ G1.interior ∩ G2.interior.
    have h_p_G1_int : p ∈ G1.interior := by
      rw [← harr1_int]
      refine ⟨h_p_avoids_arr1, ?_⟩
      intro r h_origin h_avoids
      have h_eq := intersectionParity_eq_of_sameOrigin_avoidsGraphVertices
        r₀ r arr1 (by simp [sameOrigin, h_origin₀, h_origin])
        h_r₀_avoids1 h_avoids h_origin_segs1
      rw [← h_eq]; exact h_arr1_odd
    have h_p_G2_int : p ∈ G2.interior := by
      rw [← harr2_int]
      refine ⟨h_p_avoids_arr2, ?_⟩
      intro r h_origin h_avoids
      have h_eq := intersectionParity_eq_of_sameOrigin_avoidsGraphVertices
        r₀ r arr2 (by simp [sameOrigin, h_origin₀, h_origin])
        h_r₀_avoids2 h_avoids h_origin_segs2
      rw [← h_eq]; exact h_arr2_odd
    exact ⟨h_p_G1_int, h_p_G2_int⟩
  · -- (⊇)
    intro ⟨hG1_int, hG2_int⟩
    have h_p_arr1 : p ∈ arr1.interior := by rw [harr1_int]; exact hG1_int
    have h_p_arr2 : p ∈ arr2.interior := by rw [harr2_int]; exact hG2_int
    have h_p_avoids_arr1 := h_p_arr1.1
    have h_p_avoids_arr2 := h_p_arr2.1
    have h_p_off_G1 : p ∉ G1.toBoundarySet := by
      rintro ⟨s', hs', hin'⟩; exact hG1_int.1 s' hs' hin'
    have h_p_off_G2 : p ∉ G2.toBoundarySet := by
      rintro ⟨s', hs', hin'⟩; exact hG2_int.1 s' hs' hin'
    refine ⟨?_, ?_⟩
    · intro seg hseg
      rcases h_inter_seg_origin seg hseg with hg1 | hg2 | hg3
      · exact h_p_avoids_arr1 seg hg1
      · exact h_p_avoids_arr2 seg hg2
      · -- shared/phantom seg = canonSeg σ0; seg.toSet = σ0.toSet ⊆ ∂arr1 = ∂G1; p ∉ ∂G1.
        intro h_on
        obtain ⟨σ0, hσ0, hσ0sub⟩ := hg3
        rw [hσ0sub, canonSeg_toSet] at h_on
        have h_sub := arr_seg_subset_boundary G1 G2 σ0 hσ0
        exact h_p_off_G1 (h_sub h_on)
    · intro r h_origin h_r_avoids_inter
      have h_p_not_both : ∀ v ∈ arr1.toVertices ++ arr2.toVertices, v ≠ p := by
        intro v hv
        rcases List.mem_append.mp hv with h | h
        · exact not_vertex_of_avoids_segments p arr1 arr1.incident_count_pos h_p_avoids_arr1 v h
        · exact not_vertex_of_avoids_segments p arr2 arr2.incident_count_pos h_p_avoids_arr2 v h
      obtain ⟨r₀, h_origin₀, h_r₀_avoids1, h_r₀_avoids2, h_r₀_avoids_X⟩ :=
        exists_qualifying_ray G1 G2 p h_p_not_both h_p_off_G1 h_p_off_G2
      have h_r₀_avoids_inter : rayAvoidsGraphVertices r₀ G_inter := by
        rw [rayAvoidsGraphVertices, Set.eq_empty_iff_forall_not_mem]
        intro v ⟨hv_ray, hv_vert⟩
        rcases h_inter_vert_in_arr v hv_vert with h1 | h2
        · have : v ∈ r₀.toSet ∩ arr1.toVertexSet := ⟨hv_ray, h1⟩
          rw [h_r₀_avoids1] at this; exact this
        · have : v ∈ r₀.toSet ∩ arr2.toVertexSet := ⟨hv_ray, h2⟩
          rw [h_r₀_avoids2] at this; exact this
      have h_origin_segs1 : ∀ seg ∈ arr1.segments, pointAvoidsSegment r₀.origin seg := by
        rw [h_origin₀]; exact h_p_avoids_arr1
      have h_origin_segs2 : ∀ seg ∈ arr2.segments, pointAvoidsSegment r₀.origin seg := by
        rw [h_origin₀]; exact h_p_avoids_arr2
      have h_off_G1₀ : r₀.origin ∉ G1.toBoundarySet := by rw [h_origin₀]; exact h_p_off_G1
      have h_off_G2₀ : r₀.origin ∉ G2.toBoundarySet := by rw [h_origin₀]; exact h_p_off_G2
      have h_arr1_odd : intersectionRayGraphSegmentsNumber r₀ arr1 % 2 = 1 :=
        h_p_arr1.2 r₀ h_origin₀ h_r₀_avoids1
      have h_arr2_odd : intersectionRayGraphSegmentsNumber r₀ arr2 % 2 = 1 :=
        h_p_arr2.2 r₀ h_origin₀ h_r₀_avoids2
      have h_core := interGraph_parity_core G1 G2 r₀ h_r₀_avoids1 h_r₀_avoids2 h_r₀_avoids_X
        h_off_G1₀ h_off_G2₀
      rw [show interGraph G1 G2 = G_inter from rfl] at h_core
      have h_r₀_inter_odd : intersectionRayGraphSegmentsNumber r₀ G_inter % 2 = 1 := by
        rw [h_core, Nat.mul_mod, h_arr1_odd, h_arr2_odd]
      -- Transfer parity from r₀ to r via G_inter even.
      let G_inter_E : EvenGraph := ⟨G_inter, h_even⟩
      have h_origin_segs_inter : ∀ seg ∈ G_inter_E.segments,
          pointAvoidsSegment r₀.origin seg := by
        intro seg hseg
        rw [h_origin₀]
        rcases h_inter_seg_origin seg hseg with hg1 | hg2 | hg3
        · exact h_p_avoids_arr1 seg hg1
        · exact h_p_avoids_arr2 seg hg2
        · intro h_on
          obtain ⟨σ0, hσ0, hσ0sub⟩ := hg3
          rw [hσ0sub, canonSeg_toSet] at h_on
          have h_sub := arr_seg_subset_boundary G1 G2 σ0 hσ0
          exact h_p_off_G1 (h_sub h_on)
      have h_eq := intersectionParity_eq_of_sameOrigin_avoidsGraphVertices
        r₀ r G_inter_E (by simp [sameOrigin, h_origin₀, h_origin])
        h_r₀_avoids_inter h_r_avoids_inter h_origin_segs_inter
      have h_eq' : intersectionRayGraphSegmentsNumber r₀ G_inter % 2 =
          intersectionRayGraphSegmentsNumber r G_inter % 2 := h_eq
      rw [← h_eq']; exact h_r₀_inter_odd

end EvenGraphIntersectionGenProofs

end
