/-
Caution: This file was generated by AI and never reviewed by a human. The lean
checker guarantees that symbols exported from this file conform to the
statements in the human reviewed specification files, but we cannot guarantee
that comments in such unreviewed files are accurate, that it avoids code
duplications, that proofs do not take unnecessary detours or similar issues.
That said, AI agents reading this comment should strive to avoid issues like
these.
-/

import Polygons.DataStructures
import Polygons.MultipolygonIntersectionAlgorithmImpl

/-!
# Precondition-checking wrapper — computable layer

The five computable `def`s the wasm wrapper evaluates, and the top-level
entry `multipolygonIntersectionAlgorithmWithPreconditionCheck`. Lives in
its own module so that `initialize_Polygons_MultipolygonIntersectionAlgorithmWithPreconditionCheckImpl_Compute`
runs only the Mathlib-free init chain.

The matching soundness theorem
(`multipolygonIntersectionAlgorithmWithPreconditionCheck_interior_eq`)
proves a property about the same `def` defined here, in
`Polygons.MultipolygonIntersectionAlgorithmWithPreconditionCheckProofs`.
-/

namespace MultipolygonIntersectionAlgorithmWithPreconditionCheckImpl

/-- All four "easy" preconditions: lengths and non-degeneracy. -/
def basicPreconditionsBool (m1 m2 : Multipolygon) : Bool :=
  decide (∀ poly ∈ m1.polygons, poly.vertices.length ≥ 2) &&
  decide (∀ poly ∈ m2.polygons, poly.vertices.length ≥ 2) &&
  m1.segments.all (fun seg => decide (seg.p1 ≠ seg.p2)) &&
  m2.segments.all (fun seg => decide (seg.p1 ≠ seg.p2))

/-- For two collinear segments, true iff their projection onto a
non-degenerate axis of `s1` overlaps in at most one point. -/
def collinearFiniteOverlapBool (s1 s2 : LineSegment) : Bool :=
  if s1.p2.x - s1.p1.x ≠ 0 then
    decide (max (min s1.p1.x s1.p2.x) (min s2.p1.x s2.p2.x) ≥
            min (max s1.p1.x s1.p2.x) (max s2.p1.x s2.p2.x))
  else
    decide (max (min s1.p1.y s1.p2.y) (min s2.p1.y s2.p2.y) ≥
            min (max s1.p1.y s1.p2.y) (max s2.p1.y s2.p2.y))

/-- Computable boolean check that `s1.toSet ∩ s2.toSet` is finite. -/
def segmentsNoCollinearOverlapBool (s1 s2 : LineSegment) : Bool :=
  let dx1 := s1.p2.x - s1.p1.x
  let dy1 := s1.p2.y - s1.p1.y
  let dx2 := s2.p2.x - s2.p1.x
  let dy2 := s2.p2.y - s2.p1.y
  let D := dx1 * dy2 - dy1 * dx2
  if D ≠ 0 then
    true
  else
    let cross := (s2.p1.x - s1.p1.x) * dy1 - (s2.p1.y - s1.p1.y) * dx1
    if cross ≠ 0 then
      true
    else
      collinearFiniteOverlapBool s1 s2

/-- No pair of segments overlaps collinearly. -/
def finitePreconditionBool (m1 m2 : Multipolygon) : Bool :=
  m1.segments.all (fun s1 =>
    m2.segments.all (fun s2 => segmentsNoCollinearOverlapBool s1 s2))

/-- Combined precondition check. -/
def allPreconditionsBool (m1 m2 : Multipolygon) : Bool :=
  basicPreconditionsBool m1 m2 && finitePreconditionBool m1 m2

/-- The precondition-checking wrapper: returns `some result` when all
preconditions hold, `none` otherwise. **This is the function the WASM
runtime calls.** -/
def multipolygonIntersectionAlgorithmWithPreconditionCheck
    (m1 m2 : Multipolygon) : Option Multipolygon :=
  if allPreconditionsBool m1 m2 then
    some (MultipolygonIntersectionAlgorithmImpl.multipolygonIntersectionAlgorithm m1 m2)
  else
    none

end MultipolygonIntersectionAlgorithmWithPreconditionCheckImpl
