/-
Caution: This file was generated by AI and never reviewed by a human. The lean
checker guarantees that symbols exported from this file conform to the
statements in the human reviewed specification files, but we cannot guarantee
that comments in such unreviewed files are accurate, that it avoids code
duplications, that proofs do not take unnecessary detours or similar issues.
That said, AI agents reading this comment should strive to avoid issues like
these.
-/

import Polygons.DataStructures
import Polygons.EvenGraphDecompositionImpl
import Polygons.RayIntersectionAlgorithmImpl

namespace MultipolygonIntersectionAlgorithmImpl

/-!
# Multipolygon intersection algorithm — computable layer

The 18 runtime `def`s the algorithm evaluates, lifted out of
`Polygons.MultipolygonIntersectionAlgorithmProofs` so the WASM build can
initialise this module alone (and DCE every theorem-only initialiser
the proof file pulls in).

Each `def` here is the *exact* definition the proof file's theorems are
about; there is no duplication. The proof file imports this Compute
sibling and only contains theorems plus a handful of proof-only `def`s
(`paramOnSeg`, `canonicalRefinementPoints`, `splitStructuralProperty`,
`boundaryCaptureProperty`).
-/

def vecCmpAlongSeg (p1 p2 : Vector2D) (a b : Vector2D) : Ordering :=
  let dx := p2.x - p1.x
  let dy := p2.y - p1.y
  if (if dx < 0 then -dx else dx) ≥ (if dy < 0 then -dy else dy) then
    -- compare on x (signed by dx direction)
    if dx ≥ 0 then compare a.x b.x else compare b.x a.x
  else
    if dy ≥ 0 then compare a.y b.y else compare b.y a.y



def segSegIntersect (s1 s2 : LineSegment) : Option Vector2D :=
  -- Treat segment s1 as a "ray" but bidirectional via two cases.
  -- Solve t1*(p2-p1) + ... using 2x2 determinant.
  let dx1 := s1.p2.x - s1.p1.x
  let dy1 := s1.p2.y - s1.p1.y
  let dx2 := s2.p2.x - s2.p1.x
  let dy2 := s2.p2.y - s2.p1.y
  let D := dx1 * dy2 - dy1 * dx2
  if D = 0 then
    none -- parallel or collinear; ignore
  else
    let bx := s2.p1.x - s1.p1.x
    let by_ := s2.p1.y - s1.p1.y
    let t1Num := bx * dy2 - by_ * dx2
    let t2Num := bx * dy1 - by_ * dx1
    -- Need 0 ≤ t1Num/D ≤ 1 and 0 ≤ t2Num/D ≤ 1.
    if 0 ≤ t1Num * D ∧ t1Num * D ≤ D * D ∧
       0 ≤ t2Num * D ∧ t2Num * D ≤ D * D then
      let t1 := t1Num / D
      some ⟨s1.p1.x + t1 * dx1, s1.p1.y + t1 * dy1⟩
    else
      none



def pointOnSegmentBool (p : Vector2D) (a b : Vector2D) : Bool :=
  let abx := b.x - a.x
  let aby := b.y - a.y
  let apx := p.x - a.x
  let apy := p.y - a.y
  let cross := apx * aby - apy * abx
  let dot := apx * abx + apy * aby
  let lenSq := abx * abx + aby * aby
  decide (cross = 0) && decide (0 ≤ dot) && decide (dot ≤ lenSq)



def sortAlongSeg (p1 p2 : Vector2D) (l : List Vector2D) : List Vector2D :=
  l.mergeSort (fun a b => (vecCmpAlongSeg p1 p2 a b).isLE)



universe u
def dedupConsec {α : Type u} [DecidableEq α] : List α → List α
  | [] => []
  | [a] => [a]
  | a :: b :: rest => if a = b then dedupConsec (b :: rest) else a :: dedupConsec (b :: rest)



def splitSegmentAtPoints (seg : LineSegment) (pts : List Vector2D) : List LineSegment :=
  let allPts := seg.p1 :: seg.p2 :: pts
  let sorted := sortAlongSeg seg.p1 seg.p2 allPts
  let deduped := dedupConsec sorted
  let pairs := deduped.zip deduped.tail
  pairs.map (fun (a, b) => ⟨a, b⟩)



def refinementPointsForSegment (seg : LineSegment) (m other : Multipolygon) : List Vector2D :=
  let crossings := other.segments.filterMap (segSegIntersect seg)
  let selfVerts := m.allVertices.filter (fun v =>
    pointOnSegmentBool v seg.p1 seg.p2 && decide (v ≠ seg.p1) && decide (v ≠ seg.p2))
  crossings ++ selfVerts



def refinedSegments (m other : Multipolygon) : List LineSegment :=
  m.segments.flatMap (fun seg =>
    splitSegmentAtPoints seg (refinementPointsForSegment seg m other))



def rayAvoidsVerticesBool (p : Vector2D) (k : Rat) (m : Multipolygon) : Bool :=
  m.allVertices.all (fun v =>
    -- Ray hits v iff v.y - p.y = k * (v.x - p.x) and v.x - p.x ≥ 0 (if dir.x = 1)
    -- Avoid: NOT (v.x ≥ p.x AND v.y - p.y = k * (v.x - p.x)).
    !(decide (v.x ≥ p.x) && decide (v.y - p.y = k * (v.x - p.x))))



def rayCountWithSlopeMultipolygon (p : Vector2D) (k : Rat) (m : Multipolygon) : Nat :=
  let r : Ray := ⟨p, ⟨1, k⟩, by intro h; exact absurd (congrArg Vector2D.x h) (show (1 : Rat) ≠ 0 from by decide)⟩
  m.segments.countP (fun seg => RayIntersectionAlgorithmImpl.rayIntersectsSegmentBool r seg)



def rayCountSearchMultipolygon (p : Vector2D) (m : Multipolygon) (fuel : Nat) : Nat :=
  match fuel with
  | 0 => 0
  | n+1 =>
    let k : Rat := (m.allVertices.length + 1 - n.cast : Nat)
    if rayAvoidsVerticesBool p k m then
      rayCountWithSlopeMultipolygon p k m
    else
      rayCountSearchMultipolygon p m n



def pointInsideMultipolygonBool (p : Vector2D) (m : Multipolygon) : Bool :=
  -- First check: not on boundary.
  let onBoundary := m.segments.any (fun seg => pointOnSegmentBool p seg.p1 seg.p2)
  if onBoundary then false
  else
    rayCountSearchMultipolygon p m (m.allVertices.length + 1) % 2 = 1



def slopeRay (p : Vector2D) (k : Rat) : Ray :=
  ⟨p, ⟨1, k⟩, by intro h; exact absurd (congrArg Vector2D.x h) (show (1 : Rat) ≠ 0 from by decide)⟩



def segmentMidpoint (seg : LineSegment) : Vector2D :=
  ⟨(seg.p1.x + seg.p2.x) / 2, (seg.p1.y + seg.p2.y) / 2⟩



def selectInsideOther (segs : List LineSegment) (other : Multipolygon) : List LineSegment :=
  segs.filter (fun seg => pointInsideMultipolygonBool (segmentMidpoint seg) other)



def intersectionGraphSegments (m1 m2 : Multipolygon) : List LineSegment :=
  selectInsideOther (refinedSegments m1 m2) m2 ++
  selectInsideOther (refinedSegments m2 m1) m1



def decomposeSegments (segs : List LineSegment) : List Polygon :=
  EvenGraphDecompositionImpl.decomposeList segs



def multipolygonIntersectionAlgorithm (m1 m2 : Multipolygon) : Multipolygon :=
  ⟨decomposeSegments (intersectionGraphSegments m1 m2)⟩


end MultipolygonIntersectionAlgorithmImpl
