/-
Caution: This file was generated by AI and never reviewed by a human. The lean
checker guarantees that symbols exported from this file conform to the
statements in the human reviewed specification files, but we cannot guarantee
that comments in such unreviewed files are accurate, that it avoids code
duplications, that proofs do not take unnecessary detours or similar issues.
That said, AI agents reading this comment should strive to avoid issues like
these.
-/

import Polygons.Multipolygon
import Polygons.EvenGraph
import Polygons.EvenGraphIntersection
import Polygons.EvenGraphDecomposition

/-!
# Multipolygon Intersection – Implementation

Proof that the intersection of the interiors of two multipolygons (with
per-polygon non-degenerate segments and finite boundary intersection) can be
expressed as the interior of a single multipolygon.

The argument mirrors `PolygonIntersectionProofs`:
1. Convert each multipolygon to an even graph via `Multipolygon.toEvenGraph`.
2. Form the intersection of the two even graphs via `evenGraphIntersection`,
   whose interior equals the intersection of the input interiors.
3. Decompose this even graph into polygon-derived even graphs via
   `EvenGraph.exists_polygon_decomposition`; package the polygons as a
   multipolygon.
4. The multipolygon's interior is the symmetric difference of the polygon
   interiors minus the multipolygon boundary
   (`Multipolygon.interior_eq_symmDiffAll_sdiff_boundary`), which matches the
   `combine_interior_eq_symmDiff_sdiff_boundary` form on the decomposed
   polygon graphs.
-/

open Classical Set

noncomputable section

namespace MultipolygonIntersectionProofs

theorem exists_multipolygon_inter_interior_eq_multipolygon_interior_impl
    (m1 m2 : Multipolygon)
    (h1_len : ∀ poly ∈ m1.polygons, poly.vertices.length ≥ 2)
    (h2_len : ∀ poly ∈ m2.polygons, poly.vertices.length ≥ 2)
    (h1_nondeg : ∀ seg ∈ m1.segments, seg.p1 ≠ seg.p2)
    (h2_nondeg : ∀ seg ∈ m2.segments, seg.p1 ≠ seg.p2)
    (h_fin : Set.Finite (m1.toBoundarySet ∩ m2.toBoundarySet)) :
    ∃ m : Multipolygon, m1.interior ∩ m2.interior = m.interior := by
  set G1 : EvenGraph := m1.toEvenGraph h1_len h1_nondeg with hG1_def
  set G2 : EvenGraph := m2.toEvenGraph h2_len h2_nondeg with hG2_def
  have hb1 : G1.toBoundarySet = m1.toBoundarySet :=
    Multipolygon.toEvenGraph_toBoundarySet_eq m1 h1_len h1_nondeg
  have hb2 : G2.toBoundarySet = m2.toBoundarySet :=
    Multipolygon.toEvenGraph_toBoundarySet_eq m2 h2_len h2_nondeg
  have hi1 : G1.interior = m1.interior :=
    Multipolygon.toEvenGraph_interior_eq m1 h1_len h1_nondeg
  have hi2 : G2.interior = m2.interior :=
    Multipolygon.toEvenGraph_interior_eq m2 h2_len h2_nondeg
  have h_fin12 : Set.Finite (G1.toBoundarySet ∩ G2.toBoundarySet) := by
    rw [hb1, hb2]; exact h_fin
  obtain ⟨h_even, h_interior_eq⟩ :=
    evenGraphIntersection_isEven_and_interior_eq G1 G2 h_fin12
  set Gint : EvenGraph :=
    ⟨evenGraphIntersection G1 G2 h_fin12, h_even⟩ with hGint_def
  have hGint_int : Gint.interior = m1.interior ∩ m2.interior := by
    rw [h_interior_eq, hi1, hi2]
  obtain ⟨polyGraphs, h_polyGraphs, h_equiv⟩ :=
    EvenGraph.exists_polygon_decomposition Gint
  let polyOf : EvenGraph → Polygon := fun pG =>
    if h : pG ∈ polyGraphs then (h_polyGraphs pG h).choose else ⟨[]⟩
  have polyOf_mem : ∀ pG (hmem : pG ∈ polyGraphs),
      polyOf pG = (h_polyGraphs pG hmem).choose := by
    intro pG hmem
    show (if h : pG ∈ polyGraphs then (h_polyGraphs pG h).choose else ⟨[]⟩) = _
    rw [dif_pos hmem]
  have h_each_int : ∀ pG ∈ polyGraphs, (polyOf pG).interior = pG.interior := by
    intro pG hmem
    obtain ⟨h_len, h_distinct, hpG_eq⟩ := (h_polyGraphs pG hmem).choose_spec
    calc (polyOf pG).interior
        = (h_polyGraphs pG hmem).choose.interior := by rw [polyOf_mem pG hmem]
      _ = ((h_polyGraphs pG hmem).choose.toEvenGraph h_len h_distinct).interior :=
          (Polygon.toEvenGraph_interior_eq _ h_len h_distinct).symm
      _ = pG.interior := congrArg EvenGraph.interior hpG_eq.symm
  have h_each_bd : ∀ pG ∈ polyGraphs, (polyOf pG).toBoundarySet = pG.toBoundarySet := by
    intro pG hmem
    obtain ⟨h_len, h_distinct, hpG_eq⟩ := (h_polyGraphs pG hmem).choose_spec
    calc (polyOf pG).toBoundarySet
        = (h_polyGraphs pG hmem).choose.toBoundarySet := by rw [polyOf_mem pG hmem]
      _ = ((h_polyGraphs pG hmem).choose.toEvenGraph h_len h_distinct).toBoundarySet :=
          (Polygon.toEvenGraph_boundary_eq _ h_len h_distinct).symm
      _ = pG.toBoundarySet := congrArg (fun G : EvenGraph => G.toBoundarySet) hpG_eq.symm
  -- Per-polygon well-formedness of the resulting list.
  have h_polyOf_len : ∀ pG ∈ polyGraphs,
      (polyOf pG).vertices.length ≥ 2 := by
    intro pG hmem
    obtain ⟨h_len, _, _⟩ := (h_polyGraphs pG hmem).choose_spec
    rw [polyOf_mem pG hmem]; exact h_len
  have h_polyOf_distinct : ∀ pG ∈ polyGraphs,
      ∀ seg ∈ (polyOf pG).segments, seg.p1 ≠ seg.p2 := by
    intro pG hmem
    obtain ⟨_, h_distinct, _⟩ := (h_polyGraphs pG hmem).choose_spec
    rw [polyOf_mem pG hmem]; exact h_distinct
  let polys : List Polygon := polyGraphs.map polyOf
  let m : Multipolygon := ⟨polys⟩
  -- Transfer per-polygon hypotheses to the multipolygon.
  have hm_len : ∀ poly ∈ m.polygons, poly.vertices.length ≥ 2 := by
    intro poly hp
    change poly ∈ polys at hp
    rw [List.mem_map] at hp
    obtain ⟨pG, hpG, rfl⟩ := hp
    exact h_polyOf_len pG hpG
  have hm_distinct : ∀ seg ∈ m.segments, seg.p1 ≠ seg.p2 := by
    intro seg hseg
    -- seg ∈ m.segments = m.polygons.flatMap Polygon.segments
    obtain ⟨poly, hpoly, hps⟩ := List.mem_flatMap.mp hseg
    change poly ∈ polys at hpoly
    rw [List.mem_map] at hpoly
    obtain ⟨pG, hpG, rfl⟩ := hpoly
    exact h_polyOf_distinct pG hpG seg hps
  refine ⟨m, ?_⟩
  -- The map of `polys` through `Polygon.interior` matches the map of
  -- `polyGraphs` through `EvenGraph.interior`.
  have h_map_int :
      polys.map Polygon.interior = polyGraphs.map EvenGraph.interior := by
    show (polyGraphs.map polyOf).map Polygon.interior = polyGraphs.map EvenGraph.interior
    rw [List.map_map]
    refine List.map_congr_left ?_
    intro pG hmem
    exact h_each_int pG hmem
  -- The multipolygon boundary equals the combined boundary of the
  -- decomposition graphs.
  have h_bd_set :
      m.toBoundarySet = (EvenGraph.combine polyGraphs).toBoundarySet := by
    rw [EvenGraph.combine_toBoundarySet]
    ext p
    -- LHS: ∃ seg ∈ m.segments, p ∈ seg.toSet, with m.segments = polys.flatMap Polygon.segments.
    -- RHS: ∃ G ∈ polyGraphs, p ∈ G.toBoundarySet.
    show (∃ seg ∈ m.segments, p ∈ seg.toSet) ↔
         p ∈ ⋃ G ∈ polyGraphs, G.toBoundarySet
    show (∃ seg ∈ polys.flatMap Polygon.segments, p ∈ seg.toSet) ↔ _
    simp only [Set.mem_iUnion, exists_prop, List.mem_flatMap]
    constructor
    · rintro ⟨seg, ⟨poly, hpoly_mem, hseg⟩, hp_in⟩
      change poly ∈ polys at hpoly_mem
      rw [List.mem_map] at hpoly_mem
      obtain ⟨pG, hpG_mem, hpG_eq⟩ := hpoly_mem
      refine ⟨pG, hpG_mem, ?_⟩
      rw [← h_each_bd pG hpG_mem, hpG_eq]
      exact ⟨seg, hseg, hp_in⟩
    · rintro ⟨pG, hmem, hp_in⟩
      rw [← h_each_bd pG hmem] at hp_in
      obtain ⟨seg, hseg, hps⟩ := hp_in
      refine ⟨seg, ⟨polyOf pG, ?_, hseg⟩, hps⟩
      change polyOf pG ∈ polyGraphs.map polyOf
      rw [List.mem_map]
      exact ⟨pG, hmem, rfl⟩
  -- Assemble: m1.interior ∩ m2.interior = Gint.interior = symmDiff form = m.interior.
  rw [Multipolygon.interior_eq_symmDiffAll_sdiff_boundary m hm_len hm_distinct,
      ← hGint_int, h_equiv.interior_eq,
      EvenGraph.combine_interior_eq_symmDiff_sdiff_boundary,
      ← h_bd_set, ← h_map_int]

end MultipolygonIntersectionProofs

end
