/-
Caution: This file was generated by AI and never reviewed by a human. The lean
checker guarantees that symbols exported from this file conform to the
statements in the human reviewed specification files, but we cannot guarantee
that comments in such unreviewed files are accurate, that it avoids code
duplications, that proofs do not take unnecessary detours or similar issues.
That said, AI agents reading this comment should strive to avoid issues like
these.
-/

import Polygons.MultipolygonIntersection
import Polygons.MultipolygonIntersectionAlgorithm
import Polygons.MultipolygonIntersectionAlgorithmWithPreconditionCheckImpl

/-!
# Polygon Intersection With Precondition Check — Implementation

A wrapper around `multipolygonIntersectionAlgorithm` that first verifies the
preconditions of the main correctness theorem
`multipolygonIntersectionAlgorithm_interior_eq` via a computable check, and
returns `none` if any precondition fails.

The preconditions:
1. `∀ poly ∈ m1.polygons, poly.vertices.length ≥ 2`
2. `∀ poly ∈ m2.polygons, poly.vertices.length ≥ 2`
3. Every segment of `m1` is non-degenerate.
4. Every segment of `m2` is non-degenerate.
5. `m1.toBoundarySet ∩ m2.toBoundarySet` is finite.

Conditions (1)–(4) are immediately decidable. For (5), we use a sufficient
computable test: no pair of segments `(s1 ∈ m1.segments, s2 ∈ m2.segments)`
overlaps collinearly. Two collinear segments overlap iff their interiors
share more than a single point; equivalently, the determinant `D = 0`
(parallel/collinear) and one segment's endpoint parameters along the line
of the other intersect the unit interval in more than a single point.
-/

/- The six runtime `def`s (`basicPreconditionsBool`,
`collinearFiniteOverlapBool`, `segmentsNoCollinearOverlapBool`,
`finitePreconditionBool`, `allPreconditionsBool`, and the entry point
`multipolygonIntersectionAlgorithmWithPreconditionCheck`) live in
`Polygons.MultipolygonIntersectionAlgorithmWithPreconditionCheckImpl`.
This file contains only the proofs about them. -/

namespace MultipolygonIntersectionAlgorithmWithPreconditionCheckProofs
open MultipolygonIntersectionAlgorithmWithPreconditionCheckImpl

open Set

/-! ### Soundness of the precondition check

If the boolean check returns `true`, the mathematical preconditions of
`multipolygonIntersectionAlgorithm_interior_eq` hold. Each clause is split into
its own lemma. -/

theorem basicPreconditionsBool_iff (m1 m2 : Multipolygon) :
    basicPreconditionsBool m1 m2 = true ↔
      (∀ poly ∈ m1.polygons, poly.vertices.length ≥ 2) ∧
      (∀ poly ∈ m2.polygons, poly.vertices.length ≥ 2) ∧
      (∀ seg ∈ m1.segments, seg.p1 ≠ seg.p2) ∧
      (∀ seg ∈ m2.segments, seg.p1 ≠ seg.p2) := by
  unfold basicPreconditionsBool
  simp only [Bool.and_eq_true, decide_eq_true_eq, List.all_eq_true]
  tauto

/-- Helper: a point on a segment lies between the two endpoint coordinate
    extremes on each axis. -/
private lemma mem_seg_x_in_range (seg : LineSegment) (p : Vector2D) (h : p ∈ seg.toSet) :
    min seg.p1.x seg.p2.x ≤ p.x ∧ p.x ≤ max seg.p1.x seg.p2.x := by
  obtain ⟨t, ht_nn, ht_le, hpx, _⟩ := h
  refine ⟨?_, ?_⟩
  · rcases le_total seg.p1.x seg.p2.x with hle | hle
    · rw [min_eq_left hle]; nlinarith
    · rw [min_eq_right hle]; nlinarith
  · rcases le_total seg.p1.x seg.p2.x with hle | hle
    · rw [max_eq_right hle]; nlinarith
    · rw [max_eq_left hle]; nlinarith

private lemma mem_seg_y_in_range (seg : LineSegment) (p : Vector2D) (h : p ∈ seg.toSet) :
    min seg.p1.y seg.p2.y ≤ p.y ∧ p.y ≤ max seg.p1.y seg.p2.y := by
  obtain ⟨t, ht_nn, ht_le, _, hpy⟩ := h
  refine ⟨?_, ?_⟩
  · rcases le_total seg.p1.y seg.p2.y with hle | hle
    · rw [min_eq_left hle]; nlinarith
    · rw [min_eq_right hle]; nlinarith
  · rcases le_total seg.p1.y seg.p2.y with hle | hle
    · rw [max_eq_right hle]; nlinarith
    · rw [max_eq_left hle]; nlinarith

/-- Per-pair subsingleton: when the no-collinear-overlap check holds for a
    pair of segments, their set intersection has at most one point. -/
private lemma segmentsNoCollinearOverlapBool_inter_subsingleton
    (s1 s2 : LineSegment) (h : segmentsNoCollinearOverlapBool s1 s2 = true) :
    (s1.toSet ∩ s2.toSet).Subsingleton := by
  unfold segmentsNoCollinearOverlapBool at h
  simp only at h
  split_ifs at h with hD hCross
  · -- D ≠ 0 branch: at most one solution.
    intro p ⟨hp1, hp2⟩ q ⟨hq1, hq2⟩
    obtain ⟨tp, _, _, hpx1, hpy1⟩ := hp1
    obtain ⟨tq, _, _, hqx1, hqy1⟩ := hq1
    obtain ⟨up, _, _, hpx2, hpy2⟩ := hp2
    obtain ⟨uq, _, _, hqx2, hqy2⟩ := hq2
    have hkey : (tp - tq) *
        ((s1.p2.x - s1.p1.x) * (s2.p2.y - s2.p1.y) -
         (s1.p2.y - s1.p1.y) * (s2.p2.x - s2.p1.x)) = 0 := by
      linear_combination
        (s2.p2.y - s2.p1.y) * (hpx2 - hpx1 - hqx2 + hqx1)
          - (s2.p2.x - s2.p1.x) * (hpy2 - hpy1 - hqy2 + hqy1)
    have htp : tp = tq := by
      rcases mul_eq_zero.mp hkey with h1 | h1
      · linarith
      · exact absurd h1 hD
    apply Vector2D.ext
    · rw [hpx1, hqx1, htp]
    · rw [hpy1, hqy1, htp]
  · -- D = 0, cross ≠ 0 branch: intersection empty.
    push_neg at hD
    intro p ⟨hp1, hp2⟩ _ _
    obtain ⟨tp, _, _, hpx1, hpy1⟩ := hp1
    obtain ⟨up, _, _, hpx2, hpy2⟩ := hp2
    exfalso
    apply hCross
    linear_combination
      (s1.p2.y - s1.p1.y) * (hpx1 - hpx2)
        - (s1.p2.x - s1.p1.x) * (hpy1 - hpy2) + up * hD
  · -- D = 0, cross = 0, collinearFiniteOverlapBool branch.
    push_neg at hD hCross
    -- h : collinearFiniteOverlapBool s1 s2 = true
    unfold collinearFiniteOverlapBool at h
    intro p ⟨hp1, hp2⟩ q ⟨hq1, hq2⟩
    -- p, q ∈ s1.toSet, so each is in [min s1.p1.x s1.p2.x, max ...].
    -- Same for s2. The intersection of these intervals has ≤ 1 point.
    have hp1_x := mem_seg_x_in_range s1 p hp1
    have hp2_x := mem_seg_x_in_range s2 p hp2
    have hq1_x := mem_seg_x_in_range s1 q hq1
    have hq2_x := mem_seg_x_in_range s2 q hq2
    have hp1_y := mem_seg_y_in_range s1 p hp1
    have hp2_y := mem_seg_y_in_range s2 p hp2
    have hq1_y := mem_seg_y_in_range s1 q hq1
    have hq2_y := mem_seg_y_in_range s2 q hq2
    split_ifs at h with hdx1
    · -- dx1 ≠ 0: project onto x.
      rw [decide_eq_true_eq] at h
      -- h : max (min s1.p1.x s1.p2.x) (min s2.p1.x s2.p2.x)
      --   ≥ min (max s1.p1.x s1.p2.x) (max s2.p1.x s2.p2.x)
      -- p.x and q.x both ≥ max(min, min), and ≤ min(max, max). So p.x = q.x.
      have hpx_eq : p.x = q.x := by
        have h_p_lo : max (min s1.p1.x s1.p2.x) (min s2.p1.x s2.p2.x) ≤ p.x := by
          rw [max_le_iff]; exact ⟨hp1_x.1, hp2_x.1⟩
        have h_p_hi : p.x ≤ min (max s1.p1.x s1.p2.x) (max s2.p1.x s2.p2.x) := by
          rw [le_min_iff]; exact ⟨hp1_x.2, hp2_x.2⟩
        have h_q_lo : max (min s1.p1.x s1.p2.x) (min s2.p1.x s2.p2.x) ≤ q.x := by
          rw [max_le_iff]; exact ⟨hq1_x.1, hq2_x.1⟩
        have h_q_hi : q.x ≤ min (max s1.p1.x s1.p2.x) (max s2.p1.x s2.p2.x) := by
          rw [le_min_iff]; exact ⟨hq1_x.2, hq2_x.2⟩
        linarith
      -- Now p.y = q.y from collinearity (dx1 ≠ 0 and points on s1).
      obtain ⟨tp, _, _, hpx_p1, hpy_p1⟩ := hp1
      obtain ⟨tq, _, _, hqx_p1, hqy_p1⟩ := hq1
      have htp_eq_tq : tp = tq := by
        have hp_x : p.x - s1.p1.x = tp * (s1.p2.x - s1.p1.x) := by linarith
        have hq_x : q.x - s1.p1.x = tq * (s1.p2.x - s1.p1.x) := by linarith
        have heq : tp * (s1.p2.x - s1.p1.x) = tq * (s1.p2.x - s1.p1.x) := by
          linarith
        exact mul_right_cancel₀ hdx1 heq
      apply Vector2D.ext
      · exact hpx_eq
      · rw [hpy_p1, hqy_p1, htp_eq_tq]
    · -- dx1 = 0: project onto y. dy1 ≠ 0 since s1 non-degenerate? We need it.
      push_neg at hdx1
      rw [decide_eq_true_eq] at h
      have hpy_eq : p.y = q.y := by
        have h_p_lo : max (min s1.p1.y s1.p2.y) (min s2.p1.y s2.p2.y) ≤ p.y := by
          rw [max_le_iff]; exact ⟨hp1_y.1, hp2_y.1⟩
        have h_p_hi : p.y ≤ min (max s1.p1.y s1.p2.y) (max s2.p1.y s2.p2.y) := by
          rw [le_min_iff]; exact ⟨hp1_y.2, hp2_y.2⟩
        have h_q_lo : max (min s1.p1.y s1.p2.y) (min s2.p1.y s2.p2.y) ≤ q.y := by
          rw [max_le_iff]; exact ⟨hq1_y.1, hq2_y.1⟩
        have h_q_hi : q.y ≤ min (max s1.p1.y s1.p2.y) (max s2.p1.y s2.p2.y) := by
          rw [le_min_iff]; exact ⟨hq1_y.2, hq2_y.2⟩
        linarith
      -- p.x = q.x: in this branch dx1 = 0, so all points on s1 have x = s1.p1.x.
      obtain ⟨tp, _, _, hpx_p1, _⟩ := hp1
      obtain ⟨tq, _, _, hqx_p1, _⟩ := hq1
      have hp_x : p.x = s1.p1.x := by
        rw [hpx_p1]
        have : (1 - tp) * s1.p1.x + tp * s1.p2.x = s1.p1.x + tp * (s1.p2.x - s1.p1.x) := by
          ring
        rw [this, hdx1]; ring
      have hq_x : q.x = s1.p1.x := by
        rw [hqx_p1]
        have : (1 - tq) * s1.p1.x + tq * s1.p2.x = s1.p1.x + tq * (s1.p2.x - s1.p1.x) := by
          ring
        rw [this, hdx1]; ring
      apply Vector2D.ext
      · rw [hp_x, hq_x]
      · exact hpy_eq

theorem finitePreconditionBool_implies_finite
    (m1 m2 : Multipolygon)
    (h : finitePreconditionBool m1 m2 = true) :
    Set.Finite (m1.toBoundarySet ∩ m2.toBoundarySet) := by
  unfold finitePreconditionBool at h
  rw [List.all_eq_true] at h
  -- Express the boundary intersection as a finite biUnion of per-pair intersections.
  have h_eq : m1.toBoundarySet ∩ m2.toBoundarySet =
      ⋃ s1 ∈ m1.segments, ⋃ s2 ∈ m2.segments, s1.toSet ∩ s2.toSet := by
    ext p
    simp only [Multipolygon.toBoundarySet, Set.mem_inter_iff, Set.mem_setOf_eq,
               Set.mem_iUnion]
    constructor
    · rintro ⟨⟨s1, hs1, hp1⟩, ⟨s2, hs2, hp2⟩⟩
      exact ⟨s1, hs1, s2, hs2, hp1, hp2⟩
    · rintro ⟨s1, hs1, s2, hs2, hp1, hp2⟩
      exact ⟨⟨s1, hs1, hp1⟩, ⟨s2, hs2, hp2⟩⟩
  rw [h_eq]
  -- Finite biUnion of finite sets.
  refine Set.Finite.biUnion (Set.finite_coe_iff.mp ?_) ?_
  · exact (List.finite_toSet m1.segments).to_subtype
  intro s1 hs1
  refine Set.Finite.biUnion (Set.finite_coe_iff.mp ?_) ?_
  · exact (List.finite_toSet m2.segments).to_subtype
  intro s2 hs2
  have hs1_all := h s1 hs1
  rw [List.all_eq_true] at hs1_all
  exact (segmentsNoCollinearOverlapBool_inter_subsingleton s1 s2
    (hs1_all s2 hs2)).finite

/-- A non-degenerate line segment contains infinitely many points. -/
private lemma LineSegment.toSet_infinite_of_nondeg
    (seg : LineSegment) (h : seg.p1 ≠ seg.p2) :
    seg.toSet.Infinite := by
  -- Define f : ℕ → Vector2D using parameter t = 1/(n+2).
  let f : ℕ → Vector2D := fun n =>
    ⟨(1 - 1/((n : ℚ) + 2)) * seg.p1.x + (1/((n : ℚ) + 2)) * seg.p2.x,
     (1 - 1/((n : ℚ) + 2)) * seg.p1.y + (1/((n : ℚ) + 2)) * seg.p2.y⟩
  apply Set.infinite_of_injective_forall_mem (f := f)
  · intro n m hnm
    have hn_pos : (0 : ℚ) < (n : ℚ) + 2 := by positivity
    have hm_pos : (0 : ℚ) < (m : ℚ) + 2 := by positivity
    have hx : (1 - 1/((n : ℚ) + 2)) * seg.p1.x + (1/((n : ℚ) + 2)) * seg.p2.x =
              (1 - 1/((m : ℚ) + 2)) * seg.p1.x + (1/((m : ℚ) + 2)) * seg.p2.x := by
      have := congrArg Vector2D.x hnm
      simpa [f] using this
    have hy : (1 - 1/((n : ℚ) + 2)) * seg.p1.y + (1/((n : ℚ) + 2)) * seg.p2.y =
              (1 - 1/((m : ℚ) + 2)) * seg.p1.y + (1/((m : ℚ) + 2)) * seg.p2.y := by
      have := congrArg Vector2D.y hnm
      simpa [f] using this
    have hx' : (1/((n : ℚ) + 2) - 1/((m : ℚ) + 2)) * (seg.p2.x - seg.p1.x) = 0 := by
      linarith [hx]
    have hy' : (1/((n : ℚ) + 2) - 1/((m : ℚ) + 2)) * (seg.p2.y - seg.p1.y) = 0 := by
      linarith [hy]
    have hinv : 1/((n : ℚ) + 2) - 1/((m : ℚ) + 2) = 0 := by
      by_cases hxeq : seg.p2.x - seg.p1.x = 0
      · have hyne : seg.p2.y - seg.p1.y ≠ 0 := by
          intro hyeq
          apply h
          apply Vector2D.ext <;> linarith
        rcases mul_eq_zero.mp hy' with h1 | h1
        · exact h1
        · exact absurd h1 hyne
      · rcases mul_eq_zero.mp hx' with h1 | h1
        · exact h1
        · exact absurd h1 hxeq
    have hinv_eq : 1/((n : ℚ) + 2) = 1/((m : ℚ) + 2) := by linarith
    have h_eq : ((n : ℚ) + 2) = ((m : ℚ) + 2) := by
      have hn_ne : ((n : ℚ) + 2) ≠ 0 := ne_of_gt hn_pos
      have hm_ne : ((m : ℚ) + 2) ≠ 0 := ne_of_gt hm_pos
      have := hinv_eq
      field_simp at this
      -- After `field_simp`, `this : m = n` (as ℕ). Cast back to ℚ.
      have hnm : (m : ℚ) = (n : ℚ) := by exact_mod_cast this
      linarith
    have hncast : (n : ℚ) = (m : ℚ) := by linarith
    exact_mod_cast hncast
  · intro n
    refine ⟨1/((n : ℚ) + 2), ?_, ?_, ?_, ?_⟩
    · positivity
    · have hpos : (0 : ℚ) < (n : ℚ) + 2 := by positivity
      have h2 : (1 : ℚ) ≤ (n : ℚ) + 2 := by
        have : (0 : ℚ) ≤ (n : ℚ) := by exact_mod_cast Nat.zero_le n
        linarith
      rw [div_le_one hpos]; linarith
    · rfl
    · rfl

/-- Helper: in the false branch of `collinearFiniteOverlapBool` with `dx1 ≠ 0`,
    we can construct an injection ℕ → s1.toSet ∩ s2.toSet. -/
private lemma segmentsNoCollinearOverlapBool_complete_of_finite_x
    (s1 s2 : LineSegment)
    (hdx1 : s1.p2.x - s1.p1.x ≠ 0)
    (hD : (s1.p2.x - s1.p1.x) * (s2.p2.y - s2.p1.y) -
          (s1.p2.y - s1.p1.y) * (s2.p2.x - s2.p1.x) = 0)
    (hCross : (s2.p1.x - s1.p1.x) * (s1.p2.y - s1.p1.y) -
              (s2.p1.y - s1.p1.y) * (s1.p2.x - s1.p1.x) = 0)
    (h_lt : max (min s1.p1.x s1.p2.x) (min s2.p1.x s2.p2.x) <
            min (max s1.p1.x s1.p2.x) (max s2.p1.x s2.p2.x)) :
    (s1.toSet ∩ s2.toSet).Infinite := by
  set a' := max (min s1.p1.x s1.p2.x) (min s2.p1.x s2.p2.x) with ha'_def
  set b' := min (max s1.p1.x s1.p2.x) (max s2.p1.x s2.p2.x) with hb'_def
  -- We have ha'_lt_b' : a' < b'.
  -- Bounds.
  have ha'_lo_s1 : min s1.p1.x s1.p2.x ≤ a' := le_max_left _ _
  have ha'_lo_s2 : min s2.p1.x s2.p2.x ≤ a' := le_max_right _ _
  have hb'_hi_s1 : b' ≤ max s1.p1.x s1.p2.x := min_le_left _ _
  have hb'_hi_s2 : b' ≤ max s2.p1.x s2.p2.x := min_le_right _ _
  have ha'_hi_s1 : a' ≤ max s1.p1.x s1.p2.x := le_of_lt (lt_of_lt_of_le h_lt hb'_hi_s1)
  have ha'_hi_s2 : a' ≤ max s2.p1.x s2.p2.x := le_of_lt (lt_of_lt_of_le h_lt hb'_hi_s2)
  have hb'_lo_s1 : min s1.p1.x s1.p2.x ≤ b' := le_trans ha'_lo_s1 (le_of_lt h_lt)
  have hb'_lo_s2 : min s2.p1.x s2.p2.x ≤ b' := le_trans ha'_lo_s2 (le_of_lt h_lt)
  -- a' < b' implies dx2 := s2.p2.x - s2.p1.x ≠ 0.
  have hdx2 : s2.p2.x - s2.p1.x ≠ 0 := by
    intro hdx2eq
    have h_eq_x : s2.p1.x = s2.p2.x := by linarith
    have hmin : min s2.p1.x s2.p2.x = s2.p1.x := by
      rw [h_eq_x]; exact min_self _
    have hmax : max s2.p1.x s2.p2.x = s2.p1.x := by
      rw [h_eq_x]; exact max_self _
    rw [hmax] at hb'_hi_s2
    rw [hmin] at ha'_lo_s2
    -- a' ≥ s2.p1.x and b' ≤ s2.p1.x, so a' ≥ b'. Contradiction.
    linarith
  -- For each n, define c(n) := a' + (b' - a') / (n + 2).
  -- Then x ∈ [a', b'] (in fact a' < c(n) ≤ a' + (b'-a')/2 < b' for n ≥ 0).
  -- Define t1(n) = (c(n) - s1.p1.x)/dx1, t2(n) = (c(n) - s2.p1.x)/dx2.
  -- The y-coordinate is s1.p1.y + t1(n) * (s1.p2.y - s1.p1.y).
  let dx1 := s1.p2.x - s1.p1.x
  let dy1 := s1.p2.y - s1.p1.y
  let dx2 := s2.p2.x - s2.p1.x
  let dy2 := s2.p2.y - s2.p1.y
  -- f n : the constructed point.
  let c : ℕ → ℚ := fun n => a' + (b' - a') / ((n : ℚ) + 2)
  let f : ℕ → Vector2D := fun n =>
    ⟨c n, s1.p1.y + ((c n - s1.p1.x) / dx1) * dy1⟩
  -- Key facts:
  have hba_pos : 0 < b' - a' := by linarith
  -- c n ≤ b' always, and c n ≥ a' + (b'-a')/(n+2) > a'.
  have h_c_lt_b : ∀ n : ℕ, c n ≤ b' := by
    intro n
    show a' + (b' - a') / ((n : ℚ) + 2) ≤ b'
    have hpos : (0 : ℚ) < (n : ℚ) + 2 := by positivity
    have h2 : (1 : ℚ) ≤ (n : ℚ) + 2 := by
      have : (0 : ℚ) ≤ (n : ℚ) := by exact_mod_cast Nat.zero_le n
      linarith
    have h_div_le : (b' - a') / ((n : ℚ) + 2) ≤ (b' - a') := by
      rw [div_le_iff₀ hpos]
      have := mul_le_mul_of_nonneg_left h2 (le_of_lt hba_pos)
      linarith
    linarith
  have h_c_ge_a : ∀ n : ℕ, a' < c n := by
    intro n
    show a' < a' + (b' - a') / ((n : ℚ) + 2)
    have hpos : (0 : ℚ) < (n : ℚ) + 2 := by positivity
    have : 0 < (b' - a') / ((n : ℚ) + 2) := div_pos hba_pos hpos
    linarith
  have h_c_in_s1 : ∀ n : ℕ,
      min s1.p1.x s1.p2.x ≤ c n ∧ c n ≤ max s1.p1.x s1.p2.x := by
    intro n
    refine ⟨?_, ?_⟩
    · linarith [h_c_ge_a n, ha'_lo_s1]
    · linarith [h_c_lt_b n, hb'_hi_s1]
  have h_c_in_s2 : ∀ n : ℕ,
      min s2.p1.x s2.p2.x ≤ c n ∧ c n ≤ max s2.p1.x s2.p2.x := by
    intro n
    refine ⟨?_, ?_⟩
    · linarith [h_c_ge_a n, ha'_lo_s2]
    · linarith [h_c_lt_b n, hb'_hi_s2]
  -- t1(n) ∈ [0,1].
  have h_t1_in : ∀ n : ℕ,
      0 ≤ (c n - s1.p1.x) / dx1 ∧ (c n - s1.p1.x) / dx1 ≤ 1 := by
    intro n
    have ⟨hlo, hhi⟩ := h_c_in_s1 n
    rcases lt_or_gt_of_ne hdx1 with hneg | hpos
    · -- dx1 < 0, so s1.p2.x < s1.p1.x. min = p2.x, max = p1.x.
      have hp2_lt : s1.p2.x < s1.p1.x := by show s1.p2.x < s1.p1.x; linarith
      rw [min_eq_right (le_of_lt hp2_lt)] at hlo
      rw [max_eq_left (le_of_lt hp2_lt)] at hhi
      refine ⟨?_, ?_⟩
      · exact div_nonneg_of_nonpos (by linarith) (le_of_lt hneg)
      · rw [div_le_one_of_neg hneg]; show s1.p2.x - s1.p1.x ≤ c n - s1.p1.x; linarith
    · have hp1_lt : s1.p1.x < s1.p2.x := by show s1.p1.x < s1.p2.x; linarith
      rw [min_eq_left (le_of_lt hp1_lt)] at hlo
      rw [max_eq_right (le_of_lt hp1_lt)] at hhi
      refine ⟨?_, ?_⟩
      · exact div_nonneg (by linarith) (le_of_lt hpos)
      · rw [div_le_one hpos]; linarith
  -- t2(n) ∈ [0,1].
  have h_t2_in : ∀ n : ℕ,
      0 ≤ (c n - s2.p1.x) / dx2 ∧ (c n - s2.p1.x) / dx2 ≤ 1 := by
    intro n
    have ⟨hlo, hhi⟩ := h_c_in_s2 n
    rcases lt_or_gt_of_ne hdx2 with hneg | hpos
    · have hp2_lt : s2.p2.x < s2.p1.x := by show s2.p2.x < s2.p1.x; linarith
      rw [min_eq_right (le_of_lt hp2_lt)] at hlo
      rw [max_eq_left (le_of_lt hp2_lt)] at hhi
      refine ⟨?_, ?_⟩
      · exact div_nonneg_of_nonpos (by linarith) (le_of_lt hneg)
      · rw [div_le_one_of_neg hneg]; show s2.p2.x - s2.p1.x ≤ c n - s2.p1.x; linarith
    · have hp1_lt : s2.p1.x < s2.p2.x := by show s2.p1.x < s2.p2.x; linarith
      rw [min_eq_left (le_of_lt hp1_lt)] at hlo
      rw [max_eq_right (le_of_lt hp1_lt)] at hhi
      refine ⟨?_, ?_⟩
      · exact div_nonneg (by linarith) (le_of_lt hpos)
      · rw [div_le_one hpos]; linarith
  -- f n ∈ s1.toSet.
  have h_f_in_s1 : ∀ n : ℕ, f n ∈ s1.toSet := by
    intro n
    refine ⟨(c n - s1.p1.x) / dx1, (h_t1_in n).1, (h_t1_in n).2, ?_, ?_⟩
    · -- (1-t1)*s1.p1.x + t1 * s1.p2.x = c n.
      show c n = (1 - (c n - s1.p1.x) / dx1) * s1.p1.x +
        ((c n - s1.p1.x) / dx1) * s1.p2.x
      have heq : (1 - (c n - s1.p1.x) / dx1) * s1.p1.x +
          ((c n - s1.p1.x) / dx1) * s1.p2.x =
          s1.p1.x + ((c n - s1.p1.x) / dx1) * (s1.p2.x - s1.p1.x) := by ring
      rw [heq]
      show c n = s1.p1.x + ((c n - s1.p1.x) / dx1) * dx1
      rw [div_mul_cancel₀ _ hdx1]; ring
    · show s1.p1.y + (c n - s1.p1.x) / dx1 * dy1 =
        (1 - (c n - s1.p1.x) / dx1) * s1.p1.y +
        ((c n - s1.p1.x) / dx1) * s1.p2.y
      show s1.p1.y + (c n - s1.p1.x) / dx1 * (s1.p2.y - s1.p1.y) =
        (1 - (c n - s1.p1.x) / dx1) * s1.p1.y +
        ((c n - s1.p1.x) / dx1) * s1.p2.y
      ring
  -- f n ∈ s2.toSet.
  have h_f_in_s2 : ∀ n : ℕ, f n ∈ s2.toSet := by
    intro n
    refine ⟨(c n - s2.p1.x) / dx2, (h_t2_in n).1, (h_t2_in n).2, ?_, ?_⟩
    · show c n = (1 - (c n - s2.p1.x) / dx2) * s2.p1.x +
        ((c n - s2.p1.x) / dx2) * s2.p2.x
      have heq : (1 - (c n - s2.p1.x) / dx2) * s2.p1.x +
          ((c n - s2.p1.x) / dx2) * s2.p2.x =
          s2.p1.x + ((c n - s2.p1.x) / dx2) * (s2.p2.x - s2.p1.x) := by ring
      rw [heq]
      show c n = s2.p1.x + ((c n - s2.p1.x) / dx2) * dx2
      rw [div_mul_cancel₀ _ hdx2]; ring
    · -- y-coord: f n .y = s1.p1.y + t1 * dy1.
      show s1.p1.y + (c n - s1.p1.x) / dx1 * dy1 =
        (1 - (c n - s2.p1.x) / dx2) * s2.p1.y +
        ((c n - s2.p1.x) / dx2) * s2.p2.y
      -- Rewrite the goal as an integer-form equation by clearing denominators.
      -- After multiplying by dx1 * dx2, the equation becomes
      -- (s1.p1.y - s2.p1.y) * dx1 * dx2 + (c n - s1.p1.x) * dy1 * dx2
      -- = (c n - s2.p1.x) * dy2 * dx1, which follows from hD and hCross.
      have hdx1dx2 : dx1 * dx2 ≠ 0 := mul_ne_zero hdx1 hdx2
      -- Use linear_combination on a multiplied-out form.
      have hkey : (s1.p1.y + (c n - s1.p1.x) / dx1 * dy1 -
                  ((1 - (c n - s2.p1.x) / dx2) * s2.p1.y +
                  ((c n - s2.p1.x) / dx2) * s2.p2.y)) * (dx1 * dx2) = 0 := by
        have h1 : (c n - s1.p1.x) / dx1 * dx1 = (c n - s1.p1.x) := div_mul_cancel₀ _ hdx1
        have h2 : (c n - s2.p1.x) / dx2 * dx2 = (c n - s2.p1.x) := div_mul_cancel₀ _ hdx2
        have hexp : (s1.p1.y + (c n - s1.p1.x) / dx1 * dy1 -
                  ((1 - (c n - s2.p1.x) / dx2) * s2.p1.y +
                  ((c n - s2.p1.x) / dx2) * s2.p2.y)) * (dx1 * dx2) =
            (s1.p1.y - s2.p1.y) * dx1 * dx2 +
            ((c n - s1.p1.x) / dx1 * dx1) * dy1 * dx2 -
            ((c n - s2.p1.x) / dx2 * dx2) * (s2.p2.y - s2.p1.y) * dx1 := by
          ring
        rw [hexp, h1, h2]
        -- Now: (s1.p1.y - s2.p1.y)*dx1*dx2 + (c n - s1.p1.x)*dy1*dx2
        --      - (c n - s2.p1.x)*(s2.p2.y - s2.p1.y)*dx1 = 0.
        -- This is dx2 * (s1.p1.y - s2.p1.y) * dx1
        --        + (c n - s1.p1.x) * dy1 * dx2
        --        - (c n - s2.p1.x) * dy2 * dx1.
        -- Using hD: dx1 * dy2 = dy1 * dx2 (rewritten as dy2 * dx1 - dy1 * dx2 = 0,
        -- i.e. dx1 * dy2 - dy1 * dx2 = 0). Substitute (c n - s2.p1.x) * dx1 * dy2
        -- = (c n - s2.p1.x) * dy1 * dx2.
        -- The remaining: (s1.p1.y - s2.p1.y)*dx1*dx2 + (c n - s1.p1.x - (c n - s2.p1.x))*dy1*dx2
        --              = (s1.p1.y - s2.p1.y)*dx1*dx2 + (s2.p1.x - s1.p1.x)*dy1*dx2
        --              = dx2 * [(s1.p1.y - s2.p1.y)*dx1 + (s2.p1.x - s1.p1.x)*dy1]
        --              = dx2 * (-hCross) = 0.
        linear_combination
          -(c n - s2.p1.x) * hD + dx2 * hCross
      have h_zero : s1.p1.y + (c n - s1.p1.x) / dx1 * dy1 -
            ((1 - (c n - s2.p1.x) / dx2) * s2.p1.y +
            ((c n - s2.p1.x) / dx2) * s2.p2.y) = 0 := by
        rcases mul_eq_zero.mp hkey with h1 | h1
        · exact h1
        · exact absurd h1 hdx1dx2
      linarith
  -- Injectivity of f via injectivity of c on n.
  have h_c_inj : Function.Injective c := by
    intro n m hnm
    have hba_ne : (b' - a') ≠ 0 := ne_of_gt hba_pos
    have heq : (b' - a') / ((n : ℚ) + 2) = (b' - a') / ((m : ℚ) + 2) := by
      show (b' - a') / ((n : ℚ) + 2) = (b' - a') / ((m : ℚ) + 2)
      have := hnm
      simp only [c] at this
      linarith
    -- (b'-a')/x = (b'-a')/y → x = y when (b'-a') ≠ 0.
    have hn_pos : (0 : ℚ) < (n : ℚ) + 2 := by positivity
    have hm_pos : (0 : ℚ) < (m : ℚ) + 2 := by positivity
    have hn_ne : ((n : ℚ) + 2) ≠ 0 := ne_of_gt hn_pos
    have hm_ne : ((m : ℚ) + 2) ≠ 0 := ne_of_gt hm_pos
    have h_denom_eq : ((n : ℚ) + 2) = ((m : ℚ) + 2) := by
      have h_eq2 := heq
      rw [div_eq_div_iff hn_ne hm_ne] at h_eq2
      have hmul : (b' - a') * (((m : ℚ) + 2) - ((n : ℚ) + 2)) = 0 := by linarith
      rcases mul_eq_zero.mp hmul with h1 | h1
      · exact absurd h1 hba_ne
      · linarith
    have hncast : (n : ℚ) = (m : ℚ) := by linarith
    exact_mod_cast hncast
  have h_f_inj : Function.Injective f := by
    intro n m hnm
    have hxx : c n = c m := by
      have := congrArg Vector2D.x hnm
      simpa [f] using this
    exact h_c_inj hxx
  -- Conclude.
  exact Set.infinite_of_injective_forall_mem h_f_inj
    (fun n => ⟨h_f_in_s1 n, h_f_in_s2 n⟩)

/-- Symmetric helper for the dy1 ≠ 0 branch (when dx1 = 0). -/
private lemma segmentsNoCollinearOverlapBool_complete_of_finite_y
    (s1 s2 : LineSegment)
    (hdx1 : s1.p2.x - s1.p1.x = 0)
    (hdy1 : s1.p2.y - s1.p1.y ≠ 0)
    (hD : (s1.p2.x - s1.p1.x) * (s2.p2.y - s2.p1.y) -
          (s1.p2.y - s1.p1.y) * (s2.p2.x - s2.p1.x) = 0)
    (hCross : (s2.p1.x - s1.p1.x) * (s1.p2.y - s1.p1.y) -
              (s2.p1.y - s1.p1.y) * (s1.p2.x - s1.p1.x) = 0)
    (h_lt : max (min s1.p1.y s1.p2.y) (min s2.p1.y s2.p2.y) <
            min (max s1.p1.y s1.p2.y) (max s2.p1.y s2.p2.y)) :
    (s1.toSet ∩ s2.toSet).Infinite := by
  -- From hdx1 = 0 and hD: -(s1.p2.y - s1.p1.y) * (s2.p2.x - s2.p1.x) = 0,
  -- so dx2 = 0. Then we can project onto y.
  set a' := max (min s1.p1.y s1.p2.y) (min s2.p1.y s2.p2.y) with ha'_def
  set b' := min (max s1.p1.y s1.p2.y) (max s2.p1.y s2.p2.y) with hb'_def
  have ha'_lo_s1 : min s1.p1.y s1.p2.y ≤ a' := le_max_left _ _
  have ha'_lo_s2 : min s2.p1.y s2.p2.y ≤ a' := le_max_right _ _
  have hb'_hi_s1 : b' ≤ max s1.p1.y s1.p2.y := min_le_left _ _
  have hb'_hi_s2 : b' ≤ max s2.p1.y s2.p2.y := min_le_right _ _
  have ha'_hi_s1 : a' ≤ max s1.p1.y s1.p2.y := le_of_lt (lt_of_lt_of_le h_lt hb'_hi_s1)
  have ha'_hi_s2 : a' ≤ max s2.p1.y s2.p2.y := le_of_lt (lt_of_lt_of_le h_lt hb'_hi_s2)
  have hb'_lo_s1 : min s1.p1.y s1.p2.y ≤ b' := le_trans ha'_lo_s1 (le_of_lt h_lt)
  have hb'_lo_s2 : min s2.p1.y s2.p2.y ≤ b' := le_trans ha'_lo_s2 (le_of_lt h_lt)
  have hdy2 : s2.p2.y - s2.p1.y ≠ 0 := by
    intro hdy2eq
    have h_eq_y : s2.p1.y = s2.p2.y := by linarith
    have hmin : min s2.p1.y s2.p2.y = s2.p1.y := by
      rw [h_eq_y]; exact min_self _
    have hmax : max s2.p1.y s2.p2.y = s2.p1.y := by
      rw [h_eq_y]; exact max_self _
    rw [hmax] at hb'_hi_s2
    rw [hmin] at ha'_lo_s2
    linarith
  -- D = 0 and hdx1 = 0 imply dy1 * dx2 = 0. Since dy1 ≠ 0, dx2 = 0.
  have hdx2 : s2.p2.x - s2.p1.x = 0 := by
    have := hD
    have h1 : (s1.p2.y - s1.p1.y) * (s2.p2.x - s2.p1.x) = 0 := by
      have := hD
      rw [hdx1] at this
      linarith
    rcases mul_eq_zero.mp h1 with h2 | h2
    · exact absurd h2 hdy1
    · exact h2
  -- And: cross = (s2.p1.x - s1.p1.x) * dy1 = 0 (since dx1 = 0). So s2.p1.x = s1.p1.x.
  have hsame_x : s2.p1.x = s1.p1.x := by
    have := hCross
    rw [hdx1] at this
    have h1 : (s2.p1.x - s1.p1.x) * (s1.p2.y - s1.p1.y) = 0 := by linarith
    rcases mul_eq_zero.mp h1 with h2 | h2
    · linarith
    · exact absurd h2 hdy1
  let dy1 := s1.p2.y - s1.p1.y
  let dy2 := s2.p2.y - s2.p1.y
  let c : ℕ → ℚ := fun n => a' + (b' - a') / ((n : ℚ) + 2)
  -- f n: x = s1.p1.x (since both s1 and s2 are vertical lines through s1.p1.x), y = c n.
  let f : ℕ → Vector2D := fun n => ⟨s1.p1.x, c n⟩
  have hba_pos : 0 < b' - a' := by linarith
  have h_c_lt_b : ∀ n : ℕ, c n ≤ b' := by
    intro n
    have hpos : (0 : ℚ) < (n : ℚ) + 2 := by positivity
    have h2 : (1 : ℚ) ≤ (n : ℚ) + 2 := by
      have : (0 : ℚ) ≤ (n : ℚ) := by exact_mod_cast Nat.zero_le n
      linarith
    have h_div_le : (b' - a') / ((n : ℚ) + 2) ≤ (b' - a') := by
      rw [div_le_iff₀ hpos]
      have := mul_le_mul_of_nonneg_left h2 (le_of_lt hba_pos)
      linarith
    show a' + (b' - a') / ((n : ℚ) + 2) ≤ b'
    linarith
  have h_c_ge_a : ∀ n : ℕ, a' < c n := by
    intro n
    have hpos : (0 : ℚ) < (n : ℚ) + 2 := by positivity
    have : 0 < (b' - a') / ((n : ℚ) + 2) := div_pos hba_pos hpos
    show a' < a' + (b' - a') / ((n : ℚ) + 2); linarith
  have h_c_in_s1 : ∀ n : ℕ,
      min s1.p1.y s1.p2.y ≤ c n ∧ c n ≤ max s1.p1.y s1.p2.y := by
    intro n
    refine ⟨?_, ?_⟩
    · linarith [h_c_ge_a n, ha'_lo_s1]
    · linarith [h_c_lt_b n, hb'_hi_s1]
  have h_c_in_s2 : ∀ n : ℕ,
      min s2.p1.y s2.p2.y ≤ c n ∧ c n ≤ max s2.p1.y s2.p2.y := by
    intro n
    refine ⟨?_, ?_⟩
    · linarith [h_c_ge_a n, ha'_lo_s2]
    · linarith [h_c_lt_b n, hb'_hi_s2]
  have h_t1_in : ∀ n : ℕ,
      0 ≤ (c n - s1.p1.y) / dy1 ∧ (c n - s1.p1.y) / dy1 ≤ 1 := by
    intro n
    have ⟨hlo, hhi⟩ := h_c_in_s1 n
    rcases lt_or_gt_of_ne hdy1 with hneg | hpos
    · have hp2_lt : s1.p2.y < s1.p1.y := by show s1.p2.y < s1.p1.y; linarith
      rw [min_eq_right (le_of_lt hp2_lt)] at hlo
      rw [max_eq_left (le_of_lt hp2_lt)] at hhi
      refine ⟨?_, ?_⟩
      · exact div_nonneg_of_nonpos (by linarith) (le_of_lt hneg)
      · rw [div_le_one_of_neg hneg]; show s1.p2.y - s1.p1.y ≤ c n - s1.p1.y; linarith
    · have hp1_lt : s1.p1.y < s1.p2.y := by show s1.p1.y < s1.p2.y; linarith
      rw [min_eq_left (le_of_lt hp1_lt)] at hlo
      rw [max_eq_right (le_of_lt hp1_lt)] at hhi
      refine ⟨?_, ?_⟩
      · exact div_nonneg (by linarith) (le_of_lt hpos)
      · rw [div_le_one hpos]; linarith
  have h_t2_in : ∀ n : ℕ,
      0 ≤ (c n - s2.p1.y) / dy2 ∧ (c n - s2.p1.y) / dy2 ≤ 1 := by
    intro n
    have ⟨hlo, hhi⟩ := h_c_in_s2 n
    rcases lt_or_gt_of_ne hdy2 with hneg | hpos
    · have hp2_lt : s2.p2.y < s2.p1.y := by show s2.p2.y < s2.p1.y; linarith
      rw [min_eq_right (le_of_lt hp2_lt)] at hlo
      rw [max_eq_left (le_of_lt hp2_lt)] at hhi
      refine ⟨?_, ?_⟩
      · exact div_nonneg_of_nonpos (by linarith) (le_of_lt hneg)
      · rw [div_le_one_of_neg hneg]; show s2.p2.y - s2.p1.y ≤ c n - s2.p1.y; linarith
    · have hp1_lt : s2.p1.y < s2.p2.y := by show s2.p1.y < s2.p2.y; linarith
      rw [min_eq_left (le_of_lt hp1_lt)] at hlo
      rw [max_eq_right (le_of_lt hp1_lt)] at hhi
      refine ⟨?_, ?_⟩
      · exact div_nonneg (by linarith) (le_of_lt hpos)
      · rw [div_le_one hpos]; linarith
  have h_f_in_s1 : ∀ n : ℕ, f n ∈ s1.toSet := by
    intro n
    refine ⟨(c n - s1.p1.y) / dy1, (h_t1_in n).1, (h_t1_in n).2, ?_, ?_⟩
    · -- x of f n = s1.p1.x; need (1-t)*s1.p1.x + t*s1.p2.x = s1.p1.x. Use hdx1: p1.x = p2.x.
      show s1.p1.x = (1 - (c n - s1.p1.y) / dy1) * s1.p1.x +
        (c n - s1.p1.y) / dy1 * s1.p2.x
      have hxe : s1.p1.x = s1.p2.x := by linarith
      rw [← hxe]; ring
    · show c n = (1 - (c n - s1.p1.y) / dy1) * s1.p1.y +
        (c n - s1.p1.y) / dy1 * s1.p2.y
      have heq : (1 - (c n - s1.p1.y) / dy1) * s1.p1.y +
          ((c n - s1.p1.y) / dy1) * s1.p2.y =
          s1.p1.y + ((c n - s1.p1.y) / dy1) * (s1.p2.y - s1.p1.y) := by ring
      rw [heq]
      show c n = s1.p1.y + ((c n - s1.p1.y) / dy1) * dy1
      rw [div_mul_cancel₀ _ hdy1]; ring
  have h_f_in_s2 : ∀ n : ℕ, f n ∈ s2.toSet := by
    intro n
    refine ⟨(c n - s2.p1.y) / dy2, (h_t2_in n).1, (h_t2_in n).2, ?_, ?_⟩
    · -- x of f n = s1.p1.x = s2.p1.x = s2.p2.x. Need (1-t)*s2.p1.x + t*s2.p2.x = s1.p1.x.
      show s1.p1.x = (1 - (c n - s2.p1.y) / dy2) * s2.p1.x +
        (c n - s2.p1.y) / dy2 * s2.p2.x
      have hxe2 : s2.p1.x = s2.p2.x := by linarith
      rw [← hsame_x, ← hxe2]; ring
    · show c n = (1 - (c n - s2.p1.y) / dy2) * s2.p1.y +
        (c n - s2.p1.y) / dy2 * s2.p2.y
      have heq : (1 - (c n - s2.p1.y) / dy2) * s2.p1.y +
          ((c n - s2.p1.y) / dy2) * s2.p2.y =
          s2.p1.y + ((c n - s2.p1.y) / dy2) * (s2.p2.y - s2.p1.y) := by ring
      rw [heq]
      show c n = s2.p1.y + ((c n - s2.p1.y) / dy2) * dy2
      rw [div_mul_cancel₀ _ hdy2]; ring
  have h_c_inj : Function.Injective c := by
    intro n m hnm
    have hba_ne : (b' - a') ≠ 0 := ne_of_gt hba_pos
    have heq : (b' - a') / ((n : ℚ) + 2) = (b' - a') / ((m : ℚ) + 2) := by
      show (b' - a') / ((n : ℚ) + 2) = (b' - a') / ((m : ℚ) + 2)
      have := hnm
      simp only [c] at this
      linarith
    have hn_pos : (0 : ℚ) < (n : ℚ) + 2 := by positivity
    have hm_pos : (0 : ℚ) < (m : ℚ) + 2 := by positivity
    have hn_ne : ((n : ℚ) + 2) ≠ 0 := ne_of_gt hn_pos
    have hm_ne : ((m : ℚ) + 2) ≠ 0 := ne_of_gt hm_pos
    have h_denom_eq : ((n : ℚ) + 2) = ((m : ℚ) + 2) := by
      -- Multiply both sides by ((n+2)*(m+2)) and simplify.
      have := heq
      rw [div_eq_div_iff hn_ne hm_ne] at this
      have hmul : (b' - a') * (((m : ℚ) + 2) - ((n : ℚ) + 2)) = 0 := by linarith
      rcases mul_eq_zero.mp hmul with h1 | h1
      · exact absurd h1 hba_ne
      · linarith
    have hncast : (n : ℚ) = (m : ℚ) := by linarith
    exact_mod_cast hncast
  have h_f_inj : Function.Injective f := by
    intro n m hnm
    have hxx : c n = c m := by
      have := congrArg Vector2D.y hnm
      simpa [f] using this
    exact h_c_inj hxx
  exact Set.infinite_of_injective_forall_mem h_f_inj
    (fun n => ⟨h_f_in_s1 n, h_f_in_s2 n⟩)

/-- Per-pair completeness: if the per-pair intersection is finite and `s1`
    is non-degenerate, the boolean check returns `true`. -/
private lemma segmentsNoCollinearOverlapBool_complete_of_finite
    (s1 s2 : LineSegment) (h_nondeg : s1.p1 ≠ s1.p2)
    (h_finite : (s1.toSet ∩ s2.toSet).Finite) :
    segmentsNoCollinearOverlapBool s1 s2 = true := by
  unfold segmentsNoCollinearOverlapBool
  simp only
  split_ifs with hD hCross
  · rfl
  · rfl
  · push_neg at hD hCross
    unfold collinearFiniteOverlapBool
    split_ifs with hdx1
    · -- dx1 ≠ 0 branch.
      by_contra hfalse
      simp only [decide_eq_true_eq, not_le] at hfalse
      have h_inf := segmentsNoCollinearOverlapBool_complete_of_finite_x
        s1 s2 hdx1 hD hCross hfalse
      exact h_inf h_finite
    · -- dx1 = 0 branch. So s1.p2.x = s1.p1.x. Since s1 is non-degenerate, s1.p2.y ≠ s1.p1.y.
      push_neg at hdx1
      have hdy1 : s1.p2.y - s1.p1.y ≠ 0 := by
        intro hdy1eq
        apply h_nondeg
        apply Vector2D.ext
        · linarith
        · linarith
      by_contra hfalse
      simp only [decide_eq_true_eq, not_le] at hfalse
      have h_inf := segmentsNoCollinearOverlapBool_complete_of_finite_y
        s1 s2 hdx1 hdy1 hD hCross hfalse
      exact h_inf h_finite

/-- Polygon-level completeness: if the boundary intersection is finite and
    every segment of `m1` is non-degenerate, then `finitePreconditionBool`
    returns `true`. -/
private lemma finitePreconditionBool_complete_of_finite
    (m1 m2 : Multipolygon)
    (h1_nondeg : ∀ seg ∈ m1.segments, seg.p1 ≠ seg.p2)
    (h_fin : Set.Finite (m1.toBoundarySet ∩ m2.toBoundarySet)) :
    finitePreconditionBool m1 m2 = true := by
  unfold finitePreconditionBool
  rw [List.all_eq_true]
  intro s1 hs1
  rw [List.all_eq_true]
  intro s2 hs2
  apply segmentsNoCollinearOverlapBool_complete_of_finite s1 s2 (h1_nondeg s1 hs1)
  -- s1.toSet ∩ s2.toSet ⊆ m1.toBoundarySet ∩ m2.toBoundarySet.
  apply h_fin.subset
  intro p hp
  refine ⟨⟨s1, hs1, hp.1⟩, ⟨s2, hs2, hp.2⟩⟩

/-- Completeness: whenever the mathematical preconditions of
    `multipolygonIntersectionAlgorithm_interior_eq` hold, the wrapper returns
    `some result` with the same interior-equation conclusion. -/
theorem multipolygonIntersectionAlgorithmWithPreconditionCheck_complete
    (m1 m2 : Multipolygon)
    (h1_len : ∀ poly ∈ m1.polygons, poly.vertices.length ≥ 2)
    (h2_len : ∀ poly ∈ m2.polygons, poly.vertices.length ≥ 2)
    (h1_nondeg : ∀ seg ∈ m1.segments, seg.p1 ≠ seg.p2)
    (h2_nondeg : ∀ seg ∈ m2.segments, seg.p1 ≠ seg.p2) :
    ∃ result : Multipolygon,
      multipolygonIntersectionAlgorithmWithPreconditionCheck m1 m2 = some result ∧
      m1.interior ∩ m2.interior = result.interior := by
  have h_basic : basicPreconditionsBool m1 m2 = true :=
    (basicPreconditionsBool_iff m1 m2).mpr ⟨h1_len, h2_len, h1_nondeg, h2_nondeg⟩
  have h_all : allPreconditionsBool m1 m2 = true := by
    unfold allPreconditionsBool
    exact h_basic
  refine ⟨multipolygonIntersectionAlgorithm m1 m2, ?_, ?_⟩
  · unfold multipolygonIntersectionAlgorithmWithPreconditionCheck
    rw [if_pos h_all]
    rfl
  · exact multipolygonIntersectionAlgorithm_interior_eq m1 m2
      h1_len h2_len h1_nondeg h2_nondeg

/-- Main soundness theorem: when the wrapper returns `some result`, the
    `multipolygonIntersectionAlgorithm_interior_eq` conclusion holds for
    `result`. -/
theorem multipolygonIntersectionAlgorithmWithPreconditionCheck_correct
    (m1 m2 : Multipolygon) (result : Multipolygon)
    (h : multipolygonIntersectionAlgorithmWithPreconditionCheck m1 m2 = some result) :
    m1.interior ∩ m2.interior = result.interior := by
  unfold multipolygonIntersectionAlgorithmWithPreconditionCheck at h
  by_cases hpre : allPreconditionsBool m1 m2 = true
  · rw [if_pos hpre] at h
    have h_result : result = multipolygonIntersectionAlgorithm m1 m2 :=
      (Option.some.inj h).symm
    have ⟨h1_len, h2_len, h1_nondeg, h2_nondeg⟩ :=
      (basicPreconditionsBool_iff m1 m2).mp
        (by unfold allPreconditionsBool at hpre; exact hpre)
    rw [h_result]
    exact multipolygonIntersectionAlgorithm_interior_eq m1 m2
      h1_len h2_len h1_nondeg h2_nondeg
  · rw [if_neg hpre] at h
    cases h

end MultipolygonIntersectionAlgorithmWithPreconditionCheckProofs
