/-
Caution: This file was generated by AI and never reviewed by a human. The lean
checker guarantees that symbols exported from this file conform to the
statements in the human reviewed specification files, but we cannot guarantee
that comments in such unreviewed files are accurate, that it avoids code
duplications, that proofs do not take unnecessary detours or similar issues.
That said, AI agents reading this comment should strive to avoid issues like
these.
-/

import Polygons.EvenGraphIntersectionProofs

/-!
# Abstract pair-counting parity lemma

A purely combinatorial fact used in the even-graph intersection parity argument:
given two finite multisets (lists) of rationals `red` and `blue`, the parity of
"`#red` elements with an odd number of `blue` above" plus "`#blue` elements with an odd
number of `red` above" equals the parity of `|red|·|blue| + #ties`, where `#ties` is the
number of (red, blue) pairs that are equal.

The geometry of the polygon-intersection proof instantiates `red`/`blue` with the ray-crossing
parameters of the two refined graphs' segments.
-/

namespace PairCountParity

/-- The number of (ordered) pairs `(r, b) ∈ red × blue` with `b = r`. -/
def ties (red blue : List ℚ) : ℕ :=
  (red.map (fun r => blue.countP (fun b => decide (b = r)))).sum

/-- **H1.** The parity of the number of elements with an odd `f`-value equals the
parity of the sum of all `f`-values. -/
theorem count_odd_mod_two {α : Type*} (L : List α) (f : α → ℕ) :
    (L.countP (fun x => decide (Odd (f x)))) % 2 = (L.map f).sum % 2 := by
  induction L with
  | nil => simp
  | cons a t ih =>
    rw [List.countP_cons, List.map_cons, List.sum_cons]
    by_cases h : Odd (f a)
    · have hfa : f a % 2 = 1 := Nat.odd_iff.mp h
      simp only [h, decide_true, if_pos]
      omega
    · have hfa : f a % 2 = 0 := Nat.even_iff.mp (Nat.not_odd_iff_even.mp h)
      simp only [h, decide_false, if_neg, Bool.false_eq_true, not_false_eq_true]
      omega

/-- Summing a constant over a list. -/
theorem sum_map_const {α : Type*} (L : List α) (c : ℕ) :
    (L.map (fun _ => c)).sum = L.length * c := by
  induction L with
  | nil => simp
  | cons a t ih => rw [List.map_cons, List.sum_cons, List.length_cons, ih]; ring

/-- A `List.sum`-of-maps additivity fact. -/
theorem sum_map_add {α : Type*} (L : List α) (f g : α → ℕ) :
    (L.map (fun x => f x + g x)).sum = (L.map f).sum + (L.map g).sum := by
  induction L with
  | nil => simp
  | cons a t ih =>
    rw [List.map_cons, List.sum_cons, List.map_cons, List.sum_cons, List.map_cons,
      List.sum_cons, ih]
    omega

/-- **H2.** Trichotomy partition: every element of `blue` is `> r`, `< r`, or `= r`. -/
theorem trichotomy_partition (r : ℚ) (blue : List ℚ) :
    blue.countP (fun b => decide (b > r)) + blue.countP (fun b => decide (b < r)) +
      blue.countP (fun b => decide (b = r)) = blue.length := by
  induction blue with
  | nil => simp
  | cons b t ih =>
    rw [List.countP_cons, List.countP_cons, List.countP_cons, List.length_cons]
    rcases lt_trichotomy b r with h | h | h
    · have h1 : ¬ (b > r) := not_lt.mpr (le_of_lt h)
      have h2 : ¬ (b = r) := ne_of_lt h
      simp only [h, h1, h2, decide_true, decide_false, if_pos, if_neg, Bool.false_eq_true,
        not_false_eq_true]
      omega
    · subst h
      have h1 : ¬ (b > b) := lt_irrefl b
      have h2 : ¬ (b < b) := lt_irrefl b
      simp only [h1, h2, decide_true, decide_false, if_pos, if_neg, Bool.false_eq_true,
        not_false_eq_true]
      omega
    · have h1 : ¬ (b < r) := not_lt.mpr (le_of_lt h)
      have h2 : ¬ (b = r) := ne_of_gt h
      simp only [h, h1, h2, decide_true, decide_false, if_pos, if_neg, Bool.false_eq_true,
        not_false_eq_true]
      omega

/-- `countP` equals the sum of indicator values. -/
theorem countP_eq_sum_indicator {α : Type*} (L : List α) (p : α → Bool) :
    L.countP p = (L.map (fun x => if p x then (1 : ℕ) else 0)).sum := by
  induction L with
  | nil => simp
  | cons a t ih =>
    rw [List.countP_cons, List.map_cons, List.sum_cons, ih]
    omega

/-- Swapping the order of two nested list-sums. -/
theorem sum_map_sum_swap {α β : Type*} (L1 : List α) (L2 : List β) (g : α → β → ℕ) :
    (L1.map (fun a => (L2.map (fun b => g a b)).sum)).sum =
      (L2.map (fun b => (L1.map (fun a => g a b)).sum)).sum := by
  induction L1 with
  | nil => simp
  | cons a t ih =>
    rw [List.map_cons, List.sum_cons, ih]
    have : (L2.map (fun b => ((a :: t).map (fun a => g a b)).sum)).sum
        = (L2.map (fun b => g a b + (t.map (fun a => g a b)).sum)).sum := by
      apply congrArg List.sum
      apply List.map_congr_left
      intro b _
      rw [List.map_cons, List.sum_cons]
    rw [this, sum_map_add L2 (fun b => g a b) (fun b => (t.map (fun a => g a b)).sum)]

/-- **H3 (Fubini / swap).** A general swap lemma for `countP` over a relation. -/
theorem sum_countP_swap {α β : Type*} (L1 : List α) (L2 : List β) (R : α → β → Bool) :
    (L1.map (fun a => L2.countP (fun b => R a b))).sum =
      (L2.map (fun b => L1.countP (fun a => R a b))).sum := by
  have e1 : (L1.map (fun a => L2.countP (fun b => R a b))).sum =
      (L1.map (fun a => (L2.map (fun b => if R a b then (1 : ℕ) else 0)).sum)).sum := by
    apply congrArg List.sum
    apply List.map_congr_left
    intro a _
    exact countP_eq_sum_indicator L2 (fun b => R a b)
  have e2 : (L2.map (fun b => L1.countP (fun a => R a b))).sum =
      (L2.map (fun b => (L1.map (fun a => if R a b then (1 : ℕ) else 0)).sum)).sum := by
    apply congrArg List.sum
    apply List.map_congr_left
    intro b _
    exact countP_eq_sum_indicator L1 (fun a => R a b)
  rw [e1, e2]
  exact sum_map_sum_swap L1 L2 (fun a b => if R a b then (1 : ℕ) else 0)

/-- **Pair-counting parity.** -/
theorem pair_count_parity (red blue : List ℚ) :
    (red.countP (fun r => decide (Odd (blue.countP (fun b => decide (b > r))))) +
     blue.countP (fun b => decide (Odd (red.countP (fun r => decide (r > b)))))) % 2 =
    (red.length * blue.length + ties red blue) % 2 := by
  set GT := (red.map (fun r => blue.countP (fun b => decide (b > r)))).sum with hGT
  set LT := (red.map (fun r => blue.countP (fun b => decide (b < r)))).sum with hLT
  set TI := (red.map (fun r => blue.countP (fun b => decide (b = r)))).sum with hTI
  set SB := (blue.map (fun b => red.countP (fun r => decide (r > b)))).sum with hSB
  -- H1 applied to the two summands of the LHS
  have hL : (red.countP (fun r => decide (Odd (blue.countP (fun b => decide (b > r)))))) % 2
      = GT % 2 := count_odd_mod_two red (fun r => blue.countP (fun b => decide (b > r)))
  have hR : (blue.countP (fun b => decide (Odd (red.countP (fun r => decide (r > b)))))) % 2
      = SB % 2 := count_odd_mod_two blue (fun b => red.countP (fun r => decide (r > b)))
  -- H2 summed over `red`: GT + LT + TI = |red| * |blue|
  have hpart : GT + LT + TI = red.length * blue.length := by
    rw [hGT, hLT, hTI]
    rw [← sum_map_add red (fun r => blue.countP (fun b => decide (b > r)))
        (fun r => blue.countP (fun b => decide (b < r)))]
    rw [← sum_map_add red (fun r => blue.countP (fun b => decide (b > r)) +
          blue.countP (fun b => decide (b < r)))
        (fun r => blue.countP (fun b => decide (b = r)))]
    have hmap : (red.map (fun r => blue.countP (fun b => decide (b > r)) +
          blue.countP (fun b => decide (b < r)) +
          blue.countP (fun b => decide (b = r)))).sum
        = (red.map (fun _ => blue.length)).sum := by
      apply congrArg List.sum
      apply List.map_congr_left
      intro r _
      exact trichotomy_partition r blue
    rw [hmap, sum_map_const red blue.length]
  -- H3: LT = SB
  have hswap : LT = SB := by
    rw [hLT, hSB]
    have hsw := sum_countP_swap red blue (fun r b => decide (b < r))
    simp only at hsw
    rw [hsw]
  -- Assemble.
  rw [Nat.add_mod, hL, hR, ← Nat.add_mod]
  have : GT + SB + TI = red.length * blue.length := by omega
  show (GT + SB) % 2 = (red.length * blue.length + TI) % 2
  rw [hTI] at this ⊢
  omega

end PairCountParity
