/-
Caution: This file was generated by AI and never reviewed by a human. The lean
checker guarantees that symbols exported from this file conform to the
statements in the human reviewed specification files, but we cannot guarantee
that comments in such unreviewed files are accurate, that it avoids code
duplications, that proofs do not take unnecessary detours or similar issues.
That said, AI agents reading this comment should strive to avoid issues like
these.
-/

import Polygons.Polygon
import Mathlib.Tactic.FieldSimp

open Set

open Classical

noncomputable section

namespace PolygonIntersectionHelpersProofs

/-\! ### Helper: Insert vertex into a polygon edge -/

/-- Recursively insert `pt` between the edge `(p1, p2)` in a cyclic vertex list.
    `first` is the first vertex of the polygon (for the closing edge). -/
private def insertInEdge (p1 p2 pt first : Vector2D) : List Vector2D → List Vector2D
  | [] => []
  | [v] => if v = p1 ∧ first = p2 then [v, pt] else [v]
  | v :: w :: vs =>
    if v = p1 ∧ w = p2 then v :: pt :: w :: vs
    else v :: insertInEdge p1 p2 pt first (w :: vs)

/-- Given a polygon, a segment (edge) of that polygon, and a point on the segment,
    return the polygon with the point inserted as a new vertex in that segment. -/
def polygonRefinement
    (poly : Polygon) (seg : LineSegment) (pt : Vector2D) : Polygon :=
  match poly.vertices with
  | [] => poly
  | [_] => poly
  | v :: w :: vs => ⟨insertInEdge seg.p1 seg.p2 pt v (v :: w :: vs)⟩

/-\! ### Segment splitting lemma -/

private theorem segment_split (a b pt : Vector2D)
    (h_pt : pt ∈ (LineSegment.mk a b).toSet) :
    (LineSegment.mk a pt).toSet ∪ (LineSegment.mk pt b).toSet =
    (LineSegment.mk a b).toSet := by
  obtain ⟨s, hs0, hs1, hsx, hsy⟩ := h_pt
  ext p; simp only [LineSegment.toSet, Set.mem_setOf_eq, Set.mem_union]
  constructor
  · rintro (⟨u, hu0, hu1, hux, huy⟩ | ⟨u, hu0, hu1, hux, huy⟩)
    · exact ⟨u * s, mul_nonneg hu0 hs0, by nlinarith,
            by rw [hux, hsx]; ring, by rw [huy, hsy]; ring⟩
    · exact ⟨s + u * (1 - s), by nlinarith, by nlinarith,
            by rw [hux, hsx]; ring, by rw [huy, hsy]; ring⟩
  · intro ⟨t, ht0, ht1, htx, hty⟩
    by_cases hts : t ≤ s
    · by_cases hs_zero : s = 0
      · have ht_zero : t = 0 := le_antisymm (hs_zero ▸ hts) ht0
        left
        exact ⟨0, le_refl 0, zero_le_one, by simp [htx, ht_zero], by simp [hty, ht_zero]⟩
      · left
        have hs_pos : (0 : ℚ) < s := lt_of_le_of_ne hs0 (Ne.symm hs_zero)
        exact ⟨t / s, div_nonneg ht0 (le_of_lt hs_pos),
               div_le_one_of_le₀ hts (le_of_lt hs_pos),
               by rw [htx, hsx]; field_simp; ring,
               by rw [hty, hsy]; field_simp; ring⟩
    · push_neg at hts
      by_cases hs1' : s = 1
      · linarith
      · right
        have h1s_pos : (0 : ℚ) < 1 - s := by linarith [lt_of_le_of_ne hs1 hs1']
        exact ⟨(t - s) / (1 - s),
               div_nonneg (le_of_lt (sub_pos.mpr hts)) (le_of_lt h1s_pos),
               div_le_one_of_le₀ (by linarith) (le_of_lt h1s_pos),
               by rw [htx, hsx]; field_simp; ring,
               by rw [hty, hsy]; field_simp; ring⟩

/-\! ### Cyclic boundary: recursive formulation of polygon boundary -/

/-- Boundary of a cyclic vertex list: union of segment sets for consecutive pairs,
    with closing edge from last vertex to `first`. -/
private def cyclicBoundary (first : Vector2D) : List Vector2D → Set Vector2D
  | [] => ∅
  | [v] => (LineSegment.mk v first).toSet
  | v :: w :: vs => (LineSegment.mk v w).toSet ∪ cyclicBoundary first (w :: vs)

/-- Membership in the boundary (via zip/map) iff membership in cyclicBoundary. -/
private lemma mem_boundary_iff (first v : Vector2D) (vs : List Vector2D) (p : Vector2D) :
    (∃ seg ∈ (List.zip (v :: vs) (vs ++ [first])).map (fun (a, b) => LineSegment.mk a b),
      p ∈ seg.toSet) ↔ p ∈ cyclicBoundary first (v :: vs) := by
  induction vs generalizing v with
  | nil => simp [List.zip, List.map, cyclicBoundary]
  | cons w rest ih =>
    simp only [List.cons_append, List.zip_cons_cons, List.map_cons, List.mem_cons,
               cyclicBoundary, Set.mem_union]
    exact ⟨fun ⟨seg, h, hp⟩ =>
             h.elim (fun h => Or.inl (h ▸ hp)) (fun h => Or.inr ((ih w).mp ⟨seg, h, hp⟩)),
           fun h => h.elim (fun hp => ⟨⟨v, w⟩, Or.inl rfl, hp⟩)
                    (fun hp => let ⟨seg, hm, hp'⟩ := (ih w).mpr hp; ⟨seg, Or.inr hm, hp'⟩)⟩

/-- Polygon.toBoundarySet equals cyclicBoundary for polygons with ≥ 2 vertices. -/
private lemma toBoundarySet_eq_cyclicBoundary (v w : Vector2D) (vs : List Vector2D) :
    (Polygon.mk (v :: w :: vs)).toBoundarySet = cyclicBoundary v (v :: w :: vs) := by
  ext p; simp only [Polygon.toBoundarySet, Polygon.segments, Set.mem_setOf_eq]
  exact mem_boundary_iff v v (w :: vs) p

/-\! ### Structural lemmas for insertInEdge -/

/-- The first element of insertInEdge on a nonempty list is preserved. -/
private lemma insertInEdge_cons (p1 p2 pt first v : Vector2D) (vs : List Vector2D) :
    ∃ tail, insertInEdge p1 p2 pt first (v :: vs) = v :: tail := by
  cases vs with
  | nil => simp [insertInEdge]; split <;> exact ⟨_, rfl⟩
  | cons w rest => simp [insertInEdge]; split <;> exact ⟨_, rfl⟩

/-- insertInEdge on a list of ≥ 2 elements produces a list of ≥ 2 elements
    starting with the same first element. -/
private lemma insertInEdge_form (p1 p2 pt first v w : Vector2D) (vs : List Vector2D) :
    ∃ w' vs', insertInEdge p1 p2 pt first (v :: w :: vs) = v :: w' :: vs' := by
  unfold insertInEdge; split
  · exact ⟨pt, w :: vs, rfl⟩
  · cases vs with
    | nil =>
      simp only [insertInEdge]; split
      · exact ⟨w, [pt], rfl⟩
      · exact ⟨w, [], rfl⟩
    | cons x rest =>
      simp only [insertInEdge]; split
      · exact ⟨w, pt :: x :: rest, rfl⟩
      · cases rest with
        | nil =>
          simp only [insertInEdge]; split
          · exact ⟨w, x :: [pt], rfl⟩
          · exact ⟨w, [x], rfl⟩
        | cons y rest' =>
          exact ⟨w, insertInEdge p1 p2 pt first (x :: y :: rest'), rfl⟩

/-\! ### Key preservation lemma -/

/-- insertInEdge preserves the cyclicBoundary when the inserted point lies on the edge. -/
private lemma insertInEdge_preserves (p1 p2 pt first : Vector2D)
    (h_pt : pt ∈ (LineSegment.mk p1 p2).toSet)
    (v : Vector2D) (vs : List Vector2D) :
    cyclicBoundary first (insertInEdge p1 p2 pt first (v :: vs)) =
    cyclicBoundary first (v :: vs) := by
  induction vs generalizing v with
  | nil =>
    simp only [insertInEdge]; split
    · rename_i h; obtain ⟨hv, hf⟩ := h; subst hv; subst hf
      simp only [cyclicBoundary]; exact segment_split _ _ pt h_pt
    · rfl
  | cons w rest ih =>
    simp only [insertInEdge]; split
    · rename_i h; obtain ⟨hv, hw⟩ := h; subst hv; subst hw
      simp only [cyclicBoundary]; rw [← Set.union_assoc, segment_split _ _ pt h_pt]
    · show cyclicBoundary first (v :: insertInEdge p1 p2 pt first (w :: rest)) =
           cyclicBoundary first (v :: w :: rest)
      obtain ⟨tail, htail⟩ := insertInEdge_cons p1 p2 pt first w rest
      rw [htail]; simp only [cyclicBoundary]; congr 1; rw [← htail]; exact ih w

/-\! ### Main theorems -/

/-- The boundary of the refined polygon equals the boundary of the original polygon. -/
theorem refinement_boundary_eq
    (poly : Polygon) (seg : LineSegment) (pt : Vector2D)
    (h_seg : seg ∈ poly.segments) (h_pt : pt ∈ seg.toSet) :
    (polygonRefinement poly seg pt).toBoundarySet =
    poly.toBoundarySet := by
  obtain ⟨vertices⟩ := poly
  match vertices with
  | [] => simp [Polygon.segments] at h_seg
  | [_] => simp [Polygon.segments] at h_seg
  | v :: w :: vs =>
    show (Polygon.mk (insertInEdge seg.p1 seg.p2 pt v (v :: w :: vs))).toBoundarySet =
         (Polygon.mk (v :: w :: vs)).toBoundarySet
    obtain ⟨w', vs', hform⟩ := insertInEdge_form seg.p1 seg.p2 pt v v w vs
    rw [hform, toBoundarySet_eq_cyclicBoundary v w' vs',
        toBoundarySet_eq_cyclicBoundary v w vs]
    conv_lhs => rw [← hform]
    exact insertInEdge_preserves seg.p1 seg.p2 pt v h_pt v (w :: vs)

/-\! ### Cyclic count: recursive formulation of crossing number -/

/-- Count of segments crossed by a ray, in cyclic form mirroring `cyclicBoundary`. -/
private def cyclicCount (r : Ray) (first : Vector2D) : List Vector2D → ℕ
  | [] => 0
  | [v] => if decide (rayIntersectsSegment r ⟨v, first⟩) then 1 else 0
  | v :: w :: vs =>
    (if decide (rayIntersectsSegment r ⟨v, w⟩) then 1 else 0) + cyclicCount r first (w :: vs)

/-- countP of zip equals cyclicCount for any closing vertex. -/
private lemma countP_zip_eq_cyclicCount (r : Ray) (first v : Vector2D) (vs : List Vector2D) :
    (((v :: vs).zip (vs ++ [first])).map fun (a, b) => (⟨a, b⟩ : LineSegment)).countP
      (fun seg => decide (rayIntersectsSegment r seg)) =
    cyclicCount r first (v :: vs) := by
  induction vs generalizing v with
  | nil =>
    simp only [List.zip_cons_cons, List.nil_append, List.zip_nil_right,
               List.map_cons, List.map_nil, List.countP_cons,
               List.countP_nil, cyclicCount]
    split <;> simp
  | cons w rest ih =>
    simp only [List.cons_append, List.zip_cons_cons, List.map_cons, List.countP_cons, cyclicCount,
               ih w, Nat.add_comm]

/-- `intersectionRayPolygonSegmentsNumber` equals `cyclicCount` for ≥ 2 vertices. -/
private lemma count_eq_cyclicCount (r : Ray) (v w : Vector2D) (vs : List Vector2D) :
    intersectionRayPolygonSegmentsNumber r ⟨v :: w :: vs⟩ = cyclicCount r v (v :: w :: vs) := by
  unfold intersectionRayPolygonSegmentsNumber Polygon.segments
  exact countP_zip_eq_cyclicCount r v v (w :: vs)

/-\! ### Sub-segment intersection lemmas -/

/-- If q1 ∈ r ∩ seg(a,pt) and q2 ∈ r ∩ seg(pt,b) where pt ∈ seg(a,b) and pt ∉ r,
    then we get a contradiction: pt would be on the ray. -/
private lemma ray_not_both_sub_segments (r : Ray) (a b pt : Vector2D)
    (h_pt : pt ∈ (LineSegment.mk a b).toSet)
    (h_avoids : pt ∉ r.toSet) :
    ¬(rayIntersectsSegment r ⟨a, pt⟩ ∧ rayIntersectsSegment r ⟨pt, b⟩) := by
  intro ⟨⟨q1, hq1_ray, hq1_seg⟩, ⟨q2, hq2_ray, hq2_seg⟩⟩
  apply h_avoids
  obtain ⟨t1, ht1_0, ht1_1, hq1x, hq1y⟩ := hq1_seg
  obtain ⟨t2, ht2_0, ht2_1, hq2x, hq2y⟩ := hq2_seg
  obtain ⟨s, hs0, hs1, hptx, hpty⟩ := h_pt
  obtain ⟨tr1, htr1_0, hq1x_r, hq1y_r⟩ := hq1_ray
  obtain ⟨tr2, htr2_0, hq2x_r, hq2y_r⟩ := hq2_ray
  -- Reduce structure projections
  dsimp only at hq1x hq1y hq2x hq2y hptx hpty
  -- If t1 = 1, then q1 = pt, so pt ∈ ray
  by_cases ht1_eq_1 : t1 = 1
  · subst ht1_eq_1; simp at hq1x hq1y
    exact ⟨tr1, htr1_0, by linarith, by linarith⟩
  -- If t2 = 0, then q2 = pt, so pt ∈ ray
  by_cases ht2_eq_0 : t2 = 0
  · subst ht2_eq_0; simp at hq2x hq2y
    exact ⟨tr2, htr2_0, by linarith, by linarith⟩
  -- Now t1 < 1 and t2 > 0
  have ht1_lt_1 : t1 < 1 := lt_of_le_of_ne ht1_1 ht1_eq_1
  have ht2_pos : (0 : ℚ) < t2 := lt_of_le_of_ne ht2_0 (Ne.symm ht2_eq_0)
  -- D = s*(1-t1) + t2*(1-s) > 0
  set D := s * (1 - t1) + t2 * (1 - s) with hD_def
  have hD_pos : 0 < D := by
    rw [hD_def]
    by_cases hs_eq_0 : s = 0
    · simp [hs_eq_0]; linarith
    · have : s > 0 := lt_of_le_of_ne hs0 (Ne.symm hs_eq_0)
      nlinarith
  have hD_ne : D ≠ 0 := ne_of_gt hD_pos
  set u := s * (1 - t1) / D with hu_def
  have hu_0 : 0 ≤ u := div_nonneg (by nlinarith) (le_of_lt hD_pos)
  have hu_1 : u ≤ 1 := by
    rw [hu_def]; exact div_le_one_of_le₀ (by rw [hD_def]; nlinarith) (le_of_lt hD_pos)
  -- pt.x = (1-u)*q1.x + u*q2.x
  have hcomb_x : pt.x = (1 - u) * q1.x + u * q2.x := by
    rw [hq1x, hq2x, hu_def]; field_simp [hD_ne]; rw [hD_def, hptx]; ring
  have hcomb_y : pt.y = (1 - u) * q1.y + u * q2.y := by
    rw [hq1y, hq2y, hu_def]; field_simp [hD_ne]; rw [hD_def, hpty]; ring
  -- pt is on the ray at parameter (1-u)*tr1 + u*tr2
  exact ⟨(1 - u) * tr1 + u * tr2, by nlinarith,
         by rw [hcomb_x, hq1x_r, hq2x_r]; ring,
         by rw [hcomb_y, hq1y_r, hq2y_r]; ring⟩

/-- Ray hits seg(a,b) iff it hits seg(a,pt) or seg(pt,b), when pt ∈ seg(a,b) and pt ∉ ray. -/
private lemma segment_split_rayIntersects (r : Ray) (a b pt : Vector2D)
    (h_pt : pt ∈ (LineSegment.mk a b).toSet) :
    rayIntersectsSegment r ⟨a, b⟩ ↔
    (rayIntersectsSegment r ⟨a, pt⟩ ∨ rayIntersectsSegment r ⟨pt, b⟩) := by
  have h_union := segment_split a b pt h_pt
  constructor
  · intro ⟨q, hq_ray, hq_seg⟩
    have : q ∈ (LineSegment.mk a pt).toSet ∪ (LineSegment.mk pt b).toSet :=
      h_union ▸ hq_seg
    rcases this with h | h
    · exact Or.inl ⟨q, hq_ray, h⟩
    · exact Or.inr ⟨q, hq_ray, h⟩
  · rintro (⟨q, hq_ray, hq_seg⟩ | ⟨q, hq_ray, hq_seg⟩)
    · exact ⟨q, hq_ray, h_union ▸ mem_union_left _ hq_seg⟩
    · exact ⟨q, hq_ray, h_union ▸ mem_union_right _ hq_seg⟩

/-- If ray avoids pt, the boolean count for sub-segments equals that for the original segment. -/
private lemma segment_split_xor (r : Ray) (a b pt : Vector2D)
    (h_pt : pt ∈ (LineSegment.mk a b).toSet)
    (h_avoids : pt ∉ r.toSet) :
    (if decide (rayIntersectsSegment r ⟨a, pt⟩) then 1 else 0) +
    (if decide (rayIntersectsSegment r ⟨pt, b⟩) then 1 else 0) =
    (if decide (rayIntersectsSegment r ⟨a, b⟩) then (1 : ℕ) else 0) := by
  have h_split := segment_split_rayIntersects r a b pt h_pt
  have h_not_both := ray_not_both_sub_segments r a b pt h_pt h_avoids
  by_cases h1 : rayIntersectsSegment r ⟨a, pt⟩ <;>
  by_cases h2 : rayIntersectsSegment r ⟨pt, b⟩ <;>
  simp_all

/-\! ### insertInEdge preserves cyclicCount -/

private lemma insertInEdge_count_preserves (p1 p2 pt first : Vector2D) (r : Ray)
    (h_pt : pt ∈ (LineSegment.mk p1 p2).toSet)
    (h_avoids : pt ∉ r.toSet)
    (v : Vector2D) (vs : List Vector2D) :
    cyclicCount r first (insertInEdge p1 p2 pt first (v :: vs)) =
    cyclicCount r first (v :: vs) := by
  induction vs generalizing v with
  | nil =>
    simp only [insertInEdge]; split
    · rename_i h; obtain ⟨hv, hf⟩ := h; subst hv; subst hf
      simp only [cyclicCount]
      exact segment_split_xor r v first pt h_pt h_avoids
    · rfl
  | cons w rest ih =>
    simp only [insertInEdge]; split
    · rename_i h; obtain ⟨hv, hw⟩ := h; subst hv; subst hw
      simp only [cyclicCount]
      have := segment_split_xor r v w pt h_pt h_avoids
      omega
    · show cyclicCount r first (v :: insertInEdge p1 p2 pt first (w :: rest)) =
           cyclicCount r first (v :: w :: rest)
      obtain ⟨tail, htail⟩ := insertInEdge_cons p1 p2 pt first w rest
      rw [htail]; simp only [cyclicCount]; congr 1; rw [← htail]; exact ih w

/-\! ### Vertices of refined polygon -/

/-- Original vertices are contained in the refined polygon's vertices. -/
private lemma mem_of_insertInEdge (p1 p2 pt first v : Vector2D) (vs : List Vector2D)
    (x : Vector2D) (hx : x ∈ v :: vs) :
    x ∈ insertInEdge p1 p2 pt first (v :: vs) := by
  induction vs generalizing v with
  | nil =>
    simp only [List.mem_singleton] at hx; subst hx
    simp only [insertInEdge]; split <;> exact (List.mem_cons_self _ _)
  | cons w rest ih =>
    rcases List.mem_cons.mp hx with rfl | hx'
    · simp only [insertInEdge]; split <;> exact (List.mem_cons_self _ _)
    · simp only [insertInEdge]; split
      · exact List.mem_cons_of_mem _ (List.mem_cons_of_mem _ hx')
      · exact List.mem_cons_of_mem _ (ih w hx')

/-\! ### Segment avoidance ↔ boundary avoidance -/

private lemma avoids_segments_iff_not_boundary (poly : Polygon) (p : Vector2D) :
    (∀ seg ∈ poly.segments, pointAvoidsSegment p seg) ↔ p ∉ poly.toBoundarySet := by
  simp only [Polygon.toBoundarySet, Set.mem_setOf_eq, pointAvoidsSegment]
  exact ⟨fun h hn => let ⟨seg, hs, hp⟩ := hn; h seg hs hp,
         fun h seg hs hp => h ⟨seg, hs, hp⟩⟩

/-\! ### Vertex on segment for polygons with ≥ 2 vertices -/

/-- Each vertex in a cyclic list has a successor in the zip with the shifted list. -/
private lemma vertex_has_successor (first v : Vector2D) (vs : List Vector2D)
    (x : Vector2D) (hx : x ∈ v :: vs) :
    ∃ y, (x, y) ∈ List.zip (v :: vs) (vs ++ [first]) := by
  induction vs generalizing v with
  | nil => simp at hx; subst hx; exact ⟨first, by simp⟩
  | cons w rest ih =>
    rcases List.mem_cons.mp hx with rfl | hx'
    · exact ⟨w, (List.mem_cons_self _ _)⟩
    · obtain ⟨z, hz⟩ := ih w hx'
      exact ⟨z, List.mem_cons_of_mem _ hz⟩

private lemma vertex_on_some_segment (v w : Vector2D) (vs : List Vector2D) (x : Vector2D)
    (hx : x ∈ v :: w :: vs) :
    ∃ seg ∈ (Polygon.mk (v :: w :: vs)).segments, x ∈ seg.toSet := by
  obtain ⟨y, hy⟩ := vertex_has_successor v v (w :: vs) x hx
  refine ⟨⟨x, y⟩, ?_, ⟨0, le_refl _, le_of_lt one_pos, by simp, by simp⟩⟩
  simp only [Polygon.segments, List.mem_map, Prod.exists]
  exact ⟨x, y, hy, rfl⟩

/-\! ### Exists ray avoiding vertices (re-proved locally) -/

private lemma exists_ray_avoiding_vertices' (p : Vector2D) (verts : List Vector2D)
    (h_not_vert : ∀ v ∈ verts, v ≠ p) :
    ∃ r : Ray, r.origin = p ∧ r.toSet ∩ { q | q ∈ verts } = ∅ := by
  have : Infinite ℚ := Infinite.of_injective (fun n : ℕ => (n : ℚ)) Nat.cast_injective
  let badSlopes : Finset ℚ := (verts.filterMap fun v =>
    if v.x > p.x then some ((v.y - p.y) / (v.x - p.x)) else none).toFinset
  obtain ⟨q, hq⟩ := Finset.exists_not_mem badSlopes
  have h_nonzero : (⟨1, q⟩ : Vector2D) ≠ ⟨0, 0⟩ := by
    intro h; exact absurd (congrArg Vector2D.x h) (by norm_num)
  refine ⟨⟨p, ⟨1, q⟩, h_nonzero⟩, rfl, ?_⟩
  rw [Set.eq_empty_iff_forall_not_mem]
  intro v hv
  obtain ⟨hv_ray, hv_vert⟩ := hv
  simp only [Set.mem_setOf_eq] at hv_vert
  obtain ⟨t, ht_nonneg, hvx, hvy⟩ := hv_ray
  simp only [mul_one] at hvx
  have hne : v ≠ p := h_not_vert v hv_vert
  have ht_eq : t = v.x - p.x := by linarith
  by_cases h_gt : v.x > p.x
  · have h_slope_mem : (v.y - p.y) / (v.x - p.x) ∈ badSlopes := by
      simp only [badSlopes, List.mem_toFinset, List.mem_filterMap]
      exact ⟨v, hv_vert, by simp [if_pos h_gt]⟩
    have hvmy : v.y - p.y = t * q := by linarith
    rw [ht_eq] at hvmy
    have hvx_ne : v.x - p.x ≠ 0 := ne_of_gt (by linarith : v.x - p.x > 0)
    have hq_eq : q = (v.y - p.y) / (v.x - p.x) := by
      rw [eq_div_iff hvx_ne, mul_comm]; linarith
    exact hq (hq_eq ▸ h_slope_mem)
  · push_neg at h_gt
    by_cases h_eq : v.x = p.x
    · have ht_zero : t = 0 := by linarith
      have hvy_eq : v.y = p.y := by
        have := hvy; rw [ht_zero] at this; simp at this; exact this
      exact hne (by cases v; cases p; simp_all)
    · linarith [lt_of_le_of_ne h_gt h_eq]

/-\! ### pt membership in insertInEdge result -/

/-- Helper: if (p1,p2) appears in the cyclic adjacency, insertInEdge inserts pt. -/
private lemma pt_mem_insertInEdge_aux (p1 p2 pt first v : Vector2D) (vs : List Vector2D)
    (h : (p1, p2) ∈ List.zip (v :: vs) (vs ++ [first])) :
    pt ∈ insertInEdge p1 p2 pt first (v :: vs) := by
  induction vs generalizing v with
  | nil =>
    simp at h; obtain ⟨rfl, rfl⟩ := h
    simp [insertInEdge]
  | cons w rest ih =>
    simp only [List.cons_append, List.zip_cons_cons, List.mem_cons, Prod.mk.injEq] at h
    rcases h with ⟨rfl, rfl⟩ | h_rest
    · simp [insertInEdge]
    · simp only [insertInEdge]
      split
      · exact List.mem_cons_of_mem _ (List.mem_cons_self _ _)
      · exact List.mem_cons_of_mem _ (ih w h_rest)

private lemma pt_mem_insertInEdge (p1 p2 pt v w : Vector2D) (vs : List Vector2D)
    (h_seg : ⟨p1, p2⟩ ∈ (Polygon.mk (v :: w :: vs)).segments) :
    pt ∈ insertInEdge p1 p2 pt v (v :: w :: vs) := by
  simp only [Polygon.segments, List.mem_map, Prod.exists] at h_seg
  obtain ⟨a, b, hab_zip, hab_eq⟩ := h_seg
  have hp1 : a = p1 := congrArg LineSegment.p1 hab_eq
  have hp2 : b = p2 := congrArg LineSegment.p2 hab_eq
  rw [← hp1, ← hp2]
  exact pt_mem_insertInEdge_aux a b pt v v (w :: vs) hab_zip

/-\! ### Main interior equality theorem -/

/-- The interior of the refined polygon equals the interior of the original polygon. -/
theorem refinement_interior_eq
    (poly : Polygon) (seg : LineSegment) (pt : Vector2D)
    (h_seg : seg ∈ poly.segments) (h_pt : pt ∈ seg.toSet) :
    (polygonRefinement poly seg pt).interior =
    poly.interior := by
  obtain ⟨vertices⟩ := poly
  match vertices with
  | [] => simp [Polygon.segments] at h_seg
  | [_] => simp [Polygon.segments] at h_seg
  | v :: w :: vs =>
    set poly' := Polygon.mk (v :: w :: vs) with hpoly'_def
    set refined := polygonRefinement poly' seg pt with hrefdef
    show refined.interior = poly'.interior
    have h_boundary_eq := refinement_boundary_eq
      poly' seg pt h_seg h_pt
    have href_eq : refined = ⟨insertInEdge seg.p1 seg.p2 pt v (v :: w :: vs)⟩ := by
      simp [hrefdef, polygonRefinement, hpoly'_def]
    obtain ⟨w', vs', hform⟩ := insertInEdge_form seg.p1 seg.p2 pt v v w vs
    -- Convert seg to ⟨seg.p1, seg.p2⟩ form for lemmas
    have h_seg_eq : (⟨seg.p1, seg.p2⟩ : LineSegment) = seg := by cases seg; rfl
    have h_seg' : (⟨seg.p1, seg.p2⟩ : LineSegment) ∈ poly'.segments := h_seg_eq ▸ h_seg
    -- Count equality for rays avoiding pt
    have h_count_eq : ∀ r : Ray, pt ∉ r.toSet →
        intersectionRayPolygonSegmentsNumber r refined =
        intersectionRayPolygonSegmentsNumber r poly' := by
      intro r h_avoids_pt
      rw [href_eq, hform, count_eq_cyclicCount r v w' vs',
          count_eq_cyclicCount r v w vs]
      conv_lhs => rw [← hform]
      exact insertInEdge_count_preserves seg.p1 seg.p2 pt v r h_pt h_avoids_pt v (w :: vs)
    -- Vertices of poly' ⊆ vertices of refined
    have h_vertices_sub : ∀ x, x ∈ poly'.vertices → x ∈ refined.vertices := by
      intro x hx; rw [href_eq]; simp
      exact mem_of_insertInEdge seg.p1 seg.p2 pt v v (w :: vs) x hx
    -- pt ∈ refined.vertices
    have h_pt_mem : pt ∈ refined.vertices := by
      rw [href_eq]; simp
      exact pt_mem_insertInEdge seg.p1 seg.p2 pt v w vs h_seg
    -- refined has ≥ 2 vertices
    have h_ref_len : refined.vertices.length ≥ 2 := by
      rw [href_eq, hform]; simp [List.length_cons]
    -- poly' has ≥ 2 vertices
    have h_poly_len : poly'.vertices.length ≥ 2 := by
      simp [hpoly'_def, List.length_cons]
    -- Helper: rayAvoidsVertices for refined → for poly'
    have h_avoids_transfer : ∀ r : Ray, rayAvoidsVertices r refined → rayAvoidsVertices r poly' := by
      intro r hr
      rw [rayAvoidsVertices, eq_empty_iff_forall_not_mem] at hr ⊢
      intro x hx
      exact hr x ⟨hx.1, by
        simp only [Polygon.toVertices, mem_setOf_eq] at hx ⊢
        exact h_vertices_sub x hx.2⟩
    -- Helper: rayAvoidsVertices for refined → pt ∉ r.toSet
    have h_avoids_pt : ∀ r : Ray, rayAvoidsVertices r refined → pt ∉ r.toSet := by
      intro r hr hpt_r
      rw [rayAvoidsVertices, eq_empty_iff_forall_not_mem] at hr
      exact hr pt ⟨hpt_r, by
        simp only [Polygon.toVertices, mem_setOf_eq]; exact h_pt_mem⟩
    -- Now prove the set equality
    ext p
    simp only [Polygon.interior, Set.mem_setOf_eq]
    constructor
    · -- Forward: p ∈ refined.interior → p ∈ poly'.interior
      intro ⟨h_avoids_segs_ref, h_forall_ref⟩
      -- p avoids poly' segments
      have h_avoids_segs : ∀ seg_i ∈ poly'.segments, pointAvoidsSegment p seg_i := by
        rw [avoids_segments_iff_not_boundary] at h_avoids_segs_ref ⊢
        rwa [h_boundary_eq] at h_avoids_segs_ref
      refine ⟨h_avoids_segs, ?_⟩
      -- Use interior_eq_exists for poly': provide an existential witness
      -- We need a ray from p avoiding poly' vertices with odd crossing for poly'
      -- Step 1: find a ray avoiding refined vertices
      have h_p_not_ref_vert : ∀ x ∈ refined.vertices, x ≠ p := by
        intro x hx hxp; subst hxp
        rw [avoids_segments_iff_not_boundary] at h_avoids_segs_ref
        rw [href_eq] at hx h_avoids_segs_ref
        simp at hx
        rw [hform] at hx
        have ⟨seg_x, hseg_x, hp_on⟩ := vertex_on_some_segment v w' vs' x hx
        rw [← hform] at hseg_x
        exact h_avoids_segs_ref ⟨seg_x, hseg_x, hp_on⟩
      obtain ⟨r, hr_origin, hr_avoids_verts⟩ := exists_ray_avoiding_vertices' p refined.vertices h_p_not_ref_vert
      -- Convert to rayAvoidsVertices
      have hr_avoids_ref : rayAvoidsVertices r refined := by
        rwa [rayAvoidsVertices, Polygon.toVertices]
      -- r also avoids poly' vertices
      have hr_avoids_poly := h_avoids_transfer r hr_avoids_ref
      -- Count equality
      have hr_count := h_count_eq r (h_avoids_pt r hr_avoids_ref)
      -- r has odd crossing for refined
      have hr_parity_ref := h_forall_ref r hr_origin hr_avoids_ref
      -- Therefore odd crossing for poly'
      have hr_parity_poly : intersectionRayPolygonSegmentsNumber r poly' % 2 = 1 := by
        omega
      -- Now use parity invariance for any other ray
      intro r2 hr2_origin hr2_avoids_poly
      have h_same_origin : sameOrigin r r2 := by simp [sameOrigin, hr_origin, hr2_origin]
      have h_seg_avoids : ∀ seg_i ∈ poly'.segments, pointAvoidsSegment r.origin seg_i := by
        rwa [hr_origin]
      exact (intersectionParity_eq_of_sameOrigin_avoidsVertices r r2 poly'
        h_same_origin hr_avoids_poly hr2_avoids_poly h_seg_avoids).symm ▸ hr_parity_poly
    · -- Backward: p ∈ poly'.interior → p ∈ refined.interior
      intro ⟨h_avoids_segs, h_forall_poly⟩
      -- p avoids refined segments
      have h_avoids_segs_ref : ∀ seg_i ∈ refined.segments, pointAvoidsSegment p seg_i := by
        rw [avoids_segments_iff_not_boundary] at h_avoids_segs ⊢
        rwa [← h_boundary_eq] at h_avoids_segs
      refine ⟨h_avoids_segs_ref, ?_⟩
      -- For any ray avoiding refined vertices, show odd crossing for refined
      intro r hr_origin hr_avoids_ref
      -- r avoids poly' vertices
      have hr_avoids_poly := h_avoids_transfer r hr_avoids_ref
      -- r avoids pt
      have hr_avoids_pt_r := h_avoids_pt r hr_avoids_ref
      -- Count equality
      have hr_count := h_count_eq r hr_avoids_pt_r
      -- Crossing for poly' is odd
      have hr_parity_poly := h_forall_poly r hr_origin hr_avoids_poly
      -- Therefore crossing for refined is odd
      omega

/-! ### Refinement of a polygon at ALL edges containing a point -/

/-- Recursively insert `pt` at EVERY edge of a cyclic vertex list that contains it.
    `first` is the first vertex (for the closing edge). -/
private def insertPtInAllEdges (pt first : Vector2D) : List Vector2D → List Vector2D
  | [] => []
  | [v] => if pt ∈ (LineSegment.mk v first).toSet then [v, pt] else [v]
  | v :: w :: vs =>
    if pt ∈ (LineSegment.mk v w).toSet then
      v :: pt :: insertPtInAllEdges pt first (w :: vs)
    else
      v :: insertPtInAllEdges pt first (w :: vs)

/-- Refine a polygon at ALL segments containing a given point. -/
private def refinePointAllSegs (poly : Polygon) (pt : Vector2D) : Polygon :=
  match poly.vertices with
  | [] => poly
  | [_] => poly
  | v :: w :: vs => ⟨insertPtInAllEdges pt v (v :: w :: vs)⟩

/-! ### Structural lemmas for insertPtInAllEdges -/

/-- The first element of insertPtInAllEdges on a nonempty list is preserved. -/
private lemma insertPtInAllEdges_head (pt first v : Vector2D) (vs : List Vector2D) :
    ∃ tail, insertPtInAllEdges pt first (v :: vs) = v :: tail := by
  cases vs with
  | nil => simp [insertPtInAllEdges]; split <;> exact ⟨_, rfl⟩
  | cons w rest => simp [insertPtInAllEdges]; split <;> exact ⟨_, rfl⟩

/-- insertPtInAllEdges on a list of ≥ 2 elements produces a list of ≥ 2 elements
    starting with the same first element. -/
private lemma insertPtInAllEdges_form (pt first v w : Vector2D) (vs : List Vector2D) :
    ∃ w' vs', insertPtInAllEdges pt first (v :: w :: vs) = v :: w' :: vs' := by
  simp only [insertPtInAllEdges]; split
  · exact ⟨pt, insertPtInAllEdges pt first (w :: vs), rfl⟩
  · obtain ⟨tail, htail⟩ := insertPtInAllEdges_head pt first w vs
    exact ⟨w, tail, by rw [htail]⟩

/-! ### Boundary preservation for insertPtInAllEdges -/

/-- insertPtInAllEdges preserves the cyclicBoundary. -/
private lemma insertPtInAllEdges_preserves_boundary (pt first : Vector2D)
    (v : Vector2D) (vs : List Vector2D) :
    cyclicBoundary first (insertPtInAllEdges pt first (v :: vs)) =
    cyclicBoundary first (v :: vs) := by
  induction vs generalizing v with
  | nil =>
    simp only [insertPtInAllEdges]; split
    · rename_i h; simp only [cyclicBoundary]; exact segment_split _ _ pt h
    · rfl
  | cons w rest ih =>
    simp only [insertPtInAllEdges]; split
    · rename_i h
      obtain ⟨tail, htail⟩ := insertPtInAllEdges_head pt first w rest
      conv_lhs => rw [htail]
      simp only [cyclicBoundary]
      rw [← Set.union_assoc, segment_split _ _ pt h]
      congr 1; rw [← htail]; exact ih w
    · show cyclicBoundary first (v :: insertPtInAllEdges pt first (w :: rest)) =
           cyclicBoundary first (v :: w :: rest)
      obtain ⟨tail, htail⟩ := insertPtInAllEdges_head pt first w rest
      rw [htail]; simp only [cyclicBoundary]; congr 1; rw [← htail]; exact ih w

/-- The boundary is preserved by refinePointAllSegs. -/
private lemma refinePointAllSegs_boundary_eq (poly : Polygon) (pt : Vector2D)
    (h_bdy : pt ∈ poly.toBoundarySet) :
    (refinePointAllSegs poly pt).toBoundarySet = poly.toBoundarySet := by
  obtain ⟨vertices⟩ := poly
  match vertices with
  | [] => rfl
  | [_] => rfl
  | v :: w :: vs =>
    show (Polygon.mk (insertPtInAllEdges pt v (v :: w :: vs))).toBoundarySet =
         (Polygon.mk (v :: w :: vs)).toBoundarySet
    obtain ⟨w', vs', hform⟩ := insertPtInAllEdges_form pt v v w vs
    rw [hform, toBoundarySet_eq_cyclicBoundary v w' vs',
        toBoundarySet_eq_cyclicBoundary v w vs]
    conv_lhs => rw [← hform]
    exact insertPtInAllEdges_preserves_boundary pt v v (w :: vs)

/-! ### Vertex membership for insertPtInAllEdges -/

/-- Original vertices are contained in insertPtInAllEdges result. -/
private lemma mem_of_insertPtInAllEdges (pt first v : Vector2D) (vs : List Vector2D)
    (x : Vector2D) (hx : x ∈ v :: vs) :
    x ∈ insertPtInAllEdges pt first (v :: vs) := by
  induction vs generalizing v with
  | nil =>
    simp only [List.mem_singleton] at hx; subst hx
    simp only [insertPtInAllEdges]; split <;> exact (List.mem_cons_self _ _)
  | cons w rest ih =>
    rcases List.mem_cons.mp hx with rfl | hx'
    · simp only [insertPtInAllEdges]; split <;> exact (List.mem_cons_self _ _)
    · simp only [insertPtInAllEdges]; split
      · exact List.mem_cons_of_mem _ (List.mem_cons_of_mem _ (ih w hx'))
      · exact List.mem_cons_of_mem _ (ih w hx')

/-- pt is in the result of insertPtInAllEdges when pt is on some edge. -/
private lemma pt_mem_insertPtInAllEdges (pt first v : Vector2D) (vs : List Vector2D)
    (h : pt ∈ cyclicBoundary first (v :: vs)) :
    pt ∈ insertPtInAllEdges pt first (v :: vs) := by
  induction vs generalizing v with
  | nil =>
    simp only [cyclicBoundary] at h
    simp only [insertPtInAllEdges, if_pos h]; exact List.mem_cons_of_mem _ (List.mem_cons_self _ _)
  | cons w rest ih =>
    simp only [cyclicBoundary, Set.mem_union] at h
    simp only [insertPtInAllEdges]
    rcases h with h_edge | h_rest
    · rw [if_pos h_edge]; exact List.mem_cons_of_mem _ (List.mem_cons_self _ _)
    · split
      · exact List.mem_cons_of_mem _ (List.mem_cons_of_mem _ (ih w h_rest))
      · exact List.mem_cons_of_mem _ (ih w h_rest)

/-! ### Count preservation for insertPtInAllEdges -/

private lemma insertPtInAllEdges_count_preserves (pt first : Vector2D) (r : Ray)
    (h_avoids : pt ∉ r.toSet)
    (v : Vector2D) (vs : List Vector2D) :
    cyclicCount r first (insertPtInAllEdges pt first (v :: vs)) =
    cyclicCount r first (v :: vs) := by
  induction vs generalizing v with
  | nil =>
    simp only [insertPtInAllEdges]; split
    · rename_i h; simp only [cyclicCount]
      exact segment_split_xor r v first pt h h_avoids
    · rfl
  | cons w rest ih =>
    simp only [insertPtInAllEdges]; split
    · rename_i h; simp only [cyclicCount]
      have hsplit := segment_split_xor r v w pt h h_avoids
      obtain ⟨tail, htail⟩ := insertPtInAllEdges_head pt first w rest
      rw [htail]; simp only [cyclicCount]; rw [← htail, ih w]; omega
    · show cyclicCount r first (v :: insertPtInAllEdges pt first (w :: rest)) =
           cyclicCount r first (v :: w :: rest)
      obtain ⟨tail, htail⟩ := insertPtInAllEdges_head pt first w rest
      rw [htail]; simp only [cyclicCount]; congr 1; rw [← htail]; exact ih w

/-! ### Interior equality from boundary and count equality -/

/-- Reusable lemma: if a refined polygon has the same boundary and crossing count,
    then it has the same interior. -/
private lemma interior_eq_of_same_boundary_and_count
    (poly refined : Polygon) (pt : Vector2D)
    (h_boundary_eq : refined.toBoundarySet = poly.toBoundarySet)
    (h_vert_sub : ∀ x, x ∈ poly.vertices → x ∈ refined.vertices)
    (h_pt_mem : pt ∈ refined.vertices)
    (h_ref_len : refined.vertices.length ≥ 2)
    (h_poly_len : poly.vertices.length ≥ 2)
    (h_count_eq : ∀ r : Ray, pt ∉ r.toSet →
        intersectionRayPolygonSegmentsNumber r refined =
        intersectionRayPolygonSegmentsNumber r poly) :
    refined.interior = poly.interior := by
  -- Get the first two vertices for each polygon
  obtain ⟨ref_verts⟩ := refined
  obtain ⟨poly_verts⟩ := poly
  match hpv : poly_verts with
  | [] => simp at h_poly_len
  | [_] => simp at h_poly_len
  | pv :: pw :: pvs =>
    match hrv : ref_verts with
    | [] => simp at h_ref_len
    | [_] => simp at h_ref_len
    | rv :: rw :: rvs =>
      set poly' := Polygon.mk (pv :: pw :: pvs)
      set refined' := Polygon.mk (rv :: rw :: rvs)
      -- Helper: rayAvoidsVertices for refined → for poly
      have h_avoids_transfer : ∀ r : Ray, rayAvoidsVertices r refined' → rayAvoidsVertices r poly' := by
        intro r hr
        rw [rayAvoidsVertices, eq_empty_iff_forall_not_mem] at hr ⊢
        intro x hx
        exact hr x ⟨hx.1, by
          simp only [Polygon.toVertices, mem_setOf_eq] at hx ⊢
          exact h_vert_sub x hx.2⟩
      -- Helper: rayAvoidsVertices for refined → pt ∉ r.toSet
      have h_avoids_pt : ∀ r : Ray, rayAvoidsVertices r refined' → pt ∉ r.toSet := by
        intro r hr hpt_r
        rw [rayAvoidsVertices, eq_empty_iff_forall_not_mem] at hr
        exact hr pt ⟨hpt_r, by
          simp only [Polygon.toVertices, mem_setOf_eq]; exact h_pt_mem⟩
      ext p
      simp only [Polygon.interior, Set.mem_setOf_eq]
      constructor
      · -- Forward: p ∈ refined.interior → p ∈ poly.interior
        intro ⟨h_avoids_segs_ref, h_forall_ref⟩
        have h_avoids_segs : ∀ seg_i ∈ poly'.segments, pointAvoidsSegment p seg_i := by
          rw [avoids_segments_iff_not_boundary] at h_avoids_segs_ref ⊢
          rwa [h_boundary_eq] at h_avoids_segs_ref
        refine ⟨h_avoids_segs, ?_⟩
        have h_p_not_ref_vert : ∀ x ∈ refined'.vertices, x ≠ p := by
          intro x hx hxp; subst hxp
          rw [avoids_segments_iff_not_boundary] at h_avoids_segs_ref
          have ⟨seg_x, hseg_x, hp_on⟩ := vertex_on_some_segment rv rw rvs x hx
          exact h_avoids_segs_ref ⟨seg_x, hseg_x, hp_on⟩
        obtain ⟨r, hr_origin, hr_avoids_verts⟩ := exists_ray_avoiding_vertices' p refined'.vertices h_p_not_ref_vert
        have hr_avoids_ref : rayAvoidsVertices r refined' := by
          rwa [rayAvoidsVertices, Polygon.toVertices]
        have hr_avoids_poly := h_avoids_transfer r hr_avoids_ref
        have hr_count := h_count_eq r (h_avoids_pt r hr_avoids_ref)
        have hr_parity_ref := h_forall_ref r hr_origin hr_avoids_ref
        have hr_parity_poly : intersectionRayPolygonSegmentsNumber r poly' % 2 = 1 := by omega
        intro r2 hr2_origin hr2_avoids_poly
        have h_same_origin : sameOrigin r r2 := by simp [sameOrigin, hr_origin, hr2_origin]
        have h_seg_avoids : ∀ seg_i ∈ poly'.segments, pointAvoidsSegment r.origin seg_i := by rwa [hr_origin]
        exact (intersectionParity_eq_of_sameOrigin_avoidsVertices r r2 poly'
          h_same_origin hr_avoids_poly hr2_avoids_poly h_seg_avoids).symm ▸ hr_parity_poly
      · -- Backward: p ∈ poly.interior → p ∈ refined.interior
        intro ⟨h_avoids_segs, h_forall_poly⟩
        have h_avoids_segs_ref : ∀ seg_i ∈ refined'.segments, pointAvoidsSegment p seg_i := by
          rw [avoids_segments_iff_not_boundary] at h_avoids_segs ⊢
          rwa [← h_boundary_eq] at h_avoids_segs
        refine ⟨h_avoids_segs_ref, ?_⟩
        intro r hr_origin hr_avoids_ref
        have hr_avoids_poly := h_avoids_transfer r hr_avoids_ref
        have hr_avoids_pt_r := h_avoids_pt r hr_avoids_ref
        have hr_count := h_count_eq r hr_avoids_pt_r
        have hr_parity_poly := h_forall_poly r hr_origin hr_avoids_poly
        omega

/-- The interior is preserved by refinePointAllSegs. -/
private lemma refinePointAllSegs_interior_eq (poly : Polygon) (pt : Vector2D)
    (h_bdy : pt ∈ poly.toBoundarySet) :
    (refinePointAllSegs poly pt).interior = poly.interior := by
  obtain ⟨vertices⟩ := poly
  match vertices with
  | [] => rfl
  | [_] => rfl
  | v :: w :: vs =>
    set poly' := Polygon.mk (v :: w :: vs) with hpoly'_def
    set refined := refinePointAllSegs poly' pt with hrefdef
    show refined.interior = poly'.interior
    have h_boundary_eq := refinePointAllSegs_boundary_eq poly' pt h_bdy
    have href_eq : refined = ⟨insertPtInAllEdges pt v (v :: w :: vs)⟩ := by
      simp [hrefdef, refinePointAllSegs, hpoly'_def]
    obtain ⟨w', vs', hform⟩ := insertPtInAllEdges_form pt v v w vs
    -- pt is on cyclicBoundary
    have h_bdy_cyclic : pt ∈ cyclicBoundary v (v :: w :: vs) :=
      (toBoundarySet_eq_cyclicBoundary v w vs) ▸ h_bdy
    apply interior_eq_of_same_boundary_and_count poly' refined pt h_boundary_eq
    · -- poly' vertices ⊆ refined vertices
      intro x hx; rw [href_eq]; simp
      exact mem_of_insertPtInAllEdges pt v v (w :: vs) x hx
    · -- pt ∈ refined vertices
      rw [href_eq]; simp
      exact pt_mem_insertPtInAllEdges pt v v (w :: vs) h_bdy_cyclic
    · -- refined has ≥ 2 vertices
      rw [href_eq, hform]; simp [List.length_cons]
    · -- poly' has ≥ 2 vertices
      simp [hpoly'_def, List.length_cons]
    · -- Count equality
      intro r h_avoids_pt
      rw [href_eq, hform, count_eq_cyclicCount r v w' vs',
          count_eq_cyclicCount r v w vs]
      conv_lhs => rw [← hform]
      exact insertPtInAllEdges_count_preserves pt v r h_avoids_pt v (w :: vs)

/-! ### Endpoint property for insertPtInAllEdges -/

/-- Recursive predicate: pt is at endpoints of every edge in a cyclic vertex list. -/
private def ptAtEdgeEndpoints (pt first : Vector2D) : List Vector2D → Prop
  | [] => True
  | [v] => pt ∈ (LineSegment.mk v first).toSet → pt = v ∨ pt = first
  | v :: w :: vs =>
    (pt ∈ (LineSegment.mk v w).toSet → pt = v ∨ pt = w) ∧
    ptAtEdgeEndpoints pt first (w :: vs)

/-- After insertPtInAllEdges, pt is at endpoints of every edge. -/
private lemma insertPtInAllEdges_pt_endpoint (pt first v : Vector2D) (vs : List Vector2D) :
    ptAtEdgeEndpoints pt first (insertPtInAllEdges pt first (v :: vs)) := by
  induction vs generalizing v with
  | nil =>
    simp only [insertPtInAllEdges]
    split
    · -- pt ∈ edge (v, first): result is [v, pt]
      exact ⟨fun _ => Or.inr rfl, fun _ => Or.inl rfl⟩
    · -- pt ∉ edge: result is [v]
      rename_i h; exact fun h' => absurd h' h
  | cons w rest ih =>
    simp only [insertPtInAllEdges]
    split
    · -- pt ∈ edge (v, w): result is v :: pt :: insertPtInAllEdges pt first (w :: rest)
      obtain ⟨tail, htail⟩ := insertPtInAllEdges_head pt first w rest
      show ptAtEdgeEndpoints pt first (v :: pt :: insertPtInAllEdges pt first (w :: rest))
      rw [htail]
      exact ⟨fun _ => Or.inr rfl, fun _ => Or.inl rfl, by rw [← htail]; exact ih w⟩
    · -- pt ∉ edge (v, w): result is v :: insertPtInAllEdges pt first (w :: rest)
      rename_i h_not
      obtain ⟨tail, htail⟩ := insertPtInAllEdges_head pt first w rest
      show ptAtEdgeEndpoints pt first (v :: insertPtInAllEdges pt first (w :: rest))
      rw [htail]
      exact ⟨fun h_mem => absurd h_mem h_not, by rw [← htail]; exact ih w⟩

/-- ptAtEdgeEndpoints implies the endpoint property for every pair in the cyclic zip. -/
private lemma ptAtEdgeEndpoints_imp_zip (pt first v : Vector2D) (vs : List Vector2D)
    (h : ptAtEdgeEndpoints pt first (v :: vs)) :
    ∀ (a b : Vector2D), (a, b) ∈ List.zip (v :: vs) (vs ++ [first]) →
    pt ∈ (LineSegment.mk a b).toSet → pt = a ∨ pt = b := by
  induction vs generalizing v with
  | nil =>
    intro a b h_zip h_pt
    simp [List.zip] at h_zip; obtain ⟨rfl, rfl⟩ := h_zip
    exact h h_pt
  | cons w rest ih =>
    intro a b h_zip h_pt
    simp only [List.cons_append, List.zip_cons_cons, List.mem_cons, Prod.mk.injEq] at h_zip
    rcases h_zip with ⟨rfl, rfl⟩ | h_rest
    · exact h.1 h_pt
    · exact ih w h.2 a b h_rest h_pt

/-- ptAtEdgeEndpoints (with first = v) implies the endpoint property for all polygon segments. -/
private lemma ptAtEdgeEndpoints_iff_forall_seg (pt v w : Vector2D) (vs : List Vector2D)
    (h : ptAtEdgeEndpoints pt v (v :: w :: vs)) :
    ∀ seg ∈ (Polygon.mk (v :: w :: vs)).segments,
    pt ∈ seg.toSet → pt = seg.p1 ∨ pt = seg.p2 := by
  intro seg h_seg h_pt
  simp only [Polygon.segments, List.mem_map, Prod.exists] at h_seg
  obtain ⟨a, b, h_zip, h_eq⟩ := h_seg; subst h_eq
  exact ptAtEdgeEndpoints_imp_zip pt v v (w :: vs) h a b h_zip h_pt

private lemma refinePointAllSegs_pt_endpoint (poly : Polygon) (pt : Vector2D)
    (h_bdy : pt ∈ poly.toBoundarySet) :
    ∀ seg ∈ (refinePointAllSegs poly pt).segments,
    pt ∈ seg.toSet → pt = seg.p1 ∨ pt = seg.p2 := by
  obtain ⟨vertices⟩ := poly
  match vertices with
  | [] => simp [refinePointAllSegs, Polygon.segments]
  | [_] => simp [refinePointAllSegs, Polygon.segments]
  | v :: w :: vs =>
    simp only [refinePointAllSegs]
    obtain ⟨w', vs', hform⟩ := insertPtInAllEdges_form pt v v w vs
    rw [hform]
    exact ptAtEdgeEndpoints_iff_forall_seg pt v w' vs'
      (by rw [← hform]; exact insertPtInAllEdges_pt_endpoint pt v v (w :: vs))

/-! ### Sub-segment endpoint helpers -/

/-- Extensionality for Vector2D. -/
private lemma vec_ext {a b : Vector2D} (hx : a.x = b.x) (hy : a.y = b.y) : a = b := by
  cases a; cases b; simp_all

private lemma mem_sub_seg_left (a b c : Vector2D)
    (hc : c ∈ (LineSegment.mk a b).toSet) (ha : a ∈ (LineSegment.mk c b).toSet) : a = c := by
  obtain ⟨s, hs0, hs1, hcx, hcy⟩ := hc
  obtain ⟨t, ht0, ht1, hax, hay⟩ := ha
  simp at hcx hcy hax hay
  have key_x : (a.x - b.x) * (t + s - t * s) = 0 := by nlinarith
  have key_y : (a.y - b.y) * (t + s - t * s) = 0 := by nlinarith
  by_cases h : t + s - t * s = 0
  · have ht_zero : t = 0 := by nlinarith
    have hs_zero : s = 0 := by nlinarith
    rw [hs_zero] at hcx hcy; simp at hcx hcy
    exact vec_ext hcx.symm hcy.symm
  · have hab_x : a.x = b.x := by
      rcases mul_eq_zero.mp key_x with h1 | h2; linarith; exact absurd h2 h
    have hab_y : a.y = b.y := by
      rcases mul_eq_zero.mp key_y with h1 | h2; linarith; exact absurd h2 h
    exact vec_ext (by nlinarith) (by nlinarith)

private lemma mem_sub_seg_right (a b c : Vector2D)
    (hc : c ∈ (LineSegment.mk a b).toSet) (hb : b ∈ (LineSegment.mk a c).toSet) : b = c := by
  obtain ⟨s, hs0, hs1, hcx, hcy⟩ := hc
  obtain ⟨t, ht0, ht1, hbx, hby⟩ := hb
  simp at hcx hcy hbx hby
  have key_x : (a.x - b.x) * (1 - t * s) = 0 := by nlinarith
  have key_y : (a.y - b.y) * (1 - t * s) = 0 := by nlinarith
  by_cases h : 1 - t * s = 0
  · have hts : t * s = 1 := by linarith
    have ht1' : t = 1 := by nlinarith
    have hs1' : s = 1 := by nlinarith
    subst ht1'; subst hs1'; simp at hcx hcy
    -- hcx : c.x = b.x, hcy : c.y = b.y
    exact vec_ext (by linarith) (by linarith)
  · have hab_x : a.x = b.x := by
      rcases mul_eq_zero.mp key_x with h1 | h2; linarith; exact absurd h2 h
    have hab_y : a.y = b.y := by
      rcases mul_eq_zero.mp key_y with h1 | h2; linarith; exact absurd h2 h
    exact vec_ext (by nlinarith) (by nlinarith)

/-! ### Preserves endpoint property -/

/-- insertPtInAllEdges for pt' preserves the ptAtEdgeEndpoints property for pt. -/
private lemma insertPtInAllEdges_preserves_endpoint (pt pt' first : Vector2D)
    (v : Vector2D) (vs : List Vector2D)
    (h : ptAtEdgeEndpoints pt first (v :: vs)) :
    ptAtEdgeEndpoints pt first (insertPtInAllEdges pt' first (v :: vs)) := by
  induction vs generalizing v with
  | nil =>
    simp only [insertPtInAllEdges]
    split
    · rename_i h_in
      refine ⟨fun h_mem => ?_, fun h_mem => ?_⟩
      · have h_sub : (LineSegment.mk v pt').toSet ⊆ (LineSegment.mk v first).toSet := by
          intro q hq; exact (segment_split v first pt' h_in) ▸ Set.mem_union_left _ hq
        cases h (h_sub h_mem) with
        | inl hpv => exact Or.inl hpv
        | inr hpf =>
          rw [hpf] at h_mem
          exact Or.inr (hpf.trans (mem_sub_seg_right v first pt' h_in h_mem))
      · have h_sub : (LineSegment.mk pt' first).toSet ⊆ (LineSegment.mk v first).toSet := by
          intro q hq; exact (segment_split v first pt' h_in) ▸ Set.mem_union_right _ hq
        cases h (h_sub h_mem) with
        | inl hpv =>
          rw [hpv] at h_mem
          exact Or.inl ((mem_sub_seg_left v first pt' h_in h_mem).symm.trans hpv.symm).symm
        | inr hpf => exact Or.inr hpf
    · exact h
  | cons w rest ih =>
    obtain ⟨h_edge, h_rest⟩ := h
    simp only [insertPtInAllEdges]
    split
    · rename_i h_in
      obtain ⟨tail, htail⟩ := insertPtInAllEdges_head pt' first w rest
      show ptAtEdgeEndpoints pt first (v :: pt' :: insertPtInAllEdges pt' first (w :: rest))
      rw [htail]
      refine ⟨?_, ?_, ?_⟩
      · intro h_mem
        have h_sub : (LineSegment.mk v pt').toSet ⊆ (LineSegment.mk v w).toSet := by
          intro q hq; exact (segment_split v w pt' h_in) ▸ Set.mem_union_left _ hq
        cases h_edge (h_sub h_mem) with
        | inl hpv => exact Or.inl hpv
        | inr hpw =>
          rw [hpw] at h_mem
          exact Or.inr (hpw.trans (mem_sub_seg_right v w pt' h_in h_mem))
      · intro h_mem
        have h_sub : (LineSegment.mk pt' w).toSet ⊆ (LineSegment.mk v w).toSet := by
          intro q hq; exact (segment_split v w pt' h_in) ▸ Set.mem_union_right _ hq
        cases h_edge (h_sub h_mem) with
        | inl hpv =>
          rw [hpv] at h_mem
          exact Or.inl ((mem_sub_seg_left v w pt' h_in h_mem).symm.trans hpv.symm).symm
        | inr hpw => exact Or.inr hpw
      · rw [← htail]; exact ih w h_rest
    · obtain ⟨tail, htail⟩ := insertPtInAllEdges_head pt' first w rest
      show ptAtEdgeEndpoints pt first (v :: insertPtInAllEdges pt' first (w :: rest))
      rw [htail]
      exact ⟨h_edge, by rw [← htail]; exact ih w h_rest⟩

/-- Convert from zip-based endpoint property to ptAtEdgeEndpoints. -/
private lemma zip_to_ptAtEdgeEndpoints (pt first v : Vector2D) (vs : List Vector2D)
    (h : ∀ (a b : Vector2D), (a, b) ∈ List.zip (v :: vs) (vs ++ [first]) →
         pt ∈ (LineSegment.mk a b).toSet → pt = a ∨ pt = b) :
    ptAtEdgeEndpoints pt first (v :: vs) := by
  induction vs generalizing v with
  | nil => exact h v first (by simp [List.zip])
  | cons w rest ih =>
    exact ⟨h v w ((List.mem_cons_self _ _)),
           ih w (fun a b hab => h a b (List.mem_cons_of_mem _ hab))⟩

/-- Convert from ∀ seg ∈ poly.segments to ptAtEdgeEndpoints. -/
private lemma forall_seg_to_ptAtEdgeEndpoints (pt v w : Vector2D) (vs : List Vector2D)
    (h : ∀ seg ∈ (Polygon.mk (v :: w :: vs)).segments,
         pt ∈ seg.toSet → pt = seg.p1 ∨ pt = seg.p2) :
    ptAtEdgeEndpoints pt v (v :: w :: vs) := by
  apply zip_to_ptAtEdgeEndpoints
  intro a b h_zip h_pt
  exact h ⟨a, b⟩ (by simp only [Polygon.segments, List.mem_map, Prod.exists]; exact ⟨a, b, h_zip, rfl⟩) h_pt

/-- Refining for pt' preserves the endpoint property for a different point pt. -/
private lemma refinePointAllSegs_preserves_endpoint (poly : Polygon) (pt pt' : Vector2D)
    (h_bdy : pt' ∈ poly.toBoundarySet)
    (h : ∀ seg ∈ poly.segments, pt ∈ seg.toSet → pt = seg.p1 ∨ pt = seg.p2) :
    ∀ seg ∈ (refinePointAllSegs poly pt').segments,
    pt ∈ seg.toSet → pt = seg.p1 ∨ pt = seg.p2 := by
  obtain ⟨vertices⟩ := poly
  match vertices with
  | [] => simp [refinePointAllSegs, Polygon.segments]
  | [_] => simp [refinePointAllSegs, Polygon.segments]
  | v :: w :: vs =>
    simp only [refinePointAllSegs]
    obtain ⟨w', vs', hform⟩ := insertPtInAllEdges_form pt' v v w vs
    have h_endpoints := forall_seg_to_ptAtEdgeEndpoints pt v w vs h
    have h_preserved := insertPtInAllEdges_preserves_endpoint pt pt' v v (w :: vs) h_endpoints
    rw [hform]
    exact ptAtEdgeEndpoints_iff_forall_seg pt v w' vs'
      (by rw [← hform]; exact h_preserved)

/-- Recursively refine a polygon by inserting boundary points as new vertices.
    For each point, refines ALL segments containing it. -/
private def refineWithPoints : (poly : Polygon) → (pts : List Vector2D) →
    (∀ pt ∈ pts, pt ∈ poly.toBoundarySet) → Polygon
  | poly, [], _ => poly
  | poly, pt :: rest, h_all =>
    refineWithPoints
      (refinePointAllSegs poly pt)
      rest
      (fun pt' h_mem => by
        rw [refinePointAllSegs_boundary_eq poly pt (h_all pt (List.mem_cons_self _ _))]
        exact h_all pt' (List.mem_cons_of_mem _ h_mem))

private lemma refineWithPoints_boundary_eq :
    ∀ (poly : Polygon) (pts : List Vector2D)
    (h_all : ∀ pt ∈ pts, pt ∈ poly.toBoundarySet),
    (refineWithPoints poly pts h_all).toBoundarySet = poly.toBoundarySet
  | _, [], _ => rfl
  | poly, pt :: rest, h_all =>
    (refineWithPoints_boundary_eq _ rest _).trans
      (refinePointAllSegs_boundary_eq poly pt (h_all pt (List.mem_cons_self _ _)))

private lemma refineWithPoints_interior_eq :
    ∀ (poly : Polygon) (pts : List Vector2D)
    (h_all : ∀ pt ∈ pts, pt ∈ poly.toBoundarySet),
    (refineWithPoints poly pts h_all).interior = poly.interior
  | _, [], _ => rfl
  | poly, pt :: rest, h_all =>
    (refineWithPoints_interior_eq _ rest _).trans
      (refinePointAllSegs_interior_eq poly pt (h_all pt (List.mem_cons_self _ _)))

/-! ### Endpoint preservation lemmas -/

/-- After refineWithPoints, the endpoint property is preserved through the recursion. -/
private lemma refineWithPoints_preserves_endpoint :
    ∀ (poly : Polygon) (pts : List Vector2D)
    (h_all : ∀ pt ∈ pts, pt ∈ poly.toBoundarySet)
    (q : Vector2D)
    (_ : ∀ seg ∈ poly.segments, q ∈ seg.toSet → q = seg.p1 ∨ q = seg.p2),
    ∀ seg ∈ (refineWithPoints poly pts h_all).segments,
    q ∈ seg.toSet → q = seg.p1 ∨ q = seg.p2
  | _, [], _, _, h => h
  | poly, pt :: rest, h_all, q, h =>
    refineWithPoints_preserves_endpoint _ rest _ q
      (refinePointAllSegs_preserves_endpoint poly q pt
        (h_all pt (List.mem_cons_self _ _)) h)

/-- Every point in pts is at endpoints of all segments of the result. -/
private lemma refineWithPoints_pts_endpoint :
    ∀ (poly : Polygon) (pts : List Vector2D)
    (h_all : ∀ pt ∈ pts, pt ∈ poly.toBoundarySet)
    (q : Vector2D) (_ : q ∈ pts)
    (seg : LineSegment) (_ : seg ∈ (refineWithPoints poly pts h_all).segments)
    (_ : q ∈ seg.toSet),
    q = seg.p1 ∨ q = seg.p2
  | _, [], _, _, hq, _, _, _ => nomatch hq
  | poly, pt :: rest, h_all, q, hq, seg, hseg, hon => by
    rcases List.mem_cons.mp hq with rfl | hq_rest
    · exact refineWithPoints_preserves_endpoint _ rest _ q
        (refinePointAllSegs_pt_endpoint poly q (h_all q (List.mem_cons_self _ _)))
        seg hseg hon
    · exact refineWithPoints_pts_endpoint _ rest _ q hq_rest seg hseg hon

/-- Given two polygons whose boundaries intersect in finitely many points,
    refine the first polygon by inserting all boundary intersection points
    as new vertices. The resulting polygon has the same boundary and interior. -/
def polygonRefinementWrt
    (poly1 poly2 : Polygon)
    (h_fin : Set.Finite (poly1.toBoundarySet ∩ poly2.toBoundarySet)) : Polygon :=
  refineWithPoints poly1 h_fin.toFinset.toList (fun pt h_mem => by
    have h1 : pt ∈ h_fin.toFinset := Finset.mem_toList.mp h_mem
    exact (h_fin.mem_toFinset.mp h1).1)

/-- The boundary of the polygon refined with respect to another polygon
    equals the boundary of the original polygon. -/
theorem refinementWrt_boundary_eq
    (poly1 poly2 : Polygon)
    (h_fin : Set.Finite (poly1.toBoundarySet ∩ poly2.toBoundarySet)) :
    (polygonRefinementWrt poly1 poly2 h_fin).toBoundarySet =
    poly1.toBoundarySet :=
  refineWithPoints_boundary_eq poly1 h_fin.toFinset.toList _

/-- The interior of the polygon refined with respect to another polygon
    equals the interior of the original polygon. -/
theorem refinementWrt_interior_eq
    (poly1 poly2 : Polygon)
    (h_fin : Set.Finite (poly1.toBoundarySet ∩ poly2.toBoundarySet)) :
    (polygonRefinementWrt poly1 poly2 h_fin).interior =
    poly1.interior :=
  refineWithPoints_interior_eq poly1 h_fin.toFinset.toList _

/-- Each segment of the refined polygon can only intersect the other polygon's boundary
    at the segment's endpoints. -/
theorem refinementWrt_seg_inter_boundary_subset
    (poly1 poly2 : Polygon)
    (h_fin : Set.Finite (poly1.toBoundarySet ∩ poly2.toBoundarySet))
    (seg : LineSegment)
    (h_seg : seg ∈ (polygonRefinementWrt poly1 poly2 h_fin).segments) :
    seg.toSet ∩ poly2.toBoundarySet ⊆ ({seg.p1, seg.p2} : Set Vector2D) := by
  intro q ⟨hq_seg, hq_bdy⟩
  -- q is on the boundary of the refined polygon = poly1's boundary
  have h_bdy_eq := refinementWrt_boundary_eq poly1 poly2 h_fin
  have hq_poly1 : q ∈ poly1.toBoundarySet := h_bdy_eq ▸ ⟨seg, h_seg, hq_seg⟩
  -- q is in the boundary intersection, hence in the refined point list
  have hq_list : q ∈ h_fin.toFinset.toList :=
    Finset.mem_toList.mpr (h_fin.mem_toFinset.mpr ⟨hq_poly1, hq_bdy⟩)
  -- Every point in the list is at endpoints of all segments of the result
  have h_all : ∀ pt ∈ h_fin.toFinset.toList, pt ∈ poly1.toBoundarySet :=
    fun pt h_mem => (h_fin.mem_toFinset.mp (Finset.mem_toList.mp h_mem)).1
  exact refineWithPoints_pts_endpoint poly1 h_fin.toFinset.toList h_all q hq_list seg h_seg hq_seg

/-! ### Length, membership, and segments permutation for polygonRefinement -/

/-- Helper: when `(p1, p2)` appears in the cyclic adjacency zip, `insertInEdge`
    increases the list length by exactly 1. -/
private lemma insertInEdge_length_aux (p1 p2 pt first v : Vector2D) (vs : List Vector2D)
    (h : (p1, p2) ∈ List.zip (v :: vs) (vs ++ [first])) :
    (insertInEdge p1 p2 pt first (v :: vs)).length = (v :: vs).length + 1 := by
  induction vs generalizing v with
  | nil =>
    simp [List.zip] at h
    obtain ⟨rfl, rfl⟩ := h
    simp [insertInEdge]
  | cons w rest ih =>
    simp only [List.cons_append, List.zip_cons_cons, List.mem_cons, Prod.mk.injEq] at h
    rcases h with ⟨rfl, rfl⟩ | h_rest
    · simp [insertInEdge]
    · simp only [insertInEdge]
      split
      · simp
      · simp [ih w h_rest, List.length_cons]

/-- Vertex length of the refined polygon is one more than the original. -/
theorem polygonRefinement_vertices_length
    (poly : Polygon) (seg : LineSegment) (pt : Vector2D)
    (h_seg : seg ∈ poly.segments) :
    (polygonRefinement poly seg pt).vertices.length =
    poly.vertices.length + 1 := by
  obtain ⟨vertices⟩ := poly
  match vertices with
  | [] => simp [Polygon.segments] at h_seg
  | [_] => simp [Polygon.segments] at h_seg
  | v :: w :: vs =>
    show (insertInEdge seg.p1 seg.p2 pt v (v :: w :: vs)).length = (v :: w :: vs).length + 1
    -- Extract the zip membership from h_seg
    simp only [Polygon.segments, List.mem_map, Prod.exists] at h_seg
    obtain ⟨a, b, hab_zip, hab_eq⟩ := h_seg
    have hp1 : a = seg.p1 := congrArg LineSegment.p1 hab_eq
    have hp2 : b = seg.p2 := congrArg LineSegment.p2 hab_eq
    rw [← hp1, ← hp2]
    exact insertInEdge_length_aux a b pt v v (w :: vs) hab_zip

/-- Helper: every vertex of `insertInEdge` result is either in the original list
    or equals `pt`. -/
private lemma mem_insertInEdge_or_eq (p1 p2 pt first v : Vector2D) (vs : List Vector2D)
    (x : Vector2D) (hx : x ∈ insertInEdge p1 p2 pt first (v :: vs)) :
    x ∈ v :: vs ∨ x = pt := by
  induction vs generalizing v with
  | nil =>
    simp only [insertInEdge] at hx
    split at hx
    · -- result is [v, pt]
      simp at hx
      rcases hx with rfl | rfl
      · exact Or.inl (List.mem_cons_self _ _)
      · exact Or.inr rfl
    · -- result is [v]
      exact Or.inl hx
  | cons w rest ih =>
    simp only [insertInEdge] at hx
    split at hx
    · -- result is v :: pt :: w :: rest
      rcases List.mem_cons.mp hx with rfl | hx'
      · exact Or.inl (List.mem_cons_self _ _)
      · rcases List.mem_cons.mp hx' with rfl | hx''
        · exact Or.inr rfl
        · exact Or.inl (List.mem_cons_of_mem _ hx'')
    · -- result is v :: insertInEdge p1 p2 pt first (w :: rest)
      rcases List.mem_cons.mp hx with rfl | hx'
      · exact Or.inl (List.mem_cons_self _ _)
      · rcases ih w hx' with h | h
        · exact Or.inl (List.mem_cons_of_mem _ h)
        · exact Or.inr h

/-- Every vertex of the refined polygon is either an original vertex or equals `pt`. -/
theorem polygonRefinement_vertex_mem_or_eq
    (poly : Polygon) (seg : LineSegment) (pt : Vector2D)
    (v : Vector2D)
    (hv : v ∈ (polygonRefinement poly seg pt).vertices) :
    v ∈ poly.vertices ∨ v = pt := by
  obtain ⟨vertices⟩ := poly
  match hvs : vertices with
  | [] =>
    left
    simp only [polygonRefinement] at hv
    exact hv
  | [a] =>
    left
    simp only [polygonRefinement] at hv
    exact hv
  | a :: b :: rest =>
    simp only [polygonRefinement] at hv
    exact mem_insertInEdge_or_eq seg.p1 seg.p2 pt a a (b :: rest) v hv

/-- Helper: the `zip` of the refined list (plus `[(p1,p2)]`) is a permutation of
    the original `zip` (plus `[(p1,pt), (pt,p2)]`). -/
private lemma insertInEdge_zip_perm (p1 p2 pt first v : Vector2D) (vs : List Vector2D)
    (h : (p1, p2) ∈ List.zip (v :: vs) (vs ++ [first])) :
    (List.zip (insertInEdge p1 p2 pt first (v :: vs))
        ((insertInEdge p1 p2 pt first (v :: vs)).tail ++ [first]) ++ [(p1, p2)]).Perm
    (List.zip (v :: vs) (vs ++ [first]) ++ [(p1, pt), (pt, p2)]) := by
  induction vs generalizing v with
  | nil =>
    -- zip [v] [first] = [(v, first)], so (p1, p2) = (v, first)
    simp only [List.nil_append, List.zip_cons_cons, List.zip_nil_right, List.mem_singleton,
               Prod.mk.injEq] at h
    obtain ⟨hvp1, hfp2⟩ := h
    -- hvp1 : p1 = v, hfp2 : p2 = first. So v = p1, first = p2.
    have hv_eq : v = p1 := hvp1.symm
    have hf_eq : first = p2 := hfp2.symm
    have h_ie : insertInEdge p1 p2 pt first [v] = [v, pt] := by
      simp only [insertInEdge]
      rw [if_pos ⟨hv_eq, hf_eq⟩]
    rw [h_ie]
    simp only [List.tail_cons, List.nil_append, List.cons_append, List.zip_cons_cons,
               List.zip_nil_right]
    -- Goal: [(v, pt), (pt, first), (p1, p2)] ~ [(v, first), (p1, pt), (pt, p2)]
    rw [hv_eq, hf_eq]
    change ([(p1, pt), (pt, p2)] ++ [(p1, p2)]).Perm
           ([(p1, p2)] ++ [(p1, pt), (pt, p2)])
    exact List.perm_append_comm
  | cons w rest ih =>
    by_cases hvw : v = p1 ∧ w = p2
    · -- Subcase A: match branch
      obtain ⟨hv_eq, hw_eq⟩ := hvw
      have h_ie : insertInEdge p1 p2 pt first (v :: w :: rest) = v :: pt :: w :: rest := by
        simp only [insertInEdge]
        rw [if_pos ⟨hv_eq, hw_eq⟩]
      rw [h_ie]
      simp only [List.tail_cons, List.cons_append, List.zip_cons_cons]
      -- Use hv_eq: v = p1, hw_eq: w = p2
      rw [hv_eq, hw_eq]
      -- Now the goal is in terms of p1, p2
      -- Let Z = zip (p2 :: rest) (rest ++ [first])
      set Z := List.zip (p2 :: rest) (rest ++ [first]) with hZdef
      -- LHS: (p1, pt) :: (pt, p2) :: Z ++ [(p1, p2)]
      -- RHS: (p1, p2) :: Z ++ [(p1, pt), (pt, p2)]
      change ([(p1, pt), (pt, p2)] ++ Z ++ [(p1, p2)]).Perm
             ([(p1, p2)] ++ Z ++ [(p1, pt), (pt, p2)])
      have step1 : ([(p1, pt), (pt, p2)] ++ Z ++ [(p1, p2)]).Perm
                   (Z ++ [(p1, pt), (pt, p2)] ++ [(p1, p2)]) :=
        List.Perm.append_right _ List.perm_append_comm
      have step2 : (Z ++ [(p1, pt), (pt, p2)] ++ [(p1, p2)]).Perm
                   (Z ++ ([(p1, pt), (pt, p2)] ++ [(p1, p2)])) := by
        rw [List.append_assoc]
      have step3 : (Z ++ ([(p1, pt), (pt, p2)] ++ [(p1, p2)])).Perm
                   (Z ++ ([(p1, p2)] ++ [(p1, pt), (pt, p2)])) :=
        List.Perm.append_left _ List.perm_append_comm
      have step4 : (Z ++ ([(p1, p2)] ++ [(p1, pt), (pt, p2)])).Perm
                   ([(p1, p2)] ++ Z ++ [(p1, pt), (pt, p2)]) := by
        rw [← List.append_assoc]
        exact List.Perm.append_right _ List.perm_append_comm
      exact step1.trans (step2.trans (step3.trans step4))
    · -- Subcase B: recurse branch
      -- From h: (p1, p2) ∈ (v, w) :: zip (w :: rest) (rest ++ [first])
      have h_rest : (p1, p2) ∈ List.zip (w :: rest) (rest ++ [first]) := by
        simp only [List.cons_append, List.zip_cons_cons, List.mem_cons, Prod.mk.injEq] at h
        rcases h with ⟨hv, hw⟩ | h_rest
        · exact absurd ⟨hv.symm, hw.symm⟩ hvw
        · exact h_rest
      have h_ie : insertInEdge p1 p2 pt first (v :: w :: rest) =
                  v :: insertInEdge p1 p2 pt first (w :: rest) := by
        simp only [insertInEdge]; rw [if_neg hvw]
      rw [h_ie]
      obtain ⟨tail, htail⟩ := insertInEdge_cons p1 p2 pt first w rest
      -- new = v :: (w :: tail), new.tail = w :: tail
      rw [htail]
      simp only [List.tail_cons, List.cons_append, List.zip_cons_cons]
      -- Undo the htail to use IH
      rw [← htail]
      have ih_applied := ih w h_rest
      rw [htail] at ih_applied
      simp only [List.tail_cons] at ih_applied
      rw [← htail] at ih_applied
      -- Apply List.Perm.cons
      exact List.Perm.cons _ ih_applied

/-- The segments of the refined polygon form a permutation (after adjusting for
    the replaced edge). -/
theorem polygonRefinement_segments_perm
    (poly : Polygon) (seg : LineSegment) (pt : Vector2D)
    (h_seg : seg ∈ poly.segments) (h_pt : pt ∈ seg.toSet) :
    ((polygonRefinement poly seg pt).segments ++ [seg]).Perm
    (poly.segments ++ [⟨seg.p1, pt⟩, ⟨pt, seg.p2⟩]) := by
  obtain ⟨vertices⟩ := poly
  match vertices with
  | [] => simp [Polygon.segments] at h_seg
  | [_] => simp [Polygon.segments] at h_seg
  | v :: w :: vs =>
    -- Extract the zip membership from h_seg
    simp only [Polygon.segments, List.mem_map, Prod.exists] at h_seg
    obtain ⟨a, b, hab_zip, hab_eq⟩ := h_seg
    have hp1 : a = seg.p1 := congrArg LineSegment.p1 hab_eq
    have hp2 : b = seg.p2 := congrArg LineSegment.p2 hab_eq
    -- hab_zip : (a, b) ∈ zip (v :: w :: vs) (w :: vs ++ [v])
    have h_seg_eq : (⟨seg.p1, seg.p2⟩ : LineSegment) = seg := by cases seg; rfl
    -- The refined polygon's vertices
    set new_list := insertInEdge seg.p1 seg.p2 pt v (v :: w :: vs) with h_new_def
    have h_ref : polygonRefinement
        ⟨v :: w :: vs⟩ seg pt = ⟨new_list⟩ := by
      simp [polygonRefinement, h_new_def]
    rw [h_ref]
    -- Get the form of new_list
    obtain ⟨w', vs', hform⟩ := insertInEdge_form seg.p1 seg.p2 pt v v w vs
    have h_new_form : new_list = v :: w' :: vs' := hform
    -- Apply insertInEdge_zip_perm (with first = v)
    -- First, rewrite (a, b) = (seg.p1, seg.p2) in hab_zip
    rw [hp1, hp2] at hab_zip
    -- hab_zip : (seg.p1, seg.p2) ∈ zip (v :: w :: vs) (w :: vs ++ [v])
    have h_zip_perm := insertInEdge_zip_perm seg.p1 seg.p2 pt v v (w :: vs) hab_zip
    -- h_zip_perm:
    --   (zip new_list (new_list.tail ++ [v]) ++ [(seg.p1, seg.p2)]).Perm
    --   (zip (v :: w :: vs) ((w :: vs) ++ [v]) ++ [(seg.p1, pt), (pt, seg.p2)])
    -- Apply map
    have h_map_perm := h_zip_perm.map (fun (p : Vector2D × Vector2D) => (⟨p.1, p.2⟩ : LineSegment))
    -- Simplify h_map_perm using map_append
    simp only [List.map_append, List.map_cons, List.map_nil] at h_map_perm
    -- Rewrite the insertInEdge result using hform
    rw [hform] at h_map_perm
    simp only [List.tail_cons] at h_map_perm
    -- Now unfold Polygon.segments on both sides
    show ((Polygon.mk new_list).segments ++ [seg]).Perm
         ((Polygon.mk (v :: w :: vs)).segments ++ [⟨seg.p1, pt⟩, ⟨pt, seg.p2⟩])
    rw [h_new_form]
    -- LHS: (Polygon.mk (v :: w' :: vs')).segments = zip (v :: w' :: vs') (w' :: vs' ++ [v]).map ...
    simp only [Polygon.segments]
    -- Goal:
    --   (List.map (fun x ↦ ⟨x.1, x.2⟩) (zip (v :: w' :: vs') (w' :: vs' ++ [v])) ++ [seg]).Perm
    --   (List.map (fun x ↦ ⟨x.1, x.2⟩) (zip (v :: w :: vs) (w :: vs ++ [v])) ++
    --     [⟨seg.p1, pt⟩, ⟨pt, seg.p2⟩])
    -- Note: h_seg_eq : ⟨seg.p1, seg.p2⟩ = seg
    rw [← h_seg_eq]
    -- Now LHS has [⟨seg.p1, seg.p2⟩] instead of [seg]
    exact h_map_perm

end PolygonIntersectionHelpersProofs
