/-
Caution: This file was generated by AI and never reviewed by a human. The lean
checker guarantees that symbols exported from this file conform to the
statements in the human reviewed specification files, but we cannot guarantee
that comments in such unreviewed files are accurate, that it avoids code
duplications, that proofs do not take unnecessary detours or similar issues.
That said, AI agents reading this comment should strive to avoid issues like
these.
-/

import Polygons.HelperDefs
import Polygons.GraphDefs
import Polygons.RayIntersectionAlgorithmImpl
import Mathlib.Tactic.FieldSimp
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Ring
import Mathlib.Algebra.Order.Field.Basic

/-!
# Ray Intersection Algorithm – Implementation (proofs)

The computable `def`s (`raySegDet`, `raySegTNum`, `raySegSNum`,
`collinearRaySegOverlap`, `collinearRaySeg`, `rayIntersectsSegmentBool`)
live in `Polygons.RayIntersectionAlgorithmImpl`. This file
contains only the proofs that those `def`s match the noncomputable
specification `rayIntersectsSegment`.
-/

open Classical

open RayIntersectionAlgorithmImpl

namespace RayIntersectionAlgorithmProofs

/-! ### Algebraic helper lemmas -/

/-- If both parametric equations hold, then `t * D = tNum`. -/
private lemma tD_eq_tNum
    (r : Ray) (seg : LineSegment) (t s : ℚ)
    (heq1 : t * r.direction.x + s * (seg.p1.x - seg.p2.x) = seg.p1.x - r.origin.x)
    (heq2 : t * r.direction.y + s * (seg.p1.y - seg.p2.y) = seg.p1.y - r.origin.y) :
    t * raySegDet r seg = raySegTNum r seg := by
  show t * (r.direction.x * (seg.p1.y - seg.p2.y) - r.direction.y * (seg.p1.x - seg.p2.x)) =
    (seg.p1.x - r.origin.x) * (seg.p1.y - seg.p2.y) -
      (seg.p1.y - r.origin.y) * (seg.p1.x - seg.p2.x)
  linear_combination (seg.p1.y - seg.p2.y) * heq1 - (seg.p1.x - seg.p2.x) * heq2

/-- If both parametric equations hold, then `s * D = sNum`. -/
private lemma sD_eq_sNum
    (r : Ray) (seg : LineSegment) (t s : ℚ)
    (heq1 : t * r.direction.x + s * (seg.p1.x - seg.p2.x) = seg.p1.x - r.origin.x)
    (heq2 : t * r.direction.y + s * (seg.p1.y - seg.p2.y) = seg.p1.y - r.origin.y) :
    s * raySegDet r seg = raySegSNum r seg := by
  show s * (r.direction.x * (seg.p1.y - seg.p2.y) - r.direction.y * (seg.p1.x - seg.p2.x)) =
    r.direction.x * (seg.p1.y - r.origin.y) - r.direction.y * (seg.p1.x - r.origin.x)
  linear_combination (-r.direction.y) * heq1 + r.direction.x * heq2

/-! ### Equivalence with the noncomputable proposition -/

/-- Soundness of the non-degenerate case. -/
private lemma intersect_of_det_ne_zero
    (r : Ray) (seg : LineSegment)
    (hD : raySegDet r seg ≠ 0)
    (htD : raySegTNum r seg * raySegDet r seg ≥ 0)
    (hsD0 : 0 ≤ raySegSNum r seg * raySegDet r seg)
    (hsD1 : raySegSNum r seg * raySegDet r seg ≤ raySegDet r seg * raySegDet r seg) :
    rayIntersectsSegment r seg := by
  set D := raySegDet r seg with hDdef
  set tNum := raySegTNum r seg with htNumDef
  set sNum := raySegSNum r seg with hsNumDef
  set t : ℚ := tNum / D with htDef
  set s : ℚ := sNum / D with hsDef
  have ht_nn : 0 ≤ t := by
    rw [htDef]
    rcases lt_or_gt_of_ne hD with hDneg | hDpos
    · exact div_nonneg_of_nonpos (by nlinarith [htD]) (le_of_lt hDneg)
    · exact div_nonneg (by nlinarith [htD]) (le_of_lt hDpos)
  have hs_nn : 0 ≤ s := by
    rw [hsDef]
    rcases lt_or_gt_of_ne hD with hDneg | hDpos
    · exact div_nonneg_of_nonpos (by nlinarith [hsD0]) (le_of_lt hDneg)
    · exact div_nonneg (by nlinarith [hsD0]) (le_of_lt hDpos)
  have hs_le_one : s ≤ 1 := by
    rw [hsDef]
    rcases lt_or_gt_of_ne hD with hDneg | hDpos
    · rw [div_le_one_of_neg hDneg]; nlinarith [hsD1]
    · rw [div_le_one hDpos]; nlinarith [hsD1]
  have htD_eq : t * D = tNum := by
    rw [htDef]; field_simp
  have hsD_eq : s * D = sNum := by
    rw [hsDef]; field_simp
  -- Algebraic identity: D * ((1-s)*p1.x + s*p2.x) = D * (origin.x + t*dir.x).
  have hkey_x : D * ((1 - s) * seg.p1.x + s * seg.p2.x) =
                D * (r.origin.x + t * r.direction.x) := by
    have h1 : t * D = tNum := htD_eq
    have h2 : s * D = sNum := hsD_eq
    have hDexp : D = r.direction.x * (seg.p1.y - seg.p2.y) -
                     r.direction.y * (seg.p1.x - seg.p2.x) := hDdef
    have htN : tNum = (seg.p1.x - r.origin.x) * (seg.p1.y - seg.p2.y) -
                      (seg.p1.y - r.origin.y) * (seg.p1.x - seg.p2.x) := htNumDef
    have hsN : sNum = r.direction.x * (seg.p1.y - r.origin.y) -
                      r.direction.y * (seg.p1.x - r.origin.x) := hsNumDef
    rw [htN] at h1
    rw [hsN] at h2
    rw [hDexp] at h1 h2 ⊢
    linear_combination (-r.direction.x) * h1 + (-(seg.p1.x - seg.p2.x)) * h2
  have hkey_y : D * ((1 - s) * seg.p1.y + s * seg.p2.y) =
                D * (r.origin.y + t * r.direction.y) := by
    have h1 : t * D = tNum := htD_eq
    have h2 : s * D = sNum := hsD_eq
    have hDexp : D = r.direction.x * (seg.p1.y - seg.p2.y) -
                     r.direction.y * (seg.p1.x - seg.p2.x) := hDdef
    have htN : tNum = (seg.p1.x - r.origin.x) * (seg.p1.y - seg.p2.y) -
                      (seg.p1.y - r.origin.y) * (seg.p1.x - seg.p2.x) := htNumDef
    have hsN : sNum = r.direction.x * (seg.p1.y - r.origin.y) -
                      r.direction.y * (seg.p1.x - r.origin.x) := hsNumDef
    rw [htN] at h1
    rw [hsN] at h2
    rw [hDexp] at h1 h2 ⊢
    linear_combination (-r.direction.y) * h1 + (-(seg.p1.y - seg.p2.y)) * h2
  have heq_x : (1 - s) * seg.p1.x + s * seg.p2.x = r.origin.x + t * r.direction.x :=
    mul_left_cancel₀ hD hkey_x
  have heq_y : (1 - s) * seg.p1.y + s * seg.p2.y = r.origin.y + t * r.direction.y :=
    mul_left_cancel₀ hD hkey_y
  refine ⟨⟨r.origin.x + t * r.direction.x, r.origin.y + t * r.direction.y⟩,
          ⟨t, ht_nn, rfl, rfl⟩,
          ⟨s, hs_nn, hs_le_one, ?_, ?_⟩⟩
  · exact heq_x.symm
  · exact heq_y.symm

/-- Completeness of the non-degenerate case. -/
private lemma cond_of_intersect_det_ne_zero
    (r : Ray) (seg : LineSegment)
    (_hD : raySegDet r seg ≠ 0)
    (h : rayIntersectsSegment r seg) :
    raySegTNum r seg * raySegDet r seg ≥ 0 ∧
    0 ≤ raySegSNum r seg * raySegDet r seg ∧
    raySegSNum r seg * raySegDet r seg ≤ raySegDet r seg * raySegDet r seg := by
  obtain ⟨q, hq_ray, hq_seg⟩ := h
  obtain ⟨t, ht_nn, hqx_eq, hqy_eq⟩ := hq_ray
  obtain ⟨s, hs_nn, hs_le_one, hqx_seg, hqy_seg⟩ := hq_seg
  have heq1 : t * r.direction.x + s * (seg.p1.x - seg.p2.x) = seg.p1.x - r.origin.x := by
    have hh : r.origin.x + t * r.direction.x = (1 - s) * seg.p1.x + s * seg.p2.x := by
      rw [← hqx_eq, hqx_seg]
    linarith [hh]
  have heq2 : t * r.direction.y + s * (seg.p1.y - seg.p2.y) = seg.p1.y - r.origin.y := by
    have hh : r.origin.y + t * r.direction.y = (1 - s) * seg.p1.y + s * seg.p2.y := by
      rw [← hqy_eq, hqy_seg]
    linarith [hh]
  have htD_eq : t * raySegDet r seg = raySegTNum r seg := tD_eq_tNum r seg t s heq1 heq2
  have hsD_eq : s * raySegDet r seg = raySegSNum r seg := sD_eq_sNum r seg t s heq1 heq2
  have hD2_nn : 0 ≤ raySegDet r seg * raySegDet r seg := mul_self_nonneg _
  refine ⟨?_, ?_, ?_⟩
  · have hrw : raySegTNum r seg * raySegDet r seg =
                t * (raySegDet r seg * raySegDet r seg) := by
      rw [← htD_eq]; ring
    rw [hrw]
    exact mul_nonneg ht_nn hD2_nn
  · have hrw : raySegSNum r seg * raySegDet r seg =
                s * (raySegDet r seg * raySegDet r seg) := by
      rw [← hsD_eq]; ring
    rw [hrw]
    exact mul_nonneg hs_nn hD2_nn
  · have hrw : raySegSNum r seg * raySegDet r seg =
                s * (raySegDet r seg * raySegDet r seg) := by
      rw [← hsD_eq]; ring
    rw [hrw]
    have hh : s * (raySegDet r seg * raySegDet r seg) ≤
              1 * (raySegDet r seg * raySegDet r seg) :=
      mul_le_mul_of_nonneg_right hs_le_one hD2_nn
    linarith [hh]

/-- Soundness in the degenerate (parallel) case. -/
private lemma intersect_of_det_zero
    (r : Ray) (seg : LineSegment)
    (hD : raySegDet r seg = 0)
    (_htN : raySegTNum r seg = 0)
    (hsN : raySegSNum r seg = 0)
    (h_overlap : collinearRaySegOverlap r seg = true) :
    rayIntersectsSegment r seg := by
  unfold collinearRaySegOverlap at h_overlap
  by_cases hdx : r.direction.x ≠ 0
  · rw [if_pos hdx] at h_overlap
    set t1 : ℚ := (seg.p1.x - r.origin.x) / r.direction.x with ht1_def
    set t2 : ℚ := (seg.p2.x - r.origin.x) / r.direction.x with ht2_def
    have ht_max_nn : (0 : ℚ) ≤ max t1 t2 := of_decide_eq_true h_overlap
    have h_t1_x : t1 * r.direction.x = seg.p1.x - r.origin.x := by
      rw [ht1_def]; field_simp
    have h_t2_x : t2 * r.direction.x = seg.p2.x - r.origin.x := by
      rw [ht2_def]; field_simp
    clear_value t1 t2
    have hp1_x : seg.p1.x = r.origin.x + t1 * r.direction.x := by linarith [h_t1_x]
    have hp2_x : seg.p2.x = r.origin.x + t2 * r.direction.x := by linarith [h_t2_x]
    have hsN' : r.direction.x * (seg.p1.y - r.origin.y) =
                r.direction.y * (seg.p1.x - r.origin.x) := by
      have hh : raySegSNum r seg = 0 := hsN
      unfold raySegSNum at hh
      linarith [hh]
    have hp1_y : seg.p1.y = r.origin.y + t1 * r.direction.y := by
      have hkey : r.direction.x * (seg.p1.y - r.origin.y) =
                  r.direction.x * (t1 * r.direction.y) := by
        have hexp : r.direction.x * (t1 * r.direction.y) =
                    r.direction.y * (t1 * r.direction.x) := by ring
        rw [hexp, h_t1_x, hsN']
      have h_eq := mul_left_cancel₀ hdx hkey
      linarith [h_eq]
    have hD' : r.direction.x * (seg.p1.y - seg.p2.y) =
               r.direction.y * (seg.p1.x - seg.p2.x) := by
      have hh : raySegDet r seg = 0 := hD
      unfold raySegDet at hh
      linarith [hh]
    have h_p1x_minus_p2x : seg.p1.x - seg.p2.x = (t1 - t2) * r.direction.x := by
      have hexp : (t1 - t2) * r.direction.x = t1 * r.direction.x - t2 * r.direction.x := by ring
      rw [hexp, h_t1_x, h_t2_x]; ring
    have h_p1y_minus_p2y : seg.p1.y - seg.p2.y = (t1 - t2) * r.direction.y := by
      have hkey : r.direction.x * (seg.p1.y - seg.p2.y) =
                  r.direction.x * ((t1 - t2) * r.direction.y) := by
        have hexp : r.direction.x * ((t1 - t2) * r.direction.y) =
                    r.direction.y * ((t1 - t2) * r.direction.x) := by ring
        rw [hexp, ← h_p1x_minus_p2x, hD']
      exact mul_left_cancel₀ hdx hkey
    have hp2_y : seg.p2.y = r.origin.y + t2 * r.direction.y := by
      have hexp : seg.p2.y = seg.p1.y - (seg.p1.y - seg.p2.y) := by ring
      rw [hexp, h_p1y_minus_p2y, hp1_y]; ring
    rcases lt_or_ge t2 t1 with h12 | h12
    · -- t2 < t1, so max t1 t2 = t1, pick s = 0
      have hmax : max t1 t2 = t1 := max_eq_left (le_of_lt h12)
      rw [hmax] at ht_max_nn
      refine ⟨⟨r.origin.x + t1 * r.direction.x, r.origin.y + t1 * r.direction.y⟩,
              ⟨t1, ht_max_nn, rfl, rfl⟩, ⟨0, le_refl _, zero_le_one, ?_, ?_⟩⟩
      · show r.origin.x + t1 * r.direction.x = (1 - 0) * seg.p1.x + 0 * seg.p2.x
        rw [hp1_x]; ring
      · show r.origin.y + t1 * r.direction.y = (1 - 0) * seg.p1.y + 0 * seg.p2.y
        rw [hp1_y]; ring
    · -- t1 ≤ t2, so max t1 t2 = t2, pick s = 1
      have hmax : max t1 t2 = t2 := max_eq_right h12
      rw [hmax] at ht_max_nn
      refine ⟨⟨r.origin.x + t2 * r.direction.x, r.origin.y + t2 * r.direction.y⟩,
              ⟨t2, ht_max_nn, rfl, rfl⟩, ⟨1, zero_le_one, le_refl _, ?_, ?_⟩⟩
      · show r.origin.x + t2 * r.direction.x = (1 - 1) * seg.p1.x + 1 * seg.p2.x
        rw [hp2_x]; ring
      · show r.origin.y + t2 * r.direction.y = (1 - 1) * seg.p1.y + 1 * seg.p2.y
        rw [hp2_y]; ring
  · push_neg at hdx
    have hcond : ¬ (r.direction.x ≠ 0) := fun h => h hdx
    rw [if_neg hcond] at h_overlap
    have hdy : r.direction.y ≠ 0 := by
      intro hdy
      apply r.direction_nonzero
      ext
      · exact hdx
      · exact hdy
    set t1 : ℚ := (seg.p1.y - r.origin.y) / r.direction.y with ht1_def
    set t2 : ℚ := (seg.p2.y - r.origin.y) / r.direction.y with ht2_def
    have ht_max_nn : (0 : ℚ) ≤ max t1 t2 := of_decide_eq_true h_overlap
    have h_t1_y : t1 * r.direction.y = seg.p1.y - r.origin.y := by
      rw [ht1_def]; field_simp
    have h_t2_y : t2 * r.direction.y = seg.p2.y - r.origin.y := by
      rw [ht2_def]; field_simp
    clear_value t1 t2
    have hp1_y : seg.p1.y = r.origin.y + t1 * r.direction.y := by linarith [h_t1_y]
    have hp2_y : seg.p2.y = r.origin.y + t2 * r.direction.y := by linarith [h_t2_y]
    have hp1_x : seg.p1.x = r.origin.x := by
      have hsN' : raySegSNum r seg = 0 := hsN
      unfold raySegSNum at hsN'
      rw [hdx] at hsN'
      have hh : r.direction.y * (seg.p1.x - r.origin.x) = 0 := by linarith [hsN']
      have h_diff : seg.p1.x - r.origin.x = 0 := by
        rcases mul_eq_zero.mp hh with h | h
        · exact absurd h hdy
        · exact h
      linarith [h_diff]
    have hp2_x : seg.p2.x = r.origin.x := by
      have hD' : raySegDet r seg = 0 := hD
      unfold raySegDet at hD'
      rw [hdx] at hD'
      have hh : r.direction.y * (seg.p1.x - seg.p2.x) = 0 := by linarith [hD']
      have h_diff : seg.p1.x - seg.p2.x = 0 := by
        rcases mul_eq_zero.mp hh with h | h
        · exact absurd h hdy
        · exact h
      linarith [hp1_x, h_diff]
    rcases lt_or_ge t2 t1 with h12 | h12
    · -- t2 < t1, max t1 t2 = t1, pick s = 0
      have hmax : max t1 t2 = t1 := max_eq_left (le_of_lt h12)
      rw [hmax] at ht_max_nn
      refine ⟨⟨r.origin.x + t1 * r.direction.x, r.origin.y + t1 * r.direction.y⟩,
              ⟨t1, ht_max_nn, rfl, rfl⟩, ⟨0, le_refl _, zero_le_one, ?_, ?_⟩⟩
      · show r.origin.x + t1 * r.direction.x = (1 - 0) * seg.p1.x + 0 * seg.p2.x
        rw [hp1_x, hdx]; ring
      · show r.origin.y + t1 * r.direction.y = (1 - 0) * seg.p1.y + 0 * seg.p2.y
        rw [hp1_y]; ring
    · -- t1 ≤ t2, max t1 t2 = t2, pick s = 1
      have hmax : max t1 t2 = t2 := max_eq_right h12
      rw [hmax] at ht_max_nn
      refine ⟨⟨r.origin.x + t2 * r.direction.x, r.origin.y + t2 * r.direction.y⟩,
              ⟨t2, ht_max_nn, rfl, rfl⟩, ⟨1, zero_le_one, le_refl _, ?_, ?_⟩⟩
      · show r.origin.x + t2 * r.direction.x = (1 - 1) * seg.p1.x + 1 * seg.p2.x
        rw [hp2_x, hdx]; ring
      · show r.origin.y + t2 * r.direction.y = (1 - 1) * seg.p1.y + 1 * seg.p2.y
        rw [hp2_y]; ring

/-- Completeness in the degenerate case. -/
private lemma cond_of_intersect_det_zero
    (r : Ray) (seg : LineSegment)
    (hD : raySegDet r seg = 0)
    (h : rayIntersectsSegment r seg) :
    raySegTNum r seg = 0 ∧ raySegSNum r seg = 0 ∧
    collinearRaySegOverlap r seg = true := by
  obtain ⟨q, hq_ray, hq_seg⟩ := h
  obtain ⟨t, ht_nn, hqx_eq, hqy_eq⟩ := hq_ray
  obtain ⟨s, hs_nn, hs_le_one, hqx_seg, hqy_seg⟩ := hq_seg
  have heq1 : t * r.direction.x + s * (seg.p1.x - seg.p2.x) = seg.p1.x - r.origin.x := by
    have hh : r.origin.x + t * r.direction.x = (1 - s) * seg.p1.x + s * seg.p2.x := by
      rw [← hqx_eq, hqx_seg]
    linarith [hh]
  have heq2 : t * r.direction.y + s * (seg.p1.y - seg.p2.y) = seg.p1.y - r.origin.y := by
    have hh : r.origin.y + t * r.direction.y = (1 - s) * seg.p1.y + s * seg.p2.y := by
      rw [← hqy_eq, hqy_seg]
    linarith [hh]
  have htD_eq : t * raySegDet r seg = raySegTNum r seg := tD_eq_tNum r seg t s heq1 heq2
  have hsD_eq : s * raySegDet r seg = raySegSNum r seg := sD_eq_sNum r seg t s heq1 heq2
  have htN : raySegTNum r seg = 0 := by
    rw [← htD_eq, hD, mul_zero]
  have hsN : raySegSNum r seg = 0 := by
    rw [← hsD_eq, hD, mul_zero]
  refine ⟨htN, hsN, ?_⟩
  show collinearRaySegOverlap r seg = true
  unfold collinearRaySegOverlap
  by_cases hdx : r.direction.x ≠ 0
  · rw [if_pos hdx]
    -- Introduce t1, t2 as abstract variables tied to their values via equations.
    let t1' : ℚ := (seg.p1.x - r.origin.x) / r.direction.x
    let t2' : ℚ := (seg.p2.x - r.origin.x) / r.direction.x
    show decide (max t1' t2' ≥ 0) = true
    have ht1_eq : t1' * r.direction.x = seg.p1.x - r.origin.x := by
      show (seg.p1.x - r.origin.x) / r.direction.x * r.direction.x = seg.p1.x - r.origin.x
      field_simp
    have ht2_eq : t2' * r.direction.x = seg.p2.x - r.origin.x := by
      show (seg.p2.x - r.origin.x) / r.direction.x * r.direction.x = seg.p2.x - r.origin.x
      field_simp
    have h_combine : r.origin.x + t * r.direction.x =
                     (1 - s) * seg.p1.x + s * seg.p2.x := by
      rw [← hqx_eq, hqx_seg]
    -- Generalize t1', t2' to abstract variables
    suffices h : ∀ (t1 t2 : ℚ),
        t1 * r.direction.x = seg.p1.x - r.origin.x →
        t2 * r.direction.x = seg.p2.x - r.origin.x →
        decide (max t1 t2 ≥ 0) = true by
      exact h t1' t2' ht1_eq ht2_eq
    intro t1 t2 h1 h2
    have h_mul : t * r.direction.x = ((1 - s) * t1 + s * t2) * r.direction.x :=
      calc t * r.direction.x
          = ((1 - s) * seg.p1.x + s * seg.p2.x) - r.origin.x := by linarith [h_combine]
        _ = (1 - s) * (seg.p1.x - r.origin.x) + s * (seg.p2.x - r.origin.x) := by ring
        _ = (1 - s) * (t1 * r.direction.x) + s * (t2 * r.direction.x) := by rw [h1, h2]
        _ = ((1 - s) * t1 + s * t2) * r.direction.x := by ring
    have ht_eq : t = (1 - s) * t1 + s * t2 := mul_right_cancel₀ hdx h_mul
    have h_le : (1 - s) * t1 + s * t2 ≤ max t1 t2 := by
      have h1s : 0 ≤ 1 - s := by linarith
      have ha : (1 - s) * t1 ≤ (1 - s) * max t1 t2 :=
        mul_le_mul_of_nonneg_left (le_max_left _ _) h1s
      have hb : s * t2 ≤ s * max t1 t2 :=
        mul_le_mul_of_nonneg_left (le_max_right _ _) hs_nn
      nlinarith [ha, hb]
    have hmax_nn : (0 : ℚ) ≤ max t1 t2 := by linarith [ht_eq, h_le, ht_nn]
    exact decide_eq_true hmax_nn
  · push_neg at hdx
    have hcond : ¬ (r.direction.x ≠ 0) := fun h => h hdx
    rw [if_neg hcond]
    show decide (max ((seg.p1.y - r.origin.y) / r.direction.y)
                 ((seg.p2.y - r.origin.y) / r.direction.y) ≥ 0) = true
    have hdy : r.direction.y ≠ 0 := by
      intro hdy
      apply r.direction_nonzero
      ext
      · exact hdx
      · exact hdy
    let t1' : ℚ := (seg.p1.y - r.origin.y) / r.direction.y
    let t2' : ℚ := (seg.p2.y - r.origin.y) / r.direction.y
    show decide (max t1' t2' ≥ 0) = true
    have ht1_eq : t1' * r.direction.y = seg.p1.y - r.origin.y := by
      show (seg.p1.y - r.origin.y) / r.direction.y * r.direction.y = seg.p1.y - r.origin.y
      field_simp
    have ht2_eq : t2' * r.direction.y = seg.p2.y - r.origin.y := by
      show (seg.p2.y - r.origin.y) / r.direction.y * r.direction.y = seg.p2.y - r.origin.y
      field_simp
    have h_combine : r.origin.y + t * r.direction.y =
                     (1 - s) * seg.p1.y + s * seg.p2.y := by
      rw [← hqy_eq, hqy_seg]
    suffices h : ∀ (t1 t2 : ℚ),
        t1 * r.direction.y = seg.p1.y - r.origin.y →
        t2 * r.direction.y = seg.p2.y - r.origin.y →
        decide (max t1 t2 ≥ 0) = true by
      exact h t1' t2' ht1_eq ht2_eq
    intro t1 t2 h1 h2
    have h_mul : t * r.direction.y = ((1 - s) * t1 + s * t2) * r.direction.y :=
      calc t * r.direction.y
          = ((1 - s) * seg.p1.y + s * seg.p2.y) - r.origin.y := by linarith [h_combine]
        _ = (1 - s) * (seg.p1.y - r.origin.y) + s * (seg.p2.y - r.origin.y) := by ring
        _ = (1 - s) * (t1 * r.direction.y) + s * (t2 * r.direction.y) := by rw [h1, h2]
        _ = ((1 - s) * t1 + s * t2) * r.direction.y := by ring
    have ht_eq : t = (1 - s) * t1 + s * t2 := mul_right_cancel₀ hdy h_mul
    have h_le : (1 - s) * t1 + s * t2 ≤ max t1 t2 := by
      have h1s : 0 ≤ 1 - s := by linarith
      have ha : (1 - s) * t1 ≤ (1 - s) * max t1 t2 :=
        mul_le_mul_of_nonneg_left (le_max_left _ _) h1s
      have hb : s * t2 ≤ s * max t1 t2 :=
        mul_le_mul_of_nonneg_left (le_max_right _ _) hs_nn
      nlinarith [ha, hb]
    have hmax_nn : (0 : ℚ) ≤ max t1 t2 := by linarith [ht_eq, h_le, ht_nn]
    exact decide_eq_true hmax_nn

/-- Equivalence theorem: the computable ray-segment intersection test
    matches the noncomputable proposition. -/
theorem rayIntersectsSegmentBool_iff (r : Ray) (seg : LineSegment) :
    rayIntersectsSegmentBool r seg = true ↔ rayIntersectsSegment r seg := by
  unfold rayIntersectsSegmentBool
  by_cases hD : raySegDet r seg = 0
  · simp [hD]
    constructor
    · rintro ⟨h_col, h_overlap⟩
      unfold collinearRaySeg at h_col
      simp at h_col
      obtain ⟨htN, hsN⟩ := h_col
      exact intersect_of_det_zero r seg hD htN hsN h_overlap
    · intro h
      obtain ⟨htN, hsN, h_overlap⟩ := cond_of_intersect_det_zero r seg hD h
      refine ⟨?_, h_overlap⟩
      unfold collinearRaySeg
      simp [htN, hsN]
  · simp [hD]
    constructor
    · rintro ⟨htD, hsD0, hsD1⟩
      exact intersect_of_det_ne_zero r seg hD htD hsD0 hsD1
    · intro h
      obtain ⟨htD, hsD0, hsD1⟩ := cond_of_intersect_det_ne_zero r seg hD h
      exact ⟨htD, hsD0, hsD1⟩

/-- Decidability of `rayIntersectsSegment` (constructive, via the boolean test). -/
instance (r : Ray) (seg : LineSegment) : Decidable (rayIntersectsSegment r seg) :=
  decidable_of_iff _ (rayIntersectsSegmentBool_iff r seg)

end RayIntersectionAlgorithmProofs
